Repository ParabolInc/parabol, pull requests merged in 2021-07, with the labels that each got.

#5128 templateDimension dataloader should only return non removed dimensions
  packages/server/graphql/mutations/startSprintPoker.ts
Labels: bug, p2

#5209 updating meeting cards styles for improved contrast and HTML semantics
  packages/client/components/MeetingCard.tsx
Labels: user experience

#5232 Adds empty alt property to meeting card images for a11y
  packages/client/components/MeetingCard.tsx
Labels: a11y
