Repository ParabolInc/parabol, pull requests merged in 2022-05, with the labels that each got.

#6473 feat(DX): add npm script for newMutation
  codegen.json
  packages/server/graphql/public/README.md
  scripts/codeshift/baseClientMutation.ts
  scripts/codeshift/baseMutation.ts
  scripts/codeshift/baseMutationQuery.ts
  scripts/codeshift/baseMutationSQL.sql
  scripts/codeshift/basePayload.ts
  scripts/codeshift/baseSuccessPayload.ts
  scripts/codeshift/baseTypeDef.graphql
  scripts/codeshift/newMutation.ts
Labels: Squad: 2

#6447 feat(enableSAMLforDomain): support updates
  package.json
  packages/client/package.json
  packages/gql-executor/package.json
  packages/server/__tests__/globalSetup.ts
  packages/server/graphql/private/mutations/enableSAMLForDomain.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/private/typeDefs/enableSAMLForDomain.graphql
  packages/server/package.json
  packages/server/tsconfig.json
  yarn.lock
Labels: Squad: 2

#6481 feat(ado): Sprint Poker Estimates
  packages/client/components/AzureDevOpsFieldDimensionDropdown.tsx
  packages/client/components/AzureDevOpsFieldMenu.tsx
  packages/client/components/AzureDevOpsScopingSearchResults.tsx
  packages/client/components/AzureDevOpsScopingSelectAllIssues.tsx
  packages/client/components/PokerDimensionFinalScorePicker.tsx
  packages/client/components/PokerEstimateHeaderCard.tsx
  packages/client/hooks/useMakeStageSummaries.ts
  packages/client/mutations/AddAgendaItemMutation.ts
  packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts
  packages/client/mutations/UpdateAzureDevOpsDimensionFieldMutation.ts
  packages/client/shared/gqlIds/AzureDevOpsDimensionFieldId.ts
  packages/client/types/constEnums.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/graphql/mutations/setTaskEstimate.ts
  packages/server/graphql/mutations/updateAzureDevOpsDimensionField.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AzureDevOpsDimensionField.ts
  packages/server/graphql/types/AzureDevOpsIntegration.ts
  packages/server/graphql/types/AzureDevOpsTeamIntegration.ts
  packages/server/graphql/types/AzureDevOpsWorkItem.ts
  packages/server/graphql/types/EstimateStage.ts
  packages/server/graphql/types/Task.ts
  packages/server/graphql/types/TeamIntegrations.ts
  packages/server/graphql/types/TeamMemberIntegrations.ts
  packages/server/postgres/migrations/1650768593875_add-AzureDevOpsDimensionFieldMap.ts
  packages/server/postgres/migrations/1650935732791_taskEstimateAzureDevOps.ts
  packages/server/postgres/queries/generated/getAzureDevOpsDimensionFieldMapsQuery.ts
  packages/server/postgres/queries/generated/getGitHubAuthByUserIdTeamIdQuery.ts
  packages/server/postgres/queries/generated/getLatestTaskEstimatesQuery.ts
  packages/server/postgres/queries/generated/getMeetingTaskEstimatesQuery.ts
  packages/server/postgres/queries/generated/getSimilarTaskEstimateQuery.ts
  packages/server/postgres/queries/generated/insertTaskEstimateQuery.ts
  packages/server/postgres/queries/generated/upsertAzureDevOpsDimensionFieldMapQuery.ts
  packages/server/postgres/queries/getAzureDevOpsDimensionFieldMaps.ts
  packages/server/postgres/queries/insertTaskEstimate.ts
  packages/server/postgres/queries/src/getAzureDevOpsDimensionFieldMapsQuery.sql
  packages/server/postgres/queries/src/insertTaskEstimateQuery.sql
  packages/server/postgres/queries/src/upsertAzureDevOpsDimensionFieldMapQuery.sql
  packages/server/postgres/queries/upsertAzureDevOpsDimensionFieldMap.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/azureDevOps/azureDevOpsFieldTypeToId.ts
Labels: enhancement, Squad: 1

#6539 fix(metrics): add UTM parameters to URLs in team invitation emails
  packages/client/modules/email/components/TeamInvite.tsx
Labels: One Review Required

#6559 feat(standups): Place viewer's card at the start of the list
  packages/client/components/TeamPromptMeeting.tsx
Labels: One Review Required

#6494 feat: Notifications support for MS Teams
  package.json
  packages/client/components/MSTeamsProviderLogo.tsx
  packages/client/components/MSTeamsSVG.tsx
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsConfigMenu.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
  packages/client/mutations/AddTeamMemberIntegrationAuthMutation.ts
  packages/client/mutations/RemoveIntegrationProviderMutation.ts
  packages/client/mutations/RemoveTeamMemberIntegrationAuthMutation.ts
  packages/client/styles/theme/images/graphics/msteams.svg
  packages/client/types/constEnums.ts
  packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/updateIntegrationProvider.ts
  packages/server/graphql/types/IntegrationProviderServiceEnum.ts
  packages/server/graphql/types/MSTeamsIntegration.ts
  packages/server/graphql/types/TeamMemberIntegrations.ts
  packages/server/graphql/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
  packages/server/package.json
  packages/server/postgres/migrations/1651778831990_addMSTeamsIntegrationProvider.ts
  packages/server/postgres/queries/generated/getBestTeamIntegrationAuthQuery.ts
  packages/server/postgres/queries/generated/getIntegrationProvidersByIdsQuery.ts
  packages/server/postgres/queries/generated/getSharedIntegrationProvidersQuery.ts
  packages/server/postgres/queries/generated/getTeamMemberIntegrationAuthQuery.ts
  packages/server/postgres/queries/generated/removeTeamMemberIntegrationAuthQuery.ts
  packages/server/postgres/queries/generated/upsertIntegrationProviderQuery.ts
  packages/server/postgres/queries/generated/upsertTeamMemberIntegrationAuthQuery.ts
  packages/server/postgres/queries/getIntegrationProvidersByIds.ts
  packages/server/utils/MSTeamsServerManager.ts
  yarn.lock
Labels: enhancement, Squad: 1

#6566 chore: readd gitlab feature flag
  packages/client/components/ScopePhaseArea.tsx
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuSignup.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/server/graphql/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required

#6578 feat(Jira Server): Use the newer Jira Software logo
  packages/client/components/JiraServerProviderLogo.tsx
  packages/client/styles/theme/images/graphics/jira-blue.svg
  packages/client/styles/theme/images/graphics/jira-software-blue.svg
Labels: One Review Required

#6581 fix: Due date month could sometimes not be set to the current month
  packages/client/components/DueDatePicker.tsx
Labels: One Review Required

#6586 fix: pr template location
  .github/pull_request_template.md
Labels: One Review Required

#6600 docs: Fix code policy link in PR template
  .github/pull_request_template.md
Labels: One Review Required

#6603 fix: added write permission to pull request labeler workflow
  .github/workflows/labeler.yml
Labels: One Review Required

#6597 feat(Azure DevOps): Correctly format Sprint Poker comments as HTML
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: bug, integrations

#6612 fix: stop-color warning in SVG
  packages/client/components/AzureDevOpsSVG.tsx
Labels: One Review Required

#6613 fix(jira): Fix server error when pushing task to jira
  packages/server/graphql/types/JiraIssue.ts
Labels: One Review Required

#6614 feat(standups): Display active users and invite button in standup meeting
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Labels: One Review Required

#6617 feat(metrics): migrate and consolidate integration related metrics
  packages/server/graphql/mutations/addAtlassianAuth.ts
  packages/server/graphql/mutations/addGitHubAuth.ts
  packages/server/graphql/mutations/addSlackAuth.ts
  packages/server/graphql/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/createTaskIntegration.ts
  packages/server/graphql/mutations/removeAtlassianAuth.ts
  packages/server/graphql/mutations/removeGitHubAuth.ts
  packages/server/graphql/mutations/removeSlackAuth.ts
  packages/server/graphql/mutations/removeTeamMemberIntegrationAuth.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required

#6619 chore: remove gitlab flag
  packages/client/components/ScopePhaseArea.tsx
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuSignup.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/server/graphql/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required

#6629 feat(standups): Improved standups options button size
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
Labels: One Review Required
