Repository ParabolInc/parabol, pull requests merged in 2022-11, with the labels that each got.

#7364 fix: Jira issues sometimes are not loading in poker meeting sidebar
  packages/server/dataloader/atlassianLoaders.ts
Labels: size/xs

#7367 chore: Remove @types/ioredis package
  packages/server/package.json
  yarn.lock
Labels: size/xs

#7365 fix(Azure DevOps): fix adding issues to Sprint Poker
  packages/client/components/AzureDevOpsScopingSearchResults.tsx
Labels: One Review Required, size/s

#7368 fix(Team): leave team does not work until refresh
  packages/client/modules/teamDashboard/components/LeaveTeamModal/LeaveTeamModal.tsx
  packages/client/modules/teamDashboard/components/ManageTeam/ManageTeamMember.tsx
  packages/client/mutations/RemoveTeamMemberMutation.ts
Labels: One Review Required, size/s

#7366 feat(metrics): disable Company properties update to HubSpot
  packages/server/utils/updateHubspot.ts
Labels: One Review Required, size/m

#7372 chore: Fix isPatient0 migration runtime
  packages/server/postgres/migrations/1666387804873_userPatient0.ts
Labels: One Review Required, size/s

#7346 feat: implement setIsFreeMeetingTemplate mutation
  codegen.json
  packages/server/database/types/MeetingTemplate.ts
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/private/mutations/setIsFreeMeetingTemplate.ts
  packages/server/graphql/private/typeDefs/setIsFreeMeetingTemplate.graphql
  packages/server/graphql/private/types/SetIsFreeMeetingTemplateSuccess.ts
Labels: Squad: 2, size/s

#7391 feat: add template limit feature flag
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: Squad: 2, One Review Required, size/xs

#7394 fix: header name should be more general
  packages/client/components/EditorHelpModal/EditorHelpModal.tsx
Labels: One Review Required

#7389 chore(CircleCI): split backup from deployment
  .circleci/config.yml
Labels: size/s

#7377 fix: update tier when leaving org
  packages/server/database/migrations/20221107180234-adjustUserTiers.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
Labels: Squad: 2, size/s

#7393 fix: added CorsOptions to email images
  packages/client/components/ExportToCSVButton.tsx
  packages/client/modules/email/components/EmailVerificationEmail.tsx
  packages/client/modules/email/components/Header/Header.tsx
  packages/client/modules/email/components/MeetingSummaryEmailRootSSR.tsx
  packages/client/modules/email/components/NotificationSummaryEmail.tsx
  packages/client/modules/email/components/ResetPasswordEmail.tsx
  packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/LogoFooter.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingSummaryEmail.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/SummaryEmailScheduleCalendar.tsx
  packages/client/modules/email/components/TeamInvite.tsx
  packages/client/modules/email/components/UpcomingInvoiceEmail.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/types/cors.ts
  packages/server/graphql/mutations/inviteToTeam.ts
Labels: size/m

#7361 fix: Send button is disabled in retro discussion on mobile
  packages/client/components/DiscussionThreadInput.tsx
Labels: One Review Required, size/s

#7203 fix: snackbar messages are not bottom centered during standups
  packages/client/components/Snackbar.tsx
Labels: One Review Required

#7403 fix: add delete confirmation button and waiting effect
  packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveTeam.tsx
  packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.tsx
Labels: size/s

#7400 chore: Cleanup packages to support future bundled server build
  package.json
  packages/client/utils/AtlassianManager.ts
  packages/server/GoogleLanguageManager.ts
  packages/server/email/createEmailVerification.ts
  packages/server/graphql/mutations/helpers/attemptLogin.ts
  packages/server/graphql/mutations/resetPassword.ts
  packages/server/graphql/mutations/signUpWithPassword.ts
  packages/server/graphql/private/mutations/removeAuthIdentity.ts
  packages/server/package.json
  packages/server/utils/AzureDevOpsServerManager.ts
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
  scripts/webpack/utils/clientTransformRules.js
  scripts/webpack/utils/transformRules.js
  yarn.lock
Labels: One Review Required, size/m

#7432 fix: snack on jira auth error
  packages/client/mutations/AddAtlassianAuthMutation.ts
  packages/server/graphql/mutations/addAtlassianAuth.ts
Labels: One Review Required, size/s

#7440 feat(teams-limit): add teams limit feature flag
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required, size/xs

#7382 feat(metrics): Remove HubSpot updates
  packages/server/utils/segmentIo.ts
  packages/server/utils/updateHubspot.ts
Labels: One Review Required, size/m

#7153 feat: add "go to dashboard" or "sign in" button to "invitation link expired" screen
  packages/client/components/InvitationLinkErrorExpired.tsx
  packages/server/graphql/queries/massInvitation.ts
Labels: size/s

#7461 fix(dx): Run all yarn clean commands, even if one fails
  package.json
Labels: One Review Required, size/xs

#7441 feat(teams-limit): add limit exceeded and locking flags
  packages/server/database/types/Organization.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/types/Organization.ts
Labels: size/s

#7452 feat: prevent cloning templates
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
Labels: size/s

#7460 feat: update selected template for free teams
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
Labels: size/s

#7491 fix(xss): Fix XSS Attack in template
  packages/client/components/TypeAheadLabel.tsx
  packages/client/package.json
  yarn.lock
Labels: size/s

#7446 feat: oauth2 redirect to cloudflare
  .env.example
  packages/client/types/modules.d.ts
  packages/client/utils/AtlassianClientManager.ts
  packages/client/utils/GitHubClientManager.ts
  packages/client/utils/SlackClientManager.ts
  packages/server/createSSR.ts
  packages/server/oauth2redirects.js
  packages/server/types/modules.d.ts
  packages/server/utils/AtlassianServerManager.ts
  packages/server/utils/SlackServerManager.ts
  scripts/webpack/dev.client.config.js
Labels: One Review Required, size/s

#7489 feat: prevent creating new templates from server
  packages/server/graphql/mutations/addPokerTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
Labels: size/s

#7493 feat: add ai summary feature flag
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required, size/xs

#7447 feat(notifications): Improved emails
  packages/client/modules/email/components/EmailNotifications/EmailKickedOut.tsx
  packages/client/modules/email/components/EmailNotifications/EmailMeetingStageTimeLimitEnd.tsx
  packages/client/modules/email/components/EmailNotifications/EmailNotificationPicker.tsx
  packages/client/modules/email/components/EmailNotifications/EmailNotificationTemplate.tsx
  packages/client/modules/email/components/EmailNotifications/EmailPromoteToBillingLeader.tsx
  packages/client/modules/email/components/EmailNotifications/EmailResponseMentioned.tsx
  packages/client/modules/email/components/EmailNotifications/EmailTeamArchived.tsx
  packages/client/modules/email/components/EmailNotifications/EmailTeamInvitation.tsx
  packages/client/modules/email/components/Header/Header.tsx
  packages/client/modules/email/components/NotificationSummaryEmail.tsx
  packages/client/modules/email/components/NotificationSummaryEmailRoot.tsx
  packages/server/email/notificationSummaryCreator.tsx
  packages/server/graphql/private/mutations/sendBatchNotificationEmails.ts
Labels: size/l

#7507 chore(ci): lint
  .github/workflows/check.yml
  .github/workflows/typecheck.yml
  nx.json
  package.json
  packages/client/components/Checkbox.tsx
  packages/client/components/JiraFieldMenu.tsx
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/UpgradeCreditCardFormField.tsx
  packages/client/components/UpgradeCreditCardFormFieldBlock.tsx
  packages/client/components/UpgradeCreditCardFormFieldIcon.tsx
  packages/client/components/UpgradeCreditCardNumberFormField.tsx
  packages/client/package.json
  packages/client/styles/theme/fontLoader.ts
  packages/integration-tests/tsconfig.json
  packages/server/database/types/JiraDimensionField.ts
  packages/server/graphql/public/typeDefs/updateJiraDimensionField.graphql
  packages/server/package.json
  packages/server/postgres/queries/getTeamsByIds.ts
  packages/server/postgres/queries/updateTeamByTeamId.ts
  packages/server/postgres/queries/upsertJiraDimensionFieldMap.ts
Labels: size/m
