Repository ParabolInc/parabol, pull requests merged in 2022-07, with the labels that each got.

#6834 feat(metrics): Add Segment event to track when onboarding user clicks the Demo Meeting Card
  packages/client/components/DemoMeetingCard.tsx
Labels: One Review Required

#6823 feat(standups): Decrease top/bottom list margins in standup response editor
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: Squad: 1, One Review Required

#6819 refactor: new GitHub & Jira issue queries
  packages/client/components/GitHubMenuItem.tsx
  packages/client/components/GitHubScopingSearchFilterMenu.tsx
  packages/client/components/GitLabMenuItem.tsx
  packages/client/components/JiraMenuItem.tsx
  packages/client/components/JiraScopingSearchResults.tsx
  packages/client/components/JiraServerMenuItem.tsx
  packages/client/components/MenuItemAvatar.tsx
  packages/client/components/NewGitHubIssueInput.tsx
  packages/client/components/NewGitHubIssueMenu.tsx
  packages/client/components/NewGitLabIssueMenu.tsx
  packages/client/components/NewJiraIssueInput.tsx
  packages/client/components/NewJiraIssueMenu.tsx
  packages/client/components/RepoIntegrationGitHubMenuItem.tsx
  packages/client/components/RepoIntegrationJiraMenuItem.tsx
  packages/client/components/TaskFooterIntegrateMenuList.tsx
  packages/client/hooks/useGetRepoContributions.ts
Labels: Squad: 3

#6878 feat(standups): Display standups as active instead of started
  packages/client/utils/meetings/lookups.ts
Labels: Squad: 1, One Review Required

#6881 fix: access more than 10 Jira projects in task footer
  packages/client/components/GitHubScopingSearchResults.tsx
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/server/graphql/queries/repoIntegrations.ts
  packages/server/graphql/types/TeamMember.ts
Labels: One Review Required, Squad: 3

#6901 fix: impersonate user bug
  packages/client/Atmosphere.ts
Labels: Squad: 3

#6911 feat: mattermost info icon
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
Labels: Squad: 3

#6892 feat(Azure DevOps): Add SaaS url to sprint poker estimation
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: enhancement

#6908 feat(metrics): Add more Segment events to Standups
  packages/server/graphql/mutations/addComment.ts
  packages/server/graphql/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/utils/analytics/analytics.ts
Labels: analytics, One Review Required

#6928 feat(standups): Beta badge within meeting
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/components/TeamPromptMeeting.tsx
Labels: One Review Required

#6967 fix: add query parameter to identify the page source
  packages/client/utils/makeAppURL.ts
  packages/server/graphql/mutations/helpers/addSeedTasks.ts
Labels: One Review Required
