Repository ParabolInc/parabol, pull requests merged in 2022-06, with the labels that each got.

#6476 feat(restrictDomains): Add table and mutations
  codegen.json
  packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx
  packages/client/package.json
  packages/client/validation/regex.ts
  packages/server/graphql/public/mutations/addApprovedOrganizationDomains.ts
  packages/server/graphql/public/mutations/removeApprovedOrganizationDomains.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/rules/isOrgTier.ts
  packages/server/graphql/public/rules/isViewerBillingLeader.ts
  packages/server/graphql/public/typeDefs/addApprovedOrganizationDomains.graphql
  packages/server/graphql/public/typeDefs/removeApprovedOrganizationDomains.graphql
  packages/server/graphql/public/types/AddApprovedOrganizationDomainsSuccess.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/RemoveApprovedOrganizationDomainsSuccess.ts
  packages/server/postgres/migrations/1651098260151_OrganizationApprovedDomains.ts
  packages/server/postgres/queries/generated/getApprovedOrganizationDomainsQuery.ts
  packages/server/postgres/queries/generated/insertApprovedOrganizationDomainsQuery.ts
  packages/server/postgres/queries/generated/removeApprovedOrganizationDomainsQuery.ts
  packages/server/postgres/queries/getApprovedOrganizationDomainsFromPG.ts
  packages/server/postgres/queries/insertApprovedOrganizationDomains.ts
  packages/server/postgres/queries/removeApprovedOrganizationDomainsToPG.ts
  packages/server/postgres/queries/src/getApprovedOrganizationDomainsQuery.sql
  packages/server/postgres/queries/src/insertApprovedOrganizationDomainsQuery.sql
  packages/server/postgres/queries/src/removeApprovedOrganizationDomainsQuery.sql
  yarn.lock
Labels: Squad: 3

#6658 feat(standups): Update relative `createdAt` automatically
  packages/client/components/TeamPrompt/TeamPromptLastUpdatedTime.tsx
Labels: One Review Required

#6667 fix(sprint-poker): Prevent kicking facilitator off the meeting while modifying the scope
  packages/client/mutations/UpdatePokerScopeMutation.ts
Labels: One Review Required

#6664 feat(domainStats): Support querying domain stat fields
  codegen.json
  packages/server/graphql/mutations/addFeatureFlag.ts
  packages/server/graphql/public/mutations/addFeatureFlag.ts
  packages/server/graphql/public/typeDefs/Company.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/AddFeatureFlagPayload.ts
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddFeatureFlagPayload.ts
  packages/server/graphql/types/Company.ts
  packages/server/graphql/types/NotificationSubscriptionPayload.ts
  packages/server/graphql/types/Organization.ts
  packages/server/graphql/types/User.ts
  packages/server/graphql/types/UserFeatureFlags.ts
Labels: One Review Required

#6183 feat(integration-tests): add more testing to the 2-minute demo
  .circleci/config.yml
  packages/client/components/NewMeetingSidebar.tsx
  packages/client/components/ReflectionGroupVoting.tsx
  packages/client/components/VoteSettingsStepper.tsx
  packages/client/modules/demo/components/CreateAccountSection.tsx
  packages/integration-tests/README.md
  packages/integration-tests/lint-staged.config.js
  packages/integration-tests/package.json
  packages/integration-tests/playwright.config.ts
  packages/integration-tests/tests/retrospective-demo/reflect.test.ts
  packages/integration-tests/tests/retrospective-demo/retrospective-demo-helpers.ts
  packages/integration-tests/tests/retrospective-demo/smoke.test.ts
  packages/integration-tests/tests/retrospective-demo/step1-reflect.test.ts
  packages/integration-tests/tests/retrospective-demo/step2-group.test.ts
  packages/integration-tests/tests/retrospective-demo/step3-vote.test.ts
  packages/integration-tests/tests/retrospective-demo/step4-discuss.test.ts
  packages/server/postgres/queries/generated/getBestTeamIntegrationAuthQuery.ts
  packages/server/postgres/queries/generated/getTeamMemberIntegrationAuthQuery.ts
  yarn.lock
Labels: Squad: 2

#6695 fix(standups): Discussion thread drawer is cut off on mobile
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
Labels: One Review Required

#6684 feat(standups): Standups responses grid UI improvements
  packages/client/components/TeamPrompt/TeamPromptGridDimensions.ts
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/TeamPromptMeeting.tsx
Labels: One Review Required

#6604 refactor: gitlab issues query part 2
  packages/client/components/GitLabScopingSearchResults.tsx
  packages/client/components/GitLabScopingSearchResultsRoot.tsx
  packages/client/mutations/connections/getGitLabProjectsConn.ts
  packages/client/mutations/connections/getGitLabProjectsIssuesConn.ts
  packages/client/mutations/handlers/handleGitLabCreateIssue.ts
  packages/server/graphql/nestedSchema/GitLab/queries/getProjectIssues.graphql
  packages/server/graphql/types/GitLabIntegration.ts
  packages/server/integrations/gitlab/GitLabServerManager.ts
Labels: Squad: 3

#6563 refactor: gitlab issues query part 1
  packages/client/components/GitLabScopingSearchResults.tsx
  packages/client/components/GitLabScopingSearchResultsRoot.tsx
  packages/client/mutations/connections/getGitLabProjectsConn.ts
  packages/client/mutations/connections/getGitLabProjectsIssuesConn.ts
  packages/client/mutations/handlers/handleGitLabCreateIssue.ts
  packages/server/graphql/nestedSchema/GitLab/queries/getProjectIssues.graphql
  packages/server/graphql/nestedSchema/GitLab/queries/getProjects.graphql
  packages/server/graphql/queries/helpers/fetchGitLabProjects.ts
  packages/server/graphql/types/GitLabIntegration.ts
  packages/server/integrations/gitlab/GitLabServerManager.ts
Labels: Squad: 3

#6713 feat: remove auth identity
  codegen.json
  packages/server/graphql/graphql.ts
  packages/server/graphql/mutations/emailPasswordReset.ts
  packages/server/graphql/mutations/helpers/processEmailPasswordReset.ts
  packages/server/graphql/private/mutations/removeAuthIdentity.ts
  packages/server/graphql/private/typeDefs/removeAuthIdentity.graphql
  packages/server/graphql/private/types/RemoveAuthIdentitySuccess.ts
Labels: Squad: 3

#6708 feat: change email domain
  codegen.json
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/private/typeDefs/changeEmailDomain.graphql
  packages/server/graphql/private/types/ChangeEmailDomainSuccess.ts
  packages/server/postgres/queries/generated/updateDomainsInOrganizationApprovedDomainQuery.ts
  packages/server/postgres/queries/generated/updateUserEmailDomainsQuery.ts
  packages/server/postgres/queries/src/updateDomainsInOrganizationApprovedDomainQuery.sql
  packages/server/postgres/queries/src/updateUserEmailDomainsQuery.sql
  packages/server/postgres/queries/updateDomainsInOrganizationApprovedDomainToPG.ts
  packages/server/postgres/queries/updateUserEmailDomainsToPG.ts
  yarn.lock
Labels: Squad: 3

#6722 fix(jira): Fix add missing jira field new algorithm
  packages/server/graphql/mutations/addMissingJiraField.ts
Labels: One Review Required

#6717 chore: update release_test.md
  .github/ISSUE_TEMPLATE/release_test.md
Labels: One Review Required

#6716 fix(poker): Fix wrong controls when estimating Parabol tasks
  packages/client/components/PokerDimensionValueControl.tsx
Labels: One Review Required

#6530 refactor: update createFragmentContainer to usePaginationFragment #6431
  packages/client/components/DashTopBar.tsx
  packages/client/components/Dashboard.tsx
  packages/client/components/MobileDashTopBar.tsx
  packages/client/components/MyDashboardTimeline.tsx
  packages/client/components/NotificationDropdown.tsx
  packages/client/components/NotificationRow.tsx
  packages/client/components/ParabolScopingSearchResults.tsx
  packages/client/components/ParabolScopingSearchResultsRoot.tsx
  packages/client/components/TimelineFeedList.tsx
  packages/client/components/TopBarNotifications.tsx
  packages/client/hooks/useLoadMoreOnScrollBottom.tsx
  packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingInvoices.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/containers/OrgBilling/OrgBillingRoot.tsx
  packages/client/modules/userDashboard/containers/OrgMembers/OrgMembersRoot.tsx
Labels: frontend, Squad: 2

#6703 feat: add integrations task for first-time users, use jsdom to attach the /integration link
  packages/client/utils/draftjs/convertToTaskContent.ts
  packages/server/graphql/mutations/helpers/addSeedTasks.ts
  packages/server/package.json
  packages/server/utils/draftjs/convertHtmlToTaskContent.ts
  packages/server/utils/draftjs/simpleDOMBuilder.ts
  yarn.lock
Labels: Squad: 2

#6732 fix: Center add/start meeting button content
  packages/client/components/StartMeetingFAB.tsx
  packages/client/components/TopBarStartMeetingButton.tsx
Labels: One Review Required

#6745 feat: add team charter template
  packages/server/database/migrations/20220614155505-addTeamCharterTemplate.ts
Labels: Squad: 3

#6736 fix: updates caniuse-lite version in yarn lock file
  package.json
  yarn.lock
Labels: Squad: 2, One Review Required

#6753 feat(standups): Make response in discussion drawer scrollable
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
Labels: One Review Required

#6754 fix(standups): Reduced list padding in standups response
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: Squad: 1, One Review Required

#6758 fix(standups): Editor doesn't work on Safari
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/package.json
  yarn.lock
Labels: Squad: 1, One Review Required

#6787 fix(standups): Allow reactjis to be added after initial response submission
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
Labels: One Review Required

#6795 fix: reuse invite link
  packages/client/mutations/AcceptTeamInvitationMutation.ts
Labels: Squad: 3

#6778 feat(standups): Response submission UX redesign
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: One Review Required

#6786 feat(insights): usage stats analytics
  packages/client/components/Insights.tsx
  packages/client/components/InsightsDomainNudge.tsx
  packages/server/graphql/types/SegmentEventTrackOptions.ts
Labels: Squad: 3

#6785 feat(insights): usage snack nag
  packages/client/components/Dashboard.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/hooks/useUsageSnackNag.ts
Labels: Squad: 3

#6733 feat: export admin data
  packages/client/components/ExportToCSVButton.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailExportCSVButton.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/containers/OrgMembers/OrgMembersRoot.tsx
Labels: Squad: 3

#6794 feat(Retrospective): Add more prominent enter to submit hint
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
Labels: Squad: 2

#6798 feat: retro template search filter
  packages/client/clientSchema.graphql
  packages/client/components/TypeAheadLabel.tsx
  packages/client/modules/meeting/components/ReflectTemplateItem.tsx
  packages/client/modules/meeting/components/ReflectTemplateList.tsx
  packages/client/modules/meeting/components/ReflectTemplateListOrg.tsx
  packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
  packages/client/modules/meeting/components/ReflectTemplateListTeam.tsx
  packages/client/modules/meeting/components/ReflectTemplateModal.tsx
  packages/client/modules/meeting/components/ReflectTemplateSearchBar.tsx
Labels: Squad: 3

#6701 feat(standups): Links
  packages/client/components/EditorLinkChanger/EditorLinkChangerDraftjs.tsx
  packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
  packages/client/components/EditorLinkChanger/EditorLinkChangerTipTap.tsx
  packages/client/components/EditorLinkViewer/EditorLinkViewer.tsx
  packages/client/components/EditorLinkViewer/EditorLinkViewerDraft.tsx
  packages/client/components/EditorLinkViewer/EditorLinkViewerTipTap.tsx
  packages/client/components/TaskEditor/useLinks.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/components/promptResponse/tiptapConfig.ts
  packages/client/package.json
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/updateJiraDimensionField.ts
  packages/server/graphql/mutations/updateTeamName.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/postgres/migrations/1625576993064_sortJiraDimensionFields.ts
  packages/server/utils/ensureJiraDimensionField.ts
  yarn.lock
Labels: Squad: 1
