Repository ParabolInc/parabol, pull requests merged in 2022-12, with the labels that each got.

#7363 feat(Sprint Poker): Hitting up and down arrow keys cycles through poker cards
  packages/client/components/PokerCardDeck.tsx
Labels: size/s

#7356 feat(metrics): Enable Google Analytics client side page_view tracking
  packages/client/components/AnalyticsPage.tsx
  packages/client/package.json
  packages/client/types/modules.d.ts
  packages/server/createSSR.ts
  packages/server/graphql/types/User.ts
  scripts/webpack/dev.client.config.js
  yarn.lock
Labels: One Review Required, size/s

#7514 fix: revert slack change until approval
  packages/client/utils/GitHubClientManager.ts
  packages/client/utils/SlackClientManager.ts
  packages/server/utils/SlackServerManager.ts
Labels: size/s

#7510 feat: add heard seen respected template
  packages/server/database/migrations/20221201121536-addHeardSeenRespectedTemplate.ts
Labels: size/m

#7492 fix: There should be no scroll bar on task header
  packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx
Labels: One Review Required, size/xs

#7527 feat(notifications): Remaining email notifications
  packages/client/modules/email/components/EmailNotifications/EmailNotificationPicker.tsx
  packages/client/modules/email/components/EmailNotifications/EmailPaymentRejected.tsx
  packages/client/modules/email/components/EmailNotifications/EmailTaskInvolves.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailTaskCard.tsx
Labels: One Review Required, size/m

#7533 feat(recurrence): added human readable recurring meeting indicator
  packages/client/components/TeamPrompt/Recurrence/HumanReadableRecurrenceRule.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/package.json
  yarn.lock
Labels: One Review Required, size/s

#7538 feat(recurrence): Added standups time left indicator
  packages/client/components/TeamPrompt/Recurrence/TimeLeftBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptMeetingStatus.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/client/utils/date/relativeDate.ts
  packages/server/graphql/public/mutations/startRecurrence.ts
Labels: One Review Required, size/m

#7523 fix(metrics): Always include email in traits for identify calls
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/helpers/updateUserProfile.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/private/mutations/autopauseUsers.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/mutations/disconnectSocket.ts
  packages/server/graphql/public/mutations/addFeatureFlag.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/setUserTierForUserIds.ts
Labels: One Review Required, size/m

#7546 feat(standups): Auto-open response discussion based on query param
  packages/client/components/ResponseMentioned.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/client/modules/email/components/EmailNotifications/EmailResponseMentioned.tsx
  packages/client/utils/makeAppURL.ts
Labels: One Review Required, size/s

#7551 fix(metrics): enable send_page_view on ReactGA initialization
  packages/client/components/AnalyticsPage.tsx
Labels: One Review Required, size/xs

#7175 feat(pg): support SSL certs
  .env.example
  packages/server/postgres/README.md
  packages/server/postgres/getPgConfig.ts
  packages/server/postgres/getPgSSL.js
  packages/server/postgres/pgmConfig.js
  packages/server/postgres/pgtypedConfig.js
Labels: size/s

#7532 chore: limit direct access to locked meetings
  packages/client/components/ActionMeeting.tsx
  packages/client/components/ActionMeetingLastCall.tsx
  packages/client/components/MeetingLockedOverlay.tsx
  packages/client/components/PokerMeeting.tsx
  packages/client/components/RetroMeeting.tsx
  packages/client/components/RetroMeetingSidebar.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
  packages/client/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.tsx
  packages/client/utils/meetings/isPhaseComplete.ts
  packages/server/graphql/types/NewMeeting.ts
Labels: One Review Required, size/m

#7534 feat(ai-summary): discussion summary in meeting summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/types/Discussion.ts
  packages/server/postgres/migrations/1670328109485_addSummaryToDiscussion.ts
  packages/server/postgres/queries/src/updateDiscussionsQuery.sql
  packages/server/postgres/queries/updateDiscussions.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/m

#7543 feat(ai-summary): whole meeting summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/server/database/types/Meeting.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/types/NewMeeting.ts
  packages/server/postgres/migrations/1670328109485_addSummaryToDiscussion.ts
Labels: size/m

#7561 chore(Jira): Add logging for some error cases
  packages/client/utils/AtlassianManager.ts
  packages/server/graphql/public/mutations/updateJiraDimensionField.ts
Labels: One Review Required, size/s

#7540 feat(dx/notifications): Make notification publishing generic
  codegen.json
  packages/client/components/NotificationPicker.tsx
  packages/client/mutations/UpsertTeamPromptResponseMutation.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/server/database/rethinkDriver.ts
  packages/server/graphql/public/mutations/helpers/publishNotification.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/graphql/public/typeDefs/AddedNotification.graphql
  packages/server/graphql/public/typeDefs/upsertTeamPromptResponse.graphql
  packages/server/graphql/public/types/AddedNotification.ts
  packages/server/graphql/public/types/UpsertTeamPromptResponseSuccess.ts
Labels: One Review Required, size/m

#7516 fix: Retrospective demo canonical link
  packages/server/createSSR.ts
Labels: One Review Required, size/xs

#7545 feat(ai-summary): add topic summary to discussion thread
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/client/utils/constants.ts
  packages/server/graphql/mutations/helpers/addSummariesToThreads.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/postgres/migrations/1670328109485_addSummaryToDiscussion.ts
  packages/server/postgres/migrations/1670438374119_addAIUser.ts
Labels: size/m

#7423 fix: prevent virtual keyboard hiding after submitting a comment on mobile
  packages/client/components/SendCommentButton.tsx
  packages/client/components/TaskEditor/CommentEditor.tsx
Labels: size/s

#7521 fix: upgrade daypicker
  packages/client/components/Action/Action.tsx
  packages/client/components/AddTeamMemberAvatarButton.tsx
  packages/client/components/DueDatePicker.tsx
  packages/client/components/SendCommentButton.tsx
  packages/client/components/StageTimerModalEndTime.tsx
  packages/client/components/StageTimerModalEndTimeDate.tsx
  packages/client/components/StageTimerModalEndTimeHour.tsx
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/package.json
  packages/client/styles/daypicker.css
  packages/client/styles/theme/globalStyles.ts
  packages/integration-tests/playwright.config.ts
  yarn.lock
Labels: size/m

#7547 feat(standups): Standup response replied-to notification
  codegen.json
  packages/client/components/NotificationPicker.tsx
  packages/client/components/ResponseMentioned.tsx
  packages/client/components/ResponseReplied.tsx
  packages/client/modules/email/components/EmailNotifications/EmailNotificationPicker.tsx
  packages/client/modules/email/components/EmailNotifications/EmailResponseReplied.tsx
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationResponseReplied.ts
  packages/server/graphql/mutations/addComment.ts
  packages/server/graphql/public/typeDefs/NotifyResponseReplied.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/NotifyResponseMentioned.ts
  packages/server/graphql/public/types/NotifyResponseReplied.ts
Labels: One Review Required, size/m

#7542 feat(recurrence): Added current meeting link to ended meeting badge in standups
  packages/client/components/TeamPrompt/Recurrence/TimeLeftBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptMeetingStatus.tsx
  packages/client/hooks/useAnimatedCard.ts
  packages/client/hooks/useTransition.ts
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/client/mutations/StartTeamPromptMutation.ts
  packages/client/utils/date/relativeDate.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: One Review Required, size/m

#7584 fix: bump sanitize-svg version
  packages/client/package.json
  packages/server/package.json
Labels: size/xs

#7581 fix: new meetings were locked with the history limit
  packages/server/graphql/types/NewMeeting.ts
  packages/server/graphql/types/helpers/isMeetingLocked.ts
Labels: size/xs

#7574 fix(notifications): Remove bad shortlinks + dead code
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/notifyMattermost.ts
Labels: One Review Required, size/m

#7576 chore: Add comments to rootSchema
  .vscode/launch.json
  packages/server/graphql/public/rootSchema.ts
Labels: size/s

#7526 feat(teams-limit): add addFeatureFlagToOrg mutation and support teams limit feature flag
  codegen.json
  packages/server/database/types/Organization.ts
  packages/server/graphql/private/mutations/addFeatureFlagToOrg.ts
  packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
  packages/server/graphql/private/types/AddFeatureFlagToOrgSuccess.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/m

#7429 fix: Organization Image is on top of default
  packages/client/components/Avatar/Avatar.tsx
  packages/client/components/OrgAvatarInput.tsx
Labels: size/xs

#7571 feat(ai-summary): ai explainer
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/client/types/constEnums.ts
  packages/server/graphql/mutations/helpers/addSummariesToThreads.ts
Labels: One Review Required, size/s

#7600 fix: access custom template
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
Labels: One Review Required

#7599 fix: new meetings were locked with the history limit
  packages/server/graphql/types/NewMeeting.ts
  packages/server/graphql/types/helpers/isMeetingLocked.ts
Labels: One Review Required, size/xs

#7594 chore(metrics): change upgrade CTA events to standard definitions
  packages/client/components/MeetingLockedOverlay.tsx
  packages/client/components/TimelineEventCompletedActionMeeting.tsx
  packages/client/components/TimelineEventCompletedRetroMeeting.tsx
  packages/client/components/TimelineEventPokerComplete.tsx
  packages/client/components/TimelineEventTeamPromptComplete.tsx
  packages/client/components/TimelineHistoryLockedCard.tsx
  packages/server/graphql/types/UpgradeCTALocationEnum.ts
Labels: analytics, One Review Required, size/s

#7563 feat(teams-limit): enable usage stats when teams limit exceeded
  packages/client/components/NotificationPicker.tsx
  packages/client/components/TeamsLimitExceededNotification.tsx
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationTeamsLimitExceeded.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/AddNotificationPayload.graphql
  packages/server/graphql/public/typeDefs/NotifyTeamsLimitExceeded.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/NotifyTeamsLimitExceeded.ts
  packages/server/graphql/types/NotificationEnum.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  yarn.lock
Labels: size/m

#7595 chore: add data team as reviewers for analytics changes
  .github/reviewers.yml
Labels: analytics, One Review Required, size/xs

#7578 fix: emoji length check
  packages/client/validation/Legitity.ts
  packages/server/graphql/mutations/helpers/validateScaleValue.ts
Labels: size/s

#7580 chore: Fix missing public types in private schema
  packages/server/graphql/private/rootSchema.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
Labels: size/m

#7572 feat(ai-summary): auto update meeting summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/types/MeetingSubscriptionPayload.ts
  packages/server/utils/publish.ts
Labels: size/s

#7604 fix: Broken summary pages
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
Labels: One Review Required, size/s
