Repository ParabolInc/parabol, pull requests merged in 2022-08, with the labels that each got.

#6983 fix(metrics): update activeUserCount & activeTeamCount for companies in HubSpot more often
  packages/server/utils/updateHubspot.ts
Labels: One Review Required

#6961 feat(standups): Added beta badge to standups on new meeting view
  packages/client/components/NewMeetingCarousel.tsx
Labels: One Review Required

#6981 feat(metrics): Refactor meeting related events
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/sendMeetingJoinToSegment.ts
  packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/startTeamPrompt.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/helpers.ts
Labels: One Review Required

#6885 feat(standups): Summary Page
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
  packages/client/components/TimelineEventTeamPromptComplete.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/QuickStats.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummary.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/makeTeamPromptStats.ts
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/server/graphql/mutations/endTeamPrompt.ts
  packages/server/graphql/public/typeDefs/TimelineEventTeamPromptComplete.graphql
  packages/server/graphql/public/types/TimelineEventTeamPromptComplete.ts
  packages/server/graphql/types/TeamPromptMeeting.ts
Labels: Squad: 1

#6879 feat(standups): Customized start standup notification
  packages/client/components/TeamPrompt/TeamPromptEditablePrompt.tsx
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Labels: Squad: 1

#6966 fix: allow to go to the discuss phase without voting
  packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts
  packages/server/database/types/DiscussStage.ts
Labels: One Review Required

#6991 feat(standups): Rename Async standup -> standup
  packages/client/components/MeetingCard.tsx
  packages/client/components/NewMeetingCarousel.tsx
  packages/client/modules/email/components/TeamInvite.tsx
  packages/server/database/types/MeetingTeamPrompt.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
Labels: One Review Required

#6962 feat: remove manual pausing
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/mutations/InactivateUserMutation.ts
  packages/client/types/constEnums.ts
  packages/server/graphql/mutations/inactivateUser.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/InactivateUserPayload.ts
Labels: Squad: 3

#6984 fix: Make new meeting dialog full screen on mobile
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingActions.tsx
Labels: One Review Required

#6900 feat: increase locking restrictions
  packages/client/mutations/AcceptTeamInvitationMutation.ts
  packages/client/types/constEnums.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/graphql/public/mutations/helpers/getIsAnyViewerTeamLocked.ts
Labels: Squad: 3

#6972 feat: meeting modal key shortcuts
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingActions.tsx
  packages/client/components/NewMeetingCarousel.tsx
Labels: Squad: 2, Squad: 3

#6964 fix: add billing info
  packages/client/modules/teamDashboard/components/ProviderRow/AzureDevOpsProviderRow.tsx
  packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts
  packages/server/graphql/queries/invoices.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: Squad: 3

#6955 fix(resetPassword): Reset request count daily
  packages/client/components/ForgotPasswordPage.tsx
  packages/server/graphql/mutations/emailPasswordReset.ts
Labels: One Review Required, Squad: 3

#6997 feat(metrics): Add `isActive` and `featureFlags` as new User Properties for Segment identify calls
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/public/mutations/addFeatureFlag.ts
Labels: One Review Required

#7003 feat(metrics): identify user's tier upon login
  packages/server/graphql/private/mutations/connectSocket.ts
Labels: One Review Required

#7027 fix: fix truncated sprint poker description in new meeting dialog
  packages/client/components/NewMeeting.tsx
Labels: One Review Required

#7009 fix(metrics): remove duplicate viewerId in various Segment events
  packages/client/components/DemoMeetingCard.tsx
  packages/client/components/ErrorBoundary.tsx
  packages/client/components/GitLabScopingSearchFilterMenu.tsx
  packages/client/components/ScopingSearchInput.tsx
  packages/client/components/SpotlightSearchBar.tsx
  packages/client/components/TutorialMeetingCard.tsx
  packages/client/hooks/useAnimatedSpotlightSource.ts
  packages/client/hooks/useDraggableReflectionCard.tsx
  packages/client/hooks/useSpotlightSimulatedDrag.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/JiraServerProviderRow.tsx
  packages/client/mutations/SendClientSegmentEventMutation.ts
  packages/client/mutations/UpdatePokerScopeMutation.ts
  packages/client/utils/getSearchQueryFromMeeting.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
Labels: One Review Required

#7008 fix: bug that set org count to 0
  packages/client/components/InsightsCharts.tsx
  packages/server/graphql/public/types/Company.ts
  packages/server/postgres/pgtypedConfig.js
Labels: Squad: 3

#7010 feat(metrics): Use HubSpot Private apps access token for HubSpot calls
  packages/server/utils/updateHubspot.ts
Labels: One Review Required

#7029 fix(standups): Update 'lastMeetingType' after a team prompt meeting starts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/startTeamPrompt.ts
Labels: One Review Required

#7052 fix: Don't import team prompt summary for SSR
  CHANGELOG.md
  lerna.json
  package.json
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/package.json
  packages/gql-executor/package.json
  packages/server/package.json
Labels: One Review Required

#7058 feat(metrics): add 'inviterId' to Invite Accepted events
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required

#7066 fix: remove double scrollbar on discuss phase
  packages/client/components/RetroDiscussPhase.tsx
Labels: One Review Required, Squad: 3

#7064 feat: add scrum template
  packages/server/database/migrations/20220815156512-addScrumValuesTemplate.ts
Labels: Squad: 3

#7007 feat: implement azure task integration
  packages/client/components/AddToAzureMenuItem.tsx
  packages/client/components/AzureDevOpsScopingSearchResults.tsx
  packages/client/components/GitHubMenuItem.tsx
  packages/client/components/GitLabMenuItem.tsx
  packages/client/components/IntegratedTaskContent.tsx
  packages/client/components/JiraMenuItem.tsx
  packages/client/components/JiraServerMenuItem.tsx
  packages/client/components/NewGitHubIssueMenu.tsx
  packages/client/components/NewGitLabIssueMenu.tsx
  packages/client/components/NewJiraIssueMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuList.tsx
  packages/client/components/TaskFooterIntegrateMenuSignup.tsx
  packages/client/components/TaskIntegrationLink.tsx
  packages/client/components/TaskIntegrationMenuItem.tsx
  packages/client/components/TaskWatermark.tsx
  packages/client/mutations/CreateTaskIntegrationMutation.ts
  packages/client/shared/gqlIds/AzureDevOpsProjectId.ts
  packages/client/shared/gqlIds/IntegrationRepoId.ts
  packages/client/types/constEnums.ts
  packages/client/utils/AzureDevOpsClientManager.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/graphql/mutations/createTaskIntegration.ts
  packages/server/graphql/mutations/helpers/createTaskInService.ts
  packages/server/graphql/queries/helpers/fetchAllRepoIntegrations.ts
  packages/server/graphql/types/AzureDevOpsRemoteProject.ts
  packages/server/graphql/types/Task.ts
  packages/server/integrations/TaskIntegrationManagerFactory.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/getAzureOrgNameFromURL.ts
  packages/server/utils/makeCreateAzureTaskComment.ts
Labels: Squad: 2, Squad: 3

#7085 fix(integrations): Not working integrate task menu
  packages/client/components/TaskIntegrationMenuItem.tsx
Labels: One Review Required

#7091 fix: show the team lead first in the preview of team selector
  packages/client/components/NewMeetingTeamPickerAvatars.tsx
Labels: One Review Required

#6940 fix: Contrast of selected highlight of the current phase is low
  packages/client/components/MeetingSubnavItem.tsx
  packages/client/components/NewMeetingSidebarPhaseListItem.tsx
Labels: One Review Required

#7078 fix: hyperlink default focus
  packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
Labels: Squad: 1, One Review Required, Squad: 3

#7065 fix: demo comments are always anonymous
  packages/client/components/ThreadedCommentHeader.tsx
  packages/client/modules/demo/commentLookup.ts
  packages/client/modules/demo/initDB.ts
  packages/integration-tests/tests/retrospective-demo/step4-discuss.test.ts
Labels: Squad: 3

#7077 chore: update vscode import settings
  .vscode/settings.json
Labels: Squad: 3

#7079 fix: center new meeting dialog slides on mobile
  packages/client/components/NewMeetingCarousel.tsx
Labels: One Review Required

#6942 feat(retro): prompt user to go to next phase or end meeting
  packages/client/components/BottomControlBarReady.tsx
  packages/client/components/BottomControlBarReadyButton.tsx
  packages/client/components/BottomControlBarTips.tsx
  packages/client/components/BottomNavControl.tsx
Labels: Squad: 2

#7102 feat(tiptap): Emoji Support
  packages/client/components/EmojiMenu.tsx
  packages/client/components/TaskEditor/EmojiMenuContainer.tsx
  packages/client/components/TaskEditor/useEmojis.tsx
  packages/client/components/TaskEditor/withEmojis.tsx
  packages/client/components/promptResponse/EmojiMenuTipTap.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/components/promptResponse/tiptapConfig.ts
  packages/client/package.json
  yarn.lock
Labels: One Review Required

#7109 fix(DX): Fix the PR labeler
  .github/workflows/labeler.yml
Labels: size/xs

#7063 feat(dd sourcemaps): add source maps to deploy. fix(deploy): using staging .env, reverted code to
  .circleci/config.yml
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
Labels: size/s

#7115 fix: increased the line-height of text in Standup responses
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: Squad: 1, One Review Required

#7067 feat(metrics): clean up some properties for Task Created events
  packages/client/components/ErrorBoundary.tsx
  packages/client/mutations/CreateTaskIntegrationMutation.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/createTaskIntegration.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  packages/server/graphql/types/Task.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/m

#7096 fix(New meeting dialog): truncate template dropdown text
  packages/client/components/DropdownToggleInner.tsx
Labels: Squad: 2

#7093 fix: azure work item id & change item link to project name
  packages/client/components/AzureDevOpsScopingSearchResultItem.tsx
  packages/client/components/AzureDevOpsScopingSearchResults.tsx
  packages/client/mutations/CreateTaskMutation.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/graphql/types/AzureDevOpsRemoteProject.ts
  packages/server/graphql/types/AzureDevOpsWorkItem.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/azureDevOps/azureDevOpsFieldTypeToId.ts
Labels: size/m, Squad: 3

#7097 fix: azure refresh auth
  packages/server/dataloader/azureDevOpsLoaders.ts
Labels: Squad: 3

#7132 fix: Changed copy on /create-account page
  packages/client/components/AuthenticationPage.tsx
Labels: One Review Required, size/xs

#7117 feat(metrics): Add Task Estimate Set event
  packages/server/graphql/mutations/setTaskEstimate.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/m

#7129 feat(metrics): identify if user is patient 0 upon login
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/isPatientZero.ts
  packages/server/graphql/mutations/helpers/updateUserProfile.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/types/User.ts
  packages/server/postgres/queries/getPatientZeroByDomain.ts
  packages/server/postgres/queries/src/getPatientZeroByDomainQuery.sql
Labels: One Review Required, size/s

#7112 feat: usage stats clarity improvements
  packages/client/components/Insights.tsx
  packages/client/components/InsightsCharts.tsx
  packages/client/components/InsightsDomainPanel.tsx
Labels: size/m, Squad: 3

#7049 feat(standups): Recurrence - restart recurrence in `startRecurrence` mutation
  codegen.json
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startRecurrence.ts
  packages/server/graphql/public/mutations/stopRecurrence.ts
  packages/server/postgres/queries/getMeetingSeriesByIds.ts
  packages/server/postgres/queries/restartMeetingSeries.ts
  packages/server/postgres/queries/src/restartMeetingSeriesByIdQuery.sql
  packages/server/postgres/types/MeetingSeries.ts
  packages/server/utils/analytics/analytics.ts
Labels: Squad: 1, size/m

#7135 feat(dx): createFragmentContainer -> useFragment codeshift automation
  scripts/codeshift/convertToUseFragment.ts
Labels: size/m
