Repository ParabolInc/parabol, pull requests merged in 2022-10, with the labels that each got.

#7228 chore: update code review policy
  docs/codeReview.md
Labels: size/s

#7105 feat(standups): Starting and stopping recurrence from meeting menu
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
  packages/client/mutations/StopRecurrenceMutation.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/public/mutations/stopRecurrence.ts
  packages/server/graphql/public/typeDefs/MeetingSeries.graphql
  packages/server/graphql/public/typeDefs/stopRecurrence.graphql
  packages/server/graphql/public/types/MeetingSeries.ts
  packages/server/graphql/public/types/StopRecurrenceSuccess.ts
  packages/server/graphql/types/NewMeeting.ts
Labels: size/m

#6910 feat(Retro): Prompt user to drag cards in group phase
  packages/client/components/DiscussPhaseReflectionGrid.tsx
  packages/client/components/GroupingKanban.tsx
  packages/client/components/GroupingKanbanColumn.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionCard/ReflectionCardRoot.tsx
  packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx
  packages/client/components/ReflectionGroup/ReflectionGroup.tsx
  packages/client/components/RetroReflectPhase/ReflectionStack.tsx
  packages/client/hooks/useDraggableReflectionCard.tsx
Labels: enhancement

#7147 feat: show users who added a reactji
  packages/client/components/ReflectionCard/EmojiUsersReaction.tsx
  packages/client/components/ReflectionCard/ReactjiCount.tsx
  packages/client/components/ReflectionCard/ReactjiSection.tsx
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/client/mutations/AddReactjiToReactableMutation.ts
  packages/client/types/constEnums.ts
  packages/client/types/modules.d.ts
  packages/server/graphql/types/Reactji.ts
  packages/server/utils/getGroupedReactjis.ts
Labels: size/m

#7209 chore: bootstrap release-release for automatic changelog & version changes
  .github/workflows/release-hotfix.yml
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size/s

#7255 fix: unsubscribe analytics bug
  packages/server/utils/analytics/analytics.ts
Labels: Squad: 2, size/xs

#7261 feat(metrics): Send isPatient0 property to Google Analytics
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/isPatientZero.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/s

#7269 fix: participants follow facilitator
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/TaskEditor/CommentEditor.tsx
Labels: size/s

#7285 feat: show you in emoji list instead of viewer name
  packages/client/components/ReflectionCard/EmojiUsersReaction.tsx
Labels: Squad: 2, One Review Required, size/s

#7267 fix: assign new billing leader after deleting billing leader
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
Labels: Squad: 2, size/s

#7279 fix: missing daki prompt
  packages/server/database/migrations/20221012142324-fixDakiMigration.ts
Labels: Squad: 2, size/s

#7286 feat(notifications): Batch notification emails - improve who gets emails
  packages/client/modules/email/components/NotificationSummaryEmail.tsx
  packages/server/graphql/private/mutations/sendBatchNotificationEmails.ts
Labels: One Review Required

#7257 fix(Jira): show only available fields in Sprint Poker
  packages/client/components/AddMissingJiraFieldModal.tsx
  packages/client/components/JiraFieldDimensionDropdown.tsx
  packages/client/components/JiraFieldMenu.tsx
  packages/client/components/PokerDimensionValueControl.tsx
  packages/client/components/PokerDiscussVoting.tsx
  packages/client/components/useSetTaskEstimate.ts
  packages/client/mutations/AddMissingJiraFieldMutation.ts
  packages/client/mutations/UpdateAzureDevOpsDimensionFieldMutation.ts
  packages/client/mutations/UpdateJiraDimensionFieldMutation.ts
  packages/client/mutations/UpdateJiraServerDimensionFieldMutation.ts
  packages/client/utils/AtlassianManager.ts
  packages/server/database/migrations/20210624121905-sortJiraDimensionFields.ts
  packages/server/database/types/JiraDimensionField.ts
  packages/server/database/types/Team.ts
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/graphql/mutations/addMissingJiraField.ts
  packages/server/graphql/mutations/setTaskEstimate.ts
  packages/server/graphql/mutations/updateJiraDimensionField.ts
  packages/server/graphql/mutations/updatePokerScope.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/updateJiraDimensionField.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/updateJiraDimensionField.graphql
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddMissingJiraFieldPayload.ts
  packages/server/graphql/types/AtlassianTeamIntegration.ts
  packages/server/graphql/types/AzureDevOpsTeamIntegration.ts
  packages/server/graphql/types/EstimateStage.ts
  packages/server/graphql/types/JiraDimensionField.ts
  packages/server/graphql/types/JiraIssue.ts
  packages/server/graphql/types/Team.ts
  packages/server/graphql/types/TeamIntegrations.ts
  packages/server/graphql/types/TeamSubscriptionPayload.ts
  packages/server/graphql/types/UpdateJiraDimensionFieldPayload.ts
  packages/server/postgres/migrations/1625576993064_sortJiraDimensionFields.ts
  packages/server/postgres/migrations/1663850062796_JiraDimensionFieldMap.ts
  packages/server/postgres/queries/getJiraDimensionFieldMap.ts
  packages/server/postgres/queries/getTeamsByIds.ts
  packages/server/postgres/queries/src/getJiraDimensionFieldMapQuery.sql
  packages/server/postgres/queries/src/updateJiraDimensionFieldMapQuery.sql
  packages/server/postgres/queries/src/updateTeamByOrgIdQuery.sql
  packages/server/postgres/queries/src/updateTeamByTeamIdQuery.sql
  packages/server/postgres/queries/src/upsertJiraDimensionFieldMapQuery.sql
  packages/server/postgres/queries/updateJiraDimensionFieldMap.ts
  packages/server/postgres/queries/updateTeamByTeamId.ts
  packages/server/postgres/queries/upsertJiraDimensionFieldMap.ts
  packages/server/utils/atlassian/jiraFields.ts
  packages/server/utils/ensureJiraDimensionField.ts
Labels: size/xl

#7258 chore: use SDL for JiraIssue
  codegen.json
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/graphql/public/typeDefs/AtlassianIntegration.graphql
  packages/server/graphql/public/typeDefs/JiraIssue.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/AtlassianIntegration.ts
  packages/server/graphql/public/types/JiraIssue.ts
  packages/server/graphql/queries/helpers/connectionFromTasks.ts
  packages/server/graphql/types/AtlassianIntegration.ts
  packages/server/graphql/types/JiraIssue.ts
  packages/server/graphql/types/JiraRemoteProject.ts
  packages/server/graphql/types/NotificationSubscriptionPayload.ts
  packages/server/utils/publish.ts
Labels: size/l

#7264 fix(Jira): Link to documentation if we cannot find a story point field
  packages/client/components/JiraFieldDimensionDropdown.tsx
  packages/client/components/JiraFieldMenu.tsx
  packages/client/types/constEnums.ts
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/graphql/public/typeDefs/JiraIssue.graphql
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  packages/server/utils/atlassian/jiraFields.ts
Labels: size/m

#7300 chore: Fix missing types
  packages/client/components/EditorLinkChanger/EditorLinkChangerDraftjs.tsx
Labels: size/xs

#7296 chore: Run auto assign reviewer workflow on pull request target
  .github/workflows/assign_reviewers.yml
Labels: size/xs

#7317 fix(Retro): a card dragged from an expanded group disappeared
  packages/client/hooks/useDraggableReflectionCard.tsx
Labels: size/xs

#7313 feat: end meeting from meetings view
  packages/client/components/MeetingCardOptionsMenu.tsx
Labels: Squad: 2, size/s

#7324 fix: add noindex for ppmis
  packages/server/createSSR.ts
Labels: One Review Required, size/xs

#7323 feat: rename christmas template
  packages/server/database/migrations/20221021163318-rename-christmas-template.ts
Labels: Squad: 2, One Review Required, size/s

#7326 chore: Fix whitespace in links
  packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
Labels: size/xs

#7320 fix(metrics): set disableAnonymity default to false in Meeting related events
  packages/server/utils/analytics/helpers.ts
Labels: One Review Required, size/xs

#7337 fix: EstimateStage was broken for Jira if the issue could not be fetched
  packages/server/graphql/types/EstimateStage.ts
Labels: size/xs

#7234 feat: speed up repo integrations query
  packages/client/components/GitHubScopingSearchResults.tsx
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuList.tsx
  packages/client/hooks/useAllIntegrations.ts
  packages/client/mutations/AddAtlassianAuthMutation.ts
  packages/client/mutations/AddGitHubAuthMutation.ts
  packages/client/shared/gqlIds/IntegrationRepoId.ts
  packages/server/dataloader/RedisCache.ts
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/graphql/mutations/addAtlassianAuth.ts
  packages/server/graphql/mutations/addGitHubAuth.ts
  packages/server/graphql/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/createTaskIntegration.ts
  packages/server/graphql/mutations/editCommenting.ts
  packages/server/graphql/mutations/helpers/createGitLabTask.ts
  packages/server/graphql/mutations/helpers/createTaskInService.ts
  packages/server/graphql/mutations/helpers/getUsersToIgnore.ts
  packages/server/graphql/mutations/removeAtlassianAuth.ts
  packages/server/graphql/mutations/removeGitHubAuth.ts
  packages/server/graphql/mutations/removeTeamMemberIntegrationAuth.ts
  packages/server/graphql/queries/allAvailableRepoIntegrations.ts
  packages/server/graphql/queries/helpers/fetchAllRepoIntegrations.ts
  packages/server/graphql/queries/helpers/fetchGitHubRepos.ts
  packages/server/graphql/queries/helpers/fetchGitLabProjects.ts
  packages/server/graphql/queries/helpers/getAllCachedRepoIntegrations.ts
  packages/server/graphql/queries/helpers/getPrevUsedRepoIntegrations.ts
  packages/server/graphql/queries/helpers/repoIntegrationHelpers.ts
  packages/server/graphql/queries/helpers/sortRepoIntegrations.ts
  packages/server/graphql/queries/helpers/updateRepoIntegrationsCacheByPerms.ts
  packages/server/graphql/queries/repoIntegrations.ts
  packages/server/graphql/types/TeamMember.ts
  packages/server/integrations/jiraServer/JiraServerRestManager.ts
  packages/server/integrations/updatePrevUsedRepoIntegrationsCache.ts
  packages/server/package.json
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/GraphQLRedisPubSub.ts
  packages/server/utils/PubSubPromise.ts
  packages/server/utils/getAllRepoIntegrationsRedisKey.ts
  packages/server/utils/getListeningUserIds.ts
  packages/server/utils/getPrevUsedRepoIntegrationsRedisKey.ts
  packages/server/utils/getPubSub.ts
  packages/server/utils/getRedis.ts
  packages/server/utils/getTaskServicesWithPerms.ts
  yarn.lock
Labels: size/xl

#7312 fix: avoid overriding custom group name with a single card
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
Labels: size/s

#7345 feat: add isFree to meeting template
  packages/server/database/migrations/20221025161717-addIsFreeMeetingTemplate.ts
  packages/server/database/types/MeetingTemplate.ts
  packages/server/graphql/types/MeetingTemplate.ts
  packages/server/utils/analytics/helpers.ts
Labels: size/s

#7354 fix: task integration demo bug
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/client/modules/demo/initDB.ts
Labels: size/s

#7327 feat(standups): Added ended meeting view
  packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/client/components/promptResponse/tiptapConfig.ts
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
Labels: One Review Required, size/m

#7315 fix: use fallback values for PokerCardDeck
  packages/client/components/PokerCardDeck.tsx
Labels: One Review Required, size/s

#7325 fix: put isPatient0 on User row
  packages/server/__tests__/user.test.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/isPatientZero.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/types/User.ts
  packages/server/postgres/migrations/1642094555266_addJiraServerIntegrationProvider.ts
  packages/server/postgres/migrations/1644936872423_addTeamPromptResponseTable.ts
  packages/server/postgres/migrations/1651778831990_addMSTeamsIntegrationProvider.ts
  packages/server/postgres/migrations/1654861495447_addIntegrationSearchQuery.ts
  packages/server/postgres/migrations/1654861495450_migrateSecureDomain.ts
  packages/server/postgres/migrations/1656389795923_addAzureDevOpsDimensionFieldMapWorkItemType.ts
  packages/server/postgres/migrations/1659973034251_alterMeetingSeries.ts
  packages/server/postgres/migrations/1663850062796_JiraDimensionFieldMap.ts
  packages/server/postgres/migrations/1666387804873_userPatient0.ts
  packages/server/postgres/queries/getAUserForDomain.ts
  packages/server/postgres/queries/getPatientZeroByDomain.ts
  packages/server/postgres/queries/src/getAUserForDomainQuery.sql
  packages/server/postgres/queries/src/getPatientZeroByDomainQuery.sql
  packages/server/postgres/queries/src/insertUserQuery.sql
Labels: size/m

#7357 feat(timer picker): add 10 minutes option
  packages/client/components/StageTimerMinutePicker.tsx
Labels: One Review Required
