Repository ParabolInc/parabol, pull requests merged in 2022-09, with the labels that each got.

#7142 style: increase font size of standup meeting title
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Labels: Squad: 1, One Review Required, size/xs

#7111 chore: add pull-request-stats github workflow
  .github/workflows/stats.yml
Labels: size/s, pr_stats

#7131 fix(demo): prevent demo meeting auto-start after page refresh
  packages/client/components/BeginDemoModal.tsx
  packages/client/components/BottomControlBarTips.tsx
  packages/client/hooks/useDemoMeeting.tsx
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/client/modules/demo/initDB.ts
Labels: Squad: 2, size/s

#7138 fix(demo): card quick return to original position without hangs
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
Labels: Squad: 2, size/s

#7172 chore: Automatically add reviewers
  .github/reviewers.yml
  .github/workflows/assign_reviewers.yml
Labels: One Review Required, size/s

#7176 fix: only check clientGraphQLServer for isDemoRoute
  packages/client/components/BottomControlBarTips.tsx
Labels: One Review Required, size/xs

#7170 fix(poker): fix an bug where task estimate is not written to DB when it's a Parabol task
  packages/server/graphql/mutations/setTaskEstimate.ts
Labels: One Review Required, size/xs

#7171 feat(metrics): Add metrics about `disableAnonymity` in retro meetings
  packages/server/graphql/mutations/setMeetingSettings.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/helpers.ts
Labels: size/s

#7184 ci: update to Lerna V5 and integrate with Nx
  lerna.json
  nx.json
  package.json
  yarn.lock
Labels: size/xl

#7195 ci: setting write permissions to the PR for external contributor
  .github/workflows/assign_reviewers.yml
Labels: One Review Required, size/xs

#7189 chore: add Standup smoke test into the testing basics
  .github/ISSUE_TEMPLATE/release_test.md
Labels: One Review Required, size/xs

#7205 chore: Weekly review stats in Slack
  .github/workflows/stats.yml
  scripts/reviewStats.ts
Labels: size/m

#7198 fix: Fix cannot read email of undefined in ErrorBoundary
  packages/client/components/ErrorBoundary.tsx
Labels: One Review Required, size/xs

#7216 fix: disable the Nx parallel run precommit
  package.json
Labels: One Review Required, size/xs

#7183 feat: add password reset to user profile
  packages/client/components/Panel/Panel.tsx
  packages/client/components/PasswordResetLink.tsx
  packages/client/components/StandardHubUserMenu.tsx
  packages/client/modules/userDashboard/components/UserProfile.tsx
  static/images/icons/password_black_24dp.svg
Labels: Squad: 2, One Review Required, size/m

#7180 chore: Add jira server key generation script
  scripts/create-jira-keys.sh
Labels: size/s

#7219 chore: Use separate PAT for auto assigning reviewers
  .github/workflows/assign_reviewers.yml
Labels: One Review Required, size/xs

#7224 fix(notifications): UTM params on notification email link
  packages/client/modules/email/components/NotificationSummaryEmail.tsx
Labels: One Review Required, size/xs

#7227 chore: Tweak review stats schedule to match other reminders
  .github/workflows/stats.yml
Labels: size/xs

#7226 feat: let super users invite to team
  packages/server/graphql/mutations/inviteToTeam.ts
Labels: enhancement, Squad: 2, One Review Required, size/xs

#7190 feat: unsubscribe from summary emails
  codegen.json
  packages/client/components/EmailNotifications.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/LogoFooter.tsx
  packages/client/modules/userDashboard/components/UserProfile.tsx
  packages/client/mutations/ToggleSummaryEmailMutation.ts
  packages/server/database/types/User.ts
  packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts
  packages/server/graphql/public/mutations/toggleSummaryEmail.ts
  packages/server/graphql/public/typeDefs/toggleSummaryEmail.graphql
  packages/server/graphql/public/types/ToggleSummaryEmailSuccess.ts
  packages/server/graphql/types/User.ts
  packages/server/postgres/migrations/1663254566765_addSendSummaryEmailToUser.ts
  packages/server/postgres/queries/src/updateUserQuery.sql
  packages/server/utils/analytics/analytics.ts
Labels: Squad: 2, size/m

#7232 feat(analytics): 'Copied Invite Link' event
  packages/client/components/CopyLink.tsx
  packages/client/components/MassInvitationTokenLink.tsx
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/modules/meeting/components/CopyShortLink/CopyShortLink.tsx
Labels: One Review Required, size/s

#7231 feat(analytics): 'Sent invite accepted' event
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/xs

#7237 chore: boot message changed to include Server ID and task.
  packages/gql-executor/gqlExecutor.ts
  packages/server/listenHandler.ts
Labels: One Review Required, size/xs

#7141 style: replace back arrow with logo
  packages/client/components/LogoBlock/LogoBlock.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Labels: Squad: 1, size/s

#7238 fix: Autofocus the input in the discussion drawer when opened
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/TaskEditor/CommentEditor.tsx
Labels: size/s

#7225 feat(notifications): Auto-open notifications from email
  packages/client/components/TopBarNotifications.tsx
  packages/client/modules/email/components/NotificationSummaryEmail.tsx
  packages/client/utils/makeAppURL.ts
Labels: size/s

#7239 fix: Hover over avatar to see names not working for some users
  packages/client/components/ActionMeeting.tsx
  packages/client/components/PokerMeeting.tsx
  packages/client/components/RetroMeeting.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatar.tsx
  packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatarGroup.tsx
Labels: size/m

#6998 chore(security): upgrade node to 16.16.0
  .circleci/config.yml
  .github/workflows/typecheck.yml
  docker/Dockerfile.prod
  package.json
  packages/gql-executor/package.json
  packages/integration-tests/package.json
  packages/server/package.json
  yarn.lock
Labels: size/s

#7230 chore(Review stats): Count IssueComment events towards comment count
  scripts/reviewStats.ts
Labels: One Review Required, size/s

#7242 chore: Use correct node version for review stats
  .github/workflows/stats.yml
Labels: size/xs
