Repository ParabolInc/parabol, pull requests merged in 2022-02, with the labels that each got.

#5481 Add GraphQL server tests to circle ci
  .circleci/config.yml
  packages/server/__tests__/jiraServerIntegration.test.ts
  packages/server/email/getMailManager.ts
  packages/server/package.json
  yarn.lock
Labels: DX, devops

#5990 feat(dd-rum): identify user on Datadog session
  packages/client/Atmosphere.ts
  packages/client/components/AnalyticsPage.tsx
Labels: analytics

#5961 feat(integration-tests): add integration tests using Playwright
  .circleci/config.yml
  packages/integration-tests/.eslintignore
  packages/integration-tests/.eslintrc.js
  packages/integration-tests/.gitignore
  packages/integration-tests/README.md
  packages/integration-tests/lint-staged.config.js
  packages/integration-tests/package.json
  packages/integration-tests/playwright.config.ts
  packages/integration-tests/tests/config.ts
  packages/integration-tests/tests/retrospective-demo/reflect.test.ts
  packages/integration-tests/tests/retrospective-demo/smoke.test.ts
  packages/integration-tests/tsconfig.json
  yarn.lock
Labels: discussion

#6104 build(server): fix jest transforms
  packages/server/jest.config.js
  packages/server/package.json
  yarn.lock
Labels: bug, devops, backend
