Repository ParabolInc/parabol, pull requests merged in 2023-07, with the labels that each got.

#8440 feat(suggest-groups): add loading feedback while waiting for OpenAI response
  codegen.json
  packages/client/components/RetroGroupPhase.tsx
  packages/client/mutations/fragments/GenerateGroupsFrag.ts
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/public/typeDefs/GenerateGroupsSuccess.graphql
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/types/GenerateGroupsSuccess.ts
Labels: size/s

#8445 feat(suggest-groups): add reset groups button
  codegen.json
  packages/client/components/RetroGroupPhase.tsx
  packages/client/mutations/AutogroupMutation.ts
  packages/client/mutations/ResetReflectionGroupsMutation.ts
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/public/mutations/autogroup.ts
  packages/server/graphql/public/mutations/resetReflectionGroups.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/generateGroups.graphql
  packages/server/graphql/public/typeDefs/resetReflectionGroups.graphql
  packages/server/graphql/public/types/ResetReflectionGroupsSuccess.ts
  packages/server/graphql/types/RetrospectiveMeeting.ts
Labels: size/m

#8473 chore: add task and comment to release checks
  .github/ISSUE_TEMPLATE/release_test.md
Labels: One Review Required, size/xs

#8474 chore: hide invoices for enterprise users
  packages/client/modules/userDashboard/components/OrgBilling/OrgBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
Labels: One Review Required, size/s

#8461 fix: upgrade graphiql
  packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx
  packages/client/package.json
  yarn.lock
Labels: size/s

#8450 chore: add radix Dialog component
  packages/client/components/ShareTopicModal.tsx
  packages/client/components/ShareTopicRoot.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
  packages/client/package.json
  packages/client/tailwindTheme.ts
  packages/client/ui/Dialog/Dialog.tsx
  packages/client/ui/Dialog/DialogActions.tsx
  packages/client/ui/Dialog/DialogClose.tsx
  packages/client/ui/Dialog/DialogContent.tsx
  packages/client/ui/Dialog/DialogDescription.tsx
  packages/client/ui/Dialog/DialogOverlay.tsx
  packages/client/ui/Dialog/DialogTitle.tsx
  packages/client/ui/Dialog/useDialogState.tsx
  tailwind.config.js
  yarn.lock
Labels: size/m

#8446 chore: refactor postDeploy to preDeploy
  .github/workflows/build.yml
  README.md
  app.json
  docker/entrypoint.prod.sh
  docker/parabol-ubi/docker-build/README.md
  docker/parabol-ubi/docker-host-st/README.md
  docker/parabol-ubi/docker-host-st/docker-compose.yaml
  package.json
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/postgres/migrations/postDeploy/1613857272859_backfillUserTable.ts
  packages/server/postgres/migrations/postDeploy/1615148741896_backfillTeamTable.ts
  packages/server/postgres/migrations/postDeploy/1619383917863_updateDeletedUserEmails.ts
  packages/server/postgres/migrations/postDeploy/1620887961308_backfillSegmentId.ts
  packages/server/postgres/migrations/postDeploy/1621238616230_backfillTier.ts
  packages/server/postgres/migrations/postDeploy/1622701938472_backfillOverLimitCopy.ts
  packages/server/postgres/migrations/postDeploy/1623747531144_backfillMissingTeams.ts
  packages/server/postgres/migrations/postDeploy/1625120349057_changeDeletedUserEmail.ts
  packages/server/postgres/migrations/postDeploy/1625124096757_addUserEmailUniqueConstraint.ts
  scripts/README.md
  scripts/RelayPersistServer.ts
  scripts/postDeployMigrate.js
  scripts/prod.js
  scripts/toolboxSrc/preDeploy.ts
  scripts/toolboxSrc/primeIntegrations.ts
  scripts/toolboxSrc/pushToCDN.ts
  scripts/toolboxSrc/standaloneMigrations.ts
  scripts/webpack/prod.servers.config.js
  scripts/webpack/toolbox.config.js
Labels: size/l

#8486 fix: Limit number of teams that can be moved in one moveTeamToOrg call
  packages/server/graphql/mutations/moveTeamToOrg.ts
Labels: size/xs

#8496 fix: Fix create Parabol task in Sprint Poker
  packages/client/mutations/CreateTaskMutation.ts
Labels: size/xs

#8476 feat: invite users on team creation
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamFormTeamName.tsx
  packages/client/mutations/AddOrgMutation.ts
  packages/client/mutations/AddTeamMutation.ts
  packages/server/graphql/mutations/addOrg.ts
  packages/server/graphql/mutations/addTeam.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/mutations/inviteToTeam.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
Labels: size/l

#8479 chore: add metrics to invite on team creation
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/s

#8482 feat: add invite all checkbox
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
Labels: size/s

#8499 chore: replace xml-lint due to mem leak
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/package.json
  packages/server/utils/samlXMLValidator.ts
  yarn.lock
Labels: size/s

#8416 fix: use unique server name for fresh namespace
  packages/server/graphql/mutations/setAppLocation.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/listenHandler.ts
  packages/server/server.ts
  packages/server/socketHandlers/handleConnect.ts
  packages/server/utils/ServerHealthChecker.ts
  packages/server/utils/serverHealthChecker.ts
Labels: size/m

#8485 fix: show correct drawer info after upgrade
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlanDrawer.tsx
  packages/client/mutations/handlers/upgradeToTeamTierSuccessUpdater.ts
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/subscriptions/OrganizationSubscription.ts
Labels: size/s

#8487 chore: bump pg to v12.15
  .circleci/config.yml
  .github/workflows/build.yml
  docker-compose.yml
  docker/parabol-ubi/docker-host-st/docker-compose.yaml
  packages/server/postgres/Dockerfile
Labels: size/s

#8501 chore: drop unused RethinkDB tables
  packages/server/postgres/migrations/1689031398651_del-team-meetingTemplate.ts
Labels: size/s

#8505 chore: remove old autogroup mutation
  packages/server/graphql/mutations/autoGroupReflections.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AutoGroupReflectionsPayload.ts
Labels: size/m

#8449 chore: Replace TeamHealth answer emojis with their text representation
  packages/server/database/types/TeamHealthVote.ts
  packages/server/graphql/public/mutations/setTeamHealthVote.ts
  packages/server/graphql/public/types/TeamHealthStage.ts
  packages/server/postgres/migrations/1688980408626_useIndexForTeamHealthAnswers.ts
Labels: size/m

#8506 feat: Add Team Health tips
  packages/client/components/BottomControlBarTips.tsx
  packages/client/components/MeetingHelp/TeamHealthHelpMenu.tsx
Labels: size/m

#8509 fix: avoid pronoun assumptions in ai summary
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/xs

#8512 fix: can create team within existing org
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/mutations/AddTeamMutation.ts
Labels: One Review Required, size/s

#8460 chore: add radix Select component
  packages/client/components/ShareTopicModal.tsx
  packages/client/package.json
  packages/client/ui/Select/Select.tsx
  packages/client/ui/Select/SelectContent.tsx
  packages/client/ui/Select/SelectGroup.tsx
  packages/client/ui/Select/SelectItem.tsx
  packages/client/ui/Select/SelectTrigger.tsx
  packages/client/ui/Select/SelectValue.tsx
  yarn.lock
Labels: size/m

#8463 chore(share-summary): share summary dialog UI
  packages/client/components/ShareTopicModal.tsx
  packages/client/components/ShareTopicRoot.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
  packages/client/ui/Select/SelectItem.tsx
  yarn.lock
Labels: size/m

#8508 feat: Add timer sound effect
  packages/client/components/StageTimerDisplayGauge.tsx
  packages/client/hooks/useSoundEffect.ts
  packages/client/package.json
  packages/client/types/modules.d.ts
  static/sounds/tic-tac.mp3
  yarn.lock
Labels: size/s

#8478 feat: retry invoice after failed payment
  packages/server/graphql/public/mutations/updateCreditCard.ts
Labels: size/s

#8517 feat: add Zoom transcription bot in discuss phase
  packages/client/components/NewMeetingSettingsToggleTranscription.tsx
  packages/server/graphql/mutations/helpers/addRecallBot.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/public/mutations/setMeetingSettings.ts
Labels: One Review Required, size/s

#8522 chore(share-summary): add utm params and reflectionGroupId param
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Labels: One Review Required, size/s

#8548 chore: update summary url with Suggest Groups
  packages/client/mutations/EndRetrospectiveMutation.ts
Labels: One Review Required

#8521 feat: Add team filter in timeline history page
  packages/client/components/MyDashboardTimeline.tsx
  packages/client/components/MyDashboardTimelineRoot.tsx
  packages/client/components/TeamFilterMenu.tsx
  packages/client/components/TimelineFeedList.tsx
  packages/client/components/TimelineHeader.tsx
  packages/server/graphql/getAccessibleTeamIdsForUser.ts
  packages/server/graphql/queries/tasks.ts
  packages/server/graphql/types/User.ts
Labels: size/m

#8541 fix: Correctly show error when email invite fails
  packages/client/components/AddTeamMemberModal.tsx
Labels: size/s

#8462 feat(discussionPromptQuestion): Generate discussion prompt question for discussions
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/server/database/types/ReflectionGroup.ts
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/addSummariesToThreads.ts
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/types/RetroReflectionGroup.ts
  packages/server/postgres/migrations/1689705702984_addDiscussionPromptQuestionsToRetroReflectionGroup.ts
  packages/server/postgres/pg.d.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/m

#8534 feat: show stripe invoices
  packages/client/modules/userDashboard/components/InvoiceRow/InvoiceRow.tsx
  packages/server/billing/helpers/generateInvoice.ts
Labels: size/s

#8551 feat: Add meetings to the team dashboard
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/TimelineEventTeamCreated.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/teamDashboard/components/TeamArchiveHeader/TeamArchiveHeader.tsx
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
  packages/client/modules/teamDashboard/components/TeamDashMain/TeamDashMain.tsx
  packages/client/modules/teamDashboard/components/TeamDashTasksTab/TeamDashTasksTab.tsx
  packages/client/modules/teamDashboard/containers/Team/TeamContainer.tsx
  packages/client/modules/teamDashboard/containers/TeamTasksHeader/TeamTasksHeaderContainer.tsx
Labels: size/m

#8180 feat: add gcal integration user flag
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required, size/xs

#8565 chore: bump node to 18.17.0
  .circleci/config.yml
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
Labels: size/s

#8556 feat: Add team insights feature flag and types
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/client/shared/gqlIds/TeamInsightsId.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/TeamInsights.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/public/types/Team.ts
Labels: size/m

#8564 fix(al): Speedup subcategory resolver
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/public/types/ReflectTemplate.ts
Labels: size/s

#8577 Update enterprise advantages
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/utils/constants.ts
Labels: One Review Required, size/s

#8583 chore: fix open pgtyped connections after running `yarn dev`
  pm2.dev.config.js
Labels: size/xs

#8574 feat(al): Roll out Activity Library to all new users
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: size/xs

#8587 chore: Remove and ignore pg.d.ts
  .github/workflows/build.yml
  .gitignore
  packages/server/postgres/pg.d.ts
Labels: size/xs

#8563 feat: add emoji insights
  packages/client/components/Tooltip.tsx
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/server/database/types/Meeting.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/collectReactjis.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
  packages/server/graphql/public/typeDefs/TeamInsights.graphql
  packages/server/graphql/public/types/Team.ts
  packages/server/postgres/migrations/1689949187848_addTeamInsights.ts
Labels: size/m

#8227 feat(aiSummary): Replace GPT-3 with GPT-3.5 for aiSummary
  packages/server/utils/OpenAIServerManager.ts
Labels: size/s

#8584 fix: do not trust invites sent to emails from the untrusted domains
  packages/server/__tests__/inviteToTeam.test.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
Labels: One Review Required, size/s

#8585 fix: change default tab to activities in team dash
  packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
Labels: size/xs

#8596 feat: humanize count down timer
  packages/client/components/StageTimerDisplayGauge.tsx
  packages/client/package.json
  packages/client/utils/date/relativeDate.ts
  yarn.lock
Labels: One Review Required, size/s
