Repository ParabolInc/parabol, pull requests merged in 2023-05, with the labels that each got.

#7774 feat: add more dd tracing
  packages/gql-executor/gqlExecutor.ts
  packages/server/graphql/executeGraphQL.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
  packages/server/graphql/traceGraphQL.ts
  packages/server/server.ts
  packages/server/utils/PubSubPromise.ts
Labels: size/s

#8129 feat(templates): Share to org by default
  packages/server/database/types/MeetingTemplate.ts
Labels: size/xs

#8114 chore: generate kysely schema in dev
  pm2.dev.config.js
Labels: size/xs

#8135 chore(security): bump vulnerable packages
  package.json
  packages/gql-executor/package.json
  packages/server/package.json
  yarn.lock
Labels: size/l

#8146 fix: remove leading slash on dist nested dirs
  scripts/webpack/prod.servers.config.js
Labels: size/xs

#8127 fix: subscribe to acceptInvite paylods in subscription
  packages/client/subscriptions/NotificationSubscription.ts
  packages/client/subscriptions/subscriptionOnNext.ts
  packages/client/subscriptions/subscriptionUpdater.ts
  packages/server/graphql/subscribeGraphQL.ts
Labels: size/s

#8074 feat: add mainCategory and illustrationUrl to MeetingTemplate
  packages/server/database/types/MeetingTemplate.ts
  packages/server/database/types/PokerTemplate.ts
  packages/server/database/types/ReflectTemplate.ts
  packages/server/graphql/mutations/addPokerTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
  packages/server/graphql/mutations/helpers/getTemplateIllustrationUrl.ts
  packages/server/graphql/mutations/helpers/makeRetroTemplates.ts
  packages/server/graphql/mutations/updateTemplateScope.ts
  packages/server/postgres/migrations/1681935703010_templates4.ts
  packages/server/postgres/pg.d.ts
  packages/server/postgres/queries/insertMeetingTemplate.ts
Labels: size/m

#8105 fix(stripe): do not update subscription quantity on enterprise annual plan
  packages/server/graphql/private/mutations/stripeCreateInvoice.ts
Labels: One Review Required, size/s

#8130 feat(suggest-groups): Add suggestGroups org feature flag
  packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: One Review Required, size/xs

#8131 feat(rid): Poker details view
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/hooks/usePortal.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/PokerTemplateScaleDetails.tsx
  packages/client/modules/meeting/components/PokerTemplateScalePicker.tsx
  packages/client/modules/meeting/components/ScaleActions.tsx
  packages/client/modules/meeting/components/ScaleDropdownMenuItem.tsx
  packages/client/modules/meeting/components/TemplateDimensionItem.tsx
  packages/client/modules/meeting/components/TemplateDimensionList.tsx
  packages/client/mutations/AddPokerTemplateMutation.ts
  packages/client/mutations/AddReflectTemplateMutation.ts
  packages/client/mutations/UpdatePokerTemplateScopeMutation.ts
  packages/client/mutations/handlers/handleAddMeetingTemplate.ts
  packages/client/mutations/handlers/handleAddPokerTemplate.ts
  packages/client/mutations/handlers/handleRemovePokerTemplate.ts
  packages/server/graphql/mutations/addPokerTemplate.ts
Labels: One Review Required, size/m

#8143 feat(rid): Create new poker template
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
Labels: One Review Required, size/s

#8120 feat(rid): Prompt user to change template scope to org
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/modules/meeting/components/TemplateSharing.tsx
  packages/server/graphql/mutations/updateTemplateScope.ts
Labels: One Review Required, size/s

#8157 feat(recurrence): Prev/next meeting navigation
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/TeamPromptMeeting.ts
Labels: One Review Required, size/m

#8175 fix: remove flushall redis on migrate
  scripts/toolboxSrc/standaloneMigrations.ts
Labels: size/s

#8165 chore: ignore generated files in PR size
  .github/workflows/labeler.yml
Labels: size/xs

#8161 chore: Verify all checked in generated files are clean
  .circleci/config.yml
  package.json
  packages/server/postgres/pg.d.ts
Labels: One Review Required, size/xs

#8163 chore: AI opt out at org level
  packages/server/graphql/mutations/helpers/canAccessAISummary.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: size/s

#8156 feat(rid): Enter edit mode automatically for new templates
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
Labels: size/s

#8030 feat(pipeline): Docker build pipeline
  .dockerignore
  .github/workflows/docker-build.yml
  docker/parabol-ubi/docker-build/README.md
  docker/parabol-ubi/docker-build/dockerfiles/parabol.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
  docker/parabol-ubi/docker-build/entrypoints/buildenv
  docker/parabol-ubi/docker-build/environments/pipeline
Labels: enhancement, devops

#8144 fix(rid): Ignore category in search empty state
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
Labels: One Review Required, size/xs

#8121 feat(checkout-flow): add billing leader functionality
  packages/client/components/BillingLeaderMenu.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeaders.tsx
  packages/client/modules/userDashboard/components/OrgBilling/NewBillingLeaderInput.tsx
  packages/client/modules/userDashboard/components/OrgBilling/NewBillingLeaderMenu.tsx
Labels: size/m

#8164 feat: can edit & delete AI comment
  packages/client/components/ThreadedCommentHeader.tsx
  packages/server/graphql/mutations/deleteComment.ts
  packages/server/graphql/mutations/updateCommentContent.ts
  packages/server/utils/isDiscussionFromMeeting.ts
Labels: One Review Required, size/s

#8178 chore: remove node-fetch from app code
  package.json
  packages/client/jest.config.js
  packages/client/package.json
  packages/server/GoogleLanguageManager.ts
  packages/server/__tests__/common.ts
  packages/server/__tests__/jest-transform-graphql-shim.js
  packages/server/email/inlineImages.ts
  packages/server/graphql/mutations/helpers/updateUserProfile.ts
  packages/server/graphql/nestedSchema/nestGitLabEndpoint.ts
  packages/server/hubSpot/backfillHubSpot.ts
  packages/server/hubSpot/hubSpotApi.ts
  packages/server/integrations/helpers/authorizeOAuth2.ts
  packages/server/jest.config.js
  packages/server/package.json
  packages/server/utils/AtlassianServerManager.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/GoogleServerManager.ts
  packages/server/utils/MSTeamsServerManager.ts
  packages/server/utils/MattermostServerManager.ts
  packages/server/utils/SlackServerManager.ts
  yarn.lock
Labels: size/xl

#8167 fix: more logs for voting error
  packages/client/components/PokerActiveVoting.tsx
  packages/client/mutations/PokerRevealVotesMutation.ts
  packages/server/graphql/mutations/pokerRevealVotes.ts
Labels: size/s

#8081 feat: prime new columns on MeetingTemplate [merge after #8074 is in prod]
  packages/server/database/types/MeetingTemplate.ts
  packages/server/database/types/PokerTemplate.ts
  packages/server/database/types/ReflectTemplate.ts
  packages/server/dataloader/customRedisQueries.ts
  packages/server/postgres/migrations/1682541573158_templates-primed.ts
  packages/server/postgres/pg.d.ts
Labels: size/m

#8210 feat(rid): Navigate to activity lib by default from CTA
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
Labels: One Review Required, size/s

#8196 feat: build no-deps
  .dockerignore
  .github/README.md
  .github/workflows/docker-build.yml
  docker/parabol-ubi/docker-build/README.md
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
Labels: size/s

#8086 feat(prompt-to-join): Add teammate UI
  codegen.json
  packages/client/components/Checkbox.tsx
  packages/client/components/NotificationAction.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/components/RequestToJoinOrgNotification.tsx
  packages/client/components/ReviewRequestToJoinOrgModal.tsx
  packages/client/components/ReviewRequestToJoinOrgRoot.tsx
  packages/client/components/TopBarNotifications.tsx
  packages/client/hooks/usePortal.tsx
  packages/client/mutations/toasts/mapRequestToJoinOrgToToast.ts
  packages/server/database/types/NotificationRequestToJoinOrg.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/public/mutations/requestToJoinDomain.ts
  packages/server/graphql/public/typeDefs/DomainJoinRequest.graphql
  packages/server/graphql/public/typeDefs/NotifyReqestToJoinOrg.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/DomainJoinRequest.ts
  packages/server/graphql/public/types/User.ts
  packages/server/postgres/queries/getDomainJoinRequestsByIds.ts
Labels: size/m

#8197 fix: slack notification race condition
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/types/NewMeeting.ts
Labels: size/s

#8154 chore: remove __jsxRuntime path
  package.json
  packages/gql-executor/package.json
  packages/server/package.json
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
  scripts/webpack/toolbox.config.js
  scripts/webpack/utils/transformRules.js
  yarn.lock
Labels: size/s

#8236 fix: regenerate yarn.lock
  .github/workflows/labeler.yml
  yarn.lock
Labels: size/xs

#8237 fix: Add subject explicitly to create Jira key script
  scripts/create-jira-keys.sh
Labels: One Review Required, size/xs

#8223 chore(metrics): Add event parameter is_patient_0 to GA4 sign up events
  packages/client/utils/handleSuccessfulLogin.ts
Labels: One Review Required, size/xs

#8116 fix(chore): properly count emojis length
  package.json
  packages/client/modules/meeting/components/EditableTemplateScaleValueLabel.tsx
  packages/client/modules/meeting/components/NewTemplateScaleValueLabelInput.tsx
  packages/client/types/constEnums.ts
  packages/client/validation/Legitity.ts
  packages/server/graphql/mutations/helpers/validateScaleValue.ts
  yarn.lock
Labels: size/s

#8159 feat: mutable category
  codegen.json
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsBadge.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsBadges.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsCategoryBadge.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/mutations/UpdateTemplateCategoryMutation.ts
  packages/client/package.json
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/public/mutations/updateTemplateCategory.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/rules/getTeamIdFromArgTemplateId.ts
  packages/server/graphql/public/rules/isViewerOnTeam.ts
  packages/server/graphql/public/typeDefs/MeetingTemplate.graphql
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/updateTemplateCategory.graphql
  packages/server/graphql/public/types/PokerTemplate.ts
  packages/server/graphql/public/types/ReflectTemplate.ts
  packages/server/graphql/public/types/UpdateTemplateCategorySuccess.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/MeetingTemplate.ts
  packages/server/graphql/types/PokerTemplate.ts
  packages/server/graphql/types/ReflectTemplate.ts
  yarn.lock
Labels: size/xl

#8244 chore: refactor addFeatureFlagToOrg to updateOrgFeatureFlag
  codegen.json
  packages/server/graphql/private/mutations/updateOrgFeatureFlag.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/private/types/UpdateOrgFeatureFlagSuccess.ts
Labels: One Review Required, size/s

#8246 fix: NewMeeting dialog rendered the dashboard twice
  packages/client/components/Dashboard.tsx
  packages/client/components/PrivateRoutes.tsx
Labels: One Review Required, size/s

#8248 fix(discussions): Fix editing comments in standups + check-ins
  packages/server/graphql/mutations/deleteComment.ts
  packages/server/graphql/mutations/updateCommentContent.ts
  packages/server/utils/isDiscussionFromMeeting.ts
Labels: size/s

#8226 feat(rid): Sidebar for standups + checkins
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/hooks/usePortal.tsx
Labels: size/m

#7942 feat(Team Health): add new stage to retrospective
  codegen.json
  packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
  packages/client/components/NewMeetingSettingsToggleTeamHealth.tsx
  packages/client/components/NewMeetingSidebarPhaseListItem.tsx
  packages/client/components/RetroMeeting.tsx
  packages/client/components/TeamHealth.tsx
  packages/client/mutations/SetMeetingSettingsMutation.ts
  packages/client/shared/gqlIds/TeamHealthUserScoreId.ts
  packages/client/utils/constants.ts
  packages/client/utils/meetings/fromStageIdToUrl.ts
  packages/client/utils/meetings/lookups.ts
  packages/server/database/types/GenericMeetingPhase.ts
  packages/server/database/types/MeetingSettingsRetrospective.ts
  packages/server/database/types/TeamHealthPhase.ts
  packages/server/database/types/TeamHealthStage.ts
  packages/server/database/types/TeamHealthUserScore.ts
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/setMeetingSettings.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/setMeetingSettings.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/TeamHealthPhase.graphql
  packages/server/graphql/public/typeDefs/TeamHealthStage.graphql
  packages/server/graphql/public/typeDefs/TeamHealthUserScore.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/setMeetingSettings.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/public/types/TeamHealthPhase.ts
  packages/server/graphql/public/types/TeamHealthStage.ts
  packages/server/graphql/public/types/TeamHealthUserScore.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/NewMeetingPhase.ts
  packages/server/graphql/types/NewMeetingPhaseTypeEnum.ts
  packages/server/graphql/types/NewMeetingStage.ts
  packages/server/postgres/migrations/1684250022646_teamHealthPhase.ts
  packages/server/utils/getPhase.ts
Labels: size/l

#8199 feat(retros-in-disguise): added standup activity details
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsBadge.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsBadges.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsRoute.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/MeetingDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/components/DetailsBadge.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/components/IntegrationsTip.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/hooks/useActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ActivityIllustrations.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoutes.tsx
  packages/client/hooks/usePortal.tsx
  packages/client/tsconfig.json
Labels: size/xl

#8253 fix: Fix team change in new meeting window
  packages/client/components/PrivateRoutes.tsx
Labels: size/xs

#8258 feat(standups): Meeting ended integration notification
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/getSummaryText.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
Labels: One Review Required, size/s

#7933 feat(summaries): Bulk task export button
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuList.tsx
  packages/client/components/TaskIntegrationMenuItem.tsx
  packages/client/hooks/useIsIntegrated.ts
  packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasks.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasksMenu.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasksMenuRoot.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/mutations/AddAtlassianAuthMutation.ts
  packages/client/mutations/AddGitHubAuthMutation.ts
  packages/server/__tests__/processRecurrence.test.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/TeamPromptMeeting.ts
Labels: size/l

#8256 fix(copy): Make copy for ending meeting consistent
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
Labels: One Review Required, size/xs

#8267 chore: update max token limit
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/xs

#8255 fix(standups): Remove CSV download button in standups
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Labels: One Review Required, size/s

#8257 fix: checkbox color overriden by styled components
  packages/client/components/Checkbox.tsx
  packages/client/components/EmailNotifications.tsx
  packages/client/components/NewMeetingSettingsToggleAnonymity.tsx
  packages/client/components/NewMeetingSettingsToggleCheckIn.tsx
Labels: One Review Required, size/s

#8160 feat(prompt-to-join): Add teammate mutation
  codegen.json
  packages/client/components/ReviewRequestToJoinOrgModal.tsx
  packages/client/components/ReviewRequestToJoinOrgRoot.tsx
  packages/client/mutations/AcceptRequestToJoinDomainMutation.ts
  packages/client/mutations/toasts/mapRequestToJoinOrgToToast.ts
  packages/client/shared/gqlIds/DomainJoinRequestId.ts
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/billing/helpers/handleTeamOrgQuantityChanges.ts
  packages/server/billing/helpers/updateSubscriptionQuantity.ts
  packages/server/database/types/NotificationRequestToJoinOrg.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/private/mutations/autopauseUsers.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/mutations/stripeCreateInvoice.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/requestToJoinDomain.ts
  packages/server/graphql/public/typeDefs/acceptRequestToJoinDomain.graphql
  packages/server/graphql/public/types/AcceptRequestToJoinDomainSuccess.ts
  packages/server/graphql/public/types/DomainJoinRequest.ts
  packages/server/graphql/public/types/NotifyRequestToJoinOrg.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  packages/server/graphql/types/SnackbarTypeEnum.ts
  packages/server/postgres/migrations/1683902222006_domainJoinRequestAutoIncrementId.ts
  packages/server/postgres/pg.d.ts
  packages/server/postgres/queries/getDomainJoinRequestsByIds.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: size/m

#8270 feat: Don't show discussion mention toast if already on stage
  packages/client/mutations/toasts/mapDiscussionMentionedToToast.ts
Labels: size/s

#8279 fix(rid): Fix changing prompt colors in activity library
  packages/client/modules/meeting/components/EditableTemplatePromptColor.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/TemplatePromptItem.tsx
  packages/client/modules/meeting/components/TemplatePromptList.tsx
Labels: size/s

#8269 fix(recurrence): Incorrect start times due to timezone weirdness
  packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
  packages/client/shared/rruleUtil.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
Labels: size/s

#8287 fix(summaries): Race condition around bulk task exports
  packages/client/mutations/EndRetrospectiveMutation.ts
Labels: One Review Required, size/xs

#8249 chore(share-summary): Add feature flag
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: One Review Required, size/xs

#8132 feat(suggest-groups): click button to group reflections
  codegen.json
  packages/client/components/RetroGroupPhase.tsx
  packages/client/components/RetroReflectPhase/RetroReflectPhase.tsx
  packages/client/modules/demo/initDB.ts
  packages/client/mutations/AutogroupMutation.ts
  packages/client/utils/constants.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/graphql/public/mutations/autogroup.ts
  packages/server/graphql/public/typeDefs/autogroup.graphql
  packages/server/graphql/public/types/AutogroupSuccess.ts
  packages/server/graphql/types/AutogroupReflectionGroup.ts
  packages/server/graphql/types/RetrospectiveMeeting.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/estimateTokens.ts
  packages/server/utils/isValidJSON.ts
Labels: size/m
