Repository ParabolInc/parabol, pull requests merged in 2023-08, with the labels that each got.

#8590 chore: Restrict Team Health phase for starter tier
  packages/client/utils/features/isTeamHealthAvailable.ts
Labels: size/xs

#8591 chore: change default width and padding of ui/Dialog
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/modules/userDashboard/components/GcalModal/DateTimePicker.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
  packages/client/ui/Dialog/DialogClose.tsx
  packages/client/ui/Dialog/DialogContent.tsx
Labels: One Review Required, size/m

#8533 fix: exit code 1 on preDeploy failure
  scripts/toolboxSrc/preDeploy.ts
  scripts/toolboxSrc/primeIntegrations.ts
  scripts/toolboxSrc/standaloneMigrations.ts
Labels: size/s

#8595 chore: Document INVITATION_SHORTLINK environment and make optional
  .env.example
  packages/client/components/MassInvitationTokenLink.tsx
  packages/client/types/modules.d.ts
  packages/client/utils/getMassInvitationUrl.ts
  packages/server/types/modules.d.ts
Labels: size/s

#8601 fix: make AIGeneratedDiscussionPrompt org level feature flag
  packages/client/modules/demo/initDB.ts
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: One Review Required, size/s

#8619 fix(pipeline): increase size of the runner used for the build action
  .github/workflows/build.yml
Labels: DX, devops, size/xs

#8623 fix: unable to ungroup some reflection groups
  packages/server/postgres/migrations/1691421540088_updateRetroReflectionGroupSortOrderType.ts
Labels: size/s

#8617 chore: Cleanup old starter tier organizations
  packages/server/postgres/migrations/1691422128820_fixOrganizationTier.ts
Labels: size/s

#8626 fix: Remove check for whether template was updated
  packages/server/graphql/mutations/selectTemplate.ts
Labels: One Review Required, size/xs

#8571 chore(one-on-one): add oneOnOne org feature flag
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: One Review Required, size/xs

#8569 feat(standups): Standup AI Summaries
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/mutations/helpers/canAccessAISummary.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
  packages/server/graphql/mutations/helpers/generateStandupMeetingSummary.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/m

#8607 feat(standups): Notify slack when user submits standup response
  packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationList.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationRow.tsx
  packages/server/database/types/SlackNotification.ts
  packages/server/graphql/mutations/addSlackAuth.ts
  packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/graphql/types/SlackNotificationEventEnum.ts
Labels: size/m

#8638 chore: CI=true in tests
  .github/workflows/build.yml
Labels: size/xs

#8641 fix(al): Number of activities exceeds number requested
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/server/graphql/public/types/User.ts
  packages/server/utils/sendToSentry.ts
Labels: size/s

#8557 chore: Build once, run everywhere
  .env.example
  devTemplate.html
  packages/client/cdnFallback.js
  packages/client/polyfills.ts
  packages/client/types/modules.d.ts
  packages/server/createSSR.ts
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/fileStorage/S3FileStoreManager.ts
  packages/server/fileStorage/getFileStoreManager.ts
  packages/server/graphql/mutations/helpers/getTemplateIllustrationUrl.ts
  packages/server/package.json
  packages/server/server.ts
  packages/server/staticFileHandler.ts
  packages/server/types/modules.d.ts
  packages/server/utils/StaticServer.ts
  packages/server/utils/__tests__/protocolRelativeUrl-tests.js
  packages/server/utils/protocolRelativeUrl.js
  packages/server/utils/serveStatic.ts
  scripts/prod.js
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/toolboxSrc/modules.d.ts
  scripts/toolboxSrc/preDeploy.ts
  scripts/toolboxSrc/pushToCDN.ts
  scripts/toolboxSrc/tsconfig.json
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
  scripts/webpack/utils/getS3BasePath.js
  scripts/webpack/utils/getWebpackPublicPath.js
  static/images/brand/mark-cropped-192.png
  static/images/brand/mark-cropped-512.png
  static/manifest.json
  template.html
  yarn.lock
Labels: size/l

#8610 feat(standups): Post standup responses in 'meeting ended' message thread
  packages/client/utils/SlackManager.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Labels: size/m

#8637 chore: active plan visual cue
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
Labels: One Review Required, size/m

#8648 chore: fix a couple vulns
  package.json
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/package.json
  yarn.lock
Labels: size/s

#8630 fix: prevent scroll jump when emoji is added
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/TeamPrompt/TeamPromptResponseEmojis.tsx
Labels: size/s

#8652 fix: fix share topic modal can't see slack integration
  packages/client/components/ShareTopicRoot.tsx
  packages/client/components/ShareTopicRouterRoot.tsx
Labels: One Review Required, size/xs

#8655 fix: optimistic updater in UpsertTeamPromptResponseMutation
  packages/client/mutations/UpsertTeamPromptResponseMutation.ts
Labels: One Review Required, size/xs

#8625 chore(suggest-groups): increase number of suggested groups
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/xs

#8646 chore: add version and sha to predeploy logs
  scripts/toolboxSrc/modules.d.ts
  scripts/toolboxSrc/preDeploy.ts
  scripts/webpack/prod.servers.config.js
Labels: size/xs

#8661 fix: build in dev mode from clean clone
  packages/server/createSSR.ts
  scripts/codegenGraphQL.js
Labels: size/s

#8667 fix: Show Team Insights emojis correctly
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
Labels: size/s

#8665 fix: terser in prod build
  .github/workflows/build.yml
  package.json
  scripts/webpack/dev.client.config.js
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
  yarn.lock
Labels: size/s

#8662 feat(gcal): invite members from modal
  codegen.json
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/types/CreateGcalEventInput.ts
Labels: One Review Required, size/m

#8682 fix: exit early if no segment write key
  packages/server/graphql/mutations/segmentEventTrack.ts
  packages/server/utils/segmentIo.ts
Labels: size/s

#8671 style: Normalize link styles
  packages/client/components/PokerEstimateHeaderCardContent.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: One Review Required, size/s

#8536 style: avatar update
  packages/client/components/EditableAvatar/EditableAvatar.tsx
  packages/client/components/UserAvatarInput.tsx
  packages/client/modules/userDashboard/components/UserSettingsForm/UserSettingsForm.tsx
Labels: One Review Required, size/m

#8687 fix: Uncompressing emojies twice causes a failure
  packages/client/components/ReflectionCard/ReactjiCount.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/client/utils/getReactji.ts
Labels: size/s

#8697 fix(tiptap): Show <hr/> nodes
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: One Review Required, size/xs

#8658 fix(standups): do not open links twice
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/components/promptResponse/tiptapConfig.ts
  packages/client/package.json
  yarn.lock
Labels: size/s

#8693 chore: Allow non-facilitator to advance to reflect phase
  packages/client/components/RetroMeetingSidebar.tsx
  packages/server/database/types/ReflectPhase.ts
  packages/server/database/types/TeamHealthStage.ts
Labels: size/s

#8703 fix(ai-summary): update the prompt to emphasize brevity
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/xs

#8612 feat(tiptap): Loom embed extension
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/components/promptResponse/loomExtension.ts
  packages/client/components/promptResponse/tiptapConfig.ts
Labels: size/m

#8688 feat(gcal): unauthed schedule button ux
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/types/Team.ts
Labels: size/m

#8686 chore: Show disabled Team Health option to Starter tier
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/NewMeetingSettingsRetrospective.tsx
  packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
  packages/client/components/NewMeetingSettingsToggleTeamHealth.tsx
  packages/client/components/NewMeetingSettingsUpgradeForTeamHealth.tsx
  packages/server/graphql/types/UpgradeCTALocationEnum.ts
Labels: size/m

#8690 feat(standups): "Your tasks" drawer with Parabol tasks
  packages/client/components/IconLabel.tsx
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawerRoot.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/styles/helpers/cardRootStyles.ts
Labels: size/l

#8716 feat(standups): "Add task" button in Parabol task drawer
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawerRoot.tsx
Labels: One Review Required, size/s

#8695 feat: Add "Is this helpful?" for insights
  packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
  packages/server/graphql/types/SegmentEventTrackOptions.ts
Labels: size/m

#8729 chore(ci): CircleCI using the new staging domain action-staging.parabol.fun
  .circleci/config.yml
Labels: devops, size/xs

#8736 chore(doc): release test template issue and manual testing guide updated to the new staging url
  .github/ISSUE_TEMPLATE/release_test.md
  docs/manualTestingGuide.md
Labels: size/s

#8734 fix: Allow login with google with ad blocker enabled
  packages/client/utils/getAnonymousId.ts
Labels: size/xs

#8738 fix(standups): Selecting team in Parabol card throws error
  packages/client/modules/outcomeCard/components/TaskFooterTeamAssigneeMenuRoot.tsx
Labels: One Review Required, size/xs

#8629 feat(one-on-one): allow oneOnOne input in startCheckIn mutation
  packages/client/mutations/StartCheckInMutation.ts
  packages/server/database/types/Team.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/maybeCreateOneOnOneTeam.ts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/public/typeDefs/CreateOneOnOneTeamInput.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/CreateOneOnOneTeamInput.ts
  packages/server/postgres/migrations/1692638249976_isOneOnOneTeam.ts
  packages/server/postgres/queries/src/insertTeamQuery.sql
Labels: size/m

#8666 chore(one-on-one): Add user picker
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/AdhocTeamMultiSelect/AdhocTeamMultiSelect.tsx
  packages/client/ui/Chip/Chip.tsx
Labels: size/m

#8708 chore: first pass at lastUsedAt caching
  packages/client/mutations/StartRetrospectiveMutation.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/public/types/ReflectTemplate.ts
  packages/server/postgres/migrations/1692650094687_TeamMeetingTemplate.ts
  packages/server/postgres/queries/updateMeetingTemplateLastUsedAt.ts
Labels: size/m

#8726 fix: Show correct error message on login failure with invitation
  packages/client/mutations/AcceptTeamInvitationMutation.ts
  packages/client/types/constEnums.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/graphql/public/permissions.ts
Labels: size/s

#8681 chore(analytics): Add Amplitude server side event tracking
  .env.example
  packages/server/package.json
  packages/server/utils/analytics/amplitude/AmplitudeAnalytics.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/segment/SegmentAnalytics.ts
  packages/server/utils/segmentIo.ts
  yarn.lock
Labels: size/s

#8699 chore(analytics): Route analytics identify calls through analytics.ts
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/public/mutations/updateUserProfile.ts
  packages/server/utils/analytics/amplitude/AmplitudeAnalytics.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/segment/SegmentAnalytics.ts
  packages/server/utils/setUserTierForUserIds.ts
Labels: size/m

#8755 patch: team prompt q
  codegen.json
  packages/server/graphql/public/types/TeamPromptQuestion.ts
Labels: size/xs

#8685 chore: fix cleanup-changelog.sh on mac os
  scripts/cleanup-changelog.sh
Labels: One Review Required, size/s

#8761 chore: no minify server
  scripts/webpack/prod.servers.config.js
Labels: size/s

#8694 feat: give users feedback if there's a gcal error
  packages/client/mutations/StartCheckInMutation.ts
  packages/client/mutations/StartRetrospectiveMutation.ts
  packages/client/mutations/StartSprintPokerMutation.ts
  packages/client/mutations/StartTeamPromptMutation.ts
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/types/StartCheckInPayload.ts
  packages/server/graphql/types/StartRetrospectivePayload.ts
  packages/server/graphql/types/StartSprintPokerPayload.ts
Labels: size/m

#8745 chore: docker rm queryMap
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
Labels: size/xs

#8746 chore: remove __PROJECT_ROOT__
  packages/server/types/modules.d.ts
  packages/server/utils/updateGQLSchema.ts
  scripts/toolboxSrc/modules.d.ts
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.servers.config.js
  scripts/webpack/toolbox.config.js
Labels: size/s
