Repository ParabolInc/parabol, pull requests merged in 2023-04, with the labels that each got.

#7977 chore(prompt-to-join-org): add promptToJoin feature flag
  packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: One Review Required, size/xs

#7985 chore(ai-summary): invert feature flag
  packages/server/graphql/mutations/helpers/canAccessAISummary.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSentimentScore.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/s

#7958 feat(ai-summary): replace GPT-3 with ChatGPT
  packages/server/package.json
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: size/s

#7988 fix(sentiment-analysis): Fix error payload from Google Language API
  packages/server/GoogleLanguageManager.ts
  packages/server/graphql/mutations/helpers/manageGoogleNLPErrorResponse.ts
Labels: size/s

#7994 chore: fix reviewers
  .github/reviewers.yml
Labels: One Review Required, size/xs

#7908 feat(retros-in-disguise): Added activity library cards
  package.json
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityIllustrations.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryHeader.tsx
  packages/client/components/ActivityLibrary/ActivityLibrarySideBar.tsx
  packages/client/components/ActivityLibrary/SearchBar.tsx
  packages/client/components/DashTopBar.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/package.json
  tailwind.config.js
  yarn.lock
Labels: size/l

#7992 chore: Allow super users to archive teams
  packages/server/graphql/mutations/archiveTeam.ts
Labels: One Review Required, size/xs

#7850 feat(recurrence): Allow changing meeting series name
  package.json
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingRecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceDayCheckbox.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/mutations/StartTeamPromptMutation.ts
  packages/client/mutations/UpdateRecurrenceSettingsMutation.ts
  packages/server/database/types/MeetingTeamPrompt.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
  packages/server/graphql/public/typeDefs/RecurrenceSettingsInput.graphql
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/typeDefs/updateRecurrenceSettings.graphql
  tailwind.config.js
  yarn.lock
Labels: size/l

#8001 chore(ai-summary): revert chatgpt change
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/s

#7931 chore(metrics): Consolidate GA4 `sign_up` events emission
  packages/client/components/EmailPasswordAuthForm.tsx
  packages/client/components/SAMLRedirect.tsx
  packages/client/components/TeamInvitationSSO.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/LoginWithPasswordMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/client/mutations/VerifyEmailMutation.ts
  packages/client/utils/getTokenFromSSO.ts
  packages/client/utils/handleSuccessfulLogin.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/private/typeDefs/loginSAML.graphql
  packages/server/utils/SAMLHandler.ts
Labels: One Review Required, size/m

#7999 fix(sentiment-analysis): write undefined as sentimentScore for meetings without reflections with scores
  packages/server/graphql/mutations/helpers/generateWholeMeetingSentimentScore.ts
Labels: One Review Required, size/s

#8000 feat: pick a fun name for the default team when user signs up
  packages/client/utils/makeDefaultTeamName.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/updateTeamName.ts
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/s

#7998 feat(recurrence): End Recurring Meeting Confirmation Modal
  packages/client/components/MeetingCard.tsx
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/MeetingCardOptionsMenuRoot.tsx
  packages/client/components/TeamPrompt/Recurrence/EndRecurringMeetingModal.tsx
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/hooks/usePortal.tsx
Labels: One Review Required, size/m

#7997 feat: remove private schema dropdown in graphiql
  packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx
Labels: size/s

#8016 hotfix: notification meeting stage time limit end
  CHANGELOG.md
  lerna.json
  package.json
  packages/gql-executor/package.json
  packages/server/graphql/rootTypes.ts
  packages/server/package.json
Labels: size/s

#7990 feat(rid): Activity Details (no sidebar)
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsRoute.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/AzureDevOpsSVG.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/modules/meeting/components/EditableTemplateName.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/TemplateSharing.tsx
Labels: One Review Required, size/m

#7935 fix: fix syntax error when adjusting the user tier with empty list
  packages/server/postgres/queries/updateUserTiers.ts
  packages/server/utils/setUserTierForUserIds.ts
Labels: One Review Required, size/s

#8031 fix: missing font styles on inputs, textareas etc
  packages/client/styles/theme/global.css
Labels: size/s

#8032 fix: Workaround for adding Parabol tasks in Sprint Poker
  packages/client/mutations/CreateTaskMutation.ts
Labels: One Review Required, size/xs

#8028 chore: Move new feature announcement to main Dashboard
  packages/client/components/Dashboard.tsx
  packages/client/components/MyDashboardTimeline.tsx
Labels: One Review Required, size/xs

#8029 feat(retros-in-disguise): added activity library to sidebar
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
Labels: One Review Required, size/s

#8008 feat(rid): Retro Details Sidebar
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/modules/meeting/components/EditableTemplateName.tsx
  packages/client/modules/meeting/components/SelectTemplate.tsx
  packages/client/mutations/SelectTemplateMutation.ts
Labels: One Review Required, size/m

#8042 fix: ensure task exists
  packages/client/mutations/DeleteTaskMutation.ts
Labels: size/xs

#8043 fix: ensure teamMembers exist in payload
  packages/client/mutations/RemoveOrgUserMutation.ts
Labels: size/xs

#8049 chore(metrics): Add icloud.com as another generic domain
  packages/server/utils/isCompanyDomain.ts
Labels: size/xs

#7208 feat: user presence supports k8s
  packages/server/graphql/mutations/setAppLocation.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/mutations/disconnectSocket.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/listenHandler.ts
  packages/server/server.ts
  packages/server/socketHandlers/handleConnect.ts
  packages/server/socketHandlers/handleDisconnect.ts
  packages/server/utils/ServerHealthChecker.ts
  packages/server/utils/publishInternalGQL.ts
  scripts/toolboxSrc/postDeploy.ts
Labels: size/m

#7766 fix: add args to dd-trace
  docker/dev.yml
  packages/server/graphql/CompiledQueryCache.ts
  packages/server/graphql/traceGraphQL.ts
Labels: size/s

#8003 feat(prompt-to-join): Add "would you like to join org" notification
  packages/client/components/NotificationPicker.tsx
  packages/client/components/PinnedSnackbarNotifications.tsx
  packages/client/components/PromptToJoinOrgNotification.tsx
  packages/client/mutations/toasts/mapPromptToJoinOrgToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/client/mutations/toasts/promptToJoinOrgSuccessToast.ts
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationPromptToJoinOrg.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/NotifyPromptToJoinOrg.graphql
  packages/server/graphql/public/types/NotifyPromptToJoinOrg.ts
  packages/server/graphql/types/NotificationEnum.ts
  packages/server/graphql/types/SnackbarTypeEnum.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/sendPromptToJoinOrg.ts
Labels: size/m

#8060 fix: prevent spam invites
  CHANGELOG.md
  lerna.json
  package.json
  packages/client/components/AddTeamMemberModal.tsx
  packages/client/package.json
  packages/gql-executor/package.json
  packages/server/graphql/mutations/inviteToTeam.ts
  packages/server/package.json
Labels: size/s

#8027 feat(rid): Create retro template from retro categories view
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/hooks/usePortal.tsx
  packages/client/mutations/UpdateReflectTemplateScopeMutation.ts
  packages/client/mutations/handlers/handleAddReflectTemplate.ts
  packages/client/mutations/handlers/handleRemoveReflectTemplate.ts
Labels: One Review Required, size/m

#8038 fix: expire failed login attempts
  packages/server/graphql/mutations/helpers/attemptLogin.ts
Labels: size/xs

#8066 fix: Rename makeTemplateDescription -> useTemplateDescription to satisfy hooks rules
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/TimelineEventTeamPromptComplete.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/PokerTemplateItem.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateItem.tsx
  packages/client/mutations/toasts/promptToJoinOrgSuccessToast.ts
  packages/client/utils/useTemplateDescription.ts
Labels: One Review Required, size/m

#8059 fix(recurrence): prevent repeating date in standups name
  packages/server/database/types/MeetingTeamPrompt.ts
  packages/server/graphql/mutations/helpers/safeCreateTeamPrompt.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
Labels: One Review Required, size/s

#8064 chore: improve tailwind classes specificity
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
  tailwind.config.js
Labels: One Review Required, size/xs

#8004 feat(checkout-flow): right drawer
  packages/client/components/ResponsiveDashSidebar.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlanDrawer.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlanDrawerContent.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBillingHeading.tsx
  packages/client/modules/userDashboard/components/Organization/OrgNav.tsx
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/types/constEnums.ts
  packages/client/utils/constants.ts
Labels: size/m

#8068 chore: remove tailwind selector strategy
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
  tailwind.config.js
Labels: One Review Required, size/xs

#8018 chore: refactor notifications to SDL (example PR)
  codegen.json
  packages/client/utils/nullIfEmpty.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/inviteToTeam.ts
  packages/server/graphql/mutations/removeTeamMember.ts
  packages/server/graphql/mutations/setNotificationStatus.ts
  packages/server/graphql/mutations/updateTask.ts
  packages/server/graphql/public/types/ArchiveTeamPayload.ts
  packages/server/graphql/public/types/CreateTaskPayload.ts
  packages/server/graphql/public/types/InviteToTeamPayload.ts
  packages/server/graphql/public/types/NotificationMeetingStageTimeLimitEnd.ts
  packages/server/graphql/public/types/NotificationTeamInvitation.ts
  packages/server/graphql/public/types/NotifyKickedOut.ts
  packages/server/graphql/public/types/NotifyPaymentRejected.ts
  packages/server/graphql/public/types/NotifyPromoteToOrgLeader.ts
  packages/server/graphql/public/types/NotifyTaskInvolves.ts
  packages/server/graphql/public/types/NotifyTeamArchived.ts
  packages/server/graphql/public/types/RemoveTeamMemberPayload.ts
  packages/server/graphql/public/types/SetNotificationStatusPayload.ts
  packages/server/graphql/public/types/StripeFailPaymentPayload.ts
  packages/server/graphql/public/types/UpdateTaskPayload.ts
  packages/server/graphql/queries/notifications.ts
  packages/server/graphql/resolvers.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/ArchiveTeamPayload.ts
  packages/server/graphql/types/CreateTaskPayload.ts
  packages/server/graphql/types/InviteToTeamPayload.ts
  packages/server/graphql/types/Notification.ts
  packages/server/graphql/types/NotificationMeetingStageTimeLimitEnd.ts
  packages/server/graphql/types/NotificationTeamInvitation.ts
  packages/server/graphql/types/NotifyKickedOut.ts
  packages/server/graphql/types/NotifyPaymentRejected.ts
  packages/server/graphql/types/NotifyPromoteToOrgLeader.ts
  packages/server/graphql/types/NotifyTaskInvolves.ts
  packages/server/graphql/types/NotifyTeamArchived.ts
  packages/server/graphql/types/RemoveOrgUserPayload.ts
  packages/server/graphql/types/RemoveTeamMemberPayload.ts
  packages/server/graphql/types/SetNotificationStatusPayload.ts
  packages/server/graphql/types/SetOrgUserRoleAddedPayload.ts
  packages/server/graphql/types/StripeFailPaymentPayload.ts
  packages/server/graphql/types/TeamNotification.ts
  packages/server/graphql/types/UpdateTaskPayload.ts
Labels: size/xl

#7932 chore: Throw and catch GraphQL errors on the client
  packages/client/Atmosphere.ts
  packages/client/components/MeetingSelector.tsx
  packages/client/components/MeetingSeriesRedirector.tsx
  packages/client/hooks/useInitialSafeRoute.ts
  packages/client/modules/teamDashboard/containers/Team/TeamContainer.tsx
  packages/client/mutations/AcceptTeamInvitationMutation.ts
  packages/client/mutations/handlers/handleRemoveTeams.ts
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/queries/team.ts
Labels: size/l

#8036 feat(rid): Clone template
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/mutations/AddReflectTemplateMutation.ts
  packages/client/mutations/handlers/handleAddReflectTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
Labels: size/m

#8058 Create new Github Action - Notify on bug assignment
  .github/workflows/notify_bug_assign.yml
Labels: size/s

#7685 feat: SAML UI: Create updateSAML mutation
  packages/client/mutations/UpdateSAMLMutation.ts
  packages/server/graphql/private/mutations/enableSAMLForDomain.ts
  packages/server/graphql/public/mutations/helpers/SAMLHelpers/getSignOnURL.ts
  packages/server/graphql/public/mutations/helpers/SAMLHelpers/getURLWithSAMLRequestParam.ts
  packages/server/graphql/public/mutations/updateSAML.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/typeDefs/updateSAML.graphql
Labels: size/m

#8072 fix(stripe): Fix the bug when there's failed payment we charge customer extra amount
  packages/server/billing/helpers/terminateSubscription.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
Labels: size/s

#8040 chore(prompt-to-join): add request to join domain mutation
  codegen.json
  packages/client/components/PromptToJoinOrgNotification.tsx
  packages/client/mutations/RequestToJoinDomainMutation.ts
  packages/client/mutations/toasts/mapPromptToJoinOrgToToast.ts
  packages/server/graphql/public/mutations/requestToJoinDomain.ts
  packages/server/graphql/public/typeDefs/requestToJoinDomain.graphql
  packages/server/postgres/migrations/1680865284180_addDomainJoinRequestTable.ts
  packages/server/postgres/pg.d.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
  packages/server/utils/sendPromptToJoinOrg.ts
Labels: size/m

#8112 chore: ironbank security updates
  .circleci/config.yml
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
  yarn.lock
Labels: size/m

#8111 fix(meetingTemplates): Filter by 'isActive' and use PG dataloader
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/types/PokerTemplate.ts
  packages/server/postgres/queries/src/getMeetingTemplatesByIdsQuery.sql
Labels: size/s

#8117 chore(retros-in-disguise): improve activity library routing
  packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoutes.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivityRoute.tsx
  packages/client/components/PrivateRoutes.tsx
Labels: One Review Required, size/s

#8069 feat(retros-in-disguise): added create new activity view
  packages/client/components/ActivityLibrary/ActivityBadge.tsx
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryHeader.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoutes.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivityRoute.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/package.json
  static/images/illustrations/newTemplate.png
  tailwind.config.js
  yarn.lock
Labels: size/l

#8108 feat(rid): Edit Mode
  packages/client/components/ActivityLibrary/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/modules/meeting/components/TemplateSharing.tsx
Labels: size/m
