Repository ParabolInc/parabol, pull requests merged in 2023-01, with the labels that each got.

#7395 fix: task highlight sticks when adding a due date
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
Labels: One Review Required

#7607 fix(Jira): fix Sprint Poker voting for projects with duplicate fields
  packages/client/components/JiraFieldDimensionDropdown.tsx
  packages/client/components/JiraFieldMenu.tsx
  packages/client/mutations/UpdateJiraDimensionFieldMutation.ts
  packages/client/utils/AtlassianManager.ts
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/graphql/mutations/setTaskEstimate.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/updateJiraDimensionField.ts
  packages/server/graphql/public/typeDefs/JiraIssue.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/updateJiraDimensionField.graphql
  packages/server/graphql/types/AtlassianIntegration.ts
  packages/server/graphql/types/EstimateStage.ts
Labels: One Review Required, size/m

#7618 fix: emails landing in spam
  packages/client/modules/email/components/EmailFooter/EmailFooter.tsx
  packages/client/modules/email/components/ResetPasswordEmail.tsx
  packages/client/modules/email/styles.ts
  packages/client/modules/invoice/components/InvoiceFooter/InvoiceFooter.tsx
Labels: size/s

#7616 chore(DX): Show a warning on switching branch with migrations
  .husky/post-checkout
Labels: One Review Required, size/s

#7587 feat(teams-limit): usage stats warning
  packages/client/components/InsightsDomainNudge.tsx
  packages/client/components/InsightsDomainPanel.tsx
  packages/client/types/constEnums.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/public/typeDefs/Company.graphql
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/types/UpgradeCTALocationEnum.ts
Labels: size/m

#7591 feat(teams-limit): prevent new team creation
  packages/client/components/InsightsDomainNudge.tsx
  packages/client/modules/newTeam/NewTeam.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamFormTeamName.tsx
  packages/client/types/constEnums.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/mutations/addTeam.ts
  packages/server/graphql/types/UpgradeCTALocationEnum.ts
Labels: size/m

#7620 chore: Add reviewer for PRs and assignee for issues on mention
  .github/workflows/assign_mentioned.yml
Labels: size/s

#7623 fix: Legitity min/max failed on undefined value
  packages/client/jest.config.js
  packages/client/package.json
  packages/client/utils/__tests__/parseEmailAddressList.test.ts
  packages/client/validation/Legitity.ts
  packages/client/validation/__tests__/Legitity.test.ts
Labels: release hotfix, One Review Required, size/s

#7628 feat: slack uses oatuh2 redirect
  packages/client/utils/SlackClientManager.ts
  packages/server/utils/SlackServerManager.ts
Labels: size/s

#7603 feat(standups/notifications): Generalized notification toasts + new toasts
  packages/client/components/NotificationPicker.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/client/mutations/toasts/mapResponseMentionedToToast.ts
  packages/client/mutations/toasts/mapResponseRepliedToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/client/subscriptions/NotificationSubscription.ts
Labels: size/m

#7626 chore: Add client unit tests to CircleCi
  .circleci/config.yml
  package.json
  packages/client/package.json
Labels: size/s

#7633 fix: server error undefined template
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
Labels: One Review Required, size/s

#7636 feat: removed recurrence feature flag
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required, size/s

#7596 feat(notifications): Discussion Mention notifications
  codegen.json
  packages/client/components/DiscussionMentioned.tsx
  packages/client/components/NotificationPicker.tsx
  packages/client/modules/email/components/EmailNotifications/EmailDiscussionMentioned.tsx
  packages/client/modules/email/components/EmailNotifications/EmailNotificationPicker.tsx
  packages/client/mutations/toasts/mapDiscussionMentionedToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/client/utils/meetings/fromStageIdToUrl.ts
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationDiscussionMentioned.ts
  packages/server/graphql/meetingTypePredicates.ts
  packages/server/graphql/mutations/addComment.ts
  packages/server/graphql/mutations/updateCommentContent.ts
  packages/server/graphql/public/typeDefs/NotifyDiscussionMentioned.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/NotifyDiscussionMentioned.ts
  packages/server/graphql/types/Discussion.ts
  packages/server/graphql/types/GenericMeetingStage.ts
Labels: size/l

#7646 chore(ai-summary): improve prompt
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/xs

#7619 chore(ai-summary): track when the summaries are viewed
  packages/client/components/ThreadedCommentBase.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryLoading.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
  packages/server/graphql/mutations/addReactjiToReactable.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#7648 fix(ai-summary): remove AI comment from comment count
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/endRetrospective.ts
Labels: One Review Required, size/s

#7635 chore(metrics): emit sign_up events from GA4 client side
  packages/client/components/AnalyticsPage.tsx
  packages/client/components/SAMLRedirect.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/graphql/public/typeDefs/loginWithGoogle.graphql
  packages/server/graphql/public/types/LoginWithGooglePayload.ts
  packages/server/utils/SAMLHandler.ts
Labels: One Review Required, size/s

#7598 perf: Moved global style creation outside of the React render cycle
  packages/client/components/Action/Action.tsx
Labels: frontend, One Review Required, size/s

#7657 fix(ai-summary): update Parabol AI picture
  packages/server/postgres/migrations/1673613407246_updateAIUserPic.ts
Labels: One Review Required, size/s

#7665 chore: sendToSentry if unable to create topic summary
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
Labels: One Review Required, size/s

#7645 feat(teams-limit): implement organization locked modal
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/NewMeetingActions.tsx
  packages/client/modules/teamDashboard/components/Team/Team.tsx
  packages/client/modules/teamDashboard/components/UnpaidTeamModal/UnpaidTeamModal.tsx
  packages/client/mutations/UpgradeToTeamTierMutation.ts
  packages/server/graphql/mutations/helpers/isStartMeetingLocked.ts
  packages/server/graphql/types/UpgradeCTALocationEnum.ts
Labels: size/m

#7673 fix: delete empty reflection groups
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/postgres/migrations/1674074684762_deleteEmptyGroups.ts
Labels: size/s

#7416 fix: prompt highlight color does not cover the full-height of the column
  packages/client/components/RetroReflectPhase/PhaseItemColumn.tsx
Labels: size/xs, UI refinement

#7601 feat(teams-limit): Add snackbar to usage stats enabled notification
  packages/client/components/DashTopBar.tsx
  packages/client/components/PinnedSnackbarNotifications.tsx
  packages/client/components/Snackbar.tsx
  packages/client/hooks/useUsageSnackNag.ts
  packages/client/mutations/toasts/mapTeamsLimitExceededToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/queries/notifications.ts
Labels: size/l

#7606 feat(teams-limit): lock organization if limit the is exceeded for 30 days
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/database/types/ScheduledJob.ts
  packages/server/database/types/ScheduledJobOrganizationLock.ts
  packages/server/graphql/private/mutations/runScheduledJobs.ts
Labels: size/s

#7649 feat(standups): Email Summaries
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummary.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx
  packages/client/package.json
  packages/server/email/newMeetingSummaryEmailCreator.tsx
  packages/server/graphql/mutations/endTeamPrompt.ts
  packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  yarn.lock
Labels: One Review Required, size/m

#7660 fix: missing prompts in starfish retro template
  packages/server/database/migrations/20230116165620-fixStarfishTemplate.ts
Labels: One Review Required, size/s

#7676 feat(search): add search ability to meeting view
  packages/client/components/MeetingsDash.tsx
  packages/client/components/MeetingsDashEmpty.tsx
  packages/client/components/TopBarSearch.tsx
  packages/client/types/constEnums.ts
Labels: One Review Required, size/s

#7438 fix: Line breaks in comments now work on Android
  packages/client/components/DiscussionThreadInput.tsx
Labels: size/xs

#7670 chore: change "Timeline" to "History"
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MyDashboardTimeline.tsx
Labels: enhancement, size/s

#7658 chore(ai-summary): limit access to AI summaries
  packages/client/types/constEnums.ts
  packages/server/database/types/Team.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/canAccessAISummary.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/helpers/updateQualAIMeetingsCount.ts
  packages/server/graphql/types/Team.ts
  packages/server/postgres/migrations/1673629660481_addQualAIMeetingsCount.ts
  packages/server/postgres/queries/src/updateTeamByTeamIdQuery.sql
Labels: size/m

#7690 fix: use stripe invoice.paid event instead of invoice.payment_succeeded
  packages/server/billing/stripeWebhookHandler.ts
  packages/server/graphql/private/mutations/stripeInvoicePaid.ts
  packages/server/graphql/private/typeDefs/stripeInvoicePaid.graphql
Labels: size/m

#7659 feat(ai-summary): add summary to end meeting notification
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/s

#7691 fix(standups): 'next activity' -> 'current activity'
  packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
Labels: One Review Required, size/xs

#7689 chore: Cleanup private _legacy.graphql types
  packages/server/graphql/private/typeDefs/_legacy.graphql
Labels: size/xl
