Repository ParabolInc/parabol, pull requests merged in 2023-02, with the labels that each got.

#7680 chore(metrics): Add `isPatient0` property to `sign_up` events emitted by GA4
  packages/client/components/SAMLRedirect.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
Labels: One Review Required, size/s

#7705 chore(ai-summary): update meeting summary url
  packages/client/mutations/EndRetrospectiveMutation.ts
Labels: One Review Required, size/s

#7709 chore(checkout-flow): add checkout feature flag
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required, size/s

#7710 chore: update team invite email
  packages/client/modules/email/components/TeamInvite.tsx
  packages/client/types/constEnums.ts
Labels: One Review Required, size/s

#7730 chore(deps): bump deps to fix vulns
  package.json
  packages/client/package.json
  packages/server/package.json
  scripts/webpack/dev.clientdll.config.js
  yarn.lock
Labels: size/xl

#7737 chore(deps): bump webpack, undici
  package.json
  packages/client/package.json
  packages/server/package.json
  yarn.lock
Labels: size/l

#7739 fix(ai-summary): summary references "the text"
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: One Review Required, size/xs

#7679 chore: Migrate MeetingTemplate to PG (Phase 1 of 3)
  packages/server/database/types/MeetingTemplate.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/customRedisQueries.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/graphql/mutations/addPokerTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/removePokerTemplate.ts
  packages/server/graphql/mutations/removeReflectTemplate.ts
  packages/server/graphql/mutations/renameMeetingTemplate.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/updateTemplateScope.ts
  packages/server/graphql/private/mutations/setIsFreeMeetingTemplate.ts
  packages/server/graphql/private/types/SetIsFreeMeetingTemplateSuccess.ts
  packages/server/postgres/migrations/1674237759799_meetingTemplates.ts
  packages/server/postgres/queries/insertMeetingTemplate.ts
  packages/server/postgres/queries/removeMeetingTemplate.ts
  packages/server/postgres/queries/removeMeetingTemplatesForTeam.ts
  packages/server/postgres/queries/updateMeetingTemplateFreeStatusById.ts
  packages/server/postgres/queries/updateMeetingTemplateFreeStatusByName.ts
  packages/server/postgres/queries/updateMeetingTemplateLastUsedAt.ts
  packages/server/postgres/queries/updateMeetingTemplateName.ts
  packages/server/postgres/queries/updateMeetingTemplateOrgId.ts
  packages/server/postgres/queries/updateMeetingTemplateScope.ts
Labels: size/m

#7742 fix: bundle tutorial thumbnail
  packages/client/components/TutorialMeetingCard.tsx
  packages/client/types/modules.d.ts
  packages/server/types/modules.d.ts
  static/images/illustrations/tutorialthumb.jpg
Labels: size/xs

#7637 chore(teams-limit): send locked & warning email
  packages/client/components/InsightsDomainNudge.tsx
  packages/client/components/NewMeetingActions.tsx
  packages/client/components/PinnedSnackbarNotifications.tsx
  packages/client/modules/email/components/LimitsEmails/LockedEmail.tsx
  packages/client/modules/email/components/LimitsEmails/SevenDayWarningEmail.tsx
  packages/client/modules/email/components/LimitsEmails/ThirtyDayWarningEmail.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/teamDashboard/components/UnpaidTeamModal/UnpaidTeamModal.tsx
  packages/client/types/constEnums.ts
  packages/server/billing/helpers/sendTeamsLimitEmail.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/database/types/ScheduledJob.ts
  packages/server/database/types/ScheduledJobOrganizationLock.ts
  packages/server/database/types/ScheduledTeamLimitsJob.ts
  packages/server/database/types/processTeamsLimitsJob.ts
  packages/server/database/types/scheduleTeamLimitsJobs.ts
  packages/server/email/teamLimitsEmailCreator.tsx
  packages/server/graphql/mutations/helpers/isStartMeetingLocked.ts
  packages/server/graphql/private/mutations/runScheduledJobs.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/l

#7725 chore: Invert meetingHistoryLimit feature flag
  packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
  packages/server/graphql/types/helpers/isMeetingLocked.ts
Labels: One Review Required, size/s

#7749 chore: fix case-sensitive
  static/images/illustrations/tutorialThumb.jpg
Labels: size/xs

#7750 fix: yarn dev remove graphiql from dll
  scripts/webpack/dev.clientdll.config.js
Labels: size/xs

#7720 chore: prevent new rethinkdb migrations in the database/migrations directory
  package.json
  scripts/migrate.js
  scripts/toolboxSrc/migrate-create.ts
  scripts/webpack/toolbox.config.js
Labels: One Review Required, size/s

#7707 feat(recurrence): Stable link for meeting series
  packages/client/components/MeetingSeriesRedirector.tsx
  packages/client/components/MeetingSeriesRoot.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/mutations/AcceptTeamInvitationMutation.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/graphql/public/typeDefs/MeetingSeries.graphql
  packages/server/graphql/public/typeDefs/acceptTeamInvitation.graphql
  packages/server/graphql/public/types/MeetingSeries.ts
  packages/server/graphql/types/AcceptTeamInvitationPayload.ts
Labels: One Review Required, size/m

#7682 chore(teams-limit): query HubSpot API to filter out in progress deals
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/hubSpot/backfillHubSpot.ts
  packages/server/hubSpot/hubSpotApi.ts
Labels: size/m

#7681 chore(teams-limit): avoid showing nagging snackbar if the limit is fixed
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/public/types/User.ts
  packages/server/hubSpot/backfillHubSpot.ts
  packages/server/hubSpot/hubSpotApi.ts
Labels: size/m

#7753 chore: Switch to review stats package
  .github/workflows/stats.yml
  scripts/reviewStats.ts
Labels: size/m

#7752 chore(metrics): Do not call identify() on feature flag changes
  packages/server/graphql/public/mutations/addFeatureFlag.ts
Labels: size/s

#7402 feat: create bundles without node_modules
  packages/server/package.json
  scripts/prod.js
  scripts/toolboxSrc/pgMigrateRunner.ts
  scripts/toolboxSrc/rethinkMigrateRunner.ts
  scripts/toolboxSrc/standaloneMigrations.ts
  scripts/webpack/prod.servers.config.js
  scripts/webpack/utils/transformRules.js
  yarn.lock
Labels: size/l

#7716 feat(recurrence): Recurrence-specific meeting card
  packages/client/components/MeetingCard.tsx
  packages/client/components/MeetingsDash.tsx
  packages/client/styles/paletteV3.ts
Labels: One Review Required, size/m

#7747 fix(recurrence): Don't restart meetings on archived teams
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: One Review Required, size/s

#7585 feat(recurrence): Added advanced recurrence settings
  codegen.json
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingRecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/HumanReadableRecurrenceRule.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceDayCheckbox.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceTimePicker.tsx
  packages/client/components/TeamPrompt/Recurrence/TimeLeftBadge.tsx
  packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/components/TeamPrompt/TeamPromptBadge.tsx
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/hooks/useMutationProps.tsx
  packages/client/hooks/usePortal.tsx
  packages/client/mutations/StartRecurrenceMutation.ts
  packages/client/mutations/StartTeamPromptMutation.ts
  packages/client/mutations/StopRecurrenceMutation.ts
  packages/client/mutations/UpdateRecurrenceSettingsMutation.ts
  packages/client/package.json
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/mutations/startTeamPrompt.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
  packages/server/graphql/public/mutations/stopRecurrence.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
  packages/server/graphql/public/typeDefs/RRule.graphql
  packages/server/graphql/public/typeDefs/startRecurrence.graphql
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/typeDefs/stopRecurrence.graphql
  packages/server/graphql/public/typeDefs/updateRecurrenceSettings.graphql
  packages/server/graphql/public/types/RRule.ts
  packages/server/graphql/public/types/StartRecurrenceSuccess.ts
  packages/server/graphql/public/types/StartTeamPromptSuccess.ts
  packages/server/graphql/public/types/StopRecurrenceSuccess.ts
  packages/server/graphql/public/types/UpdateRecurrenceSettingsSuccess.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/StartTeamPromptPayload.ts
  packages/server/graphql/types/TeamSubscriptionPayload.ts
  packages/server/package.json
  yarn.lock
Labels: size/xl

#7765 chore: remove user feature flag
  codegen.json
  packages/client/mutations/AddFeatureFlagMutation.ts
  packages/client/mutations/UpdateFeatureFlagMutation.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/server/__tests__/addFeatureFlag.test.ts
  packages/server/__tests__/updateFeatureFlag.test.ts
  packages/server/graphql/public/mutations/updateFeatureFlag.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UpdateFeatureFlagPayload.ts
  packages/server/postgres/queries/src/removeUserFeatureFlagsQuery.sql
Labels: size/m

#7767 chore(standups): removed beta badge from standups
  packages/client/components/NewMeetingCarousel.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Labels: One Review Required, size/s

#7769 fix: sometimes meetings could not be closed
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/endSprintPoker.ts
Labels: size/xs

#7733 feat(checkout-flow): left sidebar
  packages/client/components/Dashboard.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/modules/teamDashboard/components/TeamTasksHeader/TeamTasksHeader.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationPage.tsx
  packages/client/modules/userDashboard/components/UserDashboard/UserDashboard.tsx
Labels: size/m

#7759 chore(ai-summary): track no stats in Slack summary
  packages/server/graphql/mutations/helpers/notifications/getSummaryText.ts
Labels: One Review Required, size/xs

#7760 feat: add seasonal retros
  packages/server/postgres/migrations/1676299334703_addSeasonalTemplates.ts
Labels: size/m

#7768 feat(standups): added options menu tooltip
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/utils/react/mergeRefs.ts
Labels: size/s

#7758 chore(dx): add updateCache function to dataLoader
  packages/server/dataloader/NullableDataLoader.ts
  packages/server/dataloader/RootDataLoader.ts
  packages/server/dataloader/UpdatableCacheDataLoader.ts
  packages/server/dataloader/__tests__/nullableDataLoader.test.ts
  packages/server/dataloader/foreignKeyLoaderMaker.ts
  packages/server/dataloader/rethinkForeignKeyLoader.ts
  packages/server/dataloader/rethinkPrimaryKeyLoader.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
Labels: size/s

#7775 fix: Fix server error when joining a team by invitation link
  packages/client/mutations/AcceptTeamInvitationMutation.ts
  packages/server/graphql/types/AcceptTeamInvitationPayload.ts
Labels: One Review Required, size/s

#7777 feat(recurrence): Copy meeting series permalink
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/MenuItemLabel.tsx
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
Labels: One Review Required, size/m

#7784 fix: remove font-size 18px declaration on tasks editing status label
  packages/client/components/EditingStatus/EditingStatusText.tsx
Labels: bug, size/xs, UI refinement

#7686 feat: SAML UI: Create a verifyDomain mutation
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/SAML.ts
  packages/server/graphql/private/mutations/enableSAMLForDomain.ts
  packages/server/graphql/private/mutations/helpers/normalizeSlugName.ts
  packages/server/graphql/private/mutations/verifyDomain.ts
  packages/server/graphql/private/typeDefs/verifyDomain.graphql
  packages/server/postgres/migrations/1676141596550_updateOrgIdOnSAML.ts
Labels: size/m

#7782 fix(dashboard): Meeting card shadow doesn't match card
  packages/client/components/MeetingCard.tsx
Labels: size/s

#7684 feat: SAML UI: Add UI with disabled state
  packages/client/components/InputField/BasicInput.tsx
  packages/client/components/InputField/BasicTextArea.tsx
  packages/client/components/ToggleNav/ToggleNav.tsx
  packages/client/modules/userDashboard/components/BillingMembersToggle/BillingMembersToggle.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationHeader.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSSOFrame.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSignOnUrl.tsx
  packages/client/modules/userDashboard/components/Organization/Organization.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationPage.tsx
  packages/client/modules/userDashboard/containers/OrgAuthentication/OrgAuthenticationRoot.tsx
  packages/client/utils/constants.ts
  packages/client/utils/makeMaxWidthMediaQuery.ts
  packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: size/m

#7790 chore(tiptap): Upgrade tiptap to pull in bugfixes
  packages/client/package.json
  yarn.lock
Labels: size/l

#7779 fix(standups): Autofocus the input in the discussion drawer when opened
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/TaskEditor/CommentEditor.tsx
Labels: size/s

#7795 fix(teams-limit): fix teams limit check query fails with an error on non-local environment
  packages/server/billing/helpers/teamLimitsCheck.ts
Labels: One Review Required, size/xs

#7786 chore: select best platform for the job
  docker/dev.yml
Labels: size/xs

#7780 chore: bump node, rethinkdb-ts, typescript, uWS
  .circleci/config.yml
  .github/workflows/check.yml
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
  packages/client/hooks/useRouter.ts
  packages/client/package.json
  packages/client/utils/AtlassianManager.ts
  packages/gql-executor/package.json
  packages/server/dataloader/LocalCache.ts
  packages/server/graphql/composeResolvers.ts
  packages/server/graphql/nestedSchema/nestGitLabEndpoint.ts
  packages/server/package.json
  packages/server/postgres/queries/insertDiscussions.ts
  packages/server/safetyPatchRes.ts
  packages/server/socketHandlers/handleClose.ts
  packages/server/socketHandlers/handleMessage.ts
  packages/server/socketHandlers/handleOpen.ts
  packages/server/socketHandlers/handleUpgrade.ts
  packages/server/socketHelpers/ConnectionContext.ts
  packages/server/socketHelpers/closeTransport.ts
  packages/server/socketHelpers/keepAlive.ts
  packages/server/socketHelpers/sendEncodedMessage.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  yarn.lock
Labels: size/m

#7804 fix(emails): Upgrade mailgun to 7.0.4
  packages/server/package.json
  yarn.lock
Labels: One Review Required, size/s

#7805 fix(recurrence/emails): Generate email summaries using facilitator auth
  packages/server/email/newMeetingSummaryEmailCreator.tsx
Labels: One Review Required, size/s

#7781 chore(teams-limit): remove teams limit notifications after upgrade or removing a team
  codegen.json
  packages/client/mutations/toasts/makeNotificationToastKey.ts
  packages/client/mutations/toasts/mapDiscussionMentionedToToast.ts
  packages/client/mutations/toasts/mapResponseMentionedToToast.ts
  packages/client/mutations/toasts/mapResponseRepliedToToast.ts
  packages/client/mutations/toasts/mapTeamsLimitExceededToToast.ts
  packages/client/mutations/toasts/mapTeamsLimitReminderToToast.ts
  packages/client/mutations/toasts/updateNotificationToast.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/server/billing/helpers/removeTeamLimitsJobs.ts
  packages/server/billing/helpers/removeTeamsLimitObjects.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/mutations/archiveOrganization.ts
  packages/server/graphql/mutations/helpers/upgradeToTeamTier.ts
  packages/server/graphql/mutations/updateCreditCard.ts
  packages/server/graphql/mutations/upgradeToTeamTier.ts
  packages/server/graphql/public/mutations/helpers/updateNotification.ts
  packages/server/graphql/public/typeDefs/UpatedNotification.graphql
  packages/server/graphql/public/types/UpdatedNotification.ts
  packages/server/postgres/migrations/1676461074304_NotificationOrgIdIndex.ts
Labels: size/m

#7597 chore: Added Tailwind CSS
  .vscode/extensions.json
  package.json
  packages/client/Root.tsx
  packages/client/components/Action/Action.tsx
  packages/client/package.json
  packages/client/styles/theme/fontLoader.ts
  packages/client/styles/theme/global.css
  packages/client/styles/theme/globalStyles.ts
  postcss.config.js
  scripts/webpack/dev.client.config.js
  scripts/webpack/prod.client.config.js
  static/fonts/IBMPlexMono-Regular.woff2
  static/fonts/IBMPlexMono-SemiBold.woff2
  static/fonts/IBMPlexSans-Italic.woff2
  static/fonts/IBMPlexSans-Regular.woff2
  static/fonts/IBMPlexSans-SemiBold.woff2
  static/fonts/IBMPlexSans-SemiBoldItalic.woff2
  tailwind.config.js
  yarn.lock
Labels: size/l

#7808 chore: add css extract
  package.json
  scripts/webpack/prod.client.config.js
  yarn.lock
Labels: size/s

#7807 chore(retros-in-disguise): Added retros in disguise feature flag and empty route
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
Labels: One Review Required, size/s

#7810 chore(docker): Redis and RethinkDB database versions fixed for the development docker-compose
  docker/dev.yml
Labels: size/xs

#7815 chore(docker-compose): RethinkDB fixed to v2.4.2 and Redis fixed to v6 for local development and self-hosted deployment
  docker-compose.yml
  docker/dev.yml
Labels: size/s

#7811 chore: keep types on colors
  packages/client/styles/paletteV3.ts
  packages/client/tailwind.preset.d.ts
  packages/client/tailwind.preset.js
  packages/client/tailwindTheme.ts
  packages/client/utils/taskStatus.ts
Labels: size/m

#7793 feat(checkout-flow): plans UI
  packages/client/components/InsightsCharts.tsx
  packages/client/components/InsightsDomainPanel.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBillingHeading.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgStats.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/Organization/OrgNav.tsx
  packages/client/modules/userDashboard/components/Organization/Organization.tsx
  packages/client/styles/paletteV3.ts
  packages/client/types/constEnums.ts
Labels: size/l
