Repository ParabolInc/parabol, pull requests merged in 2023-11, with the labels that each got.

#9072 feat: adds MoSCoW and RICE prioritization templates
  packages/server/postgres/migrations/1698263155574_addPrioritizationTemplates.ts
Labels: size/m

#9095 chore: remove dokku artifacts
  README.md
  docs/alternative-licenses/us-department-of-defense/README.md
  docs/deployment.md
  nginx.conf.sigil
  packages/integration-tests/README.md
  pm2.config.js
Labels: size/m

#9099 fix: restore missing pm2.config.js
  pm2.config.js
Labels: size/s

#9080 fix: gracefully handle reconnects when servers upgrade
  packages/server/activeClients.ts
  packages/server/graphql/httpGraphQLHandler.ts
  packages/server/server.ts
  packages/server/socketHandlers/handleDisconnect.ts
  packages/server/socketHandlers/handleOpen.ts
  packages/server/sse/SSEConnectionHandler.ts
  packages/server/sse/SSEPingHandler.ts
Labels: size/s

#9090 feat: More templates are free now
  packages/server/postgres/migrations/1698831891828_moreFreeRetroTemplates.ts
Labels: size/s

#9055 chore: don't lock org in case of failed payment
  packages/server/billing/helpers/terminateSubscription.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
Labels: size/xs

#9036 chore: Add getVerifiedOrgIds tests
  packages/server/dataloader/__tests__/isOrgVerified.test.ts
  packages/server/dataloader/customLoaderMakers.ts
Labels: size/m

#8958 feat(chore): Add an option to archive all done tasks
  codegen.json
  packages/client/modules/teamDashboard/components/TaskColumn/ArchiveAllDoneTasksModal.tsx
  packages/client/modules/teamDashboard/components/TaskColumn/TaskColumn.tsx
  packages/client/mutations/BatchArchiveTasksMutation.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/public/mutations/batchArchiveTasks.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/batchArchiveTasks.graphql
  packages/server/graphql/public/types/BatchArchiveTasksSuccess.ts
  packages/server/safeMutations/archiveTasksForDB.ts
Labels: size/m

#9071 chore: update sign up redirect destination
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/client/mutations/VerifyEmailMutation.ts
  packages/client/mutations/handlers/handleAuthenticationRedirect.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/s

#9119 fix: reference to SendClientSideEvent
  packages/client/components/RequestToJoin.tsx
Labels: size/xs

#9121 chore(github-templates): Release Test issue template now shows how to check e-mail verifications using debug mail provider
  .github/ISSUE_TEMPLATE/release_test.md
Labels: size/xs

#9092 chore(metrics): Segment dependency cleanup
  .env.example
  docker/parabol-ubi/docker-build/environments/buildenv
  docker/parabol-ubi/docker-build/environments/local-buildenv
  docker/parabol-ubi/docker-build/environments/pipeline
  packages/client/components/AnalyticsPage.tsx
  packages/client/components/MeetingHelp/ActionMeetingAgendaItemsHelpMenu.tsx
  packages/client/components/MeetingHelp/ActionMeetingFirstCallHelpMenu.tsx
  packages/client/components/MeetingHelp/ActionMeetingLastCallHelpMenu.tsx
  packages/client/components/MeetingHelp/CheckInHelpMenu.tsx
  packages/client/components/MeetingHelp/DiscussHelpMenu.tsx
  packages/client/components/MeetingHelp/EstimateHelpMenu.tsx
  packages/client/components/MeetingHelp/GroupHelpMenu.tsx
  packages/client/components/MeetingHelp/ReflectHelpMenu.tsx
  packages/client/components/MeetingHelp/ScopeHelpMenu.tsx
  packages/client/components/MeetingHelp/TeamHealthHelpMenu.tsx
  packages/client/components/MeetingHelp/UpdatesHelpMenu.tsx
  packages/client/components/MeetingHelp/VoteHelpMenu.tsx
  packages/client/components/NotificationDropdown.tsx
  packages/client/hooks/useClientSideTrack.ts
  packages/client/modules/userDashboard/components/CreditCardModal/CreditCardForm.tsx
  packages/client/package.json
  packages/client/types/modules.d.ts
  packages/client/utils/safeIdentify.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/graphql/mutations/deleteUser.ts
  packages/server/graphql/mutations/helpers/sendAccountRemovedEvent.ts
  packages/server/graphql/mutations/helpers/sendPokerMeetingRevoteEvent.ts
  packages/server/graphql/mutations/pokerResetDimension.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/webhookGraphQLHandler.ts
  packages/server/package.json
  packages/server/server.ts
  packages/server/types/modules.d.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
  yarn.lock
Labels: size/m

#9124 feat: create ironbank s3 artifacts manual GH
  .github/workflows/ironbank.yml
Labels: size/s

#9126 chore: ironbank github action, update permissions, add proper cp path
  .github/workflows/ironbank.yml
Labels: size/s

#9125 fix: unable to create org
  packages/client/mutations/fragments/PublicTeamsFrag.ts
Labels: size/xs

#9128 fix: autoJoin needs refresh
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: One Review Required, size/xs

#9073 chore(Snyk): Security upgrade mailgun.js from 7.0.4 to 9.3.0
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9138 chore: test, build, release. first pass
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/m

#9141 fix: use PAT for release-please
  .github/workflows/release-please.yml
Labels: size/xs

#9143 fix: use app instead of pat
  .github/workflows/release-please.yml
Labels: size/xs

#9144 chore: cancel previous in-progress workflows
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: size/s

#9145 chore: update deployment docs
  docs/deployment.md
Labels: size/xs

#9127 chore: Show helpful message in team settings for non-leads
  packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
Labels: size/s

#9129 chore: Apply no template limit feature flag to some new users
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: size/s

#9160 chore: Users with noTemplateLimit flag can use paid templates
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/SelectTemplate.tsx
  packages/client/utils/useTemplateDescription.ts
  packages/server/graphql/mutations/selectTemplate.ts
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
Labels: size/s

#9131 feat: fix custom template border
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
Labels: One Review Required, size/xs

#9178 chore: Add SAML setup to new checkout flow
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
Labels: size/s

#8493 feat: add GCS as a FileStore
  .env.example
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/fileStorage/S3FileStoreManager.ts
  packages/server/fileStorage/getFileStoreManager.ts
  packages/server/graphql/mutations/helpers/getTemplateIllustrationUrl.ts
  packages/server/postgres/migrations/1685721573097_addPrePostMortemTemplates.ts
  packages/server/postgres/migrations/1686226641890_fixed-activities.ts
  packages/server/postgres/migrations/1690364653869_addOneOnOneMeetingType.ts
Labels: size/m

#9186 fix: replace saas url with calculated value for PPMIs
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/LogoFooter.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Labels: size/s

#9166 chore: Handle migration conflicts
  .github/workflows/migration-order.yml
Labels: size/s

#9190 fix(demo): Don't show top bar or sidebar on demo summary
  packages/client/modules/summary/components/NewMeetingSummary.tsx
Labels: One Review Required, size/s

#9194 feat(admin): Base Org Admin role
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/server/database/types/OrganizationUser.ts
  packages/server/graphql/types/OrgUserRole.ts
Labels: One Review Required, size/s

#8670 fix: Avoid caching permissions with different arguments
  packages/server/graphql/public/rules/isEnvVarTrue.ts
  packages/server/graphql/public/rules/isViewerOnTeam.ts
  packages/server/graphql/public/rules/rateLimit.ts
Labels: size/s

#9187 fix: sort team names alphabetically
  packages/server/graphql/types/Organization.ts
Labels: One Review Required, size/s

#9189 fix: can auto join with saml login
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: size/xs

#9232 feat: node update v20.9.0 LTS, req rethinkdb-ts and uWS version bump
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
  packages/server/package.json
  yarn.lock
Labels: size/s

#9241 fix: release please build add systemtap
  docker/parabol-ubi/docker-build/dockerfiles/parabol.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
Labels: size/xs

#9169 chore(kudos): add kudos record when adding emoji reaction
  codegen.json
  packages/client/mutations/AddReactjiToReactableMutation.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addReactjiToReactable.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/typeDefs/AddReactjiToReactablePayload.graphql
  packages/server/graphql/public/typeDefs/Kudos.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/addReactjiToReactable.graphql
  packages/server/graphql/public/types/AddReactjiToReactableSuccess.ts
  packages/server/graphql/public/types/Kudos.ts
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddReactjiToReactablePayload.ts
  packages/server/postgres/migrations/1699561055400_addKudosesTable.ts
  packages/server/postgres/queries/getKudosesByIds.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/l

#9199 feat(kudos): display notification when kudos received
  packages/client/components/KudosReceivedNotification.tsx
  packages/client/components/NotificationPicker.tsx
  packages/client/components/NotificationTemplate.tsx
  packages/client/mutations/toasts/mapKudosReceivedToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationKudosReceived.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/typeDefs/NotifyKudosReceived.graphql
  packages/server/graphql/public/types/NotifyKudosReceived.ts
  packages/server/graphql/types/NotificationEnum.ts
Labels: size/m

#9244 chore: Fix formatting
  packages/server/graphql/public/mutations/loginWithMicrosoft.ts
Labels: size/xs

#9233 fix: author should be nullable when comment was anonymous
  packages/client/components/DiscussionMentioned.tsx
  packages/client/components/ResponseReplied.tsx
  packages/client/modules/email/components/EmailNotifications/EmailDiscussionMentioned.tsx
  packages/client/modules/email/components/EmailNotifications/EmailResponseReplied.tsx
  packages/client/mutations/toasts/mapDiscussionMentionedToToast.ts
  packages/client/mutations/toasts/mapResponseRepliedToToast.ts
  packages/server/graphql/public/typeDefs/NotifyDiscussionMentioned.graphql
  packages/server/graphql/public/typeDefs/NotifyResponseReplied.graphql
  packages/server/graphql/public/types/NotifyDiscussionMentioned.ts
  packages/server/graphql/public/types/NotifyResponseReplied.ts
Labels: size/s

#9249 chore(env-file): ununsed variables removed
  .env.example
Labels: size/xs

#9251 feat: remove gcal flag
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: One Review Required, size/s

#9164 fix: increases integration icon visibility
  packages/client/components/IconLabel.tsx
  packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterIntegrateToggle.tsx
Labels: One Review Required, size/s, UX backlog
