Repository ParabolInc/parabol, pull requests merged in 2023-03, with the labels that each got.

#7839 chore(relay): Fix convertToUseFragment naming conflict bug
  scripts/codeshift/convertToUseFragment.ts
Labels: One Review Required, size/xs

#7841 chore(relay): createFragmentContainer -> useFragment 2/N
  packages/client/components/KickedOut.tsx
  packages/client/components/MeetingCard.tsx
  packages/client/components/MeetingSidebarTeamMemberStageItems.tsx
  packages/client/components/MeetingStageTimeLimitEnd.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/NewMeetingCheckIn.tsx
  packages/client/components/NewMeetingSidebar.tsx
  packages/client/components/NewTeamOrgDropdown.tsx
  packages/client/components/NotificationPicker.tsx
  packages/client/components/NotificationTemplate.tsx
  packages/client/components/NullableTask/NullableTask.tsx
  packages/client/components/PalettePicker/PalettePicker.tsx
  packages/client/components/ParabolScopingSearchFilterMenu.tsx
  packages/client/components/ParabolScopingSearchFilterToggle.tsx
  packages/client/components/ParabolScopingSearchResultItem.tsx
  packages/client/components/ParabolScopingSelectAllTasks.tsx
  packages/client/components/PaymentRejected.tsx
  packages/client/components/PokerActiveVoting.tsx
  packages/client/components/PokerCard.tsx
  packages/client/components/PokerCardDeck.tsx
  packages/client/components/PokerDimensionValueControl.tsx
  packages/client/components/PokerDiscussVoting.tsx
  packages/client/components/PokerEstimateHeaderCard.tsx
  packages/client/components/PokerEstimateHeaderCardParabol.tsx
  packages/client/components/PokerEstimatePhase.tsx
  packages/client/components/PokerMeeting.tsx
  packages/client/components/PokerMeetingSidebar.tsx
  packages/client/components/PokerSidebarEstimateSection.tsx
  packages/client/components/PokerSidebarPhaseListItemChildren.tsx
  packages/client/components/PokerVotingRow.tsx
  packages/client/components/PromoteToBillingLeader.tsx
  packages/client/components/ReflectionCard/ColorBadge.tsx
  packages/client/components/ReflectionCard/ReactjiSection.tsx
  packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
  packages/client/components/ReflectionGroupHeader.tsx
  packages/client/components/RetroDiscussPhase.tsx
  packages/client/components/RetroGroupPhase.tsx
  packages/client/components/RetroMeetingSidebar.tsx
  packages/client/components/RetroReflectPhase/PhaseItemColumn.tsx
  packages/client/components/RetroReflectPhase/ReflectionStack.tsx
  packages/client/components/RetroReflectPhase/RetroReflectPhase.tsx
  packages/client/components/RetroSidebarDiscussSection.tsx
  packages/client/components/RetroSidebarPhaseListItemChildren.tsx
  packages/client/components/RetroVoteMetaHeader.tsx
  packages/client/components/RetroVotePhase.tsx
Labels: size/xl

#7840 chore(relay): createFragmentContainer -> useFragment 1/N
  packages/client/components/ActionMeeting.tsx
  packages/client/components/ActionMeetingAgendaItems.tsx
  packages/client/components/ActionMeetingFirstCall.tsx
  packages/client/components/ActionMeetingLastCall.tsx
  packages/client/components/ActionMeetingSidebar.tsx
  packages/client/components/ActionMeetingUpdates.tsx
  packages/client/components/ActionMeetingUpdatesPrompt.tsx
  packages/client/components/ActionSidebarAgendaItemsSection.tsx
  packages/client/components/ActionSidebarPhaseListItemChildren.tsx
  packages/client/components/AddTeamMemberAvatarButton.tsx
  packages/client/components/AddTeamMemberModal.tsx
  packages/client/components/AvatarList.tsx
  packages/client/components/AvatarListUser.tsx
  packages/client/components/AzureDevOpsScopingSearchFilterMenu.tsx
  packages/client/components/AzureDevOpsScopingSearchFilterToggle.tsx
  packages/client/components/AzureDevOpsScopingSearchInput.tsx
  packages/client/components/AzureDevOpsScopingSelectAllIssues.tsx
  packages/client/components/DashboardAvatars/DashboardAvatar.tsx
  packages/client/components/DashboardAvatars/DashboardAvatars.tsx
  packages/client/components/DashboardAvatars/TeamMemberAvatarMenu.tsx
  packages/client/components/DeckActivityAvatars.tsx
  packages/client/components/DiscussPhaseReflectionGrid.tsx
  packages/client/components/DiscussPhaseSqueeze.tsx
  packages/client/components/DiscussionThreadList.tsx
  packages/client/components/DueDatePicker.tsx
  packages/client/components/DueDateToggle.tsx
  packages/client/components/EditingStatus/EditingStatus.tsx
  packages/client/components/EstimateDimensionColumn.tsx
  packages/client/components/EstimatePhaseArea.tsx
  packages/client/components/EstimatePhaseDiscussionDrawer.tsx
  packages/client/components/FacilitatorMenu.tsx
  packages/client/components/GroupingKanban.tsx
  packages/client/components/GroupingKanbanColumn.tsx
  packages/client/components/IntegratedTaskContent.tsx
  packages/client/components/InvitationLinkErrorExpired.tsx
  packages/client/components/JiraFieldMenu.tsx
  packages/client/components/JiraScopingSearchResults.tsx
  packages/client/components/JiraScopingSearchResultsRoot.tsx
  packages/client/components/JiraScopingSelectAllIssues.tsx
Labels: One Review Required, size/xl

#7846 chore(github): Don't auto-assign at-mentioned users
  .github/workflows/assign_mentioned.yml
Labels: One Review Required, size/s

#7809 chore: Added a tailwind preset file
  packages/client/styles/paletteV3.ts
  packages/client/tailwind.preset.js
  packages/client/tailwindTheme.ts
  packages/client/utils/taskStatus.ts
  tailwind.config.js
Labels: size/m

#7799 feat(checkout-flow): plans functionality
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgStats.tsx
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/helpers/getActiveTeamCountByOrgIds.ts
  packages/server/graphql/public/types/helpers/getTeamsByOrgIds.ts
  packages/server/graphql/types/Organization.ts
Labels: size/m

#7819 fix: align search bar with meeting cards
  packages/client/components/MeetingsDash.tsx
  packages/client/components/TopBarSearch.tsx
Labels: One Review Required, size/xs

#7842 chore(relay): createFragmentContainer -> useFragment 3/N
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailReflectionCard.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMemberTaskSummaryList.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithTasks.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithoutTasks.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryAvatarHeader.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryPokerStories.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooter.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterUserAssignee.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardStatusMenu/TaskFooterTagMenu.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardStatusMenu/TaskFooterTagMenuStatusItem.tsx
  packages/client/modules/outcomeCard/components/TaskFooterUserAssigneeMenuRoot.tsx
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
  packages/client/modules/team/components/NewTeamOrgPicker.tsx
  packages/client/modules/teamDashboard/components/AgendaInput/AgendaInput.tsx
  packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveOrganization.tsx
  packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveOrganizationForm.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/AtlassianProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/GitHubProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationList.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/SlackProviderRow.tsx
  packages/client/modules/teamDashboard/components/RemoveTeamMemberModal/RemoveTeamMemberModal.tsx
  packages/client/modules/teamDashboard/components/TaskColumn/TaskColumnAddTaskSelectTeam.tsx
  packages/client/modules/teamDashboard/components/TaskColumn/TaskColumnInner.tsx
  packages/client/modules/teamDashboard/components/TeamTasksHeader/TeamTasksHeader.tsx
  packages/client/modules/teamDashboard/containers/TeamColumns/TeamColumnsContainer.tsx
  packages/client/modules/teamDashboard/containers/TeamTasksHeader/TeamTasksHeaderContainer.tsx
  packages/client/modules/userDashboard/components/InvoiceRow/InvoiceRow.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingCreditCardInfo.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingDangerZone.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingUpgrade.tsx
  packages/client/modules/userDashboard/components/OrganizationRow/OrganizationRow.tsx
Labels: One Review Required, size/xl

#7844 chore(relay): createFragmentContainer -> useFragment 4/N
  packages/client/containers/TaskCard/DraggableTask.tsx
  packages/client/modules/invoice/components/InvoiceHeader/InvoiceHeader.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/InvoiceLineItem.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/NextPeriodChargesLineItem.tsx
  packages/client/modules/meeting/components/ActionMeetingUpdatesPromptTeamHelpText.tsx
  packages/client/modules/meeting/components/AddPokerTemplateDimension.tsx
  packages/client/modules/meeting/components/AddScaleValueButtonInput.tsx
  packages/client/modules/meeting/components/EditableTemplateName.tsx
  packages/client/modules/meeting/components/EditableTemplatePromptColor.tsx
  packages/client/modules/meeting/components/EditableTemplateScaleValueColor.tsx
  packages/client/modules/meeting/components/EditableTemplateScaleValueLabel.tsx
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewMeetingCheckInPrompt.tsx
  packages/client/modules/meeting/components/NewMeetingCheckInGreeting.tsx
  packages/client/modules/meeting/components/NewTemplateScaleValueLabelInput.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/PokerTemplateScaleDetails.tsx
  packages/client/modules/meeting/components/PokerTemplateScalePicker.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateItem.tsx
  packages/client/modules/meeting/components/RemoveTemplate.tsx
  packages/client/modules/meeting/components/ScaleActions.tsx
  packages/client/modules/meeting/components/ScaleDropdownMenuItem.tsx
  packages/client/modules/meeting/components/ScaleValuePalettePicker.tsx
  packages/client/modules/meeting/components/SelectScaleDropdown.tsx
  packages/client/modules/meeting/components/SelectTemplate.tsx
  packages/client/modules/meeting/components/TemplateDimensionItem.tsx
  packages/client/modules/meeting/components/TemplateDimensionList.tsx
  packages/client/modules/meeting/components/TemplatePromptItem.tsx
  packages/client/modules/meeting/components/TemplatePromptList.tsx
  packages/client/modules/meeting/components/TemplateScaleValueItem.tsx
  packages/client/modules/meeting/components/TemplateScaleValueList.tsx
  packages/client/modules/meeting/components/TemplateSharing.tsx
  packages/client/utils/makeTemplateDescription.ts
Labels: One Review Required, size/xl

#7845 chore(relay): createFragmentContainer -> useFragment 5/N
  packages/client/components/ScopePhase.tsx
  packages/client/components/ScopePhaseArea.tsx
  packages/client/components/SelectMeetingDropdown.tsx
  packages/client/components/SelectMeetingDropdownItem.tsx
  packages/client/components/SelectSharingScopeDropdown.tsx
  packages/client/components/SelectTeamDropdown.tsx
  packages/client/components/StageTimerControl.tsx
  packages/client/components/StageTimerDisplay.tsx
  packages/client/components/StageTimerModal.tsx
  packages/client/components/StageTimerModalEditTimeEnd.tsx
  packages/client/components/StageTimerModalEditTimeLimit.tsx
  packages/client/components/StageTimerModalEndTime.tsx
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/components/StageTimerModalTimeLimit.tsx
  packages/client/components/SuggestedActionInviteYourTeam.tsx
  packages/client/components/TaskInvolves.tsx
  packages/client/components/TeamArchived.tsx
  packages/client/components/TeamDashTeamMemberMenu.tsx
  packages/client/components/TeamInvitationEmailCreateAccount.tsx
  packages/client/components/TeamInvitationEmailSignin.tsx
  packages/client/components/TeamInvitationErrorAccepted.tsx
  packages/client/components/TeamInvitationErrorExpired.tsx
  packages/client/components/TeamInvitationGoogleCreateAccount.tsx
  packages/client/components/TeamInvitationGoogleSignin.tsx
  packages/client/components/TeamInvitationNotification.tsx
  packages/client/components/ThreadedCommentBase.tsx
  packages/client/components/ThreadedCommentFooter.tsx
  packages/client/components/ThreadedCommentHeader.tsx
  packages/client/components/ThreadedItem.tsx
  packages/client/components/ThreadedItemReply.tsx
  packages/client/components/ThreadedRepliesList.tsx
  packages/client/components/ThreadedTaskBase.tsx
  packages/client/components/TimelineEventCard.tsx
  packages/client/components/TimelineEventCompletedActionMeeting.tsx
  packages/client/components/TimelineEventCompletedRetroMeeting.tsx
  packages/client/components/TimelineEventJoinedParabol.tsx
  packages/client/components/TimelineEventPokerComplete.tsx
  packages/client/components/TimelineEventTeamCreated.tsx
  packages/client/components/TimelinePriorityTasks.tsx
  packages/client/components/TimelineRightDrawer.tsx
  packages/client/components/VoteSettingsMenu.tsx
Labels: One Review Required, size/xl

#7849 feat: Add additional retrospective template illustrations
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  static/images/illustrations/aChristmasCarolRetrospectiveTemplate.png
  static/images/illustrations/alwaysBeLearningRetrospectiveTemplate.png
  static/images/illustrations/diwaliRetrospectiveTemplate.png
  static/images/illustrations/dreamTeamRetrospectiveTemplate.png
  static/images/illustrations/easterRetrospectiveTemplate.png
  static/images/illustrations/halloweenRetrospectiveTemplate.png
  static/images/illustrations/handsOnDeckActivityTemplate.png
  static/images/illustrations/heardSeenRespectedHSRTemplate.png
  static/images/illustrations/herosJourneyTemplate.png
  static/images/illustrations/highlightsLowlightsTemplate.png
  static/images/illustrations/holiRetrospectiveTemplate.png
  static/images/illustrations/hopesAndFearsTemplate.png
  static/images/illustrations/hotAirBalloonTemplate.png
  static/images/illustrations/keepProblemTryTemplate.png
  static/images/illustrations/lunarNewYearRetrospectiveTemplate.png
  static/images/illustrations/marieKondoRetrospectiveTemplate.png
  static/images/illustrations/midsummerRetrospectiveTemplate.png
  static/images/illustrations/newYearRetrospectiveTemplate.png
  static/images/illustrations/original4Template.png
  static/images/illustrations/questionsCommentsConcernsTemplate.png
  static/images/illustrations/roseThornBudTemplate.png
  static/images/illustrations/sWOTAnalysisTemplate.png
  static/images/illustrations/saMoLoTemplate.png
  static/images/illustrations/scrumValuesRetrospectiveTemplate.png
  static/images/illustrations/sixThinkingHatsTemplate.png
  static/images/illustrations/speedCarTemplate.png
  static/images/illustrations/superheroRetrospectiveTemplate.png
  static/images/illustrations/surprisedWorriedInspiredTemplate.png
  static/images/illustrations/teamCharterTemplate.png
  static/images/illustrations/teamRetreatPlanningTemplate.png
  static/images/illustrations/thanksgivingRetrospectiveTemplate.png
  static/images/illustrations/wRAPTemplate.png
Labels: size/s

#7857 fix(teams-limit): add missing billing link to 7 days warning email
  packages/client/modules/email/components/LimitsEmails/SevenDayWarningEmail.tsx
Labels: One Review Required, size/xs

#7863 chore: Add some more Legitity tests
  packages/client/validation/__tests__/Legitity.test.ts
Labels: One Review Required, size/s

#7431 fix: Icebreaker editing is not working properly on Android
  packages/client/components/EditorInputWrapper.tsx
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
Labels: size/m

#7861 fix(teams-limit): fix locked message in usage stats
  packages/client/components/InsightsDomainNudge.tsx
Labels: One Review Required, size/s

#7869 feat(recurrence): Stop Recurrence button
  packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
Labels: One Review Required, size/s

#7848 chore(metrics): Add content_group in GA4 page_view event
  packages/client/components/AnalyticsPage.tsx
  packages/client/utils/getContentGroup.ts
Labels: size/s

#7806 chore(pipeline): Databases backup and restore from CircleCI pipeline
  .circleci/config.yml
Labels: size/m

#7852 feat(checkout-flow): add Stripe elements
  codegen.json
  packages/client/modules/userDashboard/components/OrgBilling/Billing.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/client/mutations/CreatePaymentIntentMutation.ts
  packages/client/package.json
  packages/server/graphql/public/mutations/createPaymentIntent.ts
  packages/server/graphql/public/typeDefs/createPaymentIntent.graphql
  packages/server/graphql/public/types/CreatePaymentIntentSuccess.ts
  packages/server/utils/stripe/StripeManager.ts
  yarn.lock
Labels: size/m

#7897 chore: add temporary story points update result logging
  packages/client/utils/AtlassianManager.ts
Labels: size/s

#7879 feat(checkout-flow): add teams limit warning
  packages/client/components/InsightsDomainNudge.tsx
  packages/client/components/LimitExceededWarning.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
Labels: One Review Required, size/m

#7901 chore: node version bump for security updates
  .circleci/config.yml
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
Labels: size/s

#7836 feat(retros-in-disguise): Base activity library + stubbed cards
  codegen.json
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
  packages/client/components/ActivityLibrary/ActivityLibrarySideBar.tsx
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/queries/helpers/connectionFromTemplateArray.ts
  packages/server/graphql/queries/helpers/getScoredTemplates.ts
  packages/server/graphql/types/PokerMeetingSettings.ts
  packages/server/graphql/types/RetrospectiveMeetingSettings.ts
  packages/server/utils/getTemplateScore.ts
Labels: size/m

#7903 fix: handle SSE and socket done checks
  packages/server/socketHelpers/sendEncodedMessage.ts
Labels: size/xs

#7899 chore: simplify org plans button logic
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
Labels: One Review Required, size/s

#7877 chore(metrics): emit `is_patient_0` as user properties for GA4
  packages/client/components/AnalyticsPage.tsx
  packages/client/components/SAMLRedirect.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
Labels: One Review Required, size/s

#7910 feat(checkout-flow): implement billing leader UI
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeaders.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
  packages/client/types/constEnums.ts
Labels: One Review Required, size/m

#7907 fix: position of notification bell badge
  packages/client/components/TopBarIcon.tsx
Labels: size/xs

#7891 feat(rid): Basic activity library search
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/SearchBar.tsx
Labels: One Review Required, size/s

#7772 fix: do not run removeOrgUserTaskUpdater for undefined tasks
  packages/client/mutations/RemoveOrgUserMutation.ts
  packages/client/subscriptions/NotificationSubscription.ts
Labels: One Review Required, size/xs

#7874 chore(relay): createFragmentContainer -> useFragment 6/N
  packages/client/components/BillingLeaderActionMenu.tsx
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/InvitationLinkDialog.tsx
  packages/client/components/MeetingsDash.tsx
  packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx
  packages/client/components/ReflectionGroupVoting.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/components/TaskColumns/TaskColumns.tsx
  packages/client/components/TaskIntegrationLink.tsx
  packages/client/components/TeamInvitationDialog.tsx
  packages/client/components/TimelineEvent.tsx
  packages/client/components/TimelineSuggestedAction.tsx
  packages/client/components/TopBarAvatar.tsx
  packages/client/components/TopBarSearch.tsx
  packages/client/components/UserDashTeamMemberMenu.tsx
  packages/client/components/UserDashTeamMenu.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailTaskCard.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TaskSummarySection.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/InvoiceLineItemDetails.tsx
  packages/client/modules/meeting/components/EditableTemplateScaleName.tsx
  packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
  packages/client/modules/teamDashboard/components/AgendaList/AgendaList.tsx
  packages/client/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.tsx
  packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx
  packages/client/modules/teamDashboard/components/TaskColumn/TaskColumn.tsx
  packages/client/modules/teamDashboard/components/TaskColumn/TaskColumnAddTask.tsx
  packages/client/modules/teamDashboard/components/Team/Team.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationPage.tsx
  scripts/codeshift/convertToUseFragment.ts
Labels: One Review Required, size/xl

#7875 chore(relay): createFragmentContainer -> useFragment 7/7
  packages/client/components/EditableOrgName.tsx
  packages/client/components/SuggestedActionCreateNewTeam.tsx
  packages/client/components/SuggestedActionTryActionMeeting.tsx
  packages/client/components/SuggestedActionTryRetroMeeting.tsx
  packages/client/components/SuggestedActionTryTheDemo.tsx
  packages/client/components/TaskFooterIntegrateMenuRoot.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingSummaryEmail.tsx
  packages/client/modules/meeting/components/AddTemplatePrompt.tsx
  packages/client/modules/meeting/components/EditableTemplateDimension.tsx
  packages/client/modules/meeting/components/EditableTemplatePrompt.tsx
  packages/client/modules/teamDashboard/components/EditTeamName/EditableTeamName.tsx
Labels: One Review Required, size/m

#7920 chore(pipeline): Remove any reference to dev environment in the CircleCI pipeline
  .circleci/config.yml
Labels: size/s

#7873 fix: fix usage stats charts on small amount of data
  packages/client/components/InsightsCharts.tsx
Labels: size/s

#7921 chore(template-limits): add template limit flag to p0 domains
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: size/s

#7918 fix(teams-limit): count only teams that have had at least 1 meeting in the last 30 days
  packages/client/types/constEnums.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
Labels: One Review Required, size/s

#7919 chore(relay): Remove 'UNSTABLE_renderPolicy: full'
  packages/client/components/AzureDevOpsScopingSearchResults.tsx
  packages/client/components/Dashboard.tsx
  packages/client/components/DemoMeetingRoot.tsx
  packages/client/components/DiscussionThread.tsx
  packages/client/components/GitHubScopingSearchFilterMenu.tsx
  packages/client/components/GitHubScopingSearchResults.tsx
  packages/client/components/GitLabScopingSearchFilterMenu.tsx
  packages/client/components/GitLabScopingSearchResults.tsx
  packages/client/components/Insights.tsx
  packages/client/components/InvitationLink.tsx
  packages/client/components/JiraScopingSearchFilterMenuRoot.tsx
  packages/client/components/JiraScopingSearchResults.tsx
  packages/client/components/JiraServerScopingSearchFilterMenuRoot.tsx
  packages/client/components/JiraServerScopingSearchResults.tsx
  packages/client/components/MassInvitationTokenLink.tsx
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/MeetingSelector.tsx
  packages/client/components/MeetingSeriesRedirector.tsx
  packages/client/components/MyDashboardTasksAndHeader.tsx
  packages/client/components/MyDashboardTimeline.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/components/ParabolScopingSearchResults.tsx
  packages/client/components/SpotlightResults.tsx
  packages/client/components/SuggestMentionableUsers.tsx
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuList.tsx
  packages/client/components/TeamInvitation.tsx
  packages/client/components/ViewerNotOnTeam.tsx
  packages/client/modules/invoice/components/Invoice/Invoice.tsx
  packages/client/modules/meeting/components/PokerTemplateListOrg.tsx
  packages/client/modules/meeting/components/PokerTemplateListPublic.tsx
  packages/client/modules/meeting/components/ReflectTemplateListOrg.tsx
  packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
  packages/client/modules/newTeam/NewTeam.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterTeamAssigneeMenu.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx
  packages/client/modules/teamDashboard/components/TeamDashMain/TeamDashMain.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
  packages/client/modules/teamDashboard/components/UnpaidTeamModal/UnpaidTeamModal.tsx
  packages/client/modules/teamDashboard/containers/Team/TeamContainer.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBilling.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/Organization/Organization.tsx
  packages/client/modules/userDashboard/components/Organizations/Organizations.tsx
  packages/client/modules/userDashboard/components/UserProfile.tsx
  scripts/codeshift/convertToUseFragment.ts
Labels: One Review Required, size/m

#7917 fix(templates): Fix 'Create new template' button error for retros
  packages/client/modules/meeting/components/ReflectTemplateList.tsx
  packages/client/modules/meeting/components/ReflectTemplateListTeam.tsx
Labels: One Review Required, size/s

#7922 chore(dx): Add Parabol employees to reviewers to prevent auto-request-review
  .github/reviewers.yml
Labels: size/xs

#7913 fix: changing width to max-width in tailwind format
  packages/client/components/ActionMeetingUpdatesPrompt.tsx
Labels: One Review Required, size/xs

#7862 chore(teams-limit): change first warning notification text
  packages/client/components/TeamsLimitExceededNotification.tsx
  packages/client/mutations/toasts/mapTeamsLimitExceededToToast.ts
  packages/client/mutations/toasts/mapTeamsLimitReminderToToast.ts
Labels: One Review Required, size/xs

#7924 chore(tailwind): Fix rename warning
  packages/client/tailwindTheme.ts
Labels: One Review Required, size/xs

#7925 feat(standups): Persist draft responses to localstorage
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
Labels: One Review Required, size/s

#7830 feat(checkout-flow): add downgrade logic
  packages/client/modules/userDashboard/components/OrgBilling/DowngradeModal.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/mutations/DowngradeToStarterMutation.ts
  packages/client/utils/constants.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/downgradeToStarter.ts
  packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
  packages/server/graphql/mutations/upgradeToTeamTier.ts
  packages/server/graphql/types/DowngradeCTALocationEnum.ts
  packages/server/graphql/types/ReasonToDowngrade.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/getBillingLeadersByOrgId.ts
Labels: size/l

#7926 fix: slack stats
  packages/server/graphql/mutations/endRetrospective.ts
Labels: One Review Required, size/xs

#7929 chore(upgradeRelay): refactor response and variables from relay mutation types
  packages/client/components/GitHubScopingSearchFilterMenu.tsx
  packages/client/components/GitLabScopingSearchFilterMenu.tsx
  packages/client/components/NewAzureIssueInput.tsx
  packages/client/components/NewGitHubIssueInput.tsx
  packages/client/components/NewGitLabIssueInput.tsx
  packages/client/components/ParabolScopingSearchResultItem.tsx
  packages/client/components/ScopingSearchResultItem.tsx
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/components/TaskFooterIntegrateMenu.tsx
  packages/client/components/TaskFooterIntegrateMenuList.tsx
  packages/client/components/useSetTaskEstimate.ts
  packages/client/hooks/useDraggableReflectionCard.tsx
  packages/client/hooks/useGotoStageId.ts
  packages/client/hooks/useGroupMatrix.ts
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
  packages/client/modules/userDashboard/components/UserSettingsForm/UserSettingsForm.tsx
  packages/client/mutations/AddReactjiToReactableMutation.ts
  packages/client/mutations/ChangeTaskTeamMutation.ts
  packages/client/mutations/CreateTaskIntegrationMutation.ts
  packages/client/mutations/FlagReadyToAdvanceMutation.ts
  packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts
  packages/client/mutations/SelectTemplateMutation.ts
  packages/client/mutations/SetMeetingSettingsMutation.ts
  packages/client/mutations/SetTaskHighlightMutation.ts
  packages/client/mutations/StartDraggingReflectionMutation.ts
  packages/client/mutations/UpdateCommentContentMutation.ts
  packages/client/mutations/UpdateDragLocationMutation.ts
  packages/client/mutations/UpdateNewCheckInQuestionMutation.ts
  packages/client/mutations/UpdateOrgMutation.ts
  packages/client/mutations/UpdatePokerScopeMutation.ts
  packages/client/mutations/UploadOrgImageMutation.ts
  packages/client/mutations/UploadUserImageMutation.ts
  packages/client/mutations/VoteForPokerStoryMutation.ts
  packages/client/mutations/VoteForReflectionGroupMutation.ts
  packages/client/mutations/handlers/handleAuthenticationRedirect.ts
  packages/client/mutations/handlers/handleAzureCreateIssue.ts
  packages/client/mutations/handlers/handleGitHubCreateIssue.ts
  packages/client/mutations/handlers/handleGitLabCreateIssue.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/client/utils/JiraServerClientManager.ts
  packages/client/utils/getSAMLIdP.ts
Labels: size/m

#7911 chore: add libvips to dist
  package.json
  scripts/webpack/prod.servers.config.js
  yarn.lock
Labels: size/s

#7671 feat(team-health): calculate & write sentiment scores for reflections & retro meetings
  packages/server/GoogleLanguageManager.ts
  packages/server/database/types/Meeting.ts
  packages/server/database/types/Reflection.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSentimentScore.ts
  packages/server/graphql/mutations/helpers/getReflectionEntities.ts
  packages/server/graphql/mutations/helpers/getReflectionSentimentScore.ts
  packages/server/graphql/mutations/helpers/manageGoogleNLPErrorResponse.ts
  packages/server/graphql/mutations/updateReflectionContent.ts
  packages/server/graphql/types/NewMeeting.ts
Labels: size/m

#7950 fix: hanging recurrence
  CHANGELOG.md
  lerna.json
  package.json
  packages/gql-executor/package.json
  packages/server/__tests__/processRecurrence.test.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/types/RRule.ts
  packages/server/graphql/public/types/__tests__/RRule.test.ts
  packages/server/package.json
Labels: size/m

#7978 fix: org members panel UI
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Labels: One Review Required, size/s

#7927 feat(rid): Activity categories
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/hooks/useSearchFilter.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/PokerTemplate.ts
  packages/server/graphql/public/types/ReflectTemplate.ts
Labels: One Review Required, size/m
