Repository ParabolInc/parabol, pull requests merged in 2023-10, with the labels that each got.

#8892 feat: added meeting link to a meeting summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Labels: size/s

#8910 fix: standup meeting summary layout
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx
Labels: One Review Required, size/xs

#8837 feat: add support for multi-replica deploys
  .github/workflows/build.yml
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/prod.servers.config.js
Labels: size/s

#8923 fix: fix check-in discussion panel layout
  packages/client/components/DiscussionThreadListEmptyState.tsx
Labels: One Review Required, size/xs

#8927 chore: Log unexpected SAML errors to sentry
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/s

#8918 fix: saml urls
  packages/client/Atmosphere.ts
  packages/client/Root.tsx
  packages/client/hooks/useTooltip.ts
  packages/client/modules/userDashboard/components/OrgAuthentication/CopyServiceProviderURL.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationHeader.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSSOFrame.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSignOnUrl.tsx
  packages/client/package.json
  packages/client/tailwindTheme.ts
  packages/client/ui/Tooltip/Tooltip.tsx
  packages/client/ui/Tooltip/TooltipContent.tsx
  packages/client/ui/Tooltip/TooltipTrigger.tsx
  packages/client/ui/fordwardRadix.tsx
  packages/server/__tests__/loginSAML.test.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/public/typeDefs/SAML.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/SAML.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/queries/SAMLIdP.ts
  packages/server/postgres/migrations/1696275124427_samlMetadataURL.ts
  packages/server/utils/getSSOMetadataFromURL.ts
  yarn.lock
Labels: size/m

#8747 fix: move PRODUCTION bool to build time
  packages/server/PROD.ts
  packages/server/graphql/CompiledQueryCache.ts
  packages/server/graphql/DocumentCache.ts
  packages/server/graphql/executeGraphQL.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
  packages/server/graphql/private/mutations/disconnectSocket.ts
  packages/server/listenHandler.ts
  packages/server/postgres/getPgConfig.ts
  packages/server/postgres/migrations/1692638249976_isOneOnOneTeam.ts
  packages/server/server.ts
  packages/server/utils/analytics/amplitude/AmplitudeAnalytics.ts
  packages/server/utils/segmentIo.ts
  scripts/migrate.js
Labels: size/s

#8846 feat(ad-hoc): Add create team dialog
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/AddTeamDialog.tsx
  packages/client/components/AddTeamDialogRoot.tsx
  packages/client/components/AdhocTeamMultiSelect/AdhocTeamMultiSelect.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/mutations/AddTeamMutation.ts
  packages/client/ui/Input/Input.tsx
  packages/client/ui/Select/SelectTrigger.tsx
  packages/server/graphql/public/types/Organization.ts
Labels: size/m

#8938 fix: CI=true for build action
  .github/workflows/build.yml
Labels: size/xs

#8899 feat(your-work): GitHub repo filter
  packages/client/components/GitHubRepoSearchFilterMenu.tsx
  packages/client/components/GitHubScopingSearchFilterMenu.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResultsRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubRepoFilterBar.tsx
Labels: size/m

#8944 fix: Allow running tests on CI without real Stripe calls
  .github/workflows/build.yml
  packages/server/utils/stripe/StubStripeManager.ts
Labels: size/s

#8926 chore: test sentry and dd uploads
  .github/workflows/build.yml
Labels: size/s

#8931 feat(SAML): Support attributes with namespace
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/s

#8933 chore(SAML): Improved error message when email attribute is missing
  packages/client/components/ErrorAlert/ErrorAlert.tsx
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/s

#8954 chore: log recall error
  packages/server/utils/RecallAIServerManager.ts
Labels: One Review Required, size/s

#8915 feat: handle redirect in email verification
  packages/client/utils/makeAppURL.ts
  packages/server/email/createEmailVerification.ts
  packages/server/email/emailVerificationEmailCreator.tsx
  packages/server/graphql/public/mutations/signUpWithPassword.ts
Labels: One Review Required, size/s

#8928 feat: migration adds customer feedback RID template
  packages/server/postgres/migrations/1696443115482_addCustomerFeedbackTemplate.ts
Labels: One Review Required, size/m

#8946 feat: migration adds 360 review RID templates
  packages/server/postgres/migrations/1696616922662_addPeerReviewTemplates.ts
Labels: enhancement, One Review Required, size/m

#8907 feat(your-work): Jira Integration
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResultsRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraObjectCard.tsx
  packages/client/utils/AtlassianManager.ts
  packages/server/graphql/public/typeDefs/JiraIssue.graphql
  packages/server/graphql/public/types/JiraIssue.ts
Labels: size/m

#8957 feat(your-work): Open your work drawer by default
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/components/TeamPromptMeeting.tsx
Labels: One Review Required, size/s

#8950 fix: Do not serve cached opaque responses if possible
  packages/client/serviceWorker/sw.ts
Labels: size/s

#8916 feat(your-work): Jira Integration pagination
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResults.tsx
  packages/client/utils/AtlassianManager.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/AtlassianIntegration.graphql
  packages/server/graphql/public/typeDefs/JiraIssue.graphql
  packages/server/graphql/public/types/AtlassianIntegration.ts
Labels: size/m

#8878 feat: implement autoJoin mutation
  codegen.json
  packages/client/mutations/UpdateAutoJoinMutation.ts
  packages/server/database/types/Team.ts
  packages/server/graphql/public/mutations/updateAutoJoin.ts
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/updateAutoJoin.graphql
  packages/server/graphql/public/types/UpdateAutoJoinSuccess.ts
  packages/server/postgres/migrations/1695395426183_addAutoJoinToTeam.ts
  packages/server/postgres/queries/src/insertTeamQuery.sql
  packages/server/postgres/queries/src/updateTeamByTeamIdQuery.sql
Labels: size/m

#8905 chore(Snyk): Security upgrade sharp from 0.30.7 to 0.32.6
  packages/server/package.json
  yarn.lock
Labels: size/xs

#8970 feat(redis): upgrade to use Redis 7
  .circleci/config.yml
  .github/workflows/build.yml
  certs/README.md
  docker-compose.yml
  docker/dev.yml
  docker/parabol-ubi/docker-build/README.md
Labels: DX, devops, size/s

#8975 feat(ci): adding release-please action
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: DX, devops, size/s

#8979 fix: SWOT typo
  packages/server/postgres/migrations/1697477646986_swot-typo.ts
Labels: size/s

#8977 fix: dailyPulse handle nulls
  packages/server/graphql/private/queries/dailyPulse.ts
  packages/server/graphql/private/queries/helpers/authCountByDomain.ts
Labels: size/s

#8956 feat(your-work): Product analytics
  packages/client/components/ScopingSearchInput.tsx
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GCalEventCard.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GCalIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubObjectCard.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraObjectCard.tsx
  packages/client/components/TeamPrompt/WorkDrawer/ParabolTasksPanel.tsx
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/types/SegmentEventTrackOptions.ts
  packages/server/graphql/types/ServiceEnum.ts
Labels: One Review Required, size/m

#8986 feat(standups): Response permalink sharing
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/utils/makeAppURL.ts
Labels: One Review Required, size/s

#9001 fix: server health check comment out
  packages/client/Atmosphere.ts
  packages/server/listenHandler.ts
Labels: size/xs

#9023 fix: Upgrade Sentry
  packages/server/graphql/uWSAsyncHandler.ts
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9024 fix: server health checker
  packages/server/listenHandler.ts
Labels: size/xs

#9025 merge release to master
  packages/client/Atmosphere.ts
  release-please-config.json
Labels: size/xs

#8987 feat(your-work): Provide link to integration settings on error + no data
  packages/client/components/TeamPrompt/WorkDrawer/GCalIntegrationResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GCalIntegrationResultsRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResultsRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResultsRoot.tsx
Labels: One Review Required, size/s

#9029 fix: remove docker provenance
  .github/workflows/build.yml
Labels: size/s

#9032 fix: bump versions for dependencies
  release-please-config.json
Labels: size/s

#8965 feat: upgrade PG to v15.4 for local dev
  .circleci/config.yml
  .github/workflows/build.yml
  docker-compose.yml
  docker/parabol-ubi/docker-build/README.md
  docker/parabol-ubi/docker-host-st/docker-compose.yaml
  packages/server/postgres/Dockerfile
Labels: size/s

#9041 chore: add dd-ci to package.json to reduce release time
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: size/xs

#9044 fix: Link to correct CHANGELOG
  packages/client/hooks/useServiceWorkerUpdater.ts
Labels: size/xs

#9051 chore(metrics): Disable server Segment events
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/segment/SegmentAnalytics.ts
Labels: One Review Required, size/s

#9052 feat: enterprise-patch
  .env.example
  packages/server/database/types/Organization.ts
  packages/server/database/types/User.ts
  packages/server/graphql/mutations/helpers/createNewOrg.ts
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/utils/createNewLocalUser.ts
  packages/server/utils/defaultTier.ts
  scripts/toolboxSrc/setIsEnterprise.ts
Labels: size/s

#9049 feat(isEnterprise): set org as enterprise on new user or org
  .env.example
  packages/server/database/types/Organization.ts
  packages/server/database/types/User.ts
  packages/server/graphql/mutations/helpers/createNewOrg.ts
  packages/server/utils/defaultTier.ts
  scripts/toolboxSrc/setIsEnterprise.ts
  scripts/webpack/toolbox.config.js
Labels: size/s

#8983 feat(slack): Send certain notifications via slack DM
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationDiscussionMentioned.ts
  packages/server/database/types/NotificationKickedOut.ts
  packages/server/database/types/NotificationMeetingStageTimeLimitEnd.ts
  packages/server/database/types/NotificationPaymentRejected.ts
  packages/server/database/types/NotificationPromoteToBillingLeader.ts
  packages/server/database/types/NotificationPromptToJoinOrg.ts
  packages/server/database/types/NotificationRequestToJoinOrg.ts
  packages/server/database/types/NotificationResponseMentioned.ts
  packages/server/database/types/NotificationResponseReplied.ts
  packages/server/database/types/NotificationTaskInvolves.ts
  packages/server/database/types/NotificationTeamArchived.ts
  packages/server/database/types/NotificationTeamInvitation.ts
  packages/server/database/types/NotificationTeamsLimitExceeded.ts
  packages/server/database/types/NotificationTeamsLimitReminder.ts
  packages/server/graphql/mutations/addComment.ts
  packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
Labels: size/m

#9050 chore: build bumps version in gitlab
  .github/workflows/build.yml
Labels: size/s

#8912 feat(meeting-inception): implement add an activity button
  packages/client/components/AddActivityButton.tsx
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/modules/demo/initDB.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/types/Discussion.ts
Labels: size/s

#9056 fix: use SendClientSideEvent for add activity button
  packages/client/components/DiscussionThreadInput.tsx
Labels: size/xs

#8966 chore(Snyk): Security upgrade node from 18.17.0 to 18.18.2
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
Labels: size/xs

#8982 chore(Team Insights): Limit most used retro templates
  packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
Labels: size/s

#9064 chore: remove release branch
  .github/workflows/build.yml
  .github/workflows/release-please.yml
  packages/client/hooks/useServiceWorkerUpdater.ts
Labels: size/s

#9053 chore(metrics): rename column `segmentId` to `pseudoId`
  packages/client/components/EmailPasswordAuthForm.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/client/utils/GoogleClientManager.ts
  packages/server/__tests__/common.ts
  packages/server/database/types/EmailVerification.ts
  packages/server/database/types/User.ts
  packages/server/email/createEmailVerficationForExistingUser.ts
  packages/server/email/createEmailVerification.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/graphql/public/mutations/signUpWithPassword.ts
  packages/server/graphql/public/mutations/verifyEmail.ts
  packages/server/graphql/public/typeDefs/loginWithGoogle.graphql
  packages/server/graphql/public/typeDefs/signUpWithPassword.graphql
  packages/server/graphql/types/User.ts
  packages/server/postgres/migrations/1698264242460_renameUserSegmentIdToPseudoId.ts
  packages/server/postgres/migrations/1698265572466_renameEmailVerificationSegmentIdToPseudoId.ts
  packages/server/postgres/queries/insertUser.ts
  packages/server/postgres/queries/src/backfillSegmentIdQuery.sql
  packages/server/postgres/queries/src/backupUserQuery.sql
  packages/server/postgres/queries/src/insertUserQuery.sql
  packages/server/postgres/queries/src/updateUserQuery.sql
  packages/server/utils/createNewLocalUser.ts
  packages/server/utils/segmentIo.ts
Labels: One Review Required, size/m

#9058 fix: Fix service worker static cache base url
  scripts/webpack/prod.client.config.js
Labels: size/xs

#9000 chore: remove unused filesToCache logic
  packages/server/utils/StaticServer.ts
  packages/server/utils/serveStatic.ts
Labels: size/xs

#8999 chore: Delete unused GitHub webhook code
  packages/server/integrations/githubWebhookHandler.ts
  packages/server/server.ts
  packages/server/utils/makeGitHubWebhookParams.js
Labels: size/m

#9054 chore(Snyk): Security upgrade redhat/ubi8 from 8.6 to 9.2
  docker/parabol-ubi/docker-build/dockerfiles/parabol.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/security-test.dockerfile
Labels: size/xs

#8993 feat(zoom-transcription): UI improvements
  packages/client/components/DiscussionThreadListEmptyState.tsx
  packages/client/components/DiscussionThreadListEmptyTranscriptState.tsx
  packages/client/components/RetroDiscussPhase.tsx
  packages/client/components/RetroDiscussionThreadHeader.tsx
  packages/client/components/ZoomProviderLogo.tsx
  packages/client/components/ZoomSVG.tsx
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/public/mutations/addTranscriptionBot.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
Labels: size/m

#8883 feat: autoJoin verified users to team
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/s

#8995 feat(zoom-transcription): split transcript into speaker & words
  packages/client/components/DiscussionThread.tsx
  packages/client/components/DiscussionThreadList.tsx
  packages/client/components/DiscussionThreadListEmptyTranscriptState.tsx
  packages/client/components/DiscussionThreadRoot.tsx
  packages/client/components/RetroDiscussPhase.tsx
  packages/client/components/Transcription.tsx
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/graphql/types/NewMeeting.ts
  packages/server/graphql/types/RetrospectiveMeeting.ts
  packages/server/graphql/types/TranscriptBlock.ts
  packages/server/utils/RecallAIServerManager.ts
Labels: size/m

#8989 chore(auto-join): verify org founder or billing leads
  packages/server/dataloader/customLoaderMakers.ts
Labels: size/s

#9070 chore(clean-up): Cleans up all the files used for the old infrastructure and pipelines
  .circleci/config.yml
Labels: size/m

#9082 fix: do not fail installing service worker on fetch fail
  packages/client/serviceWorker/sw.ts
Labels: size/xs

#9084 fix: e-mail love@parabol.com replaced by love@parabol.co
  LICENSE
  packages/client/package.json
  packages/integration-tests/package.json
  packages/server/package.json
Labels: size/xs
