Repository ParabolInc/parabol, pull requests merged in 2023-12, with the labels that each got.

#9168 feat: update activity library card UI
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  static/images/illustrations/estimation-background.png
  static/images/illustrations/feedback-background.png
  static/images/illustrations/postmortem-background.png
  static/images/illustrations/premortem-background.png
  static/images/illustrations/retro-background.png
  static/images/illustrations/standup-background.png
  static/images/illustrations/strategy-background.png
Labels: size/m

#9240 chore: Cleanup Slack/Mattermost/MSTeams notifiers
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Labels: size/m

#9260 feat: gcal invite all by default
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
Labels: One Review Required, size/s

#9263 chore(dx): allow any branch with hotfix prefix to build
  .github/workflows/release-please.yml
  .github/workflows/release.yml
Labels: size/xs

#9261 fix: cork all http write methods
  .github/workflows/release-please.yml
  .github/workflows/release.yml
  packages/server/graphql/httpGraphQLHandler.ts
  packages/server/graphql/intranetGraphQLHandler.ts
  packages/server/jiraImagesHandler.ts
  packages/server/pipeStreamOverResponse.ts
  packages/server/safetyPatchRes.ts
  packages/server/socketHandlers/handleUpgrade.ts
  packages/server/sse/whm.js
  packages/server/utils/SAMLHandler.ts
  packages/server/utils/serveStatic.ts
Labels: size/m

#9245 feat: release checkout flow
  .github/ISSUE_TEMPLATE/release_test.md
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
  packages/client/modules/userDashboard/components/OrgBilling/Organization.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/Organization/Organization.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationPage.tsx
  packages/client/modules/userDashboard/containers/Organization/OrganizationRoot.tsx
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/m

#9195 feat(admin): Org Admin permissions - billing leader and team lead permissions
  packages/client/components/DashboardAvatars/TeamMemberAvatarMenu.tsx
  packages/client/modules/teamDashboard/components/ManageTeam/ManageTeamList.tsx
  packages/client/modules/teamDashboard/components/ManageTeam/ManageTeamMember.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
  packages/client/modules/teamDashboard/components/UnpaidTeamModal/UnpaidTeamModal.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeaders.tsx
  packages/client/modules/userDashboard/components/OrgBilling/NewBillingLeaderMenu.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/mutations/fragments/CompleteOrganizationFrag.ts
  packages/server/billing/helpers/generateInvoice.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/database/types/processTeamsLimitsJob.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/removeTeamMember.ts
  packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
  packages/server/graphql/private/mutations/sendUpcomingInvoiceEmails.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
  packages/server/graphql/public/mutations/setOrgUserRole.ts
  packages/server/graphql/public/rules/isViewerBillingLeader.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/public/types/TeamMember.ts
  packages/server/graphql/types/Organization.ts
  packages/server/graphql/types/User.ts
  packages/server/utils/authorization.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: One Review Required, size/m

#9267 fix: shake some images from server bundle
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/components/ActivityLibrary/backgroundImgMap.ts
Labels: size/s

#9275 fix: activity library settings mobile
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
Labels: One Review Required, size/m

#9277 fix: activity library colour imports
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
Labels: One Review Required, size/s

#9252 fix: gracefully remove consumer from redis on sigterm
  packages/gql-executor/gqlExecutor.ts
Labels: size/s

#9279 chore: webpack client and server in parallel
  scripts/prod.js
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
Labels: size/l

#9265 chore: Restrict prompt to join org to a smaller set of orgs
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: size/m

#9268 feat: added option to modify icebreakers with ai
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/client/mutations/UpdateNewCheckInQuestionMutation.ts
  packages/client/mutations/useModifyCheckInQuestionMutation.ts
  packages/client/package.json
  packages/client/ui/Button/Button.tsx
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/modifyCheckInQuestion.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/modifyCheckInQuestion.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/analytics/analytics.ts
  yarn.lock
Labels: size/l

#9256 chore: efficient webpack bundles
  package.json
  packages/client/polyfills.ts
  packages/client/serviceWorker/sw.ts
  scripts/prod.js
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
  yarn.lock
Labels: size/s

#9280 fix: Prompt to join org without organization feature flags
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: size/xs

#9281 fix: Update organization on accept invite
  packages/client/mutations/AcceptTeamInvitationMutation.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
Labels: size/s

#9292 fix: grab auth token before await
  packages/server/graphql/uWSAsyncHandler.ts
Labels: size/xs

#9165 chore: keep release process in GitHub
  .github/workflows/release-to-prod.yml
  .github/workflows/release-to-staging.yml
  .github/workflows/release.yml
Labels: DX, devops, size/m

#9290 fix: Fix duplicate organizations for teams with auto join
  packages/server/__tests__/autoJoin.test.ts
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/dataloader/customLoaderMakers.ts
Labels: size/m

#9294 fix: release-to-staging debug
  .github/workflows/release-to-staging.yml
  .vscode/settings.json
Labels: size/xs

#9295 fix: release-to-staging debugging 2
  .github/workflows/release-to-staging.yml
Labels: size/xs
