Repository ParabolInc/parabol, pull requests merged in 2023-06, with the labels that each got.

#8302 fix(prompt-to-join): fix add teammate routing when opened on a new tab
  packages/client/components/PrivateRoutes.tsx
Labels: One Review Required, size/xs

#8301 fix(rid): Correct styles for non-owner readonly scales
  packages/client/modules/meeting/components/PokerTemplateScalePicker.tsx
Labels: One Review Required, size/xs

#8297 chore(prompt-to-join): disable buttons when running accept request mutation
  packages/client/components/ReviewRequestToJoinOrgModal.tsx
  packages/client/mutations/AcceptRequestToJoinDomainMutation.ts
  packages/client/mutations/useAcceptRequestToJoinDomainMutation.ts
Labels: size/m

#8307 chore: remove slackin broken link from readme
  README.md
Labels: size/xs

#8300 fix: fix loader.load with undefined in accept team invitation
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
Labels: One Review Required, size/xs

#7949 feat: add zoom transcription
  packages/client/components/DiscussionThread.tsx
  packages/client/components/DiscussionThreadList.tsx
  packages/client/components/DiscussionThreadListEmptyState.tsx
  packages/client/components/DiscussionThreadRoot.tsx
  packages/client/components/NewMeetingSettingsRetrospective.tsx
  packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
  packages/client/components/NewMeetingSettingsToggleTranscription.tsx
  packages/client/components/RetroDiscussPhase.tsx
  packages/client/components/RetroDiscussionThreadHeader.tsx
  packages/client/components/Transcription.tsx
  packages/client/modules/demo/initDB.ts
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/mutations/SetMeetingSettingsMutation.ts
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/types/constEnums.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/database/types/MeetingSettingsRetrospective.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/setMeetingSettings.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/setMeetingSettings.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/types/NewMeeting.ts
  packages/server/graphql/types/RetrospectiveMeeting.ts
  packages/server/graphql/types/RetrospectiveMeetingSettings.ts
  packages/server/package.json
  packages/server/types/modules.d.ts
  packages/server/utils/RecallAIServerManager.ts
  packages/server/utils/analytics/analytics.ts
  yarn.lock
Labels: size/l

#8217 chore: remove rethink templates
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/postgres/queries/getMeetingTemplatesByIds.ts
  packages/server/postgres/queries/insertMeetingTemplate.ts
  packages/server/postgres/queries/removeMeetingTemplate.ts
  packages/server/postgres/queries/removeMeetingTemplatesForTeam.ts
  packages/server/postgres/queries/src/getMeetingTemplatesByIdsQuery.sql
  packages/server/postgres/queries/updateMeetingTemplateFreeStatusById.ts
  packages/server/postgres/queries/updateMeetingTemplateFreeStatusByName.ts
  packages/server/postgres/queries/updateMeetingTemplateLastUsedAt.ts
  packages/server/postgres/queries/updateMeetingTemplateName.ts
  packages/server/postgres/queries/updateMeetingTemplateOrgId.ts
  packages/server/postgres/queries/updateMeetingTemplateScope.ts
Labels: size/m

#8295 chore: refactor updateUserProfile
  codegen.json
  packages/client/mutations/UpdateOrgMutation.ts
  packages/client/mutations/UpdateUserProfileMutation.ts
  packages/client/mutations/UploadOrgImageMutation.ts
  packages/client/mutations/UploadUserImageMutation.ts
  packages/client/validation/makeUserServerSchema.ts
  packages/server/graphql/mutations/helpers/updateOrgValidation.ts
  packages/server/graphql/mutations/helpers/updateUserProfile.ts
  packages/server/graphql/mutations/updateOrg.ts
  packages/server/graphql/mutations/updateUserProfile.ts
  packages/server/graphql/mutations/uploadOrgImage.ts
  packages/server/graphql/mutations/uploadUserImage.ts
  packages/server/graphql/public/mutations/updateOrg.ts
  packages/server/graphql/public/mutations/updateUserProfile.ts
  packages/server/graphql/public/mutations/uploadOrgImage.ts
  packages/server/graphql/public/mutations/uploadUserImage.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/updateOrg.graphql
  packages/server/graphql/public/typeDefs/updateUserProfile.graphql
  packages/server/graphql/public/typeDefs/uploadOrgImage.graphql
  packages/server/graphql/public/typeDefs/uploadUserImage.graphql
  packages/server/graphql/public/types/File.ts
  packages/server/graphql/public/types/UpdateOrgPayload.ts
  packages/server/graphql/public/types/UpdateUserProfilePayload.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/GraphQLFileType.ts
  packages/server/graphql/types/UpdateOrgInput.ts
  packages/server/graphql/types/UpdateOrgPayload.ts
  packages/server/graphql/types/UpdateUserProfileInput.ts
  packages/server/graphql/types/UpdateUserProfilePayload.ts
Labels: size/l

#8280 feat(checkout-flow): add org details
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingDangerZone.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgDetails.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
  packages/client/utils/constants.ts
Labels: size/m

#8315 fix: Drain rethinkdb pool after running all migrations
  scripts/toolboxSrc/standaloneMigrations.ts
Labels: size/xs

#8311 fix(rid): Long team names truncate instead of wrapping
  packages/client/components/DropdownToggleInner.tsx
  packages/client/components/NewMeeting.tsx
Labels: One Review Required, size/xs

#8286 feat(team health): voting and reveal
  codegen.json
  packages/client/components/TeamHealth.tsx
  packages/client/components/TeamHealthVotingRow.tsx
  packages/client/mutations/RevealTeamHealthVotesMutation.ts
  packages/client/mutations/SetTeamHealthVoteMutation.ts
  packages/client/shared/gqlIds/TeamHealthUserScoreId.ts
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/database/types/TeamHealthPhase.ts
  packages/server/database/types/TeamHealthStage.ts
  packages/server/database/types/TeamHealthVote.ts
  packages/server/database/updateStage.ts
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/public/mutations/revealTeamHealthVotes.ts
  packages/server/graphql/public/mutations/setTeamHealthVote.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/TeamHealthStage.graphql
  packages/server/graphql/public/typeDefs/TeamHealthUserScore.graphql
  packages/server/graphql/public/typeDefs/revealTeamHealthVotes.graphql
  packages/server/graphql/public/typeDefs/setTeamHealthVote.graphql
  packages/server/graphql/public/types/TeamHealthPhase.ts
  packages/server/graphql/public/types/TeamHealthStage.ts
  packages/server/graphql/public/types/TeamHealthUserScore.ts
Labels: size/l

#8313 chore(prompt-to-join): allow non-verified emails
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: One Review Required, size/xs

#8320 fix: update the default enterprise plan ID
  packages/server/utils/stripe/StripeManager.ts
Labels: size/xs

#8298 feat(Team Health): Add summary
  packages/client/components/TeamHealth.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamHealthSummary.tsx
  packages/client/styles/theme/global.css
  packages/client/utils/blendColors.ts
  packages/client/utils/getTeamHealthVoteColor.ts
  packages/server/email/MailManagerDebug.ts
Labels: One Review Required, size/m

#8310 feat(DX): Infer parent portal IDs through React context
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/GitHubFieldMenu.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/NewMeetingRecurrenceSettings.tsx
  packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/components/ReflectionGroup/ReflectionGroup.tsx
  packages/client/components/SpotlightResults.tsx
  packages/client/components/StageTimerModalEndTimeDate.tsx
  packages/client/components/StageTimerModalEndTimeHour.tsx
  packages/client/components/StageTimerModalTimeLimit.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/hooks/useExpandedReflections.ts
  packages/client/hooks/usePortal.tsx
  packages/client/modules/meeting/components/EditableTemplatePromptColor.tsx
  packages/client/modules/meeting/components/EditableTemplateScaleValueColor.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/PokerTemplatePicker.tsx
  packages/client/modules/meeting/components/PokerTemplateScalePicker.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/RetroTemplatePicker.tsx
  packages/client/modules/meeting/components/TemplateDimensionItem.tsx
  packages/client/modules/meeting/components/TemplateDimensionList.tsx
  packages/client/modules/meeting/components/TemplatePromptItem.tsx
  packages/client/modules/meeting/components/TemplatePromptList.tsx
  packages/client/modules/meeting/components/TemplateSharing.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterTeamAssigneeMenu.tsx
Labels: size/m

#8325 fix: dumpHeap to /tmp directory
  packages/server/graphql/private/mutations/dumpHeap.ts
Labels: size/s

#8318 feat(checkout-flow): credit card UI
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
  packages/client/mutations/CreateSetupIntentMutation.ts
  packages/server/graphql/public/mutations/createSetupIntent.ts
  packages/server/graphql/public/typeDefs/createSetupIntent.graphql
  packages/server/graphql/public/types/CreateSetupIntentSuccess.ts
Labels: One Review Required, size/m

#8336 feat(analytics): Track meeting category on meeting start
  packages/server/utils/analytics/helpers.ts
Labels: One Review Required, size/xs

#8337 feat(rid): Add new users to feature flag
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: One Review Required, size/xs

#8329 fix: show all slack channels in dropdown
  packages/client/utils/SlackManager.ts
Labels: One Review Required, size/xs

#8075 style: updating plans UI for mobile screens
  packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBillingHeading.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgStats.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
Labels: size/m

#8333 fix: better description for failed to execute removeChild on Node error
  packages/client/components/ErrorComponent/ErrorComponent.tsx
Labels: size/s

#8342 chore: improve yarn clean script
  package.json
Labels: size/xs

#8261 docs: Adds new template for design issues
  .github/ISSUE_TEMPLATE/design_issue.md
Labels: design, chore, One Review Required, size/s

#8351 fix(templates): Many public templates not displayed
  CHANGELOG.md
  packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
Labels: size/xs

#8355 chore: mem restart limit
  CHANGELOG.md
  lerna.json
  package.json
  packages/client/package.json
  packages/gql-executor/package.json
  packages/integration-tests/package.json
  packages/server/package.json
  pm2.config.js
Labels: size/s

#8306 feat: text align center for icebreakers
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
Labels: One Review Required, size/s

#8361 chore(docker-image): self-hosted folder added in HOME directory
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
Labels: devops, size/xs

#8362 fix: Bump undici to latest
  CHANGELOG.md
  lerna.json
  package.json
  packages/client/package.json
  packages/gql-executor/gqlExecutor.ts
  packages/gql-executor/package.json
  packages/integration-tests/package.json
  packages/server/monkeyPatchFetch.ts
  packages/server/package.json
  packages/server/server.ts
  yarn.lock
Labels: size/s

#8339 fix(standups): allow selecting text within the standup response drawer
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
Labels: size/xs

#8367 fix(teams-limit): remove teams limit when upgrading to enterprise
  packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
Labels: One Review Required, size/xs

#8348 feat(Team Health): enable team health by default for paid tiers
  packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
  packages/client/components/NewMeetingSettingsToggleTeamHealth.tsx
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/utils/features/isTeamHealthAvailable.ts
  packages/client/utils/meetings/lookups.ts
  packages/server/database/types/MeetingSettingsRetrospective.ts
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/setMeetingSettings.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/types/TeamMeetingSettings.ts
  packages/server/postgres/migrations/1686226640890_addTeamHealthToAllMeetingSettingsRetrospective.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/isPhaseAvailable.ts
Labels: size/m

#8375 feat(Team Health): Add setting to new activity library
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
Labels: size/xs

#8377 fix(templates): Public templates missing in new environments
  packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
Labels: One Review Required, size/xs

#8382 chore: cleanup connect rethink db in migrations
  packages/server/postgres/getPgp.ts
  packages/server/postgres/migrations/1625576993065_addAtlassianAuthTable.ts
  packages/server/postgres/migrations/1631553388387_add-template-teams-users.ts
  packages/server/postgres/migrations/1640229261909_mattermostToIntegrationsTables.ts
  packages/server/postgres/migrations/1654861495450_migrateSecureDomain.ts
  packages/server/postgres/migrations/1674074684762_deleteEmptyGroups.ts
  packages/server/postgres/migrations/1676299334703_addSeasonalTemplates.ts
  packages/server/postgres/migrations/1677272969994_meetingTemplatesMove.ts
  packages/server/postgres/migrations/1682541572157_deleteUserRethink.ts
  packages/server/postgres/migrations/1684250022646_teamHealthPhase.ts
  packages/server/postgres/migrations/1685721573097_addPrePostMortemTemplates.ts
  packages/server/postgres/migrations/1686226640890_addTeamHealthToAllMeetingSettingsRetrospective.ts
Labels: size/m

#8373 feat(rid): Enhance search
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/hooks/useSearchFilter.ts
Labels: size/s

#8376 feat(rid): After navigating to or selecting a team, use that team by default
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/modules/teamDashboard/components/TeamDashMainRoot.tsx
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/utils/relay/setPreferredTeamId.ts
Labels: size/s

#8285 fix: do not cancel stripe subscription in case of failed payment
  packages/server/graphql/mutations/helpers/upgradeToTeamTierOld.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/s

#8393 fix(prompt-to-join): add scroll-y to add teammate dialog
  packages/client/components/ReviewRequestToJoinOrgModal.tsx
Labels: One Review Required, size/m

#8392 fix: reset retro groups with team health
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
Labels: size/xs

#8289 chore(checkout-flow): handle failing 3D Secure card auth
  codegen.json
  packages/client/modules/userDashboard/components/CreditCardModal/CreditCardForm.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
  packages/client/mutations/CreateSetupIntentMutation.ts
  packages/client/mutations/CreateStripeSubscriptionMutation.ts
  packages/client/mutations/OldUpgradeToTeamTierMutation.ts
  packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/billing/stripeWebhookHandler.ts
  packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
  packages/server/graphql/mutations/helpers/upgradeToTeamTier.ts
  packages/server/graphql/mutations/oldUpgradeToTeamTier.ts
  packages/server/graphql/mutations/updateCreditCard.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
  packages/server/graphql/private/mutations/upgradeToTeamTier.ts
  packages/server/graphql/public/mutations/createSetupIntent.ts
  packages/server/graphql/public/mutations/createStripeSubscription.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/createSetupIntent.graphql
  packages/server/graphql/public/typeDefs/createStripeSubscription.graphql
  packages/server/graphql/public/typeDefs/upgradeToTeamTier.graphql
  packages/server/graphql/public/types/CreateSetupIntentSuccess.ts
  packages/server/graphql/public/types/UpgradeToTeamTierSuccess.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/OldUpgradeToTeamTierPayload.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/l

#8396 chore(metrics): Add hasTeamHealth to meeting properties for meeting related events
  packages/server/utils/analytics/helpers.ts
Labels: One Review Required, size/xs

#8401 fix: del instead of hdel
  packages/server/utils/atlassian/jiraImages.ts
Labels: size/xs

#8379 chore: cleanup changelog
  CHANGELOG.md
  scripts/cleanup-changelog.sh
Labels: size/l

#8374 fix(retros): When skipping phases, mark interim stages as complete
  packages/client/hooks/useGotoStageId.ts
Labels: One Review Required, size/s

#8388 feat(al): New header
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryHeader.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/components/ActivityLibrary/SearchBar.tsx
Labels: One Review Required, size/m

#8358 feat(templateLimits): Show upgrade prompts in Activity Library
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/server/graphql/types/UpgradeCTALocationEnum.ts
Labels: One Review Required, size/m

#8403 chore: add comments for supporting multi-platform builds
  .github/workflows/build.yml
Labels: size/xs

#8399 chore: removed old apollo gql extension config
  apollo.config.js
Labels: One Review Required, size/xs

#8408 feat: FixedActivity in GQL (Part 4 of 4)
  codegen.json
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/server/database/types/MeetingTemplate.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/public/rootSchema.ts
  packages/server/graphql/public/typeDefs/MeetingTemplate.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/FixedActivity.ts
  packages/server/graphql/public/types/MeetingTemplate.ts
  packages/server/graphql/public/types/PokerTemplate.ts
  packages/server/graphql/public/types/ReflectTemplate.ts
  packages/server/graphql/public/types/User.ts
  packages/server/postgres/migrations/1685721573097_addPrePostMortemTemplates.ts
  packages/server/postgres/migrations/1685721574097_fixed-activities.ts
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.servers.config.js
Labels: size/m

#8394 feat(activity-library): Show activity description when hovering over activity card
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCardDescription.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
Labels: One Review Required, size/m

#8427 chore: add sql to kill all pg connections
  packages/server/postgres/README.md
Labels: size/s

#8428 chore: Add assignSURole script
  package.json
  scripts/toolboxSrc/assignSURole.ts
  scripts/webpack/toolbox.config.js
  yarn.lock
Labels: size/s

#8431 fix: do not show upgrade prompt for standups and checkins
  CHANGELOG.md
  lerna.json
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/package.json
  packages/gql-executor/package.json
  packages/server/package.json
Labels: size/s

#8417 chore: revert add temporary story points update result logging
  packages/client/utils/AtlassianManager.ts
Labels: One Review Required, size/s

#8331 feat(share-summary): Add share topic button to meeting summary
  packages/client/components/PrivateRoutes.tsx
  packages/client/components/ShareTopicModal.tsx
  packages/client/components/ShareTopicRoot.tsx
  packages/client/hooks/useModal.ts
  packages/client/hooks/useModalPortal.tsx
  packages/client/hooks/usePortal.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
Labels: size/m

#8293 chore: remove useActivityDetails
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsRoute.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/MeetingDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/hooks/useActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ActivityIllustrations.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/modules/meeting/components/EditableTemplateName.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/graphql/mutations/helpers/getTemplateIllustrationUrl.ts
  packages/server/postgres/migrations/1687822236394_activity-illustrations.ts
  scripts/toolboxSrc/pushToCDN.ts
Labels: size/l

#8443 fix: types in meeting tips; prevent rendering undefined
  packages/client/components/BottomControlBarTips.tsx
Labels: One Review Required, size/s

#8389 chore: fix dd-trace and relay mem leaks
  packages/client/modules/email/components/MeetingSummaryEmailRootSSR.tsx
  packages/client/modules/email/components/NotificationSummaryEmailRoot.tsx
  packages/gql-executor/gqlExecutor.ts
  packages/gql-executor/package.json
  packages/server/email/ServerEnvironment.ts
  packages/server/email/newMeetingSummaryEmailCreator.tsx
  packages/server/email/renderSSRElement.ts
  packages/server/email/renderSSRElement.tsx
  packages/server/package.json
  packages/server/server.ts
  yarn.lock
Labels: size/m

#8413 feat(AL): Activity subsections for retros
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/server/graphql/public/typeDefs/MeetingTemplate.graphql
  packages/server/graphql/public/types/ReflectTemplate.ts
Labels: One Review Required, size/m

#8455 fix: improve error message when a user cannot join an org
  packages/server/graphql/public/mutations/helpers/getIsUserIdApprovedByOrg.ts
Labels: size/xs

#8321 chore: added Tailwind CSS migration readme
  README.md
  packages/client/README.md
Labels: size/m

#8451 fix: Fix optimistic update for create task in Sprint Poker
  packages/client/mutations/CreateTaskMutation.ts
Labels: size/xs

#8423 feat(checkout-flow): update credit card functionality
  codegen.json
  packages/client/modules/userDashboard/components/CreditCardModal/CreditCardForm.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingCreditCardInfo.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/UpdatePayment.tsx
  packages/client/mutations/OldUpdateCreditCardMutation.ts
  packages/client/mutations/OldUpgradeToTeamTierMutation.ts
  packages/client/mutations/UpdateCreditCardMutation.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/client/utils/StripeClientManager.ts
  packages/server/graphql/CompiledQueryCache.ts
  packages/server/graphql/mutations/helpers/getCCFromCustomer.ts
  packages/server/graphql/mutations/helpers/stripeCardToDBCard.ts
  packages/server/graphql/mutations/oldUpdateCreditCard.ts
  packages/server/graphql/public/mutations/updateCreditCard.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/updateCreditCard.graphql
  packages/server/graphql/public/types/UpdateCreditCardSuccess.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/OldUpdateCreditCardPayload.ts
  packages/server/graphql/types/OldUpgradeToTeamTierPayload.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/l

#8436 feat(suggest-groups): improve suggest groups prompt
  packages/client/utils/constants.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/package.json
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/estimateTokens.ts
  yarn.lock
Labels: size/m

#8438 fix: Show error message when creating Jira task fails
  packages/client/components/NewAzureIssueInput.tsx
  packages/client/components/NewGitHubIssueInput.tsx
  packages/client/components/NewGitLabIssueInput.tsx
  packages/client/components/NewJiraIssueInput.tsx
  packages/client/hooks/useTimedState.ts
  packages/server/graphql/public/types/CreateTaskPayload.ts
Labels: size/m

#8437 feat(suggest-groups): update groups for subscribers
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/public/mutations/autogroup.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
Labels: size/s

#8439 feat(suggest-groups): add suggest groups tooltip
  packages/client/components/RetroGroupPhase.tsx
  packages/server/graphql/mutations/helpers/generateGroups.ts
Labels: size/s
