Repository ParabolInc/parabol, pull requests merged in 2023-09, with the labels that each got.

#8735 fix: Check if team member status on accepting an invite twice
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
Labels: size/s

#8488 chore: support SSL for redis
  .env.example
  certs/README.md
  certs/gen-redis-certs.sh
  certs/redis.crt
  certs/redis.key
  certs/redisCA.crt
  docker/dev.yml
  packages/gql-executor/RedisStream.ts
  packages/gql-executor/gqlExecutor.ts
  packages/server/dataloader/RedisCache.ts
  packages/server/utils/PubSubPromise.ts
  packages/server/utils/RedisInstance.ts
  packages/server/utils/getPubSub.ts
  packages/server/utils/getRedis.ts
  packages/server/utils/getRedisOptions.ts
  packages/server/utils/serverHealthChecker.ts
  scripts/runMigrations.js
Labels: size/m

#8768 feat: Update Slack message on meeting rename
  packages/client/utils/SlackManager.ts
  packages/server/database/types/Meeting.ts
  packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/renameMeeting.ts
  packages/server/utils/sendToSentry.ts
Labels: size/s

#8715 feat(standups): rich text in slack notifications
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/makeSlackBlocks.ts
  packages/server/utils/tiptap/convertToMarkdown.tsx
  yarn.lock
Labels: size/m

#8790 chore: Delete unused file
  packages/server/utils/getVerifiedUserDomain.ts
Labels: size/s

#8783 chore: update instances of GitLab logo SVG
  packages/client/components/GitLabSVG.tsx
  packages/client/styles/theme/images/graphics/gitlab-icon-rgb.svg
Labels: One Review Required, size/s, UI refinement, UX backlog

#8712 chore(one-on-one): show organiation picker if can't determine org automatically
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/maybeCreateOneOnOneTeam.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/helpers.ts
Labels: size/m

#8776 fix(gcal): handle Zoom add-on conflict
  packages/client/modules/userDashboard/components/GcalModal/DateTimePickers.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/types/CreateGcalEventInput.ts
Labels: size/s

#8774 feat: scroll to card section
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
Labels: size/s

#8799 fix(checkin): prevent newly added agenda item to be accessible when `agendaitems` phase has not been started yet
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
Labels: size/xs

#8805 fix: removed default button background from your tasks button
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Labels: One Review Required, size/xs

#8811 chore: Allow google to index /create-account
  nginx.conf.sigil
Labels: One Review Required, size/xs

#8815 chore: Update dev readme with assign SU script
  packages/server/graphql/private/README.md
Labels: size/xs

#8806 feat: invite link in right drawer
  packages/client/components/AddTeamMemberModal.tsx
  packages/client/components/MassInvitationTokenLink.tsx
  packages/client/modules/teamDashboard/components/TeamDashMain/TeamDrawer.tsx
  packages/server/safeMutations/insertNewTeamMember.ts
Labels: size/s

#8819 fix: allow to set task max-width
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/ThreadedTaskBase.tsx
  packages/client/containers/TaskCard/DraggableTask.tsx
  packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx
  packages/client/styles/helpers/cardRootStyles.ts
Labels: size/s

#8829 fix: filter tasks that are being created by different users in your work drawer
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
Labels: size/xs

#8835 fix: make new agenda items accessible from first call phase
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
Labels: size/xs

#8839 fix: remove memory leak from analytics
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/segmentIo.ts
Labels: size/s

#8802 feat: SAML self-serve
  codegen.json
  package.json
  packages/client/components/InputField/BasicInput.tsx
  packages/client/components/InputField/BasicTextArea.tsx
  packages/client/modules/demo/initDB.ts
  packages/client/modules/userDashboard/components/BillingMembersToggle/BillingMembersToggle.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationHeader.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSSOFrame.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSignOnUrl.tsx
  packages/client/modules/userDashboard/components/Organization/Organization.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationPage.tsx
  packages/client/modules/userDashboard/containers/OrgAuthentication/OrgAuthenticationRoot.tsx
  packages/client/mutations/UpdateSAMLMutation.ts
  packages/client/utils/getTokenFromSSO.ts
  packages/server/__tests__/globalSetup.ts
  packages/server/__tests__/loginSAML.test.ts
  packages/server/database/types/ServerAuthToken.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/emailPasswordReset.ts
  packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/private/mutations/enableSAMLForDomain.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/private/mutations/verifyDomain.ts
  packages/server/graphql/private/typeDefs/enableSAMLForDomain.graphql
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/private/typeDefs/verifyDomain.graphql
  packages/server/graphql/private/types/VerifyDomainSuccess.ts
  packages/server/graphql/public/mutations/helpers/SAMLHelpers/getSignOnURL.ts
  packages/server/graphql/public/mutations/updateSAML.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/rules/isOrgTier.ts
  packages/server/graphql/public/rules/isViewerBillingLeader.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/SAML.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/typeDefs/updateSAML.graphql
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/public/types/SAML.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/queries/SAMLIdP.ts
  packages/server/postgres/migrations/1694191002164_migrateSAML.ts
  yarn.lock
Labels: size/xl

#8845 feat: download summary as pdf
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheetCTA.tsx
Labels: size/s

#8724 feat(standups): 'Your work' GitHub integration
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawerRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResultsRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/GitHubObjectCard.tsx
  packages/client/components/TeamPrompt/WorkDrawer/ParabolTasksPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/ParabolTasksResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/ParabolTasksResultsRoot.tsx
  packages/client/styles/theme/images/graphics/github-issue-closed.svg
  packages/client/styles/theme/images/graphics/github-issue-open.svg
  packages/client/styles/theme/images/graphics/github-merged.svg
  packages/client/styles/theme/images/graphics/github-pr-closed.svg
  packages/client/styles/theme/images/graphics/github-pr-draft.svg
  packages/client/styles/theme/images/graphics/github-pr-open.svg
  packages/server/graphql/public/types/_xGitHubPullRequest.ts
Labels: size/l

#8833 fix(check-in): fix navigating from first call to a new agenda item
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
Labels: size/xs

#8854 chore: track download to pdf
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/server/utils/analytics/analytics.ts
Labels: One Review Required, size/xs

#8797 chore(metrics): Add Amplitude client-side page view tracking
  packages/client/components/AnalyticsPage.tsx
  packages/client/package.json
  packages/client/types/modules.d.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
  yarn.lock
Labels: size/s

#8852 chore: Add warning to getDataLoader
  packages/server/graphql/getDataLoader.ts
Labels: size/xs

#8864 feat(al): Show standup meeting type first in all views
  packages/server/graphql/public/types/User.ts
Labels: One Review Required, size/xs

#8862 feat: Add standup demo video to empty meeting view
  packages/client/components/MeetingsDash.tsx
  packages/client/components/MeetingsDashTutorialModal.tsx
  packages/client/components/TutorialMeetingCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  static/images/illustrations/pokerTutorialThumb.jpg
  static/images/illustrations/standupTutorialThumb.jpg
Labels: One Review Required, size/s

#8718 chore(one-on-one): Add team exists warning
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/OneOnOneTeamStatus.tsx
  packages/client/components/ActivityLibrary/OneOnOneTeamStatusComponent.tsx
  packages/client/components/AdhocTeamMultiSelect/AdhocTeamMultiSelect.tsx
  packages/server/graphql/mutations/helpers/getExistingOneOnOneTeam.ts
  packages/server/graphql/mutations/helpers/maybeCreateOneOnOneTeam.ts
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/public/typeDefs/CreateOneOnOneTeamInput.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/Query.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/CreateOneOnOneTeamInput.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/types/SegmentEventTrackOptions.ts
Labels: size/m

#8798 chore(prompt to join org): restrict to verified users
  packages/server/__tests__/setup.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/graphql/public/mutations/requestToJoinDomain.ts
  packages/server/graphql/public/mutations/signUpWithPassword.ts
  packages/server/graphql/public/mutations/verifyEmail.ts
  packages/server/jest.config.js
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
  packages/server/utils/isUserVerified.ts
  packages/server/utils/sendPromptToJoinOrg.ts
Labels: size/l

#8795 chore(analytics): Move server side segmentIo calls to analytics.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/graphql/mutations/addAgendaItem.ts
  packages/server/graphql/mutations/addOrg.ts
  packages/server/graphql/mutations/addTeam.ts
  packages/server/graphql/mutations/archiveOrganization.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/createPoll.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/publishChangeNotifications.ts
  packages/server/graphql/mutations/helpers/sendAccountRemovedToSegment.ts
  packages/server/graphql/mutations/helpers/sendPokerMeetingRevoteToSegment.ts
  packages/server/graphql/mutations/payLater.ts
  packages/server/graphql/mutations/pokerResetDimension.ts
  packages/server/graphql/mutations/setStageTimer.ts
  packages/server/graphql/mutations/updateReflectionGroupTitle.ts
  packages/server/graphql/mutations/updateTaskDueDate.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#8850 fix(billing): Stop updating Enterprise Stripe subscription quantities to AU count
  packages/server/billing/helpers/updateSubscriptionQuantity.ts
  packages/server/graphql/private/mutations/stripeCreateInvoice.ts
Labels: One Review Required, size/xs

#8874 fix(standups): 'Your tasks' -> 'Your work'
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Labels: One Review Required, size/xs

#8861 feat(standups): Add slack configuration link to standup options
  packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
Labels: One Review Required, size/s

#8842 fix: emoji tooltip info is wrong in a standup discussion drawer
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
Labels: One Review Required, size/s

#8867 chore: Show link to guide on Jira auth popup close
  packages/client/components/ScopePhaseAreaAddJira.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/AtlassianProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/ProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/ProviderRowBase.tsx
  packages/client/types/constEnums.ts
  packages/client/utils/AtlassianClientManager.ts
  packages/client/utils/getDeCasteljau.ts
Labels: size/s

#8707 feat(invitation-challenges): implement InboxReady's validate check
  packages/server/__tests__/inviteToTeam.test.ts
  packages/server/email/MailManager.ts
  packages/server/email/MailManagerMailgun.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/mutations/inviteToTeam.ts
Labels: size/m

#8873 chore: upgrade openai
  packages/server/package.json
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: One Review Required, size/s

#8870 chore: store freemail domains in pg
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/dataloader/__tests__/isCompanyDomain.test.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/addOrg.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/createNewOrg.ts
  packages/server/graphql/mutations/helpers/isPatientZero.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/private/mutations/autopauseUsers.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/queries/company.ts
  packages/server/graphql/private/queries/dailyPulse.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/types/User.ts
  packages/server/postgres/migrations/1695293482618_addFreemailDomain.ts
  packages/server/postgres/queries/getAUserForDomain.ts
  packages/server/postgres/queries/src/getAUserForDomainQuery.sql
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/getActiveDomainForOrgId.ts
  packages/server/utils/isCompanyDomain.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: size/xl

#8875 feat(standups): Display responses in single column (feature flagged)
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/TeamPromptMeeting.tsx
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: One Review Required, size/s

#8857 feat: show sidebar by meeting summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingSummaryEmail.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheetCTA.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/summary/components/NewMeetingSummaryRoot.tsx
Labels: size/s

#8889 chore(dokku): add one more web server
  pm2.config.js
Labels: devops, size/xs

#8884 fix: loom links wrap, changed layout to single column
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummary.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx
Labels: One Review Required, size/s

#8886 feat(Prompt to join org): reverse feature flag
  packages/client/modules/demo/initDB.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: size/s

#8877 feat(Team Insights): add meeting engagement insights
  packages/client/modules/teamDashboard/components/TeamDashInsights/MeetingEngagementCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/server/database/types/Comment.ts
  packages/server/database/types/Meeting.ts
  packages/server/database/types/Reflection.ts
  packages/server/database/types/ReflectionGroup.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/calculateEngagement.ts
  packages/server/graphql/mutations/helpers/gatherInsights.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
  packages/server/graphql/public/typeDefs/TeamInsights.graphql
  packages/server/graphql/public/types/Team.ts
Labels: size/m

#8879 feat(Team Insights): Add most used retro templates
  codegen.json
  packages/client/modules/teamDashboard/components/TeamDashInsights/MeetingEngagementCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
  packages/client/shared/gqlIds/TopRetroTemplateId.ts
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
  packages/server/graphql/public/typeDefs/TeamInsights.graphql
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/public/types/TopRetroTemplate.ts
Labels: size/m

#8580 fix: add transcription during discuss phase
  codegen.json
  packages/client/components/DiscussionThreadListEmptyState.tsx
  packages/client/components/RetroDiscussPhase.tsx
  packages/client/mutations/AddTranscriptionBotMutation.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/database/types/MeetingSettingsRetrospective.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/addRecallBot.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/addTranscriptionBot.ts
  packages/server/graphql/public/typeDefs/addTranscriptionBot.graphql
  packages/server/graphql/public/types/AddTranscriptionBotSuccess.ts
  packages/server/graphql/types/RetrospectiveMeeting.ts
  packages/server/graphql/types/RetrospectiveMeetingSettings.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#8818 feat(gcal): add Google Meet
  packages/client/components/GoogleMeetProviderLogo.tsx
  packages/client/components/ZoomProviderLogo.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencingMenu.tsx
  packages/client/styles/theme/images/graphics/google-meet-icon.svg
  packages/client/styles/theme/images/graphics/zoom-logo.svg
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/types/CreateGcalEventInput.ts
  packages/server/graphql/types/GcalVideoTypeEnum.ts
Labels: size/m

#8888 chore(ci): adding release branch to the build action
  .github/workflows/build.yml
Labels: devops, size/xs

#8896 chore: change gcal creds to google creds
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  scripts/toolboxSrc/primeIntegrations.ts
Labels: One Review Required, size/xs

#8906 fix: read SAML from PG
  CHANGELOG.md
  lerna.json
  packages/chronos/package.json
  packages/client/package.json
  packages/gql-executor/package.json
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/graphql/queries/SAMLIdP.ts
  packages/server/graphql/queries/verifiedInvitation.ts
  packages/server/package.json
  packages/server/utils/getSAMLURLFromEmail.ts
Labels: size/s
