Repository ParabolInc/parabol, pull requests merged in 2024-09, with the labels that each got.

#10146 feat(orgAdmins): Make org members view sortable
  packages/client/components/OrgAdminActionMenu.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
Labels: size/m

#10187 feat(orgAdmin): search in org members page
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Labels: size/s

#10180 chore(rethinkdb): Comment: Phase 2
  packages/server/postgres/migrations/1724884922936_Comment-phase2.ts
Labels: size/m

#10190 fix: multiple slack notifications
  packages/server/dataloader/integrationAuthLoaders.ts
Labels: size/xs

#10194 fix: insert discussion before comment
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/updatePokerScope.ts
  packages/server/postgres/queries/insertDiscussions.ts
  packages/server/postgres/queries/src/insertDiscussionsQuery.sql
Labels: size/m

#9193 chore(metrics): Only track 'Loaded a Page' event to Amplitude when userId is known
  packages/client/components/AnalyticsPage.tsx
Labels: size/s

#10172 chore(rethinkdb): Comment: Phase 3
  codegen.json
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/workflows/helpers/publishSimilarRetroTopics.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/Comment.ts
  packages/server/database/types/Reactji.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/calculateEngagement.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/private/mutations/generateMeetingSummary.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/public/mutations/addComment.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/deleteComment.ts
  packages/server/graphql/public/mutations/helpers/getTopics.ts
  packages/server/graphql/public/mutations/updateCommentContent.ts
  packages/server/graphql/public/types/AddCommentSuccess.ts
  packages/server/graphql/public/types/Comment.ts
  packages/server/graphql/public/types/DeleteCommentSuccess.ts
  packages/server/graphql/public/types/NotifyDiscussionMentioned.ts
  packages/server/graphql/public/types/NotifyResponseReplied.ts
  packages/server/graphql/public/types/UpdateCommentContentSuccess.ts
  packages/server/graphql/resolvers/resolveReactjis.ts
  packages/server/graphql/resolvers/resolveThreadableConnection.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/getGroupedReactjis.ts
Labels: size/m

#10201 fix(orgAdmin): user should be able to remove themselves from the org
  packages/client/components/OrgAdminActionMenu.tsx
Labels: size/xs

#10025 feat: Enable connecting to different GitLab integration providers
  codegen.json
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/Settings/SettingsWrapper.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/GitLabProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/ProviderRowBase.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingDangerZone.tsx
  packages/client/modules/userDashboard/components/OrgBilling/Organization.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/AddGitLabProviderDialog.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/EditGitLabProviderDialog.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/GitLabProviderRow.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/GitLabProviders.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/OrgIntegrations.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/RemoveIntegrationProviderDialog.tsx
  packages/client/modules/userDashboard/components/OrgIntegrations/UpsertGitLabProviderDialog.tsx
  packages/client/mutations/AddIntegrationProviderMutation.ts
  packages/client/mutations/AddTeamMemberIntegrationAuthMutation.ts
  packages/client/mutations/RemoveIntegrationProviderMutation.ts
  packages/client/mutations/RemoveTeamMemberIntegrationAuthMutation.ts
  packages/client/shared/gqlIds/OrgIntegrationProvidersId.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/client/tailwindTheme.ts
  packages/client/types/constEnums.ts
  packages/client/ui/AlertDialog/AlertDialogContent.tsx
  packages/client/ui/AlertDialog/AlertDialogTitle.tsx
  packages/client/ui/Dialog/Dialog.tsx
  packages/client/ui/Dialog/DialogTrigger.tsx
  packages/client/utils/constants.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/graphql/mutations/addIntegrationProvider.ts
  packages/server/graphql/mutations/removeIntegrationProvider.ts
  packages/server/graphql/public/mutations/updateIntegrationProvider.ts
  packages/server/graphql/public/typeDefs/AddIntegrationProviderSuccess.graphql
  packages/server/graphql/public/typeDefs/IntegrationProviderMetadataInputOAuth2.graphql
  packages/server/graphql/public/typeDefs/OrgIntegrationProviders.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/OrganizationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveIntegrationProviderSuccess.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/UpdateIntegrationProviderSuccess.graphql
  packages/server/graphql/public/types/AddIntegrationProviderSuccess.ts
  packages/server/graphql/public/types/GitLabIntegration.ts
  packages/server/graphql/public/types/OrgIntegrationProviders.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/UpdateIntegrationProviderSuccess.ts
  packages/server/graphql/types/IntegrationProviderMetadataInputOAuth2.ts
  packages/server/graphql/types/RemoveIntegrationProviderPayload.ts
  packages/server/postgres/queries/upsertIntegrationProvider.ts
  tailwind.config.js
Labels: size/xl

#9955 chore(Snyk): Upgrade openapi-fetch from 0.9.8 to 0.10.0
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#10206 fix: Anonymous comments
  packages/server/graphql/public/mutations/addComment.ts
Labels: size/xs

#10193 chore(rethinkdb): ReflectPrompt: Phase 1
  codegen.json
  packages/server/database/types/RetrospectivePrompt.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addReflectTemplatePrompt.ts
  packages/server/graphql/mutations/helpers/makeRetroTemplates.ts
  packages/server/graphql/mutations/moveReflectTemplatePrompt.ts
  packages/server/graphql/mutations/reflectTemplatePromptUpdateDescription.ts
  packages/server/graphql/mutations/reflectTemplatePromptUpdateGroupColor.ts
  packages/server/graphql/mutations/removeReflectTemplate.ts
  packages/server/graphql/mutations/removeReflectTemplatePrompt.ts
  packages/server/graphql/mutations/renameReflectTemplatePrompt.ts
  packages/server/graphql/mutations/updateTemplateScope.ts
  packages/server/graphql/public/mutations/addReflectTemplate.ts
  packages/server/graphql/public/mutations/addReflectTemplatePrompt.ts
  packages/server/graphql/public/mutations/moveReflectTemplatePrompt.ts
  packages/server/graphql/public/mutations/reflectTemplatePromptUpdateDescription.ts
  packages/server/graphql/public/mutations/reflectTemplatePromptUpdateGroupColor.ts
  packages/server/graphql/public/mutations/removeReflectTemplatePrompt.ts
  packages/server/graphql/public/mutations/renameReflectTemplatePrompt.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/types/AddReflectTemplatePromptPayload.ts
  packages/server/graphql/public/types/MoveReflectTemplatePromptPayload.ts
  packages/server/graphql/public/types/ReflectPhase.ts
  packages/server/graphql/public/types/ReflectTemplatePromptUpdateDescriptionPayload.ts
  packages/server/graphql/public/types/ReflectTemplatePromptUpdateGroupColorPayload.ts
  packages/server/graphql/public/types/RemoveReflectTemplatePromptPayload.ts
  packages/server/graphql/public/types/RenameReflectTemplatePromptPayload.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddReflectTemplatePromptPayload.ts
  packages/server/graphql/types/MoveReflectTemplatePromptPayload.ts
  packages/server/graphql/types/ReflectTemplatePromptUpdateDescriptionPayload.ts
  packages/server/graphql/types/ReflectTemplatePromptUpdateGroupColorPayload.ts
  packages/server/graphql/types/RemoveReflectTemplatePromptPayload.ts
  packages/server/graphql/types/RenameReflectTemplatePromptPayload.ts
  packages/server/postgres/migrations/1725655687704_ReflectPrompt-phase1.ts
  packages/server/postgres/queries/insertMeetingTemplate.ts
  packages/server/postgres/queries/removeMeetingTemplate.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
Labels: size/xl

#10181 fix: move to rrule-rust
  .github/workflows/test.yml
  codegen.json
  package.json
  packages/client/components/AnalyticsPage.tsx
  packages/client/components/Recurrence/RecurrenceSettings.tsx
  packages/client/components/Recurrence/RecurrenceTimePicker.tsx
  packages/client/components/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/jest.config.js
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/client/shared/__tests__/rruleUtil.test.ts
  packages/client/shared/rruleUtil.ts
  packages/server/__tests__/processRecurrence.test.ts
  packages/server/database/types/Meeting.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
  packages/server/graphql/public/types/RRule.ts
  packages/server/graphql/public/types/__tests__/RRule.test.ts
  packages/server/jest.config.js
  packages/server/package.json
  packages/server/postgres/migrations/1676020597201_scheduledJobOrgIdIndex.ts
  packages/server/utils/getNextRRuleDate.ts
  yarn.lock
Labels: size/l

#10208 chore(rethinkdb): ReflectPhase: Phase 2
  packages/server/postgres/migrations/1725913333530_ReflectPrompt-phase2.ts
Labels: size/m

#10210 chore(rethinkdb): PasswordResetRequest: One-shot
  packages/server/__tests__/globalSetup.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/PasswordResetRequest.ts
  packages/server/graphql/mutations/emailPasswordReset.ts
  packages/server/graphql/mutations/helpers/processEmailPasswordReset.ts
  packages/server/graphql/mutations/resetPassword.ts
  packages/server/postgres/migrations/1725996598345_PasswordResetRequest.ts
Labels: size/l

#10213 chore(rethinkdb): PushInvitation: One-shot
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/PushInvitation.ts
  packages/server/graphql/mutations/denyPushInvitation.ts
  packages/server/graphql/mutations/pushInvitation.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/postgres/migrations/1726078121329_PushInvitation.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
Labels: size/xl

#10204 chore: Speed up processRecurrence test
  packages/server/__tests__/processRecurrence.test.ts
Labels: size/s

#10228 fix: threadParent can exist outside comment table
  package.json
  packages/client/hooks/useSortNewReflectionGroup.ts
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/utils/handleSuccessfulLogin.ts
  packages/embedder/ai_models/ModelManager.ts
  packages/embedder/package.json
  packages/gql-executor/package.json
  packages/integration-tests/package.json
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/package.json
  packages/server/parseBody.ts
  packages/server/parseFormBody.ts
  packages/server/postgres/migrations/1726174443131_dropThreadParentId.ts
  yarn.lock
Labels: size/s

#10198 fix: Remove duplicate org users
  packages/server/__tests__/autoJoin.test.ts
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/postgres/migrations/1725438336254_addOrganizationUserUniqueConstraint.ts
Labels: size/s

#10251 fix(misc): show full length of agenda item text when hovering
  packages/client/components/MeetingSubnavItem.tsx
  packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
Labels: Skip Maintainer Review, size/s

#10262 fix: bump relay so it shares react's scheduler
  package.json
  packages/client/Atmosphere.ts
  packages/client/components/ActionMeetingUpdatesPrompt.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DueDateToggle.tsx
  packages/client/components/GroupingKanbanColumnHeader.tsx
  packages/client/components/JiraScopingSearchFilterMenu.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionGroup/ReflectionGroup.tsx
  packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
  packages/client/components/TimelineFeedList.tsx
  packages/client/hooks/useAnimatedSpotlightSource.ts
  packages/client/hooks/useMakeStageSummaries.ts
  packages/client/hooks/useSlackChannels.ts
  packages/client/hooks/useUsageSnackNag.ts
  packages/client/modules/email/components/EmailNotifications/EmailTaskInvolves.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TaskSummarySection.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/modules/userDashboard/components/UserProfileRoot.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/LoginWithMicrosoftMutation.ts
  packages/client/mutations/LoginWithPasswordMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/client/mutations/StartDraggingReflectionMutation.ts
  packages/client/mutations/handlers/handleRemoveOrgMembers.ts
  packages/client/mutations/handlers/handleUpsertTasks.ts
  packages/client/package.json
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/utils/AzureDevOpsClientManager.ts
  packages/client/utils/getNonNullEdges.ts
  relay.config.js
  yarn.lock
Labels: size/m

#10263 fix: isPaid flag when moving teams to 0-team org
  packages/server/graphql/mutations/moveTeamToOrg.ts
Labels: size/xs

#10236 feat(metrics): add mutation to generate usage report
  packages/server/graphql/private/mutations/runOrgActivityReport.ts
  packages/server/graphql/private/typeDefs/runOrgActivityReport.graphql
Labels: size/m

#10268 fix: stop series when team is no more
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
Labels: size/s

#10250 chore(rethinkdb): NewMeeting: Phase 1b
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/dragDiscussionTopic.ts
  packages/server/graphql/mutations/dragEstimatingTask.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/flagReadyToAdvance.ts
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
  packages/server/graphql/mutations/helpers/addRecallBot.ts
  packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/helpers/hideConversionModal.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/removeEmptyTasks.ts
  packages/server/graphql/mutations/helpers/removeStagesFromMeetings.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/helpers/removeUserFromMeetingStages.ts
  packages/server/graphql/mutations/helpers/safeCreateTeamPrompt.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/navigateMeeting.ts
  packages/server/graphql/mutations/payLater.ts
  packages/server/graphql/mutations/pokerResetDimension.ts
  packages/server/graphql/mutations/pokerRevealVotes.ts
  packages/server/graphql/mutations/promoteNewMeetingFacilitator.ts
  packages/server/graphql/mutations/removeReflection.ts
  packages/server/graphql/mutations/renameMeeting.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/mutations/setPhaseFocus.ts
  packages/server/graphql/mutations/setStageTimer.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/updateNewCheckInQuestion.ts
  packages/server/graphql/mutations/updatePokerScope.ts
  packages/server/graphql/mutations/updateRetroMaxVotes.ts
  packages/server/graphql/mutations/voteForPokerStory.ts
  packages/server/graphql/mutations/voteForReflectionGroup.ts
  packages/server/graphql/private/mutations/generateMeetingSummary.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/autogroup.ts
  packages/server/graphql/public/mutations/modifyCheckInQuestion.ts
  packages/server/graphql/public/mutations/resetReflectionGroups.ts
  packages/server/graphql/public/mutations/revealTeamHealthVotes.ts
  packages/server/graphql/public/mutations/setTeamHealthVote.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
  packages/server/graphql/public/mutations/updateAgendaItem.ts
  packages/server/graphql/public/mutations/updateMeetingPrompt.ts
  packages/server/graphql/public/mutations/updateMeetingTemplate.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
  packages/server/postgres/migrations/1726251201860_NewMeeting-uniq.ts
  packages/server/postgres/queries/src/updateMeetingSeriesByIdQuery.sql
  packages/server/postgres/queries/updateMeetingSeries.ts
Labels: size/l

#10274 feat: team insights skeleton, minor style nits
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsights.tsx
Labels: size/xs
