Repository ParabolInc/parabol, pull requests merged in 2024-08, with the labels that each got.

#10035 chore(rethinkdb): SuggestedAction: Phase 1
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/graphql/mutations/dismissSuggestedAction.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/postgres/migrations/1721940319404_SuggestedAction-phase1.ts
  packages/server/postgres/select.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safeMutations/removeSuggestedAction.ts
Labels: size/m

#10060 fix: discussion mentioned can be triggered by all meetings
  packages/server/graphql/public/typeDefs/NotifyDiscussionMentioned.graphql
  packages/server/graphql/public/types/NotifyDiscussionMentioned.ts
Labels: size/xs

#10063 fix: check signal for build exit code
  scripts/prod.js
Labels: size/xs

#10056 fix: Fix error in start meeting if the user has no teams
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/TimelineSuggestedAction.tsx
Labels: size/s

#10022 feat(orgAdmin): org admins can archive teams
  packages/client/modules/teamDashboard/components/TaskColumn/ArchiveAllDoneTasksModal.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembersMenu.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
  packages/client/modules/userDashboard/components/Organization/OrgNav.tsx
Labels: size/s

#6014 chore: Add orgId to IntegrationProvider
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
  packages/client/mutations/UpdateIntegrationProviderMutation.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/__tests__/common.ts
  packages/server/__tests__/jiraServerIntegration.test.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/graphql/mutations/addIntegrationProvider.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/removeIntegrationProvider.ts
  packages/server/graphql/public/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/public/mutations/updateIntegrationProvider.ts
  packages/server/graphql/public/typeDefs/AddIntegrationProviderInput.graphql
  packages/server/graphql/public/typeDefs/AddIntegrationProviderSuccess.graphql
  packages/server/graphql/public/typeDefs/IntegrationProvider.graphql
  packages/server/graphql/public/typeDefs/IntegrationProviderOAuth1.graphql
  packages/server/graphql/public/typeDefs/IntegrationProviderOAuth2.graphql
  packages/server/graphql/public/typeDefs/IntegrationProviderWebhook.graphql
  packages/server/graphql/public/typeDefs/OrganizationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/UpdateIntegrationProviderInput.graphql
  packages/server/graphql/public/typeDefs/UpdateIntegrationProviderSuccess.graphql
  packages/server/graphql/public/types/AzureDevOpsIntegration.ts
  packages/server/graphql/public/types/GcalIntegration.ts
  packages/server/graphql/public/types/GitLabIntegration.ts
  packages/server/graphql/public/types/JiraServerIntegration.ts
  packages/server/graphql/public/types/MSTeamsIntegration.ts
  packages/server/graphql/public/types/MattermostIntegration.ts
  packages/server/graphql/public/types/UpdateIntegrationProviderSuccess.ts
  packages/server/graphql/types/AddIntegrationProviderInput.ts
  packages/server/graphql/types/AddIntegrationProviderPayload.ts
  packages/server/graphql/types/IntegrationProvider.ts
  packages/server/postgres/migrations/1722526485990_orgIdForIntegrationProvider.ts
  packages/server/postgres/queries/getSharedIntegrationProviders.ts
  packages/server/postgres/queries/src/getSharedIntegrationProvidersQuery.sql
  packages/server/postgres/queries/src/upsertIntegrationProviderQuery.sql
  packages/server/postgres/queries/upsertIntegrationProvider.ts
  scripts/toolboxSrc/primeIntegrations.ts
Labels: DX, size/l

#10067 fix: null not distinct
  packages/server/postgres/migrations/1722632147643_IntegrationProvider-null-not-distinct.ts
Labels: size/s

#10066 fix: nest-graphql-endpoint support graphql v16
  packages/server/package.json
  yarn.lock
Labels: size/xs

#10042 chore(rethinkdb): SuggestedAction: Phase 2
  packages/server/postgres/migrations/1722637208553_SuggestAction-phase2.ts
Labels: size/m

#10073 fix: Fetching more than 200 Azure DevOps issues
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/s

#10078 chore: cleanup selectors
  codegen.json
  packages/client/types/generics.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/billing/helpers/handleTeamOrgQuantityChanges.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/database/types/Reactable.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/calculateEngagement.ts
  packages/server/graphql/mutations/helpers/canAccessAISummary.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/private/queries/suProOrgInfo.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/helpers/publishTeamPromptMentions.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/graphql/public/types/AddReactjiToReactableSuccess.ts
  packages/server/graphql/public/types/NotifyResponseMentioned.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/Reactable.ts
  packages/server/graphql/public/types/RetroReflection.ts
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/public/types/TeamPromptResponse.ts
  packages/server/graphql/public/types/UpsertTeamPromptResponseSuccess.ts
  packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts
  packages/server/graphql/resolvers.ts
  packages/server/graphql/types/getReactableType.ts
  packages/server/postgres/queries/getTeamPromptResponsesByIds.ts
  packages/server/postgres/queries/getTeamPromptResponsesByMeetingIds.ts
  packages/server/postgres/queries/src/getTeamPromptResponsesByIdsQuery.sql
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/l

#10017 feat: generate a summary of meeting summaries
  codegen.json
  packages/client/mutations/GenerateInsightMutation.ts
  packages/server/graphql/public/mutations/generateInsight.ts
  packages/server/graphql/public/mutations/helpers/getSummaries.ts
  packages/server/graphql/public/mutations/helpers/getTopics.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/typeDefs/generateInsight.graphql
  packages/server/graphql/public/types/GenerateInsightSuccess.ts
  packages/server/package.json
  packages/server/postgres/migrations/1722011287034_addInsight.ts
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: size/l

#10050 feat: generate new meeting summaries for a team
  codegen.json
  packages/server/graphql/private/mutations/generateMeetingSummary.ts
  packages/server/graphql/private/typeDefs/generateMeetingSummary.graphql
  packages/server/graphql/private/types/GenerateMeetingSummarySuccess.ts
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: size/m

#10087 fix: rename Insight migration
  packages/server/postgres/migrations/1722638208553_addInsight.ts
Labels: size/xs

#10091 fix: Don't fail acceptTeamInvitation for duplicate suggested actions
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
Labels: size/s

#10077 fix: Avoid refetching project template for ADO
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/s

#10096 fix: Do not add suggested actions multiple times for autojoin
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Labels: size/s

#10081 feat: update meeting summary UI
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
  packages/client/package.json
  packages/client/styles/theme/global.css
  yarn.lock
Labels: size/s

#10088 chore(rethinkdb): MeetingSettings: Phase 1
  packages/server/database/rethinkDriver.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/removePokerTemplate.ts
  packages/server/graphql/mutations/removeReflectTemplate.ts
  packages/server/graphql/mutations/selectTemplate.ts
  packages/server/graphql/mutations/updateRetroMaxVotes.ts
  packages/server/graphql/public/mutations/setMeetingSettings.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
  packages/server/postgres/migrations/1723061869934_MeetingSettings-phase1.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#10089 chore(rethinkdb): MeetingSettings: Phase 2
  packages/server/postgres/migrations/1723074637531_MeetingSettings-phase2.ts
Labels: size/m

#10104 fix: email-meeting-summaries
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
  packages/client/package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#10090 chore(rethinkdb): MeetingSettings: Phase 3
  codegen.json
  packages/client/modules/demo/initDB.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/MeetingSettings.ts
  packages/server/database/types/MeetingSettingsAction.ts
  packages/server/database/types/MeetingSettingsPoker.ts
  packages/server/database/types/MeetingSettingsRetrospective.ts
  packages/server/database/types/MeetingSettingsTeamPrompt.ts
  packages/server/database/types/TeamPromptResponsesPhase.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/safeCreateTeamPrompt.ts
  packages/server/graphql/mutations/removePokerTemplate.ts
  packages/server/graphql/mutations/removeReflectTemplate.ts
  packages/server/graphql/mutations/selectTemplate.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/updateRetroMaxVotes.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/removePokerTemplate.ts
  packages/server/graphql/public/mutations/setMeetingSettings.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/types/PokerMeetingSettings.ts
  packages/server/graphql/public/types/RemovePokerTemplatePayload.ts
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/PokerMeetingSettings.ts
  packages/server/graphql/types/RemovePokerTemplatePayload.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/Meeting.d.ts
  packages/server/postgres/types/index.d.ts
Labels: size/l

#10108 chore(rethinkdb): AgendaItem: Phase 1
  packages/client/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.tsx
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addAgendaItem.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/removeAgendaItem.ts
  packages/server/graphql/mutations/updateAgendaItem.ts
  packages/server/graphql/public/mutations/setMeetingSettings.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/postgres/migrations/1723491538114_AgendaItem-phase1.ts
  packages/server/postgres/select.ts
Labels: size/m

#10130 fix: action meetings that had templates. wtf
  packages/server/postgres/migrations/1723492538114_MeetingSettings-phase2redo.ts
Labels: size/s

#10133 fix: handle empty array to PG. fixup error handling
  packages/server/graphql/executeGraphQL.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/utils/sendToSentry.ts
Labels: size/s

#10136 fix: add missing ID
  packages/server/graphql/mutations/addAgendaItem.ts
Labels: size/xs

#10109 chore(rethinkdb): AgendaItem: Phase 3
  codegen.json
  packages/client/modules/teamDashboard/components/AgendaInput/AgendaInput.tsx
  packages/client/modules/teamDashboard/components/AgendaList/AgendaList.tsx
  packages/client/validation/makeAgendaItemSchema.ts
  packages/client/validation/makeUpdateAgendaItemSchema.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/AgendaItem.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addAgendaItem.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
  packages/server/graphql/mutations/removeAgendaItem.ts
  packages/server/graphql/mutations/updateAgendaItem.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/public/mutations/addAgendaItem.ts
  packages/server/graphql/public/mutations/removeAgendaItem.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/graphql/public/mutations/updateAgendaItem.ts
  packages/server/graphql/public/typeDefs/AgendaItem.graphql
  packages/server/graphql/public/typeDefs/CreateAgendaItemInput.graphql
  packages/server/graphql/public/typeDefs/UpdateAgendaItemInput.graphql
  packages/server/graphql/public/types/ActionMeeting.ts
  packages/server/graphql/public/types/AddAgendaItemPayload.ts
  packages/server/graphql/public/types/AgendaItemsStage.ts
  packages/server/graphql/public/types/RemoveAgendaItemPayload.ts
  packages/server/graphql/public/types/UpdateAgendaItemPayload.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddAgendaItemPayload.ts
  packages/server/graphql/types/CreateAgendaItemInput.ts
  packages/server/graphql/types/RemoveAgendaItemPayload.ts
  packages/server/graphql/types/UpdateAgendaItemInput.ts
  packages/server/graphql/types/UpdateAgendaItemPayload.ts
  packages/server/postgres/migrations/1723672980596_AgendaItem-phase2.ts
  packages/server/postgres/types/index.d.ts
Labels: size/xl

#10145 fix: no team leads
  packages/client/hooks/useMeetingMemberAvatars.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/promoteToTeamLead.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/postgres/migrations/1724174924811_oneTeamLead.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
Labels: size/s

#10151 fix: use period end instead of due at
  packages/client/modules/userDashboard/components/InvoiceRow/InvoiceRow.tsx
  packages/server/graphql/public/fields/invoices.ts
  packages/server/graphql/public/typeDefs/Invoice.graphql
Labels: size/s

#10148 chore: update contributing doc
  CONTRIBUTING.md
Labels: size/s

#10142 fix(orgAdmins): archived teams should be removed from the OrgTeams view
  packages/client/mutations/ArchiveTeamMutation.ts
Labels: Skip Maintainer Review, size/xs

#10141 fix(orgAdmins): Billing leaders should not see all teams in the org
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/server/graphql/public/types/Organization.ts
Labels: Skip Maintainer Review, size/s

#10153 feat: upgrade suggest groups openai models
  packages/server/utils/OpenAIServerManager.ts
Labels: size/xs

#10154 chore(rethinkdb): SlackAuth
  codegen.json
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addSlackAuth.ts
  packages/server/graphql/mutations/helpers/activatePrevSlackAuth.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/removeSlackAuths.ts
  packages/server/graphql/mutations/removeSlackAuth.ts
  packages/server/graphql/mutations/setDefaultSlackChannel.ts
  packages/server/graphql/mutations/setSlackNotification.ts
  packages/server/graphql/private/mutations/messageAllSlackUsers.ts
  packages/server/graphql/private/mutations/removeAllSlackAuths.ts
  packages/server/graphql/private/queries/dailyPulse.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
  packages/server/graphql/public/mutations/addSlackAuth.ts
  packages/server/graphql/public/mutations/setDefaultSlackChannel.ts
  packages/server/graphql/public/mutations/setSlackNotification.ts
  packages/server/graphql/public/types/AddSlackAuthPayload.ts
  packages/server/graphql/public/types/SetDefaultSlackChannelSuccess.ts
  packages/server/graphql/public/types/SetSlackNotificationPayload.ts
  packages/server/graphql/public/types/SlackNotification.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddSlackAuthPayload.ts
  packages/server/graphql/types/SetDefaultSlackChannelPayload.ts
  packages/server/graphql/types/SetSlackNotificationPayload.ts
  packages/server/graphql/types/SlackIntegration.ts
  packages/server/graphql/types/SlackNotification.ts
  packages/server/graphql/types/SlackNotificationEventEnum.ts
  packages/server/graphql/types/SlackNotificationEventTypeEnum.ts
  packages/server/postgres/migrations/1724261917988_SlackAuth.ts
  packages/server/postgres/select.ts
Labels: size/xl

#10163 chore(rethinkdb): SlackNotification
  .github/workflows/build.yml
  .github/workflows/release-to-prod.yml
  .github/workflows/release-to-staging.yml
  .github/workflows/style-check.yml
  .github/workflows/test.yml
  codegen.json
  packages/server/database/migrations/20190612194707-scheduledJobs.js
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/SlackNotification.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/removeSlackAuths.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/private/mutations/removeAllSlackAuths.ts
  packages/server/graphql/public/mutations/addSlackAuth.ts
  packages/server/graphql/public/mutations/setSlackNotification.ts
  packages/server/graphql/public/types/SlackNotification.ts
  packages/server/postgres/migrations/1724358892236_SlackNotification.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#10160 feat: add ai summary to demo
  packages/client/modules/demo/initDB.ts
Labels: size/xs

#10162 fix: consolidate org user menus
  packages/client/components/BillingLeaderActionMenu.tsx
  packages/client/components/BillingLeaderMenu.tsx
  packages/client/components/FlatButton.tsx
  packages/client/components/OrgAdminActionMenu.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/ui/Button/Button.tsx
  packages/server/graphql/public/fields/invoices.ts
Labels: size/m

#10166 chore(rethinkdb): Comment: Phase 1
  codegen.json
  packages/client/components/DiscussionThreadInput.tsx
  packages/embedder/workflows/helpers/publishSimilarRetroTopics.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addComment.ts
  packages/server/graphql/mutations/deleteComment.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/mutations/updateCommentContent.ts
  packages/server/graphql/public/mutations/addComment.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/deleteComment.ts
  packages/server/graphql/public/mutations/updateCommentContent.ts
  packages/server/graphql/public/typeDefs/AddCommentInput.graphql
  packages/server/graphql/public/typeDefs/Comment.graphql
  packages/server/graphql/public/typeDefs/CreatePollInput.graphql
  packages/server/graphql/public/typeDefs/CreateTaskInput.graphql
  packages/server/graphql/public/typeDefs/Poll.graphql
  packages/server/graphql/public/typeDefs/Task.graphql
  packages/server/graphql/public/typeDefs/Threadable.graphql
  packages/server/graphql/public/types/AddCommentSuccess.ts
  packages/server/graphql/public/types/DeleteCommentSuccess.ts
  packages/server/graphql/public/types/TeamPromptMeeting.ts
  packages/server/graphql/public/types/Threadable.ts
  packages/server/graphql/public/types/UpdateCommentContentSuccess.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/AddCommentInput.ts
  packages/server/graphql/types/AddCommentPayload.ts
  packages/server/graphql/types/Comment.ts
  packages/server/graphql/types/CreatePollInput.ts
  packages/server/graphql/types/CreateTaskInput.ts
  packages/server/graphql/types/DeleteCommentPayload.ts
  packages/server/graphql/types/Poll.ts
  packages/server/graphql/types/Task.ts
  packages/server/graphql/types/Threadable.ts
  packages/server/graphql/types/UpdateCommentContentPayload.ts
  packages/server/postgres/migrations/1724780116674_Comment-phase1.ts
  packages/server/postgres/select.ts
Labels: size/xl

#10173 chore(rethinkdb): Comment: Phase 2
  packages/server/postgres/migrations/1724884922936_Comment-phase2.ts
Labels: size/xl

#10178 fix: add discussion before comments
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/public/mutations/addComment.ts
  packages/server/postgres/migrations/1724884922936_Comment-phase2.ts
Labels: size/m
