Repository ParabolInc/parabol, pull requests merged in 2024-03, with the labels that each got.

#9486 fix: support single-tenant saml record
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/utils/getSAMLURLFromEmail.ts
Labels: size/xs

#9504 chore: Update reviewers
  .github/reviewers.yml
Labels: size/xs

#9498 chore: bump ts node
  packages/server/package.json
  packages/server/postgres/migrations/1693991480688_truncateReflectPromptIds.ts
  packages/server/postgres/migrations/1694191002164_migrateSAML.ts
  packages/server/postgres/migrations/1698265572466_renameEmailVerificationSegmentIdToPseudoId.ts
  yarn.lock
Labels: size/s

#9278 chore: put server assets on CDN
  .github/workflows/test.yml
  docker/parabol-ubi/docker-build/environments/pipeline
  packages/client/modules/email/components/EmailNotifications/EmailDiscussionMentioned.tsx
  packages/client/modules/email/components/EmailNotifications/EmailResponseReplied.tsx
  packages/client/serviceWorker/sw.ts
  packages/client/styles/theme/images/anonymous-avatar.png
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/fileStorage/S3FileStoreManager.ts
  packages/server/initPublicPath.ts
  packages/server/jiraImagesHandler.ts
  packages/server/selfHostedHandler.ts
  packages/server/types/modules.d.ts
  packages/server/utils/serveStatic.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/toolboxSrc/pushToCDN.ts
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.client.config.js
  scripts/webpack/prod.servers.config.js
Labels: size/m

#9497 [Snyk] Upgrade oy-vey from 0.11.2 to 0.12.1
  packages/server/package.json
Labels: size/xs

#9493 [Snyk] Upgrade sharp from 0.32.6 to 0.33.2
  packages/server/package.json
Labels: size/xs

#9509 fix: revert sharp
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9495 [Snyk] Upgrade graphql-jit from 0.7.4 to 0.8.4
  packages/server/package.json
Labels: size/xs

#9508 chore: remove pg-typed part 1
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/private/mutations/addNewFeature.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/updateFeatureFlag.ts
  packages/server/package.json
  packages/server/postgres/queries/archiveTeamsByTeamIds.ts
  packages/server/postgres/queries/src/addUserNewFeatureQuery.sql
  packages/server/postgres/queries/src/appendTeamResponseReactjiQuery.sql
  packages/server/postgres/queries/src/appendUserFeatureFlagsQuery.sql
  packages/server/postgres/queries/src/appendUserTmsQuery.sql
  packages/server/postgres/queries/src/archiveTeamsByTeamIdsQuery.sql
  packages/server/postgres/queries/src/removeTeamResponseReactjiQuery.sql
  packages/server/postgres/queries/src/removeUserFeatureFlagsQuery.sql
  packages/server/safeMutations/addTeamIdToTMS.ts
  packages/server/safeMutations/safeArchiveTeam.ts
  yarn.lock
Labels: size/m

#9503 feat: make all templates free
  packages/server/postgres/migrations/1709551949071_makeAllTemplatesFree.ts
Labels: size/s

#9507 feat: saml login no email, auth design fixups
  packages/client/components/AuthenticationDialog.tsx
  packages/client/components/AuthenticationPage.tsx
  packages/client/components/EmailPasswordAuthForm.tsx
  packages/client/components/GenericAuthentication.tsx
  packages/client/components/GoogleOAuthButtonBlock.tsx
  packages/client/components/MicrosoftOAuthButtonBlock.tsx
  packages/client/components/TeamInvitationEmailCreateAccount.tsx
  packages/client/components/TeamInvitationEmailSignin.tsx
  packages/client/components/TeamInvitationGoogleCreateAccount.tsx
  packages/client/components/TeamInvitationWrapper.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
  packages/client/utils/GoogleClientManager.ts
  packages/client/utils/MicrosoftClientManager.ts
  packages/client/utils/getOAuthPopupFeatures.ts
  packages/client/utils/getTokenFromSSO.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/queries/SAMLIdP.ts
  packages/server/graphql/public/typeDefs/Query.graphql
  packages/server/graphql/queries/SAMLIdP.ts
  packages/server/graphql/rootQuery.ts
  packages/server/utils/getSAMLURLFromEmail.ts
Labels: size/m

#9512 chore(gh-actions): reporting status to Slack if test or build GH Actions fail
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: size/s

#9511 feat: Add team sections to the Custom category in activity library
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
Labels: size/m

#9516 fix: recreate lockfile
  .github/workflows/validate_pr_title.yml
  yarn.lock
Labels: size/xs

#9285 feat: managing teams
  .vscode/launch.json
  packages/client/components/DeleteTeamDialog.tsx
  packages/client/components/OrgAdminActionMenu.tsx
  packages/client/modules/userDashboard/components/OrgBilling/Organization.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMemberMenu.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembersMenu.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembersRoot.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembersRow.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/modules/userDashboard/containers/OrgMembers/OrgMembersRoot.tsx
  packages/client/mutations/ArchiveTeamMutation.ts
  packages/client/package.json
  packages/client/ui/AlertDialog/AlertDialog.tsx
  packages/client/ui/AlertDialog/AlertDialogAction.tsx
  packages/client/ui/AlertDialog/AlertDialogCancel.tsx
  packages/client/ui/AlertDialog/AlertDialogContent.tsx
  packages/client/ui/AlertDialog/AlertDialogDescription.tsx
  packages/client/ui/AlertDialog/AlertDialogFooter.tsx
  packages/client/ui/AlertDialog/AlertDialogHeader.tsx
  packages/client/ui/AlertDialog/AlertDialogOverlay.tsx
  packages/client/ui/AlertDialog/AlertDialogPortal.tsx
  packages/client/ui/AlertDialog/AlertDialogTitle.tsx
  packages/client/ui/AlertDialog/AlertDialogTrigger.tsx
  packages/client/ui/Avatar/Avatar.tsx
  packages/client/ui/Avatar/AvatarFallback.tsx
  packages/client/ui/Avatar/AvatarImage.tsx
  packages/client/ui/Button/Button.tsx
  packages/server/graphql/types/Organization.ts
  packages/server/utils/authorization.ts
  yarn.lock
Labels: size/xl

#9524 chore(ci): add capability to manually generate Docker Images
  .github/workflows/build.yml
Labels: DX, devops, size/xs

#9526 fix: Make hasGCalError optional
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/startCheckIn.graphql
  packages/server/graphql/public/typeDefs/startRetrospective.graphql
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/types/StartRetrospectiveSuccess.ts
Labels: size/s

#9528 chore: Remove Add Activity button from discussions
  packages/client/components/AddActivityButton.tsx
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/modules/demo/initDB.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: size/s

#9525 fix: Korean greeting corrected
  packages/client/utils/makeCheckinGreeting.ts
Labels: Skip Maintainer Review, size/s

#9506 feat: Recurring GCal event dialog
  packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
  packages/client/components/NewMeetingRecurrenceSettings.tsx
  packages/client/components/Recurrence/RecurrenceSettings.tsx
  packages/client/components/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/components/ScheduleDialog.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalSettings.tsx
  packages/client/package.json
  yarn.lock
Labels: size/l

#9527 feat: Release MS Teams integration
  packages/client/modules/demo/DemoUser.ts
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/s

#9500 chore: migrate FailedAuthRequest to pg
  packages/server/__tests__/globalSetup.ts
  packages/server/database/types/FailedAuthRequest.ts
  packages/server/graphql/mutations/helpers/attemptLogin.ts
  packages/server/graphql/mutations/resetPassword.ts
  packages/server/postgres/migrations/1709927369000_addFailedAuthRequest.ts
  yarn.lock
Labels: size/s

#9537 fix: node-loader that ignores public path
  scripts/webpack/prod.servers.config.js
  scripts/webpack/utils/node-loader-private/cjs.js
  scripts/webpack/utils/node-loader-private/index.js
  scripts/webpack/utils/node-loader-private/options.json
Labels: size/s

#9534 chore: add GH Action, on Snyk PRs commit yarn.lock
  .github/workflows/snyk-yarn-lock-commit.yml
Labels: size/s

#9542 fix: use base ref for migrition order check
  .github/workflows/migration-order.yml
Labels: size/xs

#9545 fix: Only read the first ip of the x-forwarded-for header
  packages/server/utils/uwsGetIP.ts
Labels: size/xs

#9543 chore: Remove random team names
  packages/client/utils/makeDefaultTeamName.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/updateTeamName.ts
Labels: size/s

#9549 fix: Activity library illustrations in Firefox
  packages/client/components/ActivityLibrary/ActivityCard.tsx
Labels: size/xs

#9548 fix: Configure trusted proxies
  .env.example
  packages/server/utils/uwsGetIP.ts
Labels: size/xs

#9518 feat: allow 2 custom templates for every user
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/modules/meeting/components/AddNewPokerTemplate.tsx
  packages/client/modules/meeting/components/AddNewReflectTemplate.tsx
  packages/client/mutations/AddPokerTemplateMutation.ts
  packages/client/mutations/AddReflectTemplateMutation.ts
  packages/server/graphql/mutations/addPokerTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/types/AddPokerTemplatePayload.ts
  packages/server/graphql/types/AddReflectTemplatePayload.ts
  packages/server/postgres/migrations/1709933510511_addFreeCustomTemplatesRemaining.ts
  packages/server/postgres/queries/decrementFreeTemplatesRemaining.ts
Labels: size/m

#9560 fix(admin): fix an issue where ORG_ADMIN cannot see members from team they are not in
  packages/server/graphql/queries/team.ts
Labels: size/xs

#9562 chore(github): DevOps review if docker folder is modified or release-please-config is changed
  .github/reviewers.yml
Labels: size/xs

#9093 feat: switch template UI
  packages/client/components/MeetingOptions.tsx
  packages/client/components/MeetingTopBar.tsx
  packages/client/components/RetroDrawer.tsx
  packages/client/components/RetroDrawerRoot.tsx
  packages/client/components/RetroDrawerTemplateCard.tsx
  packages/client/components/RetroReflectPhase/RetroReflectPhase.tsx
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptOptions.tsx
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuItem.tsx
  packages/client/ui/Tooltip/TooltipContent.tsx
  packages/client/ui/Tooltip/TooltipTrigger.tsx
  packages/client/ui/forwardRadix.tsx
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/User.ts
Labels: size/m

#9544 feat: add functionality to change templates during a retro
  codegen.json
  packages/client/components/RetroDrawer.tsx
  packages/client/components/RetroDrawerTemplateCard.tsx
  packages/client/mutations/UpdateMeetingTemplateMutation.ts
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/public/mutations/updateMeetingTemplate.ts
  packages/server/graphql/public/typeDefs/Subscriptions.graphql
  packages/server/graphql/public/typeDefs/updateMeetingTemplate.graphql
  packages/server/graphql/public/types/UpdateMeetingTemplateSuccess.ts
Labels: size/m

#9531 feat: release AzureDevOps integration
  packages/client/components/ScopePhaseArea.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/client/utils/AzureDevOpsClientManager.ts
  packages/server/__tests__/updateFeatureFlag.test.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/CreateAzureDevOpsAuthorizeUrlPayload.ts
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/s

#9554 chore: Roll out AIGeneratedDiscussion to all users
  packages/client/modules/demo/initDB.ts
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: Skip Maintainer Review, size/s

#9494 chore: [Snyk] Upgrade dotenv from 8.0.0 to 8.6.0
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9522 chore: [Snyk] Upgrade graphql-typed from 0.6.1 to 0.7.2
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9521 chore: [Snyk] Upgrade react-swipeable-views-core from 0.13.1 to 0.14.0
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9520 chore: [Snyk] Upgrade react-dom-confetti from 0.0.10 to 0.2.0
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9564 chore: fix update snyk pr action
  .github/workflows/snyk-yarn-lock-commit.yml
  .github/workflows/synk-yarn-lock-commit.yml
Labels: Skip Maintainer Review, size/s

#9572 fix: ensure pool is callable after custom template migration
  packages/server/postgres/migrations/1709933510512_addFreeCustomTemplatesRemaining.ts
Labels: size/xs

#9579 chore: fix tsconfig problems
  packages/chronos/tsconfig.json
  packages/client/components/AnimatedFade.tsx
  packages/client/components/AzureDevOpsScopingSelectAllIssues.tsx
  packages/client/hooks/useAtlassianSites.ts
  packages/client/modules/email/components/MeetingSummaryEmailRootSSR.tsx
  packages/client/modules/email/components/NotificationSummaryEmailRoot.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingSummaryEmail.tsx
  packages/client/mutations/handlers/handleUpdateTeamMembers.ts
  packages/client/package.json
  packages/client/serviceWorker/tsconfig.json
  packages/client/tsconfig.json
  packages/client/types/modules.d.ts
  packages/client/types/reactHTML4.d.ts
  packages/client/ui/AlertDialog/AlertDialogContent.tsx
  packages/client/ui/AlertDialog/AlertDialogPortal.tsx
  packages/client/ui/AlertDialog/AlertDialogTrigger.tsx
  packages/client/utils/__tests__/parseEmailAddressList.test.ts
  packages/client/utils/getBezierTimePercentGivenDistancePercent.ts
  packages/client/utils/screenBugs/Bug.ts
  packages/client/utils/screenBugs/BugController.ts
  packages/embedder/ai_models/OpenAIGeneration.ts
  packages/embedder/embedder.ts
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/embedder/indexing/embeddingsTablesOps.ts
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/modules.d.ts
  packages/embedder/tsconfig.json
  packages/gql-executor/RedisStream.ts
  packages/gql-executor/gqlExecutor.ts
  packages/gql-executor/modules.d.ts
  packages/gql-executor/tsconfig.json
  packages/server/__tests__/autoJoin.test.ts
  packages/server/__tests__/common.ts
  packages/server/__tests__/disableAnonymity.test.ts
  packages/server/__tests__/loginSAML.test.ts
  packages/server/__tests__/processRecurrence.test.ts
  packages/server/__tests__/startRetrospective.test.ts
  packages/server/dataloader/__tests__/isCompanyDomain.test.ts
  packages/server/dataloader/__tests__/isOrgVerified.test.ts
  packages/server/dataloader/__tests__/usersCustomRedisQueries.test.ts
  packages/server/email/inlineImages.ts
  packages/server/generateUID.ts
  packages/server/graphql/executeGraphQL.ts
  packages/server/package.json
  packages/server/tsconfig.json
  packages/server/types/custom.d.ts
  packages/server/types/modules.d.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/__tests__/rateLimiters/InMemoryRateLimiter.test.ts
  packages/server/utils/getGraphQLExecutor.ts
  packages/server/utils/uwsGetHeaders.ts
  scripts/webpack/utils/getProjectRoot.d.ts
  yarn.lock
Labels: size/l

#9517 feat: prepare embedder for Production
  .env.example
  .github/workflows/build.yml
  .github/workflows/test.yml
  docker/images/parabol-ubi/README.md
  docker/images/parabol-ubi/environments/pipeline
  docker/stacks/development/docker-compose.yml
  docker/stacks/single-tenant-host/docker-compose.yml
  package.json
  packages/client/shared/gqlIds/EmbedderChannelId.ts
  packages/client/types/generics.ts
  packages/embedder/EMBEDDER_JOB_PRIORITY.ts
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/embedder/README.md
  packages/embedder/addEmbeddingsMetadata.ts
  packages/embedder/addEmbeddingsMetadataForRetrospectiveDiscussionTopic.ts
  packages/embedder/ai_models/AbstractEmbeddingsModel.ts
  packages/embedder/ai_models/AbstractGenerationModel.ts
  packages/embedder/ai_models/AbstractModel.ts
  packages/embedder/ai_models/ModelManager.ts
  packages/embedder/ai_models/OpenAIGeneration.ts
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/ai_models/TextGenerationInference.ts
  packages/embedder/custom.d.ts
  packages/embedder/embedder.ts
  packages/embedder/establishPrimaryEmbedder.ts
  packages/embedder/importHistoricalMetadata.ts
  packages/embedder/importHistoricalRetrospectiveDiscussionTopic.ts
  packages/embedder/indexing/countWords.ts
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/embedder/indexing/embeddingsTablesOps.ts
  packages/embedder/indexing/failJob.ts
  packages/embedder/indexing/getRedisClient.ts
  packages/embedder/indexing/getRootDataLoader.ts
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/iso6393To1.ts
  packages/embedder/logMemoryUse.ts
  packages/embedder/mergeAsyncIterators.ts
  packages/embedder/modules.d.ts
  packages/embedder/package.json
  packages/embedder/processJob.ts
  packages/embedder/processJobEmbed.ts
  packages/embedder/resetStalledJobs.ts
  packages/embedder/textEmbeddingsnterface.d.ts
  packages/embedder/types/modules.d.ts
  packages/embedder/types/shared.d.ts
  packages/gql-executor/RedisStream.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/publishToEmbedder.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/postgres/migrations/1703031300000_addEmbeddingTables.ts
  packages/server/postgres/migrations/1709934935000_embeddingsMetadataId.ts
  release-please-config.json
  yarn.lock
Labels: size/xl
