Repository ParabolInc/parabol, pull requests merged in 2024-01, with the labels that each got.

#9304 chore: disable autoJoin test
  packages/server/__tests__/autoJoin.test.ts
Labels: size/xs

#9303 chore: Change email summary setting copy to be clearer
  packages/client/components/EmailNotifications.tsx
Labels: size/xs

#9297 chore(meeting-inception): use retrosInDisguise flag for displaying add an activity button
  packages/client/components/DiscussionThreadInput.tsx
Labels: One Review Required, size/s

#9259 feat(kudos): send kudos by text in standups
  packages/client/components/KudosReceivedNotification.tsx
  packages/client/components/ResponseMentioned.tsx
  packages/client/modules/email/components/EmailNotifications/EmailResponseMentioned.tsx
  packages/client/mutations/AddReactjiToReactableMutation.ts
  packages/client/mutations/UpsertTeamPromptResponseMutation.ts
  packages/client/mutations/toasts/mapKudosReceivedToToast.ts
  packages/client/mutations/toasts/mapResponseMentionedToToast.ts
  packages/server/database/types/NotificationKudosReceived.ts
  packages/server/database/types/NotificationResponseMentioned.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/helpers/__tests__/getKudosUserIdsFromJson.test.ts
  packages/server/graphql/public/mutations/helpers/getKudosUserIdsFromJson.ts
  packages/server/graphql/public/mutations/helpers/publishTeamPromptMentions.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/graphql/public/typeDefs/Kudos.graphql
  packages/server/graphql/public/typeDefs/NotifyKudosReceived.graphql
  packages/server/graphql/public/typeDefs/NotifyResponseMentioned.graphql
  packages/server/graphql/public/typeDefs/upsertTeamPromptResponse.graphql
  packages/server/graphql/public/types/NotifyKudosReceived.ts
  packages/server/graphql/public/types/UpsertTeamPromptResponseSuccess.ts
  packages/server/postgres/migrations/1701679264301_storeUnicodeEmojiForKudos.ts
  packages/server/postgres/migrations/1701769672206_kudosTeamPromptResponseId.ts
Labels: size/l

#9309 chore: document SOCKET_PORT environment
  .env.example
Labels: size/xs

#9310 fix: Fix kudosSent analytics
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
Labels: size/xs

#9313 fix: add pr write permission to CI
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9315 fix: release to staging debug #4
  .github/workflows/release-to-staging.yml
Labels: size/s

#9306 chore: Convert GraphQL meeting types to use codegen
  codegen.json
  packages/server/graphql/mutations/startCheckIn.ts
  packages/server/graphql/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/typeDefs/ActionMeeting.graphql
  packages/server/graphql/public/typeDefs/AgendaItem.graphql
  packages/server/graphql/public/typeDefs/NewMeeting.graphql
  packages/server/graphql/public/typeDefs/PokerMeeting.graphql
  packages/server/graphql/public/typeDefs/RetrospectiveMeeting.graphql
  packages/server/graphql/public/typeDefs/TeamPromptMeeting.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/startCheckIn.graphql
  packages/server/graphql/public/types/ActionMeeting.ts
  packages/server/graphql/public/types/AgendaItem.ts
  packages/server/graphql/public/types/NewMeeting.ts
  packages/server/graphql/public/types/RetrospectiveMeeting.ts
  packages/server/graphql/public/types/StartCheckInSuccess.ts
  packages/server/graphql/public/types/StartRetrospectiveSuccess.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/ActionMeeting.ts
  packages/server/graphql/types/AgendaItem.ts
  packages/server/graphql/types/AutogroupReflectionGroup.ts
  packages/server/graphql/types/NewMeeting.ts
  packages/server/graphql/types/PokerMeeting.ts
  packages/server/graphql/types/RetrospectiveMeeting.ts
  packages/server/graphql/types/StartCheckInPayload.ts
  packages/server/graphql/types/StartRetrospectivePayload.ts
  packages/server/graphql/types/TeamPromptMeeting.ts
  packages/server/graphql/types/TranscriptBlock.ts
Labels: size/xl

#9321 fix: longer timeout for unplayable job
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9322 fix: gh release staging debug
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9325 fix: default to empty instead of null
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9284 feat(kudos): enable mentions in retro reflections
  packages/client/components/AndroidEditorFallback.tsx
  packages/client/components/EditorLinkChanger/EditorLinkChangerDraftjs.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionEditorWrapper.tsx
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/components/TaskEditor/useCommentPlugins.ts
  packages/client/components/TaskEditor/useLinks.tsx
  packages/client/components/TaskEditor/withEmojis.tsx
  packages/client/components/TaskEditor/withKeyboardShortcuts.tsx
  packages/client/components/TaskEditor/withMarkdown.tsx
Labels: size/l

#9318 chore: prepare start and endRetrospective for recurrence
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/startRetrospective.graphql
Labels: size/l

#9319 feat: Add custom category to activity library
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
Labels: size/s

#9330 fix: Docker build readme updated with the correct PostgreSQL version
  docker/parabol-ubi/docker-build/README.md
Labels: size/xs

#9307 chore: Update code review guidelines
  .github/pull_request_template.md
  .github/reviewers.yml
  docs/codeReview.md
Labels: size/s

#8786 feat: remove unnecessary github oauth scopes
  packages/client/types/constEnums.ts
Labels: size/xs

#9288 feat(kudos): send kudos at the end of the retro
  packages/client/components/KudosReceivedNotification.tsx
  packages/client/components/NotificationTemplate.tsx
  packages/client/mutations/toasts/mapKudosReceivedToToast.ts
  packages/server/database/types/NotificationKudosReceived.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/public/typeDefs/Kudos.graphql
  packages/server/graphql/public/typeDefs/NotifyKudosReceived.graphql
  packages/server/graphql/public/typeDefs/NotifyReqestToJoinOrg.graphql
  packages/server/graphql/public/types/Kudos.ts
  packages/server/postgres/migrations/1702642769291_isAnonymousKudos.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#9331 fix: Show correct template owner for ex-team members
  packages/server/graphql/public/types/MeetingTemplate.ts
Labels: size/xs

#9333 fix: highlight team dash in sidebar regardless of tab
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
Labels: size/s

#9223 feat: ai template recommendation
  codegen.json
  packages/client/components/ActivityLibrary/AISearch.tsx
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/mutations/GetTemplateSuggestionMutation.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/getTemplateSuggestion.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/getTemplateSuggestion.graphql
  packages/server/graphql/public/types/GetTemplateSuggestionSuccess.ts
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/types/RetrospectiveMeetingSettings.ts
  packages/server/package.json
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: size/m

#9320 fix: Allow multiple "*New Template"
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/modules/meeting/components/AddNewPokerTemplate.tsx
  packages/client/modules/meeting/components/AddNewReflectTemplate.tsx
  packages/client/modules/meeting/components/EditableTemplateName.tsx
  packages/client/mutations/AddPokerTemplateMutation.ts
  packages/client/mutations/AddReflectTemplateMutation.ts
  packages/server/graphql/mutations/addPokerTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
  packages/server/graphql/public/types/ReflectTemplate.ts
Labels: size/s

#9349 fix: gh action release switch head to version tag
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9334 feat(kudos): show snackbar when reflection with kudos created
  packages/client/mutations/CreateReflectionMutation.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
Labels: size/s

#9347 chore: Add recurring retros feature flag
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: size/s

#9351 fix: fix broken demo summary
  packages/client/modules/demo/initDB.ts
Labels: size/xs

#9350 feat: update activity library quick start
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/server/graphql/public/types/FixedActivity.ts
  packages/server/graphql/public/types/MeetingTemplate.ts
  packages/server/graphql/public/types/User.ts
Labels: size/s

#9341 chore: embedder add pgvector (and fixes)
  .github/workflows/build.yml
  packages/server/email/MailManagerDebug.ts
  packages/server/package.json
  packages/server/postgres/Dockerfile
  packages/server/postgres/extensions/install.sql
  yarn.lock
Labels: size/s

#9364 fix: support edge cases in release to prod
  .github/workflows/release-to-prod.yml
  .github/workflows/release-to-staging.yml
  .github/workflows/test.yml
Labels: size/s

#9368 fix: handle breaking syntax in pr body
  .github/workflows/release-to-prod.yml
Labels: size/xs

#9360 feat: support SERVER_SECRET rotations gracefully
  packages/client/Atmosphere.ts
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9352 chore: Prettify "Time's up" Slack message
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Labels: size/s

#9373 chore(kudos): track kudos type and meeting type in kudosSent event
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/utils/analytics/analytics.ts
Labels: Skip Maintainer Review

#9376 fix: render activity library tooltip
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
Labels: size/xs

#9382 fix: add suggested vscode extensions
  .vscode/extensions.json
Labels: size/s

#9354 feat: add notifications for mention in reflections and show kudos preview
  codegen.json
  packages/client/components/Mentioned.tsx
  packages/client/components/NotificationPicker.tsx
  packages/client/mutations/toasts/mapMentionedToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/Notification.ts
  packages/server/database/types/NotificationMentioned.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/graphql/public/typeDefs/NotifyMentioned.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/NotifyMentioned.ts
  packages/server/utils/analytics/analytics.ts
  tailwind.config.js
Labels: size/m

#9367 feat: support globs for org approvals
  packages/client/validation/regex.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/public/mutations/addApprovedOrganizationDomains.ts
  packages/server/graphql/public/mutations/helpers/getIsEmailApprovedByOrg.ts
  packages/server/graphql/public/mutations/helpers/getIsUserIdApprovedByOrg.ts
  packages/server/graphql/public/mutations/removeApprovedOrganizationDomains.ts
  packages/server/postgres/queries/getApprovedOrganizationDomainsByDomainFromPG.ts
  packages/server/postgres/queries/getApprovedOrganizationDomainsFromPG.ts
  packages/server/postgres/queries/insertApprovedOrganizationDomains.ts
  packages/server/postgres/queries/removeApprovedOrganizationDomainsToPG.ts
  packages/server/postgres/queries/src/getApprovedOrganizationDomainsByDomainsQuery.sql
  packages/server/postgres/queries/src/getApprovedOrganizationDomainsQuery.sql
  packages/server/postgres/queries/src/insertApprovedOrganizationDomainsQuery.sql
  packages/server/postgres/queries/src/removeApprovedOrganizationDomainsQuery.sql
  packages/server/postgres/queries/src/updateDomainsInOrganizationApprovedDomainQuery.sql
  packages/server/postgres/queries/updateDomainsInOrganizationApprovedDomainToPG.ts
  packages/server/utils/isEmailVerificationRequired.ts
Labels: size/m

#9385 feat: Release team insights
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/public/types/Team.ts
Labels: size/s

#9348 feat: Allow retro meeting series naming
  packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingRecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
  packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/server/__tests__/startRetrospective.test.ts
  packages/server/database/types/MeetingRetrospective.ts
  packages/server/database/types/MeetingTeamPrompt.ts
  packages/server/graphql/mutations/helpers/createMeetingSeriesTitle.ts
  packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
Labels: size/m

#9370 feat: Add meeting series end options for retros
  package.json
  packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/Categories.ts
  packages/client/components/GroupingKanban.tsx
  packages/client/components/MeetingCard.tsx
  packages/client/components/MeetingCardOptionsMenu.tsx
  packages/client/components/MeetingCardOptionsMenuRoot.tsx
  packages/client/components/NewMeeting.tsx
  packages/client/components/NewMeetingRecurrenceSettings.tsx
  packages/client/components/Recurrence/EndRecurringMeetingModal.tsx
  packages/client/components/Recurrence/HumanReadableRecurrenceRule.tsx
  packages/client/components/Recurrence/RecurrenceDayCheckbox.tsx
  packages/client/components/Recurrence/RecurrenceSettings.tsx
  packages/client/components/Recurrence/RecurrenceTimePicker.tsx
  packages/client/components/Recurrence/TimeLeftBadge.tsx
  packages/client/components/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/components/ScopePhaseArea.tsx
  packages/client/components/TeamPrompt/TeamPromptMeetingStatus.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/modules/demo/handleCompletedDemoStage.ts
  packages/client/package.json
  packages/server/__tests__/generateUID.test.ts
  packages/server/dataloader/RedisCache.ts
  packages/server/graphql/private/queries/helpers/authCount.ts
  packages/server/graphql/private/queries/helpers/authCountByDomain.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
  packages/server/package.json
  packages/server/utils/atlassian/jiraIssues.ts
  packages/server/utils/tiptap/convertToMarkdown.tsx
  yarn.lock
Labels: size/m

#9222 fix: fix recreating invite link in case of expiration
  packages/client/components/MassInvitationTokenLink.tsx
  packages/server/graphql/types/Team.ts
Labels: size/xs

#9390 fix: fix slack response replied anonymous notification
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Labels: Skip Maintainer Review, size/xs
