Repository ParabolInc/parabol, pull requests merged in 2024-05, with the labels that each got.

#9697 feat: support private S3 buckets
  .env.example
  docker/images/parabol-ubi/environments/pipeline
  docs/s3.md
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/fileStorage/README.md
  packages/server/fileStorage/S3FileStoreManager.ts
  packages/server/fileStorage/getFileStoreManager.ts
  packages/server/graphql/public/types/NotifyKudosReceived.ts
  packages/server/graphql/public/types/NotifyMentioned.ts
  packages/server/graphql/public/types/NotifyRequestToJoinOrg.ts
  packages/server/graphql/public/types/NotifyTeamsLimitExceeded.ts
  packages/server/graphql/public/types/NotifyTeamsLimitReminder.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/TeamMember.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/types/Invoice.ts
  packages/server/graphql/types/Organization.ts
  packages/server/graphql/types/TeamMember.ts
  packages/server/graphql/types/User.ts
  packages/server/package.json
  scripts/toolboxSrc/pushToCDN.ts
  yarn.lock
Labels: size/m

#9696 fix: remove oneOnOne column in Team table
  packages/server/postgres/migrations/1714579256634_removeOneOnOneTeam.ts
Labels: size/s

#9639 chore: [Snyk] Upgrade graphql from 15.7.2 to 15.8.0
  package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9703 chore: Add custom label to templates
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/RetroDrawerTemplateCard.tsx
Labels: size/s

#9705 fix: presign MeetingTemplate.illustrationUrl
  packages/server/graphql/public/types/MeetingTemplate.ts
Labels: size/xs

#9693 chore: Gracefully shutdown the embedder
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/embedder/embedder.ts
  packages/embedder/lint-staged.config.js
  packages/embedder/logMemoryUse.ts
  packages/embedder/logPerformance.ts
  packages/embedder/mergeAsyncIterators.ts
  packages/embedder/package.json
  packages/embedder/resetStalledJobs.ts
  packages/gql-executor/gqlExecutor.ts
  packages/server/server.ts
Labels: size/m

#9718 fix: remove logs from embedder
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/embedder/JobQueueError.ts
  packages/embedder/WorkflowOrchestrator.ts
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/embedder.ts
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/logPerformance.ts
  packages/embedder/workflows/embedMetadata.ts
  packages/embedder/workflows/rerankRetroTopics.ts
Labels: size/s

#9723 chore: Add some processRecurrence tracing
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: size/m

#9728 chore: add more granular process recurrence tracing
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: size/m

#9651 fix: only query templates when a user clicks the options menu
  packages/client/components/MeetingOptions.tsx
  packages/client/components/MeetingTopBar.tsx
  packages/client/components/RetroDrawer.tsx
  packages/client/components/RetroDrawerRoot.tsx
  packages/client/ui/Menu/Menu.tsx
Labels: size/m

#9736 chore: More processRecurrence tracing
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: size/m

#9708 chore: remove ai summary from discussion thread
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
Labels: size/s

#9727 feat: increase team subscription to $8
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx
  packages/client/utils/constants.ts
  packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/s

#9741 fix: Handle invitation links with invalid auth token
  packages/client/mutations/AcceptTeamInvitationMutation.ts
Labels: size/xs

#9742 fix: org admin can change team lead
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/promoteToTeamLead.ts
  packages/server/graphql/mutations/removeTeamMember.ts
Labels: size/s

#9744 fix: close websocket with reason on invalid token
  packages/client/package.json
  packages/server/socketHandlers/handleOpen.ts
  packages/server/socketHandlers/handleUpgrade.ts
  yarn.lock
Labels: size/s

#9740 fix: fix the issue where a successful upgrade won't refresh the billing page
  packages/client/mutations/handlers/upgradeToTeamTierSuccessUpdater.ts
Labels: size/xs

#9753 feat(single-tenant-host): Embedder and Text Embeddings Inference added to the stack
  .gitignore
  docker/images/parabol-ubi/README.md
  docker/stacks/single-tenant-host/README.md
  docker/stacks/single-tenant-host/docker-compose.yml
Labels: devops, size/s

#9756 chore: Trace RRule
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: size/xs

#9752 [Snyk] Upgrade @aws-sdk/client-s3 from 3.537.0 to 3.556.0
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9680 feat: add favorite activities UI to activity library
  packages/client/components/ActivityLibrary/ActivityCardFavorite.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryEmptyState.tsx
  packages/client/components/ActivityLibrary/Categories.tsx
  static/images/illustrations/favorite-empty-state.png
Labels: size/m

#9713 feat: add logic that lets users favorite a template
  codegen.json
  packages/client/components/ActivityLibrary/ActivityCardFavorite.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryEmptyState.tsx
  packages/client/components/ActivityLibrary/Categories.tsx
  packages/client/mutations/ToggleFavoriteTemplateMutation.ts
  packages/server/database/types/User.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/public/mutations/toggleFavoriteTemplate.ts
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/typeDefs/toggleFavoriteTemplate.graphql
  packages/server/graphql/public/types/ToggleFavoriteTemplateSuccess.ts
  packages/server/graphql/public/types/User.ts
  packages/server/postgres/migrations/1714598525167_addFavoriteTemplateIds.ts
Labels: size/m

#9760 fix: Send correct websocket status code
  packages/client/package.json
  packages/server/socketHandlers/handleOpen.ts
  yarn.lock
Labels: size/xs

#9763 fix: Revert @aws-sdk/client-s3 upgrade
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9739 fix: team lead can view teams in org settings
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/modules/userDashboard/components/OrgBilling/Organization.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/server/graphql/types/Organization.ts
Labels: size/s

#9770 chore: Update processRecurrence tests
  packages/server/__tests__/processRecurrence.test.ts
Labels: size/s

#9769 feat: update plan upgrade CTA label
  packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
Labels: Skip Maintainer Review, size/xs

#9767 feat: update promote team copy
  packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/types/Team.ts
Labels: size/s

#9768 feat(stripe): handle Stripe subscription events
  packages/server/billing/stripeWebhookHandler.ts
  packages/server/graphql/private/mutations/stripeDeleteSubscription.ts
  packages/server/graphql/private/mutations/stripeUpdateSubscription.ts
  packages/server/graphql/private/mutations/upgradeToTeamTier.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
Labels: size/m

#9786 feat: write equality checker to file store
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
Labels: size/s

#9797 fix: bump trebuchet-client to latest version
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9800 feat: nav style refinements
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/types/constEnums.ts
Labels: size/s

#9794 feat: Add Jira Server to Your Work
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationResults.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationResultsRoot.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraServerObjectCard.tsx
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/types/JiraServerIntegration.ts
  packages/server/graphql/types/JiraServerIssue.ts
  packages/server/integrations/jiraServer/JiraServerRestManager.ts
Labels: size/m

#9798 feat: type safety for gql perms
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/rules/getResolverDotPath.ts
  packages/server/graphql/public/rules/isOrgTier.ts
  packages/server/graphql/public/rules/isViewerBillingLeader.ts
  packages/server/graphql/public/rules/isViewerOnOrg.ts
Labels: size/s

#9805 fix: clear kudos received notifications
  packages/server/postgres/migrations/1717083323369_removeKudosNotifications.ts
Labels: size/s
