Repository ParabolInc/parabol, pull requests merged in 2024-12, with the labels that each got.

#10531 chore: clarify when Google Cloud credentials are required
  .env.example
Labels: size/xs

#10540 fix: parse draft discussions for csv
  packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
Labels: size/xs

#10533 chore: convert legacy tasks to TipTap
  packages/server/graphql/public/types/Task.ts
  packages/server/postgres/migrations/2024-11-27T00:50:24.390Z_taskContentToTipTap.ts
Labels: size/m

#10514 chore: remove teams limit
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
Labels: size/m

#10534 feat: use TipTap for the Check-in Question
  packages/client/hooks/useTipTapIcebreakerEditor.ts
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/server/database/types/CheckInPhase.ts
  packages/server/graphql/mutations/updateNewCheckInQuestion.ts
  packages/server/graphql/public/typeDefs/CheckInPhase.graphql
  packages/server/graphql/public/types/CheckInPhase.ts
Labels: size/m

#10558 feat(node): upgrade to 20.18.1, latest stable in v20
  package.json
  packages/chronos/package.json
  packages/embedder/package.json
  packages/gql-executor/package.json
  packages/server/package.json
  yarn.lock
Labels: size/s

#10557 chore: Use Logger instead of console
  packages/chronos/chronos.ts
  packages/embedder/ai_models/OpenAIGeneration.ts
  packages/embedder/ai_models/TextGenerationInference.ts
  packages/embedder/ai_models/helpers/fetchWithRetry.ts
  packages/embedder/debug.ts
  packages/embedder/logMemoryUse.ts
  packages/gql-executor/gqlExecutor.ts
  packages/server/billing/debug.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/debugJira.ts
  packages/server/email/MailManagerDebug.ts
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/fileStorage/S3FileStoreManager.ts
  packages/server/graphql/composeResolvers.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/queries/orgActivities.ts
  packages/server/hubSpot/backfillHubSpot.ts
  packages/server/jiraImagesHandler.ts
  packages/server/listenHandler.ts
  packages/server/postgres/migrations/2024-11-27T00:50:24.390Z_taskContentToTipTap.ts
  packages/server/server.ts
  packages/server/staticFileHandler.ts
  packages/server/utils/getRedisOptions.ts
  packages/server/utils/sendToSentry.ts
  packages/server/utils/serverHealthChecker.ts
  packages/server/utils/startMemwatch.js
  packages/server/utils/stripe/StubStripeManager.ts
  scripts/buildServers.js
  scripts/generateGraphQLArtifacts.js
  scripts/prod.js
  scripts/runSchemaUpdater.ts
  scripts/toolboxSrc/assignSURole.ts
  scripts/toolboxSrc/pgEnsureExtensions.ts
  scripts/toolboxSrc/pgRestore.ts
  scripts/toolboxSrc/primeIntegrations.ts
  scripts/toolboxSrc/pushToCDN.ts
  scripts/toolboxSrc/setIsEnterprise.ts
Labels: size/m

#10563 fix: tasks in poker scoping
  packages/client/components/ParabolScopingSearchResultItem.tsx
  packages/client/components/ParabolScopingSearchResults.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
  packages/client/components/promptResponse/TipTapLinkMenu.tsx
  packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
  packages/client/mutations/handlers/handleUpsertTasks.ts
Labels: size/s

#10546 feat: improve reflection group titles
  packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
  packages/client/mutations/EndDraggingReflectionMutation.ts
  packages/server/graphql/mutations/helpers/generateAIGroupTitle.ts
  packages/server/graphql/mutations/helpers/updateGroupTitle.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
  packages/server/graphql/mutations/updateReflectionContent.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/m

#10566 chore: Catch server health checker errors
  packages/server/listenHandler.ts
  packages/server/utils/serverHealthChecker.ts
Labels: size/xs

#10542 chore: Migration checkInQuestion to tiptap format
  packages/server/postgres/migrations/2024-12-05T13:40:14.859Z_checkinToTipTap.ts
Labels: size/m

#10580 chore: Properly ignore supposedly ignored errors
  packages/client/Atmosphere.ts
  packages/client/components/ActionMeetingSidebar.tsx
  packages/client/components/ActionSidebarAgendaItemsSection.tsx
  packages/client/components/AnalyticsPage.tsx
  packages/client/components/AtmosphereProvider/AtmosphereProvider.tsx
  packages/client/components/AuthProvider.tsx
  packages/client/components/MassInvitationTokenLink.tsx
  packages/client/components/MeetingSidebarTeamMemberStageItems.tsx
  packages/client/components/PokerMeetingSidebar.tsx
  packages/client/components/PokerSidebarEstimateSection.tsx
  packages/client/components/RetroMeetingSidebar.tsx
  packages/client/components/RetroSidebarDiscussSection.tsx
  packages/client/components/TeamInvitationSSO.tsx
  packages/client/hooks/useAutoCheckIn.ts
  packages/client/hooks/useGotoNext.ts
  packages/client/hooks/useGotoPrev.ts
  packages/client/hooks/useSVG.ts
  packages/client/hooks/useServiceWorkerUpdater.ts
  packages/client/hooks/useSlackChannels.ts
  packages/client/hooks/useSubscription.ts
  packages/client/hooks/useTrebuchetEvents.ts
  packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/subscribeGraphQL.ts
Labels: size/m

#10585 fix: add useEventCallback on keyboard shortcuts
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/ThreadedCommentBase.tsx
Labels: size/s

#10596 fix: Discussion bugs
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/hooks/useTipTapCommentEditor.ts
  packages/client/mutations/UpdateTaskMutation.ts
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
Labels: size/s

#10593 fix: Refresh the SAML request URL for each login attempt
  packages/client/Atmosphere.ts
  packages/client/components/EmailPasswordAuthForm.tsx
  packages/client/utils/getSAMLIdP.ts
  packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/postgres/migrations/2024-12-12T08:40:19.695Z_removeURLFromSAML.ts
  packages/server/utils/getSAMLURLFromEmail.ts
Labels: size/s

#10609 fix: Parabol poker task overwrites, ignore prototypes for equality check on tiptap
  packages/client/components/ParabolScopingSearchResultItem.tsx
  packages/client/components/PokerEstimateHeaderCardParabol.tsx
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/ThreadedCommentBase.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/hooks/useTipTapEditorContent.ts
  packages/client/hooks/useTipTapTaskEditor.ts
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
  packages/client/shared/isEqualWhenSerialized.ts
Labels: size/m

#10608 feat: remove sso without emailing all users
  packages/server/graphql/mutations/helpers/processEmailPasswordReset.ts
  packages/server/graphql/private/mutations/removeAuthIdentity.ts
  packages/server/graphql/private/typeDefs/Mutation.graphql
Labels: size/s

#10584 chore: migrate existing comments to TipTap
  packages/server/graphql/public/types/Comment.ts
  packages/server/postgres/migrations/2024-12-13T23:03:51.369Z_commentsToTipTap.ts
Labels: size/m

#10618 feat: get saml config for domain
  packages/server/graphql/private/queries/getSAMLForDomain.ts
  packages/server/graphql/private/typeDefs/GetSAMLForDomainPayload.graphql
  packages/server/graphql/private/typeDefs/GetSAMLForDomainSuccess.graphql
  packages/server/graphql/private/typeDefs/Query.graphql
Labels: size/s

#10568 feat: update suggest group titles
  packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
  packages/client/mutations/AutogroupMutation.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/s

#10623 fix: Comments in demo meeting
  packages/client/modules/demo/commentLookup.ts
  packages/client/modules/demo/initDB.ts
Labels: size/xs

#10582 fix: correct graphql.config.js
  .vscode/extensions.json
  graphql.config.js
Labels: size/s
