Repository ParabolInc/parabol, pull requests merged in 2024-06, with the labels that each got.

#9812 fix: remove custom activity badge
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
  packages/client/components/RetroDrawerTemplateCard.tsx
Labels: size/s

#9801 chore: read ReflectionGroups from PG
  codegen.json
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/embedder/workflows/helpers/publishSimilarRetroTopics.ts
  packages/server/database/rethinkDriver.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/helpers/generateDiscussionPrompt.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/removeEmptyReflectionGroup.ts
  packages/server/graphql/mutations/helpers/removeEmptyReflections.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safelyCastVote.ts
  packages/server/graphql/mutations/helpers/safelyWithdrawVote.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/updateSmartGroupTitle.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/mutations/updateReflectionGroupTitle.ts
  packages/server/graphql/mutations/voteForReflectionGroup.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/graphql/public/types/RetroReflectionGroup.ts
  packages/server/graphql/public/types/RetrospectiveMeeting.ts
Labels: size/m

#9780 feat: security banner concept
  .env.example
  packages/client/components/Action/Action.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/AuthPage/Header.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/EstimatePhaseDiscussionDrawer.tsx
  packages/client/components/GlobalBanner.tsx
  packages/client/components/NewMeetingSidebar.tsx
  packages/client/components/TeamInvitationMeetingAbstract.tsx
  packages/client/components/TeamInvitationWrapper.tsx
  packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
  packages/client/components/TimelineRightDrawer.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/teamDashboard/components/TeamDashMain/TeamDrawer.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlanDrawer.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlanDrawerContent.tsx
  packages/client/types/constEnums.ts
  packages/client/types/modules.d.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
  tailwind.config.js
Labels: size/m

#9807 chore: refactor ReflectionGroup to SDL pattern
  packages/client/mutations/AutogroupMutation.ts
  packages/client/mutations/EndDraggingReflectionMutation.ts
  packages/client/mutations/ResetReflectionGroupsMutation.ts
  packages/server/graphql/composeResolvers.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/types/RetroReflectionGroup.ts
  packages/server/graphql/types/RetroReflectionGroup.ts
Labels: size/m

#9831 fix: Add teamId index to SuggestedAction
  packages/server/database/rethinkDriver.ts
  packages/server/postgres/migrations/1717685812675_addSuggestedActionTeamIdIndex.ts
  packages/server/safeMutations/safeArchiveTeam.ts
Labels: size/s

#9819 fix: Retry S3 upload after cloudflare error
  packages/server/fileStorage/S3FileStoreManager.ts
Labels: size/s

#9829 feat: Update MeetingTemplate.updatedAt on prompt changes
  packages/server/database/rethinkDriver.ts
  packages/server/graphql/mutations/addPokerTemplateDimension.ts
  packages/server/graphql/mutations/addPokerTemplateScaleValue.ts
  packages/server/graphql/mutations/addReflectTemplatePrompt.ts
  packages/server/graphql/mutations/movePokerTemplateDimension.ts
  packages/server/graphql/mutations/movePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/moveReflectTemplatePrompt.ts
  packages/server/graphql/mutations/reflectTemplatePromptUpdateDescription.ts
  packages/server/graphql/mutations/reflectTemplatePromptUpdateGroupColor.ts
  packages/server/graphql/mutations/removePokerTemplateDimension.ts
  packages/server/graphql/mutations/removePokerTemplateScale.ts
  packages/server/graphql/mutations/removePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/removeReflectTemplatePrompt.ts
  packages/server/graphql/mutations/renamePokerTemplateDimension.ts
  packages/server/graphql/mutations/renamePokerTemplateScale.ts
  packages/server/graphql/mutations/renameReflectTemplatePrompt.ts
  packages/server/graphql/mutations/updatePokerTemplateDimensionScale.ts
  packages/server/graphql/mutations/updatePokerTemplateScaleValue.ts
  packages/server/postgres/migrations/1717685812676_addPokerTemplateScaleDimensionScaleIdIndex.ts
Labels: size/m

#9824 fix: hide ai icebreaker ui for non ai users
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/client/types/modules.d.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
Labels: size/xs

#9776 feat: Create embeddings for meeting templates
  packages/embedder/addEmbeddingsMetadataForMeetingTemplate.ts
  packages/embedder/importHistoricalMeetingTemplates.ts
  packages/embedder/importHistoricalMetadata.ts
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/embedder/indexing/meetingTemplate.ts
  packages/embedder/insertMeetingTemplatesIntoMetadataAndQueue.ts
  packages/server/postgres/migrations/1717685812677_addMeetingTemplateEmbedding.ts
Labels: size/m

#9845 feat: new nav styles refinement
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
Labels: size/m

#9844 feat: add menu to dashboard nav
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/MeetingOptions.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuContent.tsx
Labels: size/m

#9841 feat: update admin dashboard mobile styles
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/LeftDashNavParabol.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MeetingOptions.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/NextPeriodChargesLineItem.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationDetails.tsx
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/utils/sortByTier.ts
Labels: size/m

#9835 feat: add public teams dialog to dash nav
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/DashNavList/PublicTeamItem.tsx
  packages/client/components/DashNavList/PublicTeamsModal.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/LeftDashNavParabol.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MeetingOptions.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/NextPeriodChargesLineItem.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationDetails.tsx
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/utils/sortByTier.ts
  packages/server/graphql/types/Organization.ts
Labels: size/l

#9818 feat: promote Add Team in org nav dash
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/DashNavList/PublicTeamItem.tsx
  packages/client/components/DashNavList/PublicTeamsModal.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/LeftDashNavParabol.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MeetingOptions.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/NextPeriodChargesLineItem.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationDetails.tsx
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/utils/sortByTier.ts
  packages/server/graphql/types/Organization.ts
Labels: size/s

#9815 feat: update org nav dashboard styles
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/DashNavList/PublicTeamItem.tsx
  packages/client/components/DashNavList/PublicTeamsModal.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/LeftDashNavParabol.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MeetingOptions.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/NextPeriodChargesLineItem.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationDetails.tsx
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/utils/sortByTier.ts
  packages/server/graphql/types/Organization.ts
Labels: size/l

#9795 feat: update dashboard nav item styles
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/DashNavList/PublicTeamItem.tsx
  packages/client/components/DashNavList/PublicTeamsModal.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/LeftDashNavParabol.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MeetingOptions.tsx
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/modules/invoice/components/InvoiceLineItem/NextPeriodChargesLineItem.tsx
  packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/Organization/OrganizationDetails.tsx
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/client/types/constEnums.ts
  packages/client/ui/Menu/Menu.tsx
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/utils/sortByTier.ts
  packages/server/graphql/types/Organization.ts
Labels: size/l

#9838 feat: Add MeetingTemplate update embeddings trigger
  packages/embedder/ai_models/AbstractEmbeddingsModel.ts
  packages/embedder/getEmbedderPriority.ts
  packages/embedder/insertDiscussionsIntoMetadataAndQueue.ts
  packages/embedder/insertMeetingTemplatesIntoMetadataAndQueue.ts
  packages/server/postgres/migrations/1718014847553_getEmbedderPriority.ts
  packages/server/postgres/migrations/1718014858965_updateEmbeddingOnMeetingTemplateUpdate.ts
Labels: size/s

#9848 fix: add meeting block is now 70px
  packages/client/components/Dashboard/DashSidebar.tsx
Labels: size/xs

#9853 chore: Update MeetingTemplate embeddings on insert
  packages/server/postgres/migrations/1718014858965_updateEmbeddingOnMeetingTemplateUpdate.ts
Labels: size/xs

#9854 chore: Avoid undefined in embeddings for Poker scales
  packages/embedder/indexing/meetingTemplate.ts
Labels: size/xs

#9850 chore(ci): release-to jobs for both staging and production will notify Slack whenever they fail
  .github/workflows/release-to-prod.yml
  .github/workflows/release-to-staging.yml
Labels: devops, size/s

#9857 chore: Update fullText when embedding is older than reference
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/embedder/workflows/embedMetadata.ts
Labels: size/s

#9849 fix: update promote team member copy
  packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx
Labels: size/xs

#9859 fix: clicking scope link does not affect checkbox
  packages/client/components/ScopingSearchResultItem.tsx
Labels: size/s

#9851 chore: remove summary from retro reflection group
  packages/server/database/types/ReflectionGroup.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/postgres/migrations/1718641323037_removeSummaryFromRetroGroup.ts
Labels: size/s

#9856 fix: remove AI UI if user doesn't have access to AI
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
Labels: size/s

#9865 fix: ensure dashboard sidebar animates smoothly
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/ui/Menu/MenuContent.tsx
Labels: size/s

#9820 chore(rethinkdb): RetroReflection: Phase 1
  package.json
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/server/database/types/Reflection.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/helpers/calculateEngagement.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/removeEmptyReflectionGroup.ts
  packages/server/graphql/mutations/helpers/removeEmptyReflections.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
  packages/server/graphql/mutations/removeReflection.ts
  packages/server/graphql/mutations/updateReflectionContent.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/types/RetroReflection.ts
  packages/server/postgres/migrations/1717096624786_RetroReflection-phase1.ts
  yarn.lock
Labels: size/m

#9834 chore(rethinkdb): RetroReflection: Phase 2
  packages/client/utils/constants.ts
  packages/server/graphql/mutations/helpers/autoGroup/sanitizeAnalyzedEntititesResponse.ts
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/postgres/migrations/1714598525167_addFavoriteTemplateIds.ts
  packages/server/postgres/migrations/1716914102795_removeKudos.ts
  packages/server/postgres/migrations/1716995191300_allowGlobalOAuth1Provider.ts
  packages/server/postgres/migrations/1719162354561_RetroReflection-phase2.ts
  packages/server/postgres/migrations/1719262354561_reactji-rename.ts
  packages/server/postgres/queries/getTeamPromptResponsesByIds.ts
  packages/server/postgres/utils/checkEqBase.ts
  packages/server/postgres/utils/rethinkEqualityFns.ts
Labels: size/m

#9877 fix: Don't reset failed embedding jobs
  packages/embedder/resetStalledJobs.ts
Labels: size/xs

#9867 chore(rethinkdb): RetroReflection: Phase 3
  codegen.json
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/client/types/generics.ts
  packages/client/utils/smartGroup/groupReflections.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/GoogleAnalyzedEntity.ts
  packages/server/database/types/Reactable.ts
  packages/server/database/types/Reflection.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/removeEmptyReflections.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
  packages/server/graphql/mutations/removeReflection.ts
  packages/server/graphql/mutations/updateReflectionContent.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/typeDefs/Reactji.graphql
  packages/server/graphql/public/typeDefs/RetroReflection.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/NotifyMentioned.ts
  packages/server/graphql/public/types/Reactji.ts
  packages/server/graphql/public/types/RetroReflection.ts
  packages/server/graphql/public/types/RetroReflectionGroup.ts
  packages/server/graphql/resolvers.ts
  packages/server/graphql/types/Reactji.ts
  packages/server/graphql/types/RetroReflection.ts
  packages/server/graphql/types/User.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/getGroupedReactjis.ts
Labels: size/xl

#9679 fix: refactor new meeting team dropdown
  packages/client/components/ActivityLibrary/ActivityCardFavorite.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/TeamPickerModal.tsx
  packages/client/components/DropdownToggleInner.tsx
  packages/client/components/DropdownToggleV2.tsx
  packages/client/components/NewMeetingDropdown.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/components/SelectMeetingDropdown.tsx
  packages/client/package.json
  packages/client/tailwindTheme.ts
  yarn.lock
Labels: size/l

#9871 chore(rethinkdb): TimelineEvent: Phase 1
  packages/client/components/SelectMeetingDropdownItem.tsx
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/archiveTimelineEvent.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/postgres/migrations/1719348524673_TimelineEvent-phase1.ts
  packages/server/postgres/queries/insertUser.ts
  packages/server/postgres/queries/src/insertTeamQuery.sql
  packages/server/postgres/queries/src/insertUserQuery.sql
Labels: size/m

#9884 fix: handle sql null equalities
  packages/server/graphql/mutations/helpers/updateReflectionLocation/updateSmartGroupTitle.ts
Labels: size/xs

#9875 chore(rethinkdb): TimelineEvent: Phase 2
  packages/server/postgres/migrations/1719351990570_TimelineEvent-phase2.ts
Labels: size/m

#9880 fix: can scroll public teams modal
  packages/client/components/DashNavList/PublicTeamsModal.tsx
Labels: Skip Maintainer Review, size/xs

#9889 fix: download pdf shows multiple pages
  packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailReflectionCard.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Labels: size/s

#9893 fix: User can change team in Activity Library
  packages/client/components/NewMeetingActionsCurrentMeetings.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
Labels: size/s

#9876 chore(rethinkdb): TimelineEvent: Phase 3
  packages/server/database/rethinkDriver.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/archiveTimelineEvent.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/types/User.ts
Labels: size/m

#9898 fix: timeline ordering
  packages/server/graphql/types/User.ts
Labels: size/xs

#9903 chore: remove contact us message for team users that want to downgrade
  packages/client/modules/userDashboard/components/OrgBilling/OrgBillingDangerZone.tsx
Labels: size/s
