Repository ParabolInc/parabol, pull requests merged in 2024-10, with the labels that each got.

#10282 fix: Fix crash in end checkin without pinned agenda items
  packages/server/graphql/mutations/endCheckIn.ts
Labels: size/xs

#10266 chore(rethinkdb): NewMeeting: Phase 2
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/postgres/migrations/1726602922665_NewMeeting-phase2.ts
  packages/server/postgres/utils/checkEqBase.ts
  packages/server/postgres/utils/rethinkEqualityFns.ts
Labels: size/m

#10279 feat(misc): add timer control to more meeting phases
  packages/client/components/ActionMeetingAgendaItems.tsx
  packages/client/components/ActionMeetingUpdates.tsx
  packages/client/components/MeetingControlBar.tsx
  packages/client/components/PokerEstimatePhase.tsx
  packages/client/utils/showTimerInPhase.ts
Labels: size/s

#10295 fix: endTeamPrompt bugs
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/public/types/MeetingSeries.ts
Labels: size/xs

#10293 chore: migrate noaisummary flag
  packages/server/postgres/migrations/1727885996466_migrateFeatureFlags.ts
Labels: size/s

#10304 chore: improve feature flag error feedback
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/private/mutations/applyFeatureFlag.ts
  packages/server/graphql/public/typeDefs/FeatureFlag.graphql
  packages/server/graphql/public/typeDefs/FeatureFlagScope.graphql
Labels: size/s

#10270 chore: remove team insights
  codegen.json
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/MeetingEngagementCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
  packages/client/mutations/EndCheckInMutation.ts
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/mutations/EndSprintPokerMutation.ts
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/client/shared/gqlIds/TeamInsightsId.ts
  packages/client/shared/gqlIds/TopRetroTemplateId.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
  packages/server/graphql/private/typeDefs/OrganizationFeatureFlagsEnum.graphql
  packages/server/graphql/public/typeDefs/MeetingEngagement.graphql
  packages/server/graphql/public/typeDefs/OrganizationFeatureFlags.graphql
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/TeamInsights.graphql
  packages/server/graphql/public/typeDefs/TopRetroTemplate.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/public/types/TopRetroTemplate.ts
  packages/server/postgres/migrations/1727719017181_removeTeamInsights.ts
  packages/server/postgres/select.ts
Labels: size/l

#10301 fix(webserver): exits with code 0 when SIGTERM is handled
  packages/server/server.ts
  packages/server/socketHandlers/handleDisconnect.ts
Labels: size/xs

#10289 chore(rethinkdb): MeetingMember: Phase 1
  codegen.json
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/ActionMeetingMember.ts
  packages/server/database/types/MeetingMember.ts
  packages/server/database/types/PokerMeetingMember.ts
  packages/server/database/types/RetroMeetingMember.ts
  packages/server/database/types/TeamPromptMeetingMember.ts
  packages/server/dataloader/NullableDataLoader.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/helpers/safelyCastVote.ts
  packages/server/graphql/mutations/helpers/safelyWithdrawVote.ts
  packages/server/graphql/mutations/helpers/sendPokerMeetingRevoteEvent.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/pokerRevealVotes.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/mutations/setPokerSpectate.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/updateRetroMaxVotes.ts
  packages/server/graphql/mutations/voteForReflectionGroup.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/types/ActionMeeting.ts
  packages/server/graphql/public/types/MeetingSeries.ts
  packages/server/graphql/public/types/RetrospectiveMeeting.ts
  packages/server/graphql/public/types/TeamMember.ts
  packages/server/graphql/public/types/User.ts
  packages/server/postgres/migrations/1727893031268_MeetingMember-phase1.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/Meeting.d.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/helpers.ts
Labels: size/l

#10294 chore(rethinkdb): MeetingMember: Phase 2
  packages/server/postgres/migrations/1727995266026_MeetingMember-phase2.ts
Labels: size/l

#10316 fix: timeRemaining
  packages/server/graphql/public/types/NewMeetingStage.ts
Labels: size/s

#10320 fix: catch error if user tries to join meeting twice
  packages/client/hooks/useAutoCheckIn.ts
  packages/server/graphql/mutations/joinMeeting.ts
Labels: size/s

#10324 chore: update snyk workflow to use node20
  .github/workflows/synk-yarn-lock-commit.yml
Labels: Skip Maintainer Review, size/xs

#10311 chore(rethinkdb): MassInvitation: OneShot
  packages/server/database/rethinkDriver.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/createMassInvitation.ts
  packages/server/graphql/types/Team.ts
  packages/server/postgres/migrations/1728411506375_MassInvitation-1shot.ts
  packages/server/postgres/select.ts
Labels: size/m

#10312 chore(rethinkdb): NewFeature: OneShot
  codegen.json
  packages/server/database/types/User.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/private/mutations/addNewFeature.ts
  packages/server/graphql/public/types/NewFeatureBroadcast.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/types/NewFeatureBroadcast.ts
  packages/server/postgres/migrations/1728418948136_NewFeature-oneshot.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
Labels: size/m

#10325 chore(rethinkdb): TeamInvitation: Phase 1
  codegen.json
  packages/server/database/rethinkDriver.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/handleMassInviteToken.ts
  packages/server/graphql/mutations/helpers/handleTeamInviteToken.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/public/types/AcceptTeamInvitationPayload.ts
  packages/server/postgres/migrations/1728425112300_TeamInvitation-phase1.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safeMutations/safeArchiveTeam.ts
  packages/server/utils/getBestInvitationMeeting.ts
Labels: size/m

#10327 chore(rethinkdb): TeamInvitation: Phase 3
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/TeamInvitation.ts
  packages/server/dataloader/RethinkDBCache.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/handleMassInviteToken.ts
  packages/server/graphql/mutations/helpers/handleTeamInviteToken.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/queries/verifiedInvitation.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safeMutations/safeArchiveTeam.ts
Labels: size/m

#10343 fix(dd-trace): upgrade to v5.0.0
  packages/embedder/package.json
  packages/gql-executor/package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#10345 chore: remove old invite notifications
  packages/server/postgres/migrations/1728496980486_removeOldInviteNotifs.ts
Labels: size/s

#10348 chore(deployment): PR title for the PR that deploys to production states its purpose
  .github/workflows/release-to-staging.yml
Labels: size/xs

#10336 chore(rethinkdb): Task: Phase 1
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/changeTaskTeam.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/createTaskIntegration.ts
  packages/server/graphql/mutations/deleteTask.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/addSeedTasks.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/importTasksForPoker.ts
  packages/server/graphql/mutations/helpers/removeEmptyTasks.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
  packages/server/graphql/mutations/updateTask.ts
  packages/server/graphql/mutations/updateTaskDueDate.ts
  packages/server/postgres/migrations/1728578190454_Task-phase1.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/TaskIntegration.d.ts
  packages/server/safeMutations/archiveTasksForDB.ts
Labels: size/m

#10338 chore(rethinkdb): Task: Phase 2
  packages/server/postgres/migrations/1728595090540_Task-phase2.ts
Labels: size/m

#10254 feat: add Insights UI skeleton
  packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamDashInsightsTab.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsights.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsightsRoot.tsx
  packages/client/modules/teamDashboard/components/TeamDashMain/TeamDashMain.tsx
Labels: size/m

#10283 feat: show default insight
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
  packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsightContent.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsightEmptyState.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsights.tsx
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/mutations/GenerateInsightMutation.ts
  packages/client/shared/gqlIds/InsightId.ts
  packages/client/styles/theme/global.css
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/public/mutations/generateInsight.ts
  packages/server/graphql/public/typeDefs/GenerateInsightPayload.graphql
  packages/server/graphql/public/typeDefs/GenerateInsightSuccess.graphql
  packages/server/graphql/public/typeDefs/Insight.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/generateInsight.graphql
  packages/server/graphql/public/types/GenerateInsightSuccess.ts
  packages/server/graphql/public/types/Team.ts
  packages/server/postgres/migrations/1728596433080_addMeetingsCountToInsight.ts
  packages/server/postgres/types/index.d.ts
  static/images/illustrations/insights-empty-state.png
Labels: size/m

#10319 chore: remove feature flag owner
  codegen.json
  packages/server/graphql/private/mutations/removeFeatureFlagOwner.ts
  packages/server/graphql/private/typeDefs/Mutation.graphql
  packages/server/graphql/private/typeDefs/RemoveFeatureFlagOwnerSuccess.graphql
  packages/server/graphql/private/typeDefs/RemoveFeatureFlagPayload.graphql
  packages/server/graphql/private/types/RemoveFeatureFlagOwnerSuccess.ts
Labels: size/m

#10253 feat(orgAdmin): Add org admin teaser in org team page for non-enterprise orgs
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/OrgTeams/TeaserOrgTeamsRow.tsx
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/Organization.ts
Labels: size/s

#10362 fix: correct serialization of Task.content
  packages/server/postgres/migrations/1728596434080_Task-phase2fixup.ts
Labels: size/s

#10350 chore(rethinkdb): Notification: Phase 1
  packages/server/billing/helpers/removeTeamsLimitObjects.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/database/types/NotificationPaymentRejected.ts
  packages/server/database/types/processTeamsLimitsJob.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/publishChangeNotifications.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/setNotificationStatus.ts
  packages/server/graphql/private/mutations/__tests__/intranetJobsQuery.test.js
  packages/server/graphql/private/mutations/runScheduledJobs.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
  packages/server/graphql/public/mutations/addComment.ts
  packages/server/graphql/public/mutations/helpers/publishTeamPromptMentions.ts
  packages/server/graphql/public/mutations/requestToJoinDomain.ts
  packages/server/graphql/public/mutations/setOrgUserRole.ts
  packages/server/postgres/migrations/1728596443080_Notification-phase1.ts
  packages/server/postgres/queries/updateMeetingTemplateOrgId.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/Notification.d.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/utils/sendPromptToJoinOrg.ts
Labels: size/m

#10359 chore(rethinkdb): Add missing foreign key constraints
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/graphql/mutations/helpers/createNewOrg.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/postgres/helpers/insertOrgUserAudit.ts
  packages/server/postgres/migrations/1729110751093_pgSchemaFixups.ts
  packages/server/postgres/queries/src/insertOrgUserAuditQuery.sql
Labels: size/m

#10342 feat: insights feedback functionality
  packages/client/hooks/useManualClientSideTrack.ts
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/FeedbackModal.tsx
  packages/server/utils/analytics/analytics.ts
Labels: size/s

#10373 fix: complete partial value for updateTaskPayload
  packages/server/graphql/public/types/UpdateTaskPayload.ts
Labels: size/s

#10380 fix: no duplicate notification inserts
  packages/server/graphql/mutations/helpers/publishChangeNotifications.ts
Labels: size/s

#10382 chore: Add migration for shared secret integration provider
  packages/server/postgres/migrations/1729269619262_addSharedSecretIntegrationProvider.ts
Labels: size/s

#10260 chore: remove usage stats
  codegen.json
  packages/client/components/Dashboard.tsx
  packages/client/components/Insights.tsx
  packages/client/components/InsightsCharts.tsx
  packages/client/components/InsightsDomainNudge.tsx
  packages/client/components/InsightsDomainPanel.tsx
  packages/client/components/InsightsRoot.tsx
  packages/client/components/NotificationPicker.tsx
  packages/client/components/PinnedSnackbarNotifications.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/components/StandardHubUserMenu.tsx
  packages/client/components/TeamsLimitExceededNotification.tsx
  packages/client/hooks/useUsageSnackNag.ts
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/MeetingEngagementCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgStats.tsx
  packages/client/mutations/EndCheckInMutation.ts
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/mutations/EndSprintPokerMutation.ts
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/client/mutations/toasts/mapTeamsLimitExceededToToast.ts
  packages/client/mutations/toasts/popNotificationToast.ts
  packages/client/shared/gqlIds/TeamInsightsId.ts
  packages/client/shared/gqlIds/TopRetroTemplateId.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/helpers/updateTeamInsights.ts
  packages/server/graphql/public/typeDefs/MeetingEngagement.graphql
  packages/server/graphql/public/typeDefs/NotificationEnum.graphql
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/TeamInsights.graphql
  packages/server/graphql/public/typeDefs/TopRetroTemplate.graphql
  packages/server/graphql/public/types/NotifyTeamsLimitExceeded.ts
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/public/types/TopRetroTemplate.ts
  packages/server/postgres/migrations/1729899017181_removeTeamInsights.ts
  packages/server/postgres/select.ts
Labels: size/xl

#10341 feat: add insights feedback UI modal
  packages/client/hooks/useManualClientSideTrack.ts
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/FeedbackModal.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsights.tsx
  packages/server/postgres/migrations/1729696433080_addMeetingsCountToInsight.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/m

#10383 fix: Crash when starting a checkin with agenda items
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
Labels: size/s

#10386 fix: if not exists on meetingsCount
  packages/server/postgres/migrations/1729696433080_addMeetingsCountToInsight.ts
Labels: size/xs

#10394 chore: super user can generate insight
  packages/server/graphql/public/mutations/generateInsight.ts
Labels: size/xs

#10398 chore: remove kysely-ctl from prod bundle
  .config/kysely.config.ts
  .config/kyselyMigrations.ts
  scripts/toolboxSrc/standaloneMigrations.ts
Labels: size/s

#10401 fix: apply imports transform
  scripts/webpack/utils/transformRules.js
Labels: size/xs

#10361 chore: Add Mattermost Plugin IntegrationProvider
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/graphql/mutations/addIntegrationProvider.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/public/typeDefs/AddIntegrationProviderInput.graphql
  packages/server/graphql/public/typeDefs/IntegrationProviderMetadataInputSharedSecret.graphql
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/AddIntegrationProviderInput.ts
  packages/server/graphql/types/IntegrationProviderAuthStrategyEnum.ts
  packages/server/graphql/types/IntegrationProviderMetadataInputSharedSecret.ts
  packages/server/graphql/types/IntegrationProviderSharedSecret.ts
  packages/server/postgres/queries/getIntegrationProvidersByIds.ts
Labels: size/m

#10405 feat: show insights by default
  packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
Labels: size/s

#10414 fix: small bugs found in datadog logs
  codegen.json
  packages/client/components/NotificationPicker.tsx
  packages/client/components/TeamsLimitExceededNotification.tsx
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/public/typeDefs/IntegrationProviderAuthStrategyEnum.graphql
  packages/server/graphql/public/typeDefs/NotificationEnum.graphql
  packages/server/graphql/public/types/EstimateStage.ts
  packages/server/graphql/public/types/NewMeetingStage.ts
  packages/server/graphql/public/types/NotifyTeamsLimitExceeded.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/types/NotificationEnum.ts
  packages/server/utils/atlassian/jiraImages.ts
Labels: size/m

#10407 [Snyk] Upgrade @radix-ui/react-alert-dialog from 1.1.1 to 1.1.2
  packages/client/package.json
  yarn.lock
Labels: size/xs

#10424 fix: support pg tracing in dd-trace-js
  .gitignore
  package.json
  packages/embedder/addEmbeddingsMetadataForMeetingTemplate.ts
  packages/embedder/addEmbeddingsMetadataForRetrospectiveDiscussionTopic.ts
  packages/embedder/ai_models/AbstractEmbeddingsModel.ts
  packages/embedder/custom.d.ts
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/database/types/MeetingTemplate.ts
  packages/server/dataloader/__tests__/isOrgVerified.test.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/removeScheduledJobs.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/updatePokerScope.ts
  packages/server/graphql/private/mutations/runScheduledJobs.ts
  packages/server/graphql/public/types/RetroReflectionGroup.ts
  packages/server/graphql/public/types/SAML.ts
  packages/server/postgres/getKysely.ts
  packages/server/postgres/getPg.ts
  packages/server/postgres/pg.ts
  packages/server/postgres/types/Meeting.d.ts
  packages/server/postgres/types/Notification.d.ts
  packages/server/postgres/types/index.d.ts
  packages/server/safeMutations/removeSuggestedAction.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  scripts/prod.js
  scripts/webpack/prod.servers.config.js
Labels: size/m

#10426 fix: TeamMemberIntegrationAuth single fetch
  packages/embedder/embedder.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/dataloader/gcalLoaders.ts
  packages/server/dataloader/gitlabLoaders.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/graphql/mutations/helpers/createAzureTask.ts
  packages/server/graphql/mutations/helpers/createGitLabTask.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/integrations/gitlab/GitLabServerManager.ts
  packages/server/integrations/jiraServer/JiraServerRestManager.ts
  packages/server/postgres/queries/getTeamMemberIntegrationAuth.ts
  packages/server/postgres/queries/src/getTeamMemberIntegrationAuthQuery.sql
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/m

#10429 fix: latestMeeting query
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
Labels: size/s

#10432 chore(metrics): add metrics to identify who attempte to upgrade organization
  packages/server/graphql/public/mutations/createStripeSubscription.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/xs

#10396 feat(orgAdmins): show total user & team counts
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgUsage.tsx
  packages/client/modules/userDashboard/components/OrganizationRow/OrganizationRow.tsx
Labels: size/s

#10439 fix: throw on migration error
  scripts/toolboxSrc/preDeploy.ts
  scripts/toolboxSrc/standaloneMigrations.ts
Labels: size/s
