Repository ParabolInc/parabol, pull requests merged in 2024-04, with the labels that each got.

#9582 fix: embedder doesn't dive deep into schema
  packages/embedder/types/shared.d.ts
  packages/server/database/rethinkDriver.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/private/mutations/runScheduledJobs.ts
  packages/server/graphql/public/rootSchema.ts
  packages/server/integrations/gitlab/GitLabServerManager.ts
  packages/server/postgres/types/Meeting.d.ts
  packages/server/types/custom.d.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/getGitHubRequest.ts
  tsconfig.base.json
Labels: size/s

#9584 fix: embedder errors in embed length
  package.json
  packages/client/package.json
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/embedder/addEmbeddingsMetadataForRetrospectiveDiscussionTopic.ts
  packages/embedder/ai_models/AbstractEmbeddingsModel.ts
  packages/embedder/ai_models/AbstractGenerationModel.ts
  packages/embedder/ai_models/AbstractModel.ts
  packages/embedder/ai_models/ModelManager.ts
  packages/embedder/ai_models/OpenAIGeneration.ts
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/ai_models/TextGenerationInference.ts
  packages/embedder/embedder.ts
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/package.json
  packages/embedder/processJobEmbed.ts
  packages/embedder/textEmbeddingsnterface.d.ts
  packages/integration-tests/package.json
  packages/server/package.json
  yarn.lock
Labels: size/xl

#9586 fix: Fetch CORS resources from network
  packages/client/serviceWorker/sw.ts
Labels: size/xs

#9593 fix(single-tenant): application upgrades do not need --profile databases
  docker/stacks/single-tenant-host/README.md
Labels: size/xs

#9574 [Snyk] Upgrade json2csv from 5.0.5 to 5.0.7
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9575 [Snyk] Upgrade react-beautiful-dnd from 13.0.0 to 13.1.1
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9573 [Snyk] Upgrade humanize-duration from 3.29.0 to 3.31.0
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9569 [Snyk] Upgrade graphql from 15.7.2 to 15.8.0
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9595 fix: Add graphql-relay to predeploy
  package.json
Labels: size/xs

#9596 feat: update pricing page with template changes
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
  packages/client/utils/constants.ts
Labels: size/s

#9598 fix: trim inet address
  packages/server/utils/uwsGetIP.ts
Labels: size/xs

#9590 chore: Remove one on one meeting type
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/OneOnOneTeamStatus.tsx
  packages/client/components/ActivityLibrary/OneOnOneTeamStatusComponent.tsx
  packages/client/mutations/StartCheckInMutation.ts
  packages/server/database/types/Team.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/getExistingOneOnOneTeam.ts
  packages/server/graphql/mutations/helpers/maybeCreateOneOnOneTeam.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/graphql/public/typeDefs/CreateOneOnOneTeamInput.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/startCheckIn.graphql
  packages/server/graphql/public/types/CreateOneOnOneTeamInput.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/postgres/migrations/1712073121060_removeOneOnOne.ts
  packages/server/postgres/queries/src/insertTeamQuery.sql
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/analytics/helpers.ts
  static/images/illustrations/meeting_types-one_on_one.svg
  static/images/illustrations/oneOnOne.svg
Labels: size/l

#9600 fix: Don't reuse another team members integrated task
  packages/client/utils/AtlassianManager.ts
  packages/client/utils/JiraServerClientManager.ts
  packages/server/graphql/mutations/helpers/importTasksForPoker.ts
Labels: size/xs

#9597 fix: fix the issue where timer doesn't work in TEAM_HEALTH phase
  packages/client/components/MeetingControlBar.tsx
  packages/client/components/TeamHealth.tsx
Labels: size/xs

#9594 chore: update ironbank GH action to copy ip-to-server-id script
  .github/workflows/ironbank.yml
Labels: Skip Maintainer Review, size/xs

#9603 fix: fallback for missing avatar images
  packages/client/components/Avatar/Avatar.tsx
Labels: size/s

#9580 fix: fix an issue where upcoming invoice doesn't have the nextPeriodCharges field
  packages/client/modules/userDashboard/components/InvoiceRow/InvoiceRow.tsx
  packages/client/utils/makeMonthDateString.ts
  packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts
  packages/server/graphql/queries/invoices.ts
Labels: size/s

#9606 fix: type error in invite email
  packages/server/email/teamInviteEmailCreator.tsx
Labels: size/s

#9607 fix: return 100 gitlab pipeline jobs
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9611 fix: remove top level graphql-relay dependency
  package.json
  packages/client/shared/gqlIds/DomainJoinRequestId.ts
Labels: size/s

#9612 fix: Add AuthIdentityMicrosoft
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/rootTypes.ts
Labels: size/s

#9614 fix: Revert "[Snyk] Upgrade graphql from 15.7.2 to 15.8.0 (#9569)"
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9592 chore: disable change template ui if phase complete
  packages/client/components/MeetingOptions.tsx
  packages/client/components/RetroDrawer.tsx
Labels: size/s

#9557 feat: related discussions refactor
  package.json
  packages/client/components/RetroDrawerRoot.tsx
  packages/embedder/EMBEDDER_JOB_PRIORITY.ts
  packages/embedder/EmbedderJobType.ts
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/embedder/JobQueueError.ts
  packages/embedder/WorkflowOrchestrator.ts
  packages/embedder/addEmbeddingsMetadata.ts
  packages/embedder/addEmbeddingsMetadataForRetrospectiveDiscussionTopic.ts
  packages/embedder/ai_models/AbstractEmbeddingsModel.ts
  packages/embedder/ai_models/ModelManager.ts
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/custom.d.ts
  packages/embedder/debug.ts
  packages/embedder/embedder.ts
  packages/embedder/getEmbedderPriority.ts
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/embedder/indexing/failJob.ts
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/inferLanguage.ts
  packages/embedder/insertDiscussionsIntoMetadataAndQueue.ts
  packages/embedder/logPerformance.ts
  packages/embedder/package.json
  packages/embedder/processJob.ts
  packages/embedder/processJobEmbed.ts
  packages/embedder/regex.ts
  packages/embedder/workflows/embedMetadata.ts
  packages/embedder/workflows/getSimilarRetroTopics.ts
  packages/embedder/workflows/helpers/getRerankedEmbeddingsFromChunks.ts
  packages/embedder/workflows/helpers/publishSimilarRetroTopics.ts
  packages/embedder/workflows/relatedDiscussionsStart.ts
  packages/embedder/workflows/rerankRetroTopics.ts
  packages/server/dataloader/RootDataLoader.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/mutations/helpers/publishToEmbedder.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
  packages/server/postgres/migrations/1712074131388_priority.ts
  packages/server/utils/publish.ts
  scripts/webpack/dev.servers.config.js
  yarn.lock
Labels: size/xl

#9617 feat: Release activity library for everyone
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/MeetingsDash.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/components/StartMeetingFAB.tsx
  packages/client/modules/teamDashboard/components/TeamDashMain/TeamDashMain.tsx
  packages/client/modules/userDashboard/components/UserDashMain.tsx
  packages/client/modules/userDashboard/components/UserDashMain/UserDashMain.tsx
  packages/client/modules/userDashboard/components/UserDashMain/UserDashMainRoot.tsx
  packages/client/modules/userDashboard/components/UserDashboard/UserDashboard.tsx
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/graphql/public/mutations/loginWithMicrosoft.ts
  packages/server/graphql/public/mutations/signUpWithPassword.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
Labels: size/m

#9625 feat: release recurring retros
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: size/s

#9628 fix: Only list available categories in edit template
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
Labels: size/xs

#9629 chore: Add absolute date tooltip in history
  packages/client/components/SimpleTooltip.tsx
  packages/client/components/TimelineEventDate.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
  packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
Labels: size/s

#9630 feat: Make top team templates clickable
  packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
Labels: size/s

#9633 fix: use radix-ui for avatars
  .prettierrc
  .vscode/settings.json
  packages/client/components/ActionMeetingAgendaItems.tsx
  packages/client/components/ActionMeetingUpdatesPrompt.tsx
  packages/client/components/Avatar/Avatar.tsx
  packages/client/components/AvatarList.tsx
  packages/client/components/AvatarListUser.tsx
  packages/client/components/DashboardAvatars/DashboardAvatar.tsx
  packages/client/components/DeckActivityAvatars.tsx
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/EditableAvatar/EditableAvatar.tsx
  packages/client/components/MeetingSidebarTeamMemberStageItems.tsx
  packages/client/components/MentionUser/MentionUser.tsx
  packages/client/components/NewMeetingTeamPickerAvatars.tsx
  packages/client/components/OrgAvatarInput.tsx
  packages/client/components/StandardHub/StandardHub.tsx
  packages/client/components/TeamHealthVotingRow.tsx
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
  packages/client/components/TeamPrompt/TeamPromptRepliesAvatarList.tsx
  packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
  packages/client/components/ThreadedAvatarColumn.tsx
  packages/client/components/TopBarAvatar.tsx
  packages/client/components/UserAvatarInput.tsx
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewMeetingCheckInPrompt.tsx
  packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
  packages/client/modules/teamDashboard/components/ManageTeam/ManageTeamMember.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgBilling/NewBillingLeaderMenu.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgDetails.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembersRow.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/modules/userDashboard/components/OrganizationRow/OrganizationRow.tsx
  packages/client/modules/userDashboard/components/UserSettingsForm/UserSettingsForm.tsx
  packages/client/ui/Avatar/Avatar.tsx
Labels: size/l

#9635 fix: margin spacing on hover
  packages/client/modules/userDashboard/components/OrgBilling/OrgDetails.tsx
Labels: size/s

#9622 fix: vuln patch for undici
  package.json
  packages/client/package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9514 chore: migration reflection groups to pg
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/postgres/migrations/1708127504000_updateEmbeddingMetadata.ts
  packages/server/postgres/migrations/1712075131388_retroReflectionGroups2.ts
  packages/server/postgres/utils/checkEqBase.ts
  packages/server/postgres/utils/rethinkEqualityFns.ts
  packages/server/utils/PubSubPromise.ts
Labels: size/m

#9638 chore: fix ironbank action file copy
  .github/workflows/ironbank.yml
Labels: Skip Maintainer Review

#9644 fix: Migrate webpack dev server settings to v5
  scripts/webpack/dev.client.config.js
Labels: size/s

#9645 chore: add ip-to-server script dir to zip file
  .github/workflows/ironbank.yml
Labels: Skip Maintainer Review, size/xs

#9627 chore: Remove old template editing logic
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/NewMeetingSettings.tsx
  packages/client/components/NewMeetingSettingsAction.tsx
  packages/client/components/NewMeetingSettingsPoker.tsx
  packages/client/components/NewMeetingSettingsRetrospective.tsx
  packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
  packages/client/components/NewMeetingSettingsTeamPrompt.tsx
  packages/client/modules/meeting/components/AddNewPokerTemplate.tsx
  packages/client/modules/meeting/components/AddNewReflectTemplate.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/PokerTemplateItem.tsx
  packages/client/modules/meeting/components/PokerTemplateList.tsx
  packages/client/modules/meeting/components/PokerTemplateListOrg.tsx
  packages/client/modules/meeting/components/PokerTemplateListOrgRoot.tsx
  packages/client/modules/meeting/components/PokerTemplateListPublic.tsx
  packages/client/modules/meeting/components/PokerTemplateListPublicRoot.tsx
  packages/client/modules/meeting/components/PokerTemplateListTeam.tsx
  packages/client/modules/meeting/components/PokerTemplateModal.tsx
  packages/client/modules/meeting/components/PokerTemplatePicker.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateItem.tsx
  packages/client/modules/meeting/components/ReflectTemplateList.tsx
  packages/client/modules/meeting/components/ReflectTemplateListOrg.tsx
  packages/client/modules/meeting/components/ReflectTemplateListOrgRoot.tsx
  packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
  packages/client/modules/meeting/components/ReflectTemplateListPublicRoot.tsx
  packages/client/modules/meeting/components/ReflectTemplateListTeam.tsx
  packages/client/modules/meeting/components/ReflectTemplateModal.tsx
  packages/client/modules/meeting/components/ReflectTemplateSearchBar.tsx
  packages/client/modules/meeting/components/RetroTemplatePicker.tsx
  packages/client/modules/meeting/components/SelectTemplate.tsx
  packages/client/mutations/AddPokerTemplateMutation.ts
  packages/client/mutations/AddReflectTemplateMutation.ts
  packages/client/mutations/RemovePokerTemplateMutation.ts
  packages/client/mutations/UpdatePokerTemplateScopeMutation.ts
  packages/client/mutations/UpdateReflectTemplateScopeMutation.ts
  packages/client/mutations/connections/getPokerTemplateOrgConn.ts
  packages/client/mutations/connections/getPokerTemplatePublicConn.ts
  packages/client/mutations/handlers/handleMovePokerTemplateDimension.ts
  packages/client/mutations/handlers/handleRemovePokerTemplate.ts
Labels: size/xl

#9626 chore: Improve Activity Library focus and hover states
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityGrid.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
  packages/client/components/ActivityLibrary/CreateActivityCard.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/components/RetroDrawerTemplateCard.tsx
Labels: size/s

#9653 fix: change retro group schema to allow for rethinkdb table migration
  packages/server/postgres/migrations/1712075131388_retroReflectionGroups2.ts
Labels: size/s

#9652 fix: Threaded reply input does not immediately close
  packages/client/components/ThreadedReplyButton.tsx
Labels: size/xs

#9631 chore: remove noTemplateLimit flag
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/utils/useTemplateDescription.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/selectTemplate.ts
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/s

#9666 chore: update activity library custom tab empty state
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryEmptyState.tsx
Labels: size/s

#9660 feat: roll out ai icebreakers
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Labels: size/s

#9655 feat(orgAdmin): org admin can promote others to org admin
  packages/server/graphql/public/mutations/setOrgUserRole.ts
Labels: size/s

#9663 fix: support PG reconnects
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/server/postgres/getKysely.ts
  packages/server/postgres/getPg.ts
Labels: size/s

#9668 fix: can update gcal start datetime
  packages/client/modules/userDashboard/components/GcalModal/DateTimePickers.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
  packages/client/modules/userDashboard/components/GcalModal/GcalSettings.tsx
Labels: size/s

#9665 fix: Increase process recurrence timeout
  packages/chronos/chronos.ts
  packages/server/utils/PubSubPromise.ts
  packages/server/utils/publishWebhookGQL.ts
Labels: size/s

#9647 fix: Sidebar in start custom activity
  packages/client/components/ActivityLibrary/ActivityCard.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetails/components/IntegrationsTip.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
Labels: size/s

#9678 chore: Remove adhoc teams
  packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/components/SelectTeamDropdown.tsx
  packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
  packages/server/graphql/public/types/UserFeatureFlags.ts
  packages/server/graphql/types/UserFlagEnum.ts
Labels: size/s

#9675 feat: initial avatars on the fly
  packages/server/database/types/User.ts
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/fileStorage/LocalFileStoreManager.ts
  packages/server/fileStorage/S3FileStoreManager.ts
  packages/server/graphql/private/mutations/helpers/generateIdenticon.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/public/mutations/loginWithGoogle.ts
  packages/server/graphql/public/mutations/loginWithMicrosoft.ts
  packages/server/graphql/public/mutations/signUpWithPassword.ts
  packages/server/graphql/public/mutations/verifyEmail.ts
  packages/server/package.json
  packages/server/utils/createNewLocalUser.ts
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.servers.config.js
  scripts/webpack/toolbox.config.js
  yarn.lock
Labels: size/m

#9687 chore: bump packages core-js humanize-duration
  packages/client/package.json
  scripts/webpack/dev.clientdll.config.js
  yarn.lock
Labels: size/xs

#9689 fix: install plex on system
  docker/images/parabol-ubi/dockerfiles/basic.dockerfile
  packages/server/graphql/private/mutations/helpers/generateIdenticon.ts
Labels: size/s

#9690 fix: copy fonts from static
  docker/images/parabol-ubi/dockerfiles/basic.dockerfile
  scripts/webpack/prod.servers.config.js
Labels: size/s

#9670 fix: Optimize processRecurrence
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/normalizeArrayResults.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: size/s

#9692 chore(docker): fonts are managed with the rest of app related stuff
  docker/images/parabol-ubi/dockerfiles/basic.dockerfile
Labels: size/xs
