Repository ParabolInc/parabol, pull requests merged in 2024-11, with the labels that each got.

#10450 fix: teamMember is nullable in generate insight
  packages/server/graphql/public/mutations/generateInsight.ts
Labels: size/xs

#10435 feat: add an archive checkbox in timeline history page
  packages/client/components/MyDashboardTimeline.tsx
  packages/client/components/MyDashboardTimelineRoot.tsx
  packages/client/components/TimelineEventCard.tsx
  packages/client/components/TimelineFeedList.tsx
  packages/client/components/TimelineHeader.tsx
  packages/client/mutations/ArchiveTimelineEventMutation.ts
  packages/client/mutations/EndCheckInMutation.ts
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/mutations/EndSprintPokerMutation.ts
  packages/client/mutations/EndTeamPromptMutation.ts
  packages/client/mutations/connections/getUserTimelineEventsConn.ts
  packages/client/mutations/handlers/handleAddTimelineEvent.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/mutations/archiveTimelineEvent.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/public/typeDefs/EndSprintPokerSuccess.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/EndTeamPromptSuccess.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/types/EndCheckInPayload.ts
  packages/server/graphql/types/EndRetrospectivePayload.ts
  packages/server/graphql/types/EndSprintPokerPayload.ts
Labels: size/m

#10461 fix: pin react-router to static version
  packages/client/package.json
  yarn.lock
Labels: size/xs

#10464 feat: Add lastSeenAt to organization members CSV export
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Labels: size/xs

#10465 chore: Cleanup Mattermost API
  packages/server/integrations/mattermost/mattermostWebhookHandler.ts
Labels: size/s

#10463 chore: upgrade emoji mart
  packages/client/components/ReactjiPicker.tsx
  packages/client/components/ReflectionCard/AddReactjiButton.tsx
  packages/client/components/ReflectionCard/EmojiUsersReaction.tsx
  packages/client/components/ReflectionCard/ReactjiCount.tsx
  packages/client/package.json
  packages/client/types/modules.d.ts
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/utils/getReactji.ts
  packages/server/package.json
  packages/server/utils/emojiIds.ts
  packages/server/utils/getGroupedReactjis.ts
  scripts/webpack/dev.client.config.js
  scripts/webpack/prod.client.config.js
  yarn.lock
Labels: size/m

#10467 fix: supprt jsx runtime in SSR
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.servers.config.js
Labels: size/xs

#10469 fix: Fix GraphQL-JIT version
  packages/server/package.json
  yarn.lock
Labels: size/xs

#10483 fix: github pr template release test now with the correct Mattermost link
  .github/ISSUE_TEMPLATE/release_test.md
Labels: size/xs

#10484 chore: add a workflow to push to a docker repository to share with external clients
  .github/workflows/docker-external.yml
Labels: size/s

#10486 fix(docker-external): workflow name fixed
  .github/workflows/docker-external.yml
Labels: size/xs

#10470 fix: update generate insight permissions
  packages/server/graphql/public/mutations/generateInsight.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/rules/isViewerTeamLead.ts
Labels: size/s

#10488 fix: jira issues not loading when there's an img in the description
  packages/server/email/inlineImages.ts
  packages/server/utils/atlassian/jiraImages.ts
Labels: size/s

#10455 feat: Upgrade TipTap Extensions
  .gitignore
  packages/client/components/Avatar/Avatar.tsx
  packages/client/components/EditorLinkChanger/EditorLinkChangerTipTap.tsx
  packages/client/components/EditorLinkViewer/EditorLinkViewerTipTap.tsx
  packages/client/components/EmojiDropdown.tsx
  packages/client/components/MentionDropdown.tsx
  packages/client/components/TaskTagDropdown.tsx
  packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
  packages/client/components/TypeAheadLabel.tsx
  packages/client/components/promptResponse/EmojiMenuTipTap.tsx
  packages/client/components/promptResponse/MentionsTipTap.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/components/promptResponse/TipTapLinkEditor.tsx
  packages/client/components/promptResponse/TipTapLinkMenu.tsx
  packages/client/components/promptResponse/TipTapLinkPreview.tsx
  packages/client/components/promptResponse/TiptapLinkExtension.ts
  packages/client/components/promptResponse/isTextSelected.ts
  packages/client/components/promptResponse/tiptapConfig.ts
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx
  packages/client/package.json
  packages/client/styles/theme/global.css
  packages/client/ui/Button/Button.tsx
  packages/client/ui/Tooltip/TooltipContent.tsx
  packages/client/ui/cn.ts
  packages/client/utils/tiptapEmojiConfig.ts
  packages/client/utils/tiptapMentionConfig.ts
  packages/client/utils/tiptapTagConfig.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
  packages/server/utils/convertToTipTap.ts
  packages/server/utils/serverTipTapExtensions.ts
  yarn.lock
Labels: size/xl

#10502 fix: remove react imports
  packages/client/modules/userDashboard/components/OrgBilling/OrgFeatureFlags.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgFeatures.tsx
Labels: size/xs

#10513 chore: remove signUpDestinationTeam
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/client/mutations/VerifyEmailMutation.ts
Labels: size/s

#10520 fix: Adding reactions in standup via mouse works more than once
  packages/client/components/ReflectionCard/AddReactjiButton.tsx
Labels: size/xs

#10511 chore: release shareSummary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
Labels: size/s

#10522 chore: Rename Jira Server to Jira Data Center
  packages/client/components/JiraScopingSearchFilterMenu.tsx
  packages/client/components/JiraServerConfigMenu.tsx
  packages/client/components/JiraServerScopingSearchBar.tsx
  packages/client/components/JiraServerScopingSearchResults.tsx
  packages/client/components/PokerDimensionFinalScorePicker.tsx
  packages/client/components/PokerEstimateHeaderCard.tsx
  packages/client/components/ScopePhaseArea.tsx
  packages/client/components/ScopePhaseAreaAddJiraServer.tsx
  packages/client/components/TaskIntegrationLink.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationPanel.tsx
  packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationResults.tsx
  packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
  packages/client/types/constEnums.ts
  packages/client/utils/constants.ts
  packages/server/graphql/mutations/setTaskEstimate.ts
  packages/server/graphql/public/typeDefs/JiraServerIntegration.graphql
  packages/server/graphql/public/typeDefs/JiraServerIssue.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrations.graphql
  packages/server/integrations/jiraServer/JiraServerRestManager.ts
  scripts/create-jira-keys.sh
Labels: size/s

#10501 chore: use more detailed AI Summary for meetings
  codegen.json
  packages/server/graphql/mutations/generateRetroSummaries.ts
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/generateRetroSummary.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/transformRetroToAIFormat.ts
  packages/server/graphql/private/mutations/generateMeetingSummary.ts
  packages/server/graphql/private/typeDefs/generateMeetingSummary.graphql
  packages/server/graphql/private/types/GenerateMeetingSummarySuccess.ts
  packages/server/graphql/public/typeDefs/GenerateRetroSummariesPayload.graphql
  packages/server/graphql/public/typeDefs/GenerateRetroSummariesSuccess.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/types/GenerateRetroSummariesSuccess.ts
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: size/l

#10515 chore: remove ai template
  codegen.json
  package.json
  packages/client/components/ActivityLibrary/AISearch.tsx
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/mutations/GetTemplateSuggestionMutation.ts
  packages/server/graphql/public/mutations/getTemplateSuggestion.ts
  packages/server/graphql/public/typeDefs/GetTemplateSuggestionPayload.graphql
  packages/server/graphql/public/typeDefs/GetTemplateSuggestionSuccess.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/types/GetTemplateSuggestionSuccess.ts
  packages/server/utils/OpenAIServerManager.ts
  yarn.lock
Labels: size/m

#10535 chore: Make Google Language Manager optional
  .env.example
  packages/server/getGoogleLanguageManager.ts
  packages/server/graphql/mutations/helpers/getReflectionEntities.ts
  packages/server/graphql/mutations/helpers/getReflectionSentimentScore.ts
Labels: size/s

#10537 fix: show public teams
  packages/server/graphql/public/types/Organization.ts
Labels: size/xs
