Repository ParabolInc/parabol, pull requests merged in 2024-07, with the labels that each got.

#9881 fix: Avoid adding embedding jobs without metadata id
  packages/embedder/insertDiscussionsIntoMetadataAndQueue.ts
  packages/embedder/insertMeetingTemplatesIntoMetadataAndQueue.ts
Labels: size/xs

#9802 feat: Add search template mutation
  packages/client/components/ActivityLibrary/ActivityLibrary.tsx
  packages/client/components/ActivityLibrary/ActivityLibraryEmptyState.tsx
  packages/client/hooks/useDebouncedSearch.ts
  packages/client/package.json
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/importHistoricalRetrospectiveDiscussionTopic.ts
  packages/server/__tests__/user.test.ts
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/package.json
  yarn.lock
Labels: size/m

#9895 fix: remove ai from summary url if no ai env var
  packages/client/mutations/EndRetrospectiveMutation.ts
Labels: size/xs

#9902 fix: speed up team upgrade
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
  packages/server/graphql/private/mutations/stripeDeleteSubscription.ts
  packages/server/graphql/private/mutations/upgradeToTeamTier.ts
  packages/server/graphql/public/mutations/createStripeSubscription.ts
  packages/server/utils/defaultTier.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/m

#9918 fix: remove Organization.teams field from gql
  packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
Labels: size/xs

#9919 fix: bugs during upgrade/downgrade
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
  packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
  packages/client/mutations/AddOrgMutation.ts
  packages/client/mutations/DowngradeToStarterMutation.ts
  packages/client/mutations/fragments/CompleteOrganizationFrag.ts
  packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
  packages/client/package.json
  yarn.lock
Labels: size/s

#9909 fix: Allow to start recurrence for existing Standups
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
Labels: size/s

#9912 chore: Fix debug output when retrying after Cloudflare error
  packages/server/fileStorage/S3FileStoreManager.ts
Labels: size/xs

#9908 chore: Show only available integrations
  .env.example
  packages/client/components/AddToGitHubMenuItem.tsx
  packages/client/components/AddToJiraMenuItem.tsx
  packages/client/components/ScopePhaseArea.tsx
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/AtlassianProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/GitHubProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/SlackProviderRow.tsx
  packages/client/types/modules.d.ts
  packages/client/utils/AtlassianClientManager.ts
  packages/client/utils/GitHubClientManager.ts
  packages/client/utils/SlackClientManager.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
Labels: size/s

#9920 fix: Allow starting recurring meetings without GCal
  packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
  packages/client/components/ScheduleDialog.tsx
Labels: size/s

#9910 chore: Read Gitlab server URL from env for prime integrations
  .env.example
  scripts/toolboxSrc/primeIntegrations.ts
Labels: size/xs

#9923 fix: connectionContext always available
  packages/server/socketHandlers/handleOpen.ts
Labels: size/s

#9924 fix: handle failed 3DS payments
  packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
  packages/server/billing/stripeWebhookHandler.ts
  packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
  packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
  packages/server/graphql/private/mutations/stripeCreateSubscription.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/createStripeSubscription.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/m

#9883 chore(rethinkdb): Organization: Phase 1
  packages/embedder/indexing/orgIdsWithFeatureFlag.ts
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/billing/helpers/generateInvoice.ts
  packages/server/billing/helpers/generateUpcomingInvoice.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/billing/helpers/terminateSubscription.ts
  packages/server/database/types/GoogleAnalyzedEntity.ts
  packages/server/database/types/processTeamsLimitsJob.ts
  packages/server/graphql/mutations/addOrg.ts
  packages/server/graphql/mutations/addTeam.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/downgradeToStarter.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/createNewOrg.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/hideConversionModal.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
  packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/payLater.ts
  packages/server/graphql/mutations/updateReflectionContent.ts
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
  packages/server/graphql/private/mutations/endTrial.ts
  packages/server/graphql/private/mutations/flagConversionModal.ts
  packages/server/graphql/private/mutations/sendUpcomingInvoiceEmails.ts
  packages/server/graphql/private/mutations/setOrganizationDomain.ts
  packages/server/graphql/private/mutations/startTrial.ts
  packages/server/graphql/private/mutations/stripeCreateSubscription.ts
  packages/server/graphql/private/mutations/stripeDeleteSubscription.ts
  packages/server/graphql/private/mutations/stripeInvoiceFinalized.ts
  packages/server/graphql/private/mutations/stripeInvoicePaid.ts
  packages/server/graphql/private/mutations/stripeSucceedPayment.ts
  packages/server/graphql/private/mutations/stripeUpdateCreditCard.ts
  packages/server/graphql/private/mutations/updateOrgFeatureFlag.ts
  packages/server/graphql/private/mutations/upgradeToTeamTier.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/updateCreditCard.ts
  packages/server/graphql/public/mutations/updateOrg.ts
  packages/server/graphql/public/mutations/uploadOrgImage.ts
  packages/server/graphql/public/types/DomainJoinRequest.ts
  packages/server/graphql/queries/invoices.ts
  packages/server/postgres/helpers/toCreditCard.ts
  packages/server/postgres/helpers/toGoogleAnalyzedEntity.ts
  packages/server/postgres/migrations/1719435764047_Organization-phase1.ts
  packages/server/safeMutations/safeArchiveEmptyStarterOrganization.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  scripts/toolboxSrc/setIsEnterprise.ts
Labels: size/l

#9931 chore(rethinkdb): Organization: Phase 2
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/postgres/migrations/1720026588542_Organization-phase2.ts
  packages/server/postgres/utils/rethinkEqualityFns.ts
Labels: size/m

#9936 fix: Read embedder URL from env
  packages/server/graphql/public/types/User.ts
Labels: size/s

#9937 chore(client): when a release happens, links to the specific tag version
  packages/client/hooks/useServiceWorkerUpdater.ts
Labels: size/xs

#9941 chore(postgres): Postgres upgraded to 15.7 and pgvector to 0.7.0
  .github/workflows/build.yml
  .github/workflows/test.yml
  docker/images/postgres/Dockerfile
  docker/stacks/single-tenant-host/docker-compose.yml
Labels: DX, devops, size/s

#9943 chore(rethinkdb): phase 4 of RetroReflection, RetroReflectionGroup and TimelineEvent
  packages/server/postgres/migrations/1720517256158_TimelineEvent-phase4.ts
  packages/server/postgres/migrations/1720517631974_RetroReflectionGroup-phase4.ts
  packages/server/postgres/migrations/1720518455750_RetroReflection-phase4.ts
Labels: size/s

#9952 chore(rethinkdb): OrganizationUser: Phase 1
  packages/client/components/BillingLeaderActionMenu.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/billing/helpers/generateInvoice.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/billing/helpers/teamLimitsCheck.ts
  packages/server/billing/helpers/updateSubscriptionQuantity.ts
  packages/server/database/types/OrganizationUser.ts
  packages/server/dataloader/__tests__/isOrgVerified.test.ts
  packages/server/graphql/graphql.ts
  packages/server/graphql/mutations/archiveOrganization.ts
  packages/server/graphql/mutations/helpers/createNewOrg.ts
  packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/oldUpgradeToTeamTier.ts
  packages/server/graphql/private/mutations/autopauseUsers.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
  packages/server/graphql/private/mutations/stripeFailPayment.ts
  packages/server/graphql/private/mutations/toggleAllowInsights.ts
  packages/server/graphql/private/mutations/upgradeToTeamTier.ts
  packages/server/graphql/private/queries/suCountTiersForUser.ts
  packages/server/graphql/private/queries/suOrgCount.ts
  packages/server/graphql/private/queries/suProOrgInfo.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/createStripeSubscription.ts
  packages/server/graphql/public/mutations/setOrgUserRole.ts
  packages/server/graphql/public/subscriptions/organizationSubscription.ts
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/queries/helpers/countTiersForUserId.ts
  packages/server/graphql/queries/invoices.ts
  packages/server/graphql/types/OrganizationUser.ts
  packages/server/postgres/migrations/1720556055134_OrganizationUser-phase1.ts
  packages/server/safeMutations/safeArchiveEmptyStarterOrganization.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/authorization.ts
  packages/server/utils/getActiveDomainForOrgId.ts
  packages/server/utils/setTierForOrgUsers.ts
  packages/server/utils/setUserTierForOrgId.ts
  packages/server/utils/setUserTierForUserIds.ts
  scripts/toolboxSrc/setIsEnterprise.ts
Labels: size/l

#9928 chore: Make meeting series naming consistent
  packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
  packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
  packages/client/components/Recurrence/EndRecurringMeetingModal.tsx
  packages/client/components/Recurrence/RecurrenceSettings.tsx
  packages/client/components/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/components/ScheduleDialog.tsx
  packages/client/mutations/StartRetrospectiveMutation.ts
  packages/client/mutations/StartTeamPromptMutation.ts
  packages/client/mutations/UpdateRecurrenceSettingsMutation.ts
  packages/server/__tests__/startRetrospective.test.ts
  packages/server/database/types/MeetingAction.ts
  packages/server/database/types/MeetingPoker.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/helpers/createGcalEvent.ts
  packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/public/mutations/startCheckIn.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
  packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
  packages/server/graphql/public/typeDefs/CreateGcalEventInput.graphql
  packages/server/graphql/public/typeDefs/RecurrenceSettingsInput.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/startCheckIn.graphql
  packages/server/graphql/public/typeDefs/startRetrospective.graphql
  packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
  packages/server/graphql/public/typeDefs/updateRecurrenceSettings.graphql
  packages/server/graphql/public/types/CreateGcalEventInput.ts
Labels: size/m

#9953 chore(rethinkdb): OrganizationUser: Phase 2
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/postgres/migrations/1720640784862_OrganizationUser-phase2.ts
  packages/server/postgres/utils/checkEqBase.ts
Labels: size/m

#9968 fix: if the content of a task is only spaces, it gets deleted as if i…
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
Labels: size/xs

#9975 fix: add ClearAll dataloader method
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/dataloader/RootDataLoader.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMaker.ts
  packages/server/dataloader/normalizeResults.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoader.ts
  packages/server/graphql/DataLoaderCache.ts
  packages/server/graphql/getDataLoader.ts
Labels: size/m

#9981 fix: pull pgvector from image
  docker/images/postgres/Dockerfile
  docker/images/postgres/extensions/install.sql
  docker/stacks/development/docker-compose.yml
Labels: size/s

#9983 chore: parallelize codecheck
  .github/workflows/style-check.yml
  .github/workflows/test.yml
  package.json
Labels: size/s

#9956 fix: colors of the prompts for the threat level retro match now the prompts' names
  packages/server/postgres/migrations/1720689742934_fixThreatLevelPromptColors.ts
Labels: size/s

#9997 fix: Filipino checkin greeting
  packages/client/utils/makeCheckinGreeting.ts
Labels: size/xs

#9979 chore(rethinkdb): TeamMember: Phase 1
  packages/client/hooks/useSnacksForNewMeetings.ts
  packages/server/database/types/Meeting.ts
  packages/server/dataloader/RootDataLoader.ts
  packages/server/dataloader/rethinkForeignKeyLoader.ts
  packages/server/graphql/mutations/addTeam.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/deleteTask.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/softDeleteUser.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/promoteToTeamLead.ts
  packages/server/graphql/mutations/setPokerSpectate.ts
  packages/server/graphql/mutations/toggleTeamDrawer.ts
  packages/server/graphql/mutations/updateTask.ts
  packages/server/graphql/mutations/updateTeamName.ts
  packages/server/graphql/private/mutations/backupOrganization.ts
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/private/mutations/updateEmail.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/requestToJoinDomain.ts
  packages/server/graphql/public/mutations/updateUserProfile.ts
  packages/server/graphql/public/mutations/uploadUserImage.ts
  packages/server/graphql/public/typeDefs/ActionMeeting.graphql
  packages/server/graphql/public/typeDefs/NewMeeting.graphql
  packages/server/graphql/public/typeDefs/PokerMeeting.graphql
  packages/server/graphql/public/typeDefs/RetrospectiveMeeting.graphql
  packages/server/graphql/public/typeDefs/TeamPromptMeeting.graphql
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/DomainJoinRequest.ts
  packages/server/graphql/public/types/NewMeeting.ts
  packages/server/graphql/public/types/helpers/getTeamsByOrgIds.ts
  packages/server/graphql/queries/verifiedInvitation.ts
  packages/server/graphql/resolvers.ts
  packages/server/postgres/migrations/1720730818119_TeamMember-phase1.ts
  packages/server/postgres/queries/getTeamsByIds.ts
  packages/server/postgres/queries/getTeamsByOrgIds.ts
  packages/server/postgres/queries/removeUserTms.ts
  packages/server/postgres/queries/src/getTeamsByIdsQuery.sql
  packages/server/postgres/queries/src/getTeamsByOrgIdsQuery.sql
  packages/server/postgres/queries/src/removeUserTmsQuery.sql
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safeMutations/addTeamIdToTMS.ts
  packages/server/safeMutations/insertNewTeamMember.ts
  packages/server/safeMutations/safeArchiveEmptyStarterOrganization.ts
  packages/server/safeMutations/safeArchiveTeam.ts
  packages/server/safeQueries/getNewTeamLeadUserId.ts
  packages/server/utils/authorization.ts
Labels: size/xl

#10004 chore(rethinkdb): TaskHistory: One-shot
  packages/server/database/rethinkDriver.ts
  packages/server/graphql/mutations/changeTaskTeam.ts
  packages/server/graphql/mutations/createTask.ts
  packages/server/graphql/mutations/deleteTask.ts
  packages/server/graphql/mutations/helpers/addSeedTasks.ts
  packages/server/graphql/mutations/updateTask.ts
Labels: size/m

#10005 chore(rethinkdb): QueryMap: One-shot
  packages/server/__tests__/common.ts
  packages/server/database/rethinkDriver.ts
  packages/server/graphql/CompiledQueryCache.ts
  packages/server/graphql/DocumentCache.ts
  packages/server/postgres/migrations/1721348544381_QueryMapOneShot.ts
  scripts/toolboxSrc/preDeploy.ts
  scripts/toolboxSrc/primeIntegrations.ts
Labels: size/s

#10006 chore: fix broken build mig file
  packages/server/postgres/migrations/1721348544381_QueryMapOneShot.ts
Labels: size/xs

#9999 chore: Reduce Azure DevOps scope
  packages/client/utils/AzureDevOpsClientManager.ts
Labels: size/xs

#10013 chore: Fix test
  packages/server/__tests__/disableAnonymity.test.ts
Labels: size/xs

#9959 feat: GCal event series for Standup
  packages/server/graphql/public/mutations/startTeamPrompt.ts
Labels: size/s

#10002 chore: upgrade from gpt-3.5-turbo to gpt-4o-mini
  packages/server/utils/OpenAIServerManager.ts
Labels: Skip Maintainer Review, size/xs

#10015 chore: Move more integration GraphQL types to SDL
  codegen.json
  packages/client/components/JiraScopingSearchFilterMenu.tsx
  packages/server/graphql/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/mutations/removeTeamMemberIntegrationAuth.ts
  packages/server/graphql/public/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/public/mutations/removeTeamMemberIntegrationAuth.ts
  packages/server/graphql/public/typeDefs/JiraRemoteProject.graphql
  packages/server/graphql/public/typeDefs/JiraServerRemoteProject.graphql
  packages/server/graphql/public/typeDefs/RepoIntegration.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrationAuth.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrationAuthOAuth1.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrationAuthOAuth2.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrationAuthWebhook.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/typeDefs/addTeamMemberIntegrationAuth.graphql
  packages/server/graphql/public/typeDefs/removeTeamMemberIntegrationAuth.graphql
  packages/server/graphql/public/types/AddTeamMemberIntegrationAuthSuccess.ts
  packages/server/graphql/public/types/JiraRemoteProject.ts
  packages/server/graphql/public/types/RemoveTeamMemberIntegrationAuthSuccess.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthOAuth1.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthOAuth2.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthWebhook.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/AddTeamMemberIntegrationAuthPayload.ts
  packages/server/graphql/types/JiraRemoteProject.ts
  packages/server/graphql/types/RemoveTeamMemberIntegrationAuthPayload.ts
  packages/server/graphql/types/TeamMemberIntegrationAuth.ts
  packages/server/graphql/types/TeamMemberIntegrationAuthOAuth1.ts
  packages/server/graphql/types/TeamMemberIntegrationAuthOAuth2.ts
  packages/server/graphql/types/TeamMemberIntegrationAuthWebhook.ts
Labels: size/xl

#9993 chore(rethinkdb): TeamMember: Phase 2
  packages/server/__tests__/globalTeardown.ts
  packages/server/dataloader/__tests__/isOrgVerified.test.ts
  packages/server/dataloader/__tests__/usersCustomRedisQueries.test.ts
  packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
  packages/server/postgres/migrations/1721356124871_TeamMember-phase2.ts
  packages/server/postgres/utils/checkEqBase.ts
  packages/server/postgres/utils/rethinkEqualityFns.ts
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
Labels: size/m

#10027 fix: bump pm2 version
  package.json
  yarn.lock
Labels: size/xs

#10003 chore(rethinkdb): TeamMember: Phase 3
  codegen.json
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/TeamMember.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/archiveTeam.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/helpers/sendPokerMeetingRevoteEvent.ts
  packages/server/graphql/mutations/joinMeeting.ts
  packages/server/graphql/mutations/promoteToTeamLead.ts
  packages/server/graphql/mutations/removeTeamMember.ts
  packages/server/graphql/mutations/setPokerSpectate.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/toggleTeamDrawer.ts
  packages/server/graphql/private/mutations/changeEmailDomain.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
  packages/server/graphql/private/mutations/updateEmail.ts
  packages/server/graphql/private/typeDefs/_legacy.graphql
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/updateUserProfile.ts
  packages/server/graphql/public/mutations/uploadUserImage.ts
  packages/server/graphql/public/typeDefs/RepoIntegrationQueryPayload.graphql
  packages/server/graphql/public/typeDefs/TeamMember.graphql
  packages/server/graphql/public/typeDefs/_legacy.graphql
  packages/server/graphql/public/types/AcceptTeamInvitationPayload.ts
  packages/server/graphql/public/types/AddTeamMemberIntegrationAuthSuccess.ts
  packages/server/graphql/public/types/AgendaItem.ts
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/JiraServerIntegration.ts
  packages/server/graphql/public/types/NewMeeting.ts
  packages/server/graphql/public/types/NotifyTaskInvolves.ts
  packages/server/graphql/public/types/RemoveTeamMemberIntegrationAuthSuccess.ts
  packages/server/graphql/public/types/RemoveTeamMemberPayload.ts
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/public/types/TeamMember.ts
  packages/server/graphql/queries/tasks.ts
  packages/server/graphql/resolvers.ts
  packages/server/graphql/types/Team.ts
  packages/server/graphql/types/TeamMember.ts
  packages/server/postgres/types/index.d.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safeMutations/insertNewTeamMember.ts
  packages/server/utils/authorization.ts
Labels: size/l

#10021 chore(rethinkdb): TemplateScale: One-shot
  codegen.json
  packages/client/modules/meeting/components/SelectScaleDropdown.tsx
  packages/client/mutations/AddPokerTemplateScaleMutation.ts
  packages/client/mutations/RemovePokerTemplateScaleMutation.ts
  packages/client/mutations/handlers/handleAddPokerTemplateScale.ts
  packages/client/utils/dndNoise.ts
  packages/embedder/indexing/meetingTemplate.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/TemplateScale.ts
  packages/server/dataloader/customRedisQueries.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addPokerTemplateDimension.ts
  packages/server/graphql/mutations/addPokerTemplateScale.ts
  packages/server/graphql/mutations/addPokerTemplateScaleValue.ts
  packages/server/graphql/mutations/helpers/validateScaleValue.ts
  packages/server/graphql/mutations/movePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/removePokerTemplateScale.ts
  packages/server/graphql/mutations/removePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/renamePokerTemplateScale.ts
  packages/server/graphql/mutations/startSprintPoker.ts
  packages/server/graphql/mutations/updatePokerTemplateDimensionScale.ts
  packages/server/graphql/mutations/updatePokerTemplateScaleValue.ts
  packages/server/graphql/public/types/TemplateScale.ts
  packages/server/graphql/public/types/TemplateScaleRef.ts
  packages/server/graphql/public/types/TemplateScaleValue.ts
  packages/server/graphql/types/Team.ts
  packages/server/graphql/types/TemplateScale.ts
  packages/server/graphql/types/TemplateScaleRef.ts
  packages/server/graphql/types/TemplateScaleValue.ts
  packages/server/postgres/migrations/1614030642692_refs-for-meetings.ts
  packages/server/postgres/migrations/1698265600000_addPrioritizationTemplates.ts
  packages/server/postgres/migrations/1721405703862_TemplateScale.ts
  packages/server/postgres/queries/src/insertTemplateRefQuery.sql
  packages/server/postgres/queries/src/insertTemplateScaleRefQuery.sql
  packages/server/postgres/select.ts
  packages/server/postgres/types/index.d.ts
  packages/server/utils/analytics/analytics.ts
  packages/server/utils/sortOrder.ts
Labels: size/xl

#10026 fix: Disable SAML on downgrade to starter
  packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
Labels: size/xs

#9973 feat: nav updates
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/DashNavMenu.tsx
  packages/client/components/Dashboard/DashSidebar.tsx
  packages/client/components/Dashboard/LeftDashNavItem.tsx
  packages/client/components/Dashboard/MobileDashSidebar.tsx
  packages/client/components/SideBarStartMeetingButton.tsx
  packages/client/modules/userDashboard/components/Organization/OrgNav.tsx
Labels: size/m

#10033 chore(rethinkdb): TemplateDimension: One-shot
  codegen.json
  packages/client/modules/meeting/components/AddPokerTemplateDimension.tsx
  packages/client/modules/meeting/components/TemplateDimensionList.tsx
  packages/client/mutations/AddPokerTemplateDimensionMutation.ts
  packages/client/mutations/MovePokerTemplateDimensionMutation.ts
  packages/client/shared/sortOrder.ts
  packages/server/database/rethinkDriver.ts
  packages/server/database/types/TemplateDimension.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts
  packages/server/dataloader/rethinkPrimaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addPokerTemplateDimension.ts
  packages/server/graphql/mutations/addPokerTemplateScale.ts
  packages/server/graphql/mutations/addPokerTemplateScaleValue.ts
  packages/server/graphql/mutations/movePokerTemplateDimension.ts
  packages/server/graphql/mutations/movePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/pokerTemplateDimensionUpdateDescription.ts
  packages/server/graphql/mutations/removePokerTemplate.ts
  packages/server/graphql/mutations/removePokerTemplateDimension.ts
  packages/server/graphql/mutations/removePokerTemplateScale.ts
  packages/server/graphql/mutations/removePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/renamePokerTemplateDimension.ts
  packages/server/graphql/mutations/renamePokerTemplateScale.ts
  packages/server/graphql/mutations/updatePokerTemplateDimensionScale.ts
  packages/server/graphql/mutations/updatePokerTemplateScaleValue.ts
  packages/server/graphql/mutations/updateTemplateScope.ts
  packages/server/graphql/public/mutations/addPokerTemplate.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/TemplateDimension.graphql
  packages/server/graphql/public/types/TemplateScale.ts
  packages/server/graphql/types/TemplateDimension.ts
  packages/server/postgres/migrations/1614030642692_refs-for-meetings.ts
  packages/server/postgres/migrations/1698265600000_addPrioritizationTemplates.ts
  packages/server/postgres/migrations/1721858364099_TemplateDimension.ts
  packages/server/postgres/queries/updateMeetingTemplateScope.ts
  packages/server/postgres/select.ts
Labels: size/l

#9492 chore: migrate EmailVerification to pg
  packages/server/__tests__/autoJoin.test.ts
  packages/server/database/types/EmailVerification.ts
  packages/server/email/createEmailVerficationForExistingUser.ts
  packages/server/email/createEmailVerification.ts
  packages/server/graphql/public/mutations/signUpWithPassword.ts
  packages/server/graphql/public/mutations/verifyEmail.ts
  packages/server/postgres/migrations/1721868364099_addEmailVerification.ts
Labels: size/m

#10041 chore(docker-stack): force network to be called parabol on the single-tenant compose stack
  docker/stacks/single-tenant-host/docker-compose.yml
Labels: size/xs

#9954 [Snyk] Upgrade @radix-ui/react-alert-dialog from 1.0.5 to 1.1.0
  packages/client/package.json
  yarn.lock
Labels: size/xs

#9986 chore: update @radix-ui/react-alert-dialog
  packages/client/package.json
  yarn.lock
Labels: size/xs

#10016 fix(build): build prod exits with code 1 if anything goes wrong
  scripts/prod.js
Labels: size/s
