Repository ParabolInc/parabol, pull requests merged in 2024-02, with the labels that each got.

#9396 fix(env): typo in AZURE_DEVOPS vars
  .env.example
Labels: size/xs

#9393 chore: update Ironbank GH action dependencies
  .github/workflows/ironbank.yml
Labels: size/s

#9399 chore(deps): bump nodemailer
  packages/server/package.json
  yarn.lock
Labels: size/xs

#9387 fix: handle all types of errors in sendToSentry
  packages/server/utils/sendToSentry.ts
Labels: size/xs

#9405 chore: Add more Atlassian logging
  docker/dd-conf.d/gqlExecutor.yml
  docker/dd-conf.d/web.yml
  docker/dev.yml
  packages/client/utils/AtlassianManager.ts
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/graphql/types/JiraRemoteProject.ts
  packages/server/utils/AtlassianServerManager.ts
  packages/server/utils/atlassian/jiraImages.ts
  packages/server/utils/atlassian/jiraIssues.ts
  pm2.dev.config.js
Labels: size/xl

#9412 fix: fix kudos in standups in nested lists
  packages/server/graphql/public/mutations/helpers/__tests__/getKudosUserIdsFromJson.test.ts
  packages/server/graphql/public/mutations/helpers/getKudosUserIdsFromJson.ts
Labels: Skip Maintainer Review, size/m

#9394 chore: update 3d secure card number in release_test.md
  .github/ISSUE_TEMPLATE/release_test.md
Labels: Skip Maintainer Review, size/xs

#9410 chore: bump node to v20.11.0
  docker/Dockerfile.prod
  docker/parabol-ubi/docker-build/README.md
  package.json
Labels: size/s

#9372 chore: add embeddings table migration
  .env.example
  packages/server/postgres/migrations/1703031300000_addEmbeddingTables.ts
  scripts/toolboxSrc/pgEnsureExtensions.ts
  scripts/toolboxSrc/standaloneMigrations.ts
Labels: size/m

#9421 feat: speed up ai search
  packages/server/utils/OpenAIServerManager.ts
Labels: Skip Maintainer Review, size/s

#9422 fix: not all jira projects are displayed in the list if there are a lot of them
  packages/client/components/TaskFooterIntegrateMenuList.tsx
Labels: size/xs

#9424 feat: remove team template limit
  packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
  packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
  packages/client/modules/meeting/components/AddNewPokerTemplate.tsx
  packages/client/modules/meeting/components/AddNewReflectTemplate.tsx
  packages/client/modules/meeting/components/CloneTemplate.tsx
  packages/client/modules/meeting/components/PokerTemplateDetails.tsx
  packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
  packages/client/types/constEnums.ts
  packages/server/graphql/mutations/addPokerTemplate.ts
  packages/server/graphql/mutations/addReflectTemplate.ts
Labels: Skip Maintainer Review, size/s

#9435 fix: Increase the number of projects fetched per request from Atlassian
  packages/server/utils/AtlassianServerManager.ts
Labels: size/xs

#9445 feat(standalone-deployment): Standalone host deployment improved and documented
  docker/parabol-ubi/docker-host-st/.env.example
  docker/parabol-ubi/docker-host-st/README.md
  docker/parabol-ubi/docker-host-st/docker-compose.yaml
  docker/parabol-ubi/docker-host-st/postgres.conf
Labels: devops, size/m

#9455 feat: support env-defined saml issuer for PPMIs
  .env.example
  packages/server/graphql/public/mutations/helpers/SAMLHelpers/getURLWithSAMLRequestParam.ts
  packages/server/utils/getSAMLURLFromEmail.ts
Labels: size/s

#9444 chore: Associate logs with traces
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/billing/helpers/terminateSubscription.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/activatePrevSlackAuth.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/getCCFromCustomer.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/moveTeamToOrg.ts
  packages/server/graphql/mutations/navigateMeeting.ts
  packages/server/graphql/mutations/selectTemplate.ts
  packages/server/graphql/mutations/updateAzureDevOpsDimensionField.ts
  packages/server/graphql/mutations/updateGitHubDimensionField.ts
  packages/server/graphql/private/mutations/autopauseUsers.ts
  packages/server/graphql/private/mutations/connectSocket.ts
  packages/server/graphql/private/mutations/runScheduledJobs.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/graphql/public/mutations/updateGitLabDimensionField.ts
  packages/server/graphql/public/types/TeamHealthStage.ts
  packages/server/graphql/queries/helpers/fetchGitHubRepos.ts
  packages/server/graphql/queries/helpers/fetchGitLabProjects.ts
  packages/server/graphql/types/NewMeetingStage.ts
  packages/server/graphql/types/PokerMeeting.ts
  packages/server/postgres/queries/upsertAzureDevOpsDimensionFieldMap.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safetyPatchRes.ts
  packages/server/utils/AtlassianServerManager.ts
  packages/server/utils/Logger.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/RecallAIServerManager.ts
  packages/server/utils/StaticServer.ts
  packages/server/utils/publish.ts
  packages/server/utils/stripe/StripeManager.ts
Labels: size/m

#9401 chore: no force-push to prod
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9417 feat: embedder service
  .env.example
  docker/dev.yml
  package.json
  packages/embedder/.eslintrc.js
  packages/embedder/README.md
  packages/embedder/ai_models/AbstractModel.ts
  packages/embedder/ai_models/ModelManager.ts
  packages/embedder/ai_models/TextEmbeddingsInference.ts
  packages/embedder/ai_models/TextGenerationInference.ts
  packages/embedder/ai_models/helpers/fetchWithRetry.ts
  packages/embedder/embedder.ts
  packages/embedder/indexing/countWords.ts
  packages/embedder/indexing/createEmbeddingTextFrom.ts
  packages/embedder/indexing/embeddingsTablesOps.ts
  packages/embedder/indexing/getRedisClient.ts
  packages/embedder/indexing/getRootDataLoader.ts
  packages/embedder/indexing/numberVectorToString.ts
  packages/embedder/indexing/orgIdsWithFeatureFlag.ts
  packages/embedder/indexing/retrospectiveDiscussionTopic.ts
  packages/embedder/package.json
  packages/embedder/tsconfig.json
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/customRedisQueries.ts
  packages/server/postgres/getKysely.ts
  packages/server/postgres/migrations/1708127504000_updateEmbeddingMetadata.ts
  pm2.config.js
  pm2.dev.config.js
  scripts/generateGraphQLArtifacts.js
  scripts/prod.js
  scripts/runEmbedder.js
  scripts/webpack/dev.servers.config.js
  scripts/webpack/prod.servers.config.js
  scripts/webpack/toolbox.config.js
  scripts/webpack/utils/transformRules.js
  yarn.lock
Labels: size/xl

#9461 fix: merge production to avoid force push
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9463 fix: checkout prod before merging it
  .github/workflows/release-to-staging.yml
Labels: size/xs

#9416 fix: limit invites from spammers
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
Labels: size/s

#9456 fix: Fetch Jira projects in parallel
  packages/server/utils/AtlassianServerManager.ts
Labels: size/s

#9415 fix: replace lone surrogates in draft-js content
  .eslintrc.js
  package.json
  packages/chronos/package.json
  packages/client/package.json
  packages/client/utils/AtlassianManager.ts
  packages/client/utils/draftjs/extractTextFromDraftString.ts
  packages/gql-executor/package.json
  packages/integration-tests/package.json
  packages/server/package.json
  packages/server/tsconfig.json
  yarn.lock
Labels: size/s

#9434 [Snyk] Security upgrade undici from 5.26.3 to 5.28.3
  packages/server/package.json
Labels: size/xs

#9298 [Snyk] Security upgrade analytics-node from 5.2.0 to 6.0.0
  packages/server/package.json
Labels: size/xs

#9471 chore: add upload to GCS step in ironbank
  .github/workflows/ironbank.yml
Labels: size/s

#9447 chore(docker-build): simplify the docker build process and reduce docker image size
  .github/workflows/build.yml
  docker/parabol-ubi/docker-build/README.md
  docker/parabol-ubi/docker-build/dockerfiles/basic.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/parabol.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
  docker/parabol-ubi/docker-build/dockerfiles/security-test.dockerfile
  docker/parabol-ubi/docker-build/entrypoints/docker-entrypoint.sh
  docker/parabol-ubi/docker-build/environments/basic-env
  docker/parabol-ubi/docker-build/environments/legacy-build
  docker/parabol-ubi/docker-build/environments/local-buildenv
Labels: size/m

#9482 fix(docker-build): home folder is /home/node now
  docker/parabol-ubi/docker-build/dockerfiles/basic.dockerfile
Labels: size/xs
