Repository ParabolInc/parabol, pull requests merged in 2025-01, with the labels that each got.

#10630 feat: Create task from Mattermost plugin
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/CreateTaskModal/index.tsx
  packages/mattermost-plugin/components/ModalRoot.tsx
  packages/mattermost-plugin/components/Select.tsx
  packages/mattermost-plugin/components/SimpleSelect.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/public/mattermost-plugin-commands.json
  packages/mattermost-plugin/reducers.ts
  packages/mattermost-plugin/selectors.ts
Labels: size/m

#10632 feat(Mattermost): Add invite team slash command
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/index.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/useMassInvitationToken.tsx
  packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
  packages/mattermost-plugin/components/Modal.tsx
  packages/mattermost-plugin/components/ModalRoot.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/public/mattermost-plugin-commands.json
  packages/mattermost-plugin/reducers.ts
  packages/mattermost-plugin/selectors.ts
  packages/mattermost-plugin/utils/mutationResult.ts
Labels: size/l

#10636 fix: bugs in TipTap Reflection editor
  packages/client/components/GroupingKanban.tsx
  packages/client/components/GroupingKanbanColumn.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionCard/ReflectionCardAuthor.tsx
  packages/client/components/RetroGroupPhase.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
  packages/client/components/promptResponse/TipTapLinkMenu.tsx
  packages/client/hooks/useResizeObserver.ts
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailReflectionCard.tsx
  packages/client/mutations/NavigateMeetingMutation.ts
  packages/client/styles/theme/global.css
  packages/client/utils/smartGroup/getTitleFromComputedGroup.ts
  packages/server/graphql/mutations/helpers/generateAIGroupTitle.ts
  packages/server/graphql/mutations/helpers/updateGroupTitle.ts
Labels: size/m

#10641 fix: Check if integration was removed
  packages/server/dataloader/integrationAuthLoaders.ts
Labels: size/xs

#10642 chore: Disable processRecurrence tests
  packages/server/__tests__/processRecurrence.test.ts
Labels: size/s

#10635 feat(Mattermost): Invite to Meeting
  packages/mattermost-plugin/components/InviteToMeetingModal/InviteToMeetingModal.tsx
  packages/mattermost-plugin/components/InviteToMeetingModal/index.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
  packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
  packages/mattermost-plugin/components/ModalRoot.tsx
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/hooks/useMassInvitationToken.tsx
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/package.json
  packages/mattermost-plugin/prod.webpack.config.js
  packages/mattermost-plugin/public/mattermost-plugin-commands.json
  packages/mattermost-plugin/reducers.ts
  packages/mattermost-plugin/resolvers.ts
  packages/mattermost-plugin/selectors.ts
  packages/mattermost-plugin/webpack.config.js
Labels: size/m

#10653 chore: migrate old reflections to tiptap
  packages/server/postgres/migrations/2025-01-07T19:41:35.458Z_reflectionsToTipTap.ts
Labels: size/m

#10658 fix: Update mattermost-plugin version on release
  packages/mattermost-plugin/package.json
  release-please-config.json
Labels: size/s

#10660 fix: move generate retro summaries mutation to public folder
  packages/server/graphql/public/mutations/generateRetroSummaries.ts
Labels: size/s

#10663 fix: remove extra migration after rebase
  packages/server/postgres/migrations/2025-01-07T19:41:35.458Z_reflectionsToTipTap.ts
Labels: size/m

#10666 fix: rebasing migrations
  .config/kyselyMigrations.ts
  packages/server/postgres/README.md
  packages/server/postgres/migrations/2025-01-08T00:27:52.203Z_init.ts
Labels: size/s

#10671 fix: kill mattermost plugin dev server on pm2 kill
  packages/mattermost-plugin/scripts/hmrServer.js
  pm2.dev.config.js
Labels: size/s

#10672 fix: Shorten chunk names for Mattermost plugin
  packages/mattermost-plugin/prod.webpack.config.js
  packages/mattermost-plugin/webpack.config.js
Labels: size/s

#10627 chore: Upgrade @mui dependencies
  packages/client/components/AdhocTeamMultiSelect/AdhocTeamMultiSelect.tsx
  packages/client/package.json
  yarn.lock
Labels: size/xs

#10669 fix: summary does not load indefinitely if there are no votes
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/server/graphql/mutations/helpers/generateRetroSummary.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/public/typeDefs/RetrospectiveMeeting.graphql
  packages/server/graphql/public/types/RetrospectiveMeeting.ts
Labels: size/s

#10652 feat: modified/added meta tags with new content
  devTemplate.html
  packages/client/components/AuthenticationPage.tsx
  packages/client/components/GenericAuthentication.tsx
  packages/client/components/InvitationLinkDialog.tsx
  scripts/webpack/prod.client.config.js
  template.html
Labels: size/s

#10650 feat: added I Like, I Wish, I Wonder retrospective template
  packages/server/postgres/migrations/2025-01-08T15:10:42.442Z_addRetroTemplateLikeWishWonder.ts
  static/images/illustrations/iLikeIWishIWonderTemplate.png
Labels: size/s

#10664 feat: add SlashCommand to TipTap
  packages/client/hooks/useTipTapIcebreakerEditor.ts
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/package.json
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/BlurOnSubmit.ts
  packages/client/tiptap/extensions/renderSuggestion.ts
  packages/client/tiptap/extensions/slashCommand/SlashCommand.ts
  packages/client/tiptap/extensions/slashCommand/SlashCommandMenu.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
  yarn.lock
Labels: size/m

#10674 feat: update insight prompt
  packages/server/utils/OpenAIServerManager.ts
Labels: size/s

#10680 fix: consolidate organizations sorting logic
  packages/client/components/DashNavList/DashNavList.tsx
  packages/server/graphql/public/types/User.ts
Labels: Skip Maintainer Review, size/s

#10678 feat: Add images to TipTap
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionCard/ReflectionCardAuthor.tsx
  packages/client/components/ReflectionGroup/ReflectionGroup.tsx
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
  packages/client/components/Tab/Tab.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
  packages/client/components/promptResponse/TipTapLinkMenu.tsx
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/mutations/useEmbedUserAsset.ts
  packages/client/mutations/useUploadUserAsset.ts
  packages/client/package.json
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/imageBlock/ImageBlock.ts
  packages/client/tiptap/extensions/imageBlock/ImageBlockView.tsx
  packages/client/tiptap/extensions/imageBlock/ImageBlockWidth.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelector.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelectorEmbedTab.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelectorUploadTab.tsx
  packages/client/tiptap/extensions/imageUpload/ImageUpload.ts
  packages/client/tiptap/extensions/imageUpload/ImageUploadMenu.tsx
  packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
  packages/client/tiptap/extensions/slashCommand/SlashCommand.ts
  packages/client/tiptap/extensions/slashCommand/SlashCommandMenu.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
  packages/client/types/modules.d.ts
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/graphql/public/mutations/embedUserAsset.ts
  packages/server/graphql/public/mutations/uploadUserAsset.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/UploadUserAssetPayload.graphql
  packages/server/graphql/public/typeDefs/UploadUserAssetSuccess.graphql
  packages/server/utils/compressImage.ts
  yarn.lock
Labels: size/l

#10651 fix: Create mass invitation tokens for specific meetings
  packages/client/mutations/CreateMassInvitationMutation.ts
  packages/mattermost-plugin/webpack.config.js
  packages/server/graphql/types/Team.ts
Labels: size/s

#10689 chore: make ai standups more concise and add context
  packages/client/types/constEnums.ts
  packages/server/graphql/mutations/helpers/generateStandupMeetingSummary.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/s

#10703 fix: image placeholders in tiptap
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/shared/tiptap/extensions/ImageUploadBase.ts
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/imageUpload/ImageUpload.ts
  packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
Labels: size/m

#10693 feat(greetings): add Finnish and Basque greetings and a new icebreaker
  packages/client/utils/makeCheckinGreeting.ts
Labels: size/s

#10690 chore: remove discussion summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
  packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
  packages/server/graphql/mutations/helpers/handleCompletedStage.ts
  packages/server/graphql/public/typeDefs/Discussion.graphql
  packages/server/utils/OpenAIServerManager.ts
Labels: size/m

#10708 feat: group timeline events by relative dates
  packages/client/components/TimelineFeedList.tsx
  packages/client/utils/date/relativeDate.ts
  packages/client/utils/date/timelineGroups.ts
Labels: size/s

#10675 feat: add the `removeMultipleOrgUsers` mutation to support mass org user removal
  codegen.json
  packages/server/graphql/mutations/removeOrgUser.ts
  packages/server/graphql/public/mutations/removeMultipleOrgUsers.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/RemoveMultipleOrgUsersPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveMultipleOrgUsersSuccess.graphql
  packages/server/graphql/public/types/RemoveMultipleOrgUsersSuccess.ts
  packages/server/postgres/constants.ts
Labels: size/m

#10694 feat: Add GraphQL notification settings for MS Teams and Mattermost
  codegen.json
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
  packages/client/shared/gqlIds/TeamMemberIntegrationAuthId.ts
  packages/client/types/modules.d.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/dataloader/gcalLoaders.ts
  packages/server/dataloader/gitlabLoaders.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/dataloader/jiraServerLoaders.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/setTaskEstimate.ts
  packages/server/graphql/public/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/public/mutations/setNotificationSetting.ts
  packages/server/graphql/public/mutations/updateJiraServerDimensionField.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/SetNotificationSettingPayload.graphql
  packages/server/graphql/public/typeDefs/SetNotificationSettingSuccess.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrationAuthWebhook.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/types/AddTeamMemberIntegrationAuthSuccess.ts
  packages/server/graphql/public/types/AzureDevOpsIntegration.ts
  packages/server/graphql/public/types/GitLabIntegration.ts
  packages/server/graphql/public/types/JiraServerIntegration.ts
  packages/server/graphql/public/types/JiraServerRemoteProject.ts
  packages/server/graphql/public/types/MSTeamsIntegration.ts
  packages/server/graphql/public/types/MattermostIntegration.ts
  packages/server/graphql/public/types/SetNotificationSettingSuccess.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthOAuth1.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthOAuth2.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthWebhook.ts
  packages/server/integrations/TaskIntegrationManagerFactory.ts
  packages/server/postgres/migrations/2025-01-15T13:29:16.434Z_addNotificationSettings.ts
  packages/server/postgres/migrations/2025-01-20T10:49:02.535Z_removeTeamMemberIntegrationAuthChannel.ts
  packages/server/postgres/queries/getBestTeamIntegrationAuth.ts
  packages/server/postgres/queries/src/getBestTeamIntegrationAuthQuery.sql
  packages/server/utils/getTaskServicesWithPerms.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
Labels: size/l

#10710 fix: Lint Promises in conditions
  eslint.config.mjs
  packages/client/components/MobileDashTopBar.tsx
  packages/client/components/StageTimerModalEndTime.tsx
  packages/server/__tests__/jiraServerIntegration.test.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/mutations/addIntegrationProvider.ts
  packages/server/graphql/mutations/removeIntegrationProvider.ts
  packages/server/graphql/public/mutations/updateAutoJoin.ts
  packages/server/graphql/public/mutations/updateIntegrationProvider.ts
  packages/server/graphql/public/types/OrgIntegrationProviders.ts
Labels: size/s

#10695 feat: notification settings UI
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/NotificationSettings.tsx
  packages/client/mutations/SetNotificationSettingMutation.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/public/typeDefs/SetNotificationSettingSuccess.graphql
Labels: size/m

#10661 fix: S3 bucket name used from the application configuration instead of infered from CDN_URL
  packages/server/fileStorage/S3FileStoreManager.ts
  scripts/toolboxSrc/pushToCDN.ts
Labels: size/s

#10718 chore: Add AWS_S3_BUCKET to .env.example
  .env.example
Labels: size/xs

#10715 fix: Tab button style
  packages/client/components/Tab/Tab.tsx
  packages/client/tailwindTheme.ts
Labels: size/xs

#10720 fix: Check events is not null in stage timer modal
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
Labels: size/xs

#10729 chore(Mattermost): Catch notification errors
  .env.example
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
Labels: size/s

#10727 fix: simplify event timeline grouping logic
  packages/client/components/TimelineFeedList.tsx
  packages/client/utils/date/timelineGroups.ts
Labels: Skip Maintainer Review, size/s

#10735 feat: gifabol (tenor search)
  .env.example
  codegen.json
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/imageUpload/ImageSelector.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelectorSearchTab.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelectorSearchTabRoot.tsx
  packages/client/tiptap/extensions/imageUpload/ImageUpload.ts
  packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
  packages/client/tiptap/extensions/slashCommand/SlashCommandMenu.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
  packages/client/types/modules.d.ts
  packages/server/graphql/public/queries/searchGifs.ts
  packages/server/graphql/public/typeDefs/GifResponse.graphql
  packages/server/graphql/public/typeDefs/GifResponseConnection.graphql
  packages/server/graphql/public/typeDefs/GifResponseEdge.graphql
  packages/server/graphql/public/typeDefs/ImageSize.graphql
  packages/server/graphql/public/typeDefs/Query.graphql
  packages/server/graphql/public/types/GifResponse.ts
  packages/server/utils/TenorManager.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
Labels: size/l

#10744 fix(Mattermost Plugin): Load modals correctly
  packages/mattermost-plugin/Atmosphere.ts
  packages/mattermost-plugin/AtmosphereProvider.tsx
  packages/mattermost-plugin/components/AutoLogin.tsx
  packages/mattermost-plugin/components/Sidepanel/index.tsx
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/reducers.ts
  packages/mattermost-plugin/selectors.ts
Labels: size/m

#10725 fix: support edge case changeEmailDomain no users to update
  packages/server/graphql/private/mutations/changeEmailDomain.ts
Labels: size/s

#10748 fix: show invoices for enterprise customers
  packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
Labels: size/xs

#10750 fix: images keep size before loading
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/hooks/useBlockResizer.tsx
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/tiptap/extensions/imageBlock/ImageBlock.ts
  packages/client/tiptap/extensions/imageBlock/ImageBlockView.tsx
Labels: size/s

#10754 chore(web-server): reconnect window can be manually set but keeps a 60s default value
  .env.example
  packages/server/server.ts
Labels: size/s

#10753 fix: gif menu goes off screen
  packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
Labels: size/xs

#10742 chore: update public teams feature flag expiry date
  packages/server/postgres/migrations/2025-01-28T18:45:26.843Z_update-public-teams-expiry-date.ts
Labels: size/s

#10765 fix: reduce jira issue TTL from 2 days to 1 day
  packages/server/utils/atlassian/jiraIssues.ts
Labels: size/xs

#10766 chore: set oauth2redirect defaults, document env vars
  .env.example
  packages/server/graphql/private/mutations/updateEmail.ts
  packages/server/utils/AtlassianServerManager.ts
  packages/server/utils/SlackServerManager.ts
  packages/server/utils/makeOAuth2Redirect.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
Labels: size/s

#10767 fix: speed up updatePokerScope
  packages/client/mutations/UpdatePokerScopeMutation.ts
Labels: size/xs

#10768 fix: tiptap bugs
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
  packages/client/hooks/useTipTapTypingStatus.ts
  packages/client/mutations/EditCommentingMutation.ts
Labels: size/m

#10770 fix: hide deleted and voided invoices
  packages/server/graphql/public/fields/invoices.ts
Labels: size/s

#10777 fix: line breaks in reflections
  packages/client/components/SendCommentButton.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
Labels: size/s

#10779 fix: overflow-auto for comment input add max-h
  packages/client/components/DiscussionThreadInput.tsx
Labels: size/s
