Repository ParabolInc/parabol, pull requests merged in 2025-02, with the labels that each got.

#10784 chore: remove tailwinds preflight
  packages/client/styles/theme/global.css
  tailwind.config.js
Labels: size/s

#10785 fix: validate facilitatorStageId when updating poker scope
  packages/server/graphql/mutations/updatePokerScope.ts
Labels: size/s

#10791 fix: Allow navigation in meetings with invalid facilitator stage
  packages/client/utils/getSidebarItemStage.ts
Labels: size/xs

#10724 feat: release standups ai to all users
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryLoading.tsx
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgFeatureFlags.tsx
  packages/server/graphql/mutations/helpers/canAccessAI.ts
  packages/server/graphql/mutations/helpers/generateDiscussionPrompt.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/generateRetroSummary.ts
  packages/server/graphql/mutations/helpers/generateStandupMeetingSummary.ts
  packages/server/graphql/mutations/helpers/generateWholeMeetingSentimentScore.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/helpers/updateGroupTitle.ts
  packages/server/graphql/public/typeDefs/TeamPromptMeeting.graphql
  packages/server/graphql/public/types/TeamPromptMeeting.ts
Labels: size/m

#10790 fix: update the logic to match the definition of an active team with Data Sanctum
  packages/client/types/constEnums.ts
  packages/server/__tests__/isTeamActive.test.ts
  packages/server/graphql/public/types/helpers/getActiveTeamCountByTeamIds.ts
  packages/server/graphql/public/types/helpers/isTeamActive.ts
Labels: size/m

#10796 feat(Mattermost Plugin): TipTap Editor for Task and Reflection
  packages/client/shared/tiptap/addTagToTask.ts
  packages/client/shared/tiptap/convertTipTapTaskContent.ts
  packages/client/shared/types/index.d.ts
  packages/mattermost-plugin/Atmosphere.ts
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/hooks/useMassInvitationToken.tsx
  packages/mattermost-plugin/hooks/useTipTapTaskEditor.tsx
  packages/mattermost-plugin/index.css
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/package.json
  packages/mattermost-plugin/postcss.config.js
  packages/mattermost-plugin/prod.webpack.config.js
  packages/mattermost-plugin/tsconfig.json
  packages/mattermost-plugin/webpack.config.js
  packages/server/postgres/types/index.d.ts
  pm2.dev.config.js
  yarn.lock
Labels: size/m

#10800 chore: Refactor tiptap events
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/NullableTask/NullableTask.tsx
  packages/client/components/ParabolScopingSearchResultItem.tsx
  packages/client/components/PokerEstimateHeaderCardParabol.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
  packages/client/components/ResponseReplied.tsx
  packages/client/components/RetroReflectPhase/HTMLReflection.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/components/ThreadedCommentBase.tsx
  packages/client/components/promptResponse/BubbleMenuButton.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
  packages/client/components/promptResponse/TipTapLinkMenu.tsx
  packages/client/components/promptResponse/TiptapLinkExtension.ts
  packages/client/hooks/useTipTapCommentEditor.ts
  packages/client/hooks/useTipTapIcebreakerEditor.ts
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/hooks/useTipTapTaskEditor.ts
  packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
  packages/client/package.json
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/tiptap/extensions/imageUpload/ImageUpload.ts
  packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
  yarn.lock
Labels: size/m

#10795 chore: add extra logging to gql executor timeouts
  packages/server/graphql/ResponseStream.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
Labels: size/s

#10808 fix: Hook error during grouping reflections
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
Labels: size/s

#10806 fix: Don't scroll discussions on new reactjis
  packages/client/components/ThreadedCommentFooter.tsx
Labels: size/s

#10723 fix: update icebreaker styles
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
  packages/client/styles/theme/global.css
Labels: size/s

#10818 fix: revert global styles change
  packages/client/styles/theme/global.css
Labels: size/s

#10821 chore: flush pending GQL executor jobs before graceful shutdown
  packages/gql-executor/gqlExecutor.ts
  packages/server/utils/Logger.ts
  packages/server/utils/publishInternalGQL.ts
  packages/server/utils/sendToSentry.ts
Labels: size/s

#10798 feat(Mattermost Plugin): Cleanup sidepanel
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/InviteToMeetingModal/InviteToMeetingModal.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
  packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
  packages/mattermost-plugin/components/LoadingSpinner.tsx
  packages/mattermost-plugin/components/Menu.tsx
  packages/mattermost-plugin/components/Modal.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/components/Select.tsx
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/components/Sidepanel/MeetingRow.tsx
  packages/mattermost-plugin/components/Sidepanel/PanelTitle.tsx
  packages/mattermost-plugin/components/Sidepanel/SidePanel.tsx
  packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
  packages/mattermost-plugin/components/Sidepanel/index.tsx
  packages/mattermost-plugin/components/SimpleSelect.tsx
  packages/mattermost-plugin/hooks/useCurrentChannel.tsx
  packages/mattermost-plugin/hooks/useCurrentUser.tsx
  packages/mattermost-plugin/hooks/useInviteToMeeting.ts
  packages/mattermost-plugin/hooks/useInviteToTeam.ts
  packages/mattermost-plugin/hooks/useLinkTeam.tsx
  packages/mattermost-plugin/hooks/useUnlinkTeam.tsx
  packages/mattermost-plugin/package.json
  packages/mattermost-plugin/reducers.ts
  yarn.lock
Labels: size/l

#10829 fix: use canonical image storage path helper func
  packages/server/postgres/migrations/2025-01-08T15:10:42.442Z_addRetroTemplateLikeWishWonder.ts
Labels: Skip Maintainer Review

#10830 fix: app version on dev server
  scripts/webpack/dev.servers.config.js
Labels: size/xs

#10834 fix: remove hardcoded action.parabol.co from the application code
  packages/server/createSSR.ts
  packages/server/graphql/public/mutations/helpers/getTopics.ts
  packages/server/utils/OpenAIServerManager.ts
Labels: size/xs

#10835 fix: update icebreaker styles
  packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
Labels: size/xs

#10832 chore(Mattermost Plugin): Push command list from the client
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/reducers.ts
Labels: size/s

#10839 fix: bump trebuchet-client
  packages/client/package.json
Labels: size/xs

#10841 fix: no smart title, log socket server id
  packages/client/mutations/AutogroupMutation.ts
  packages/client/mutations/EndDraggingReflectionMutation.ts
  packages/server/graphql/ResponseStream.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
  packages/server/utils/publishInternalGQL.ts
Labels: size/s

#10844 chore: bump typescript
  package.json
  packages/client/Atmosphere.ts
  packages/server/fileStorage/FileStoreManager.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/graphql/private/mutations/helpers/generateIdenticon.ts
  packages/server/pipeStreamOverResponse.ts
  yarn.lock
Labels: size/s

#10852 fix: log userId on missing user disconnect
  packages/server/graphql/private/mutations/disconnectSocket.ts
Labels: size/xs

#10850 fix(Mattermost Plugin): Update Parabol URLs
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/hooks/useInviteToMeeting.ts
Labels: size/s

#10855 fix: delay cleaning user presence
  packages/client/types/AuthToken.d.ts
  packages/client/types/reactHTML4.d.ts
  packages/embedder/custom.d.ts
  packages/gql-executor/gqlExecutor.ts
  packages/server/graphql/ResponseStream.ts
  packages/server/graphql/executeGraphQL.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
  packages/server/listenHandler.ts
  packages/server/types/GQLRequest.d.ts
  packages/server/types/custom.d.ts
  packages/server/utils/PubSubPromise.ts
  packages/server/utils/getGraphQLExecutor.ts
  packages/server/utils/publishInternalGQL.ts
  packages/server/utils/publishWebhookGQL.ts
Labels: size/m

#10846 feat(orgAdmin): add sortable `memberCount` and `lastMetAt` columns in OrgTeams view
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/types/Team.ts
Labels: size/m

#10870 fix: client resub on server redeploy
  packages/client/package.json
  packages/server/graphql/subscribeGraphQL.ts
  packages/server/socketHandlers/handleClose.ts
  yarn.lock
Labels: size/s

#10871 fix: put dashboard routes inside dashboard components
  packages/client/components/Dashboard.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
Labels: size/s

#10873 fix: end xreadgroup gracefully on shutdown
  packages/gql-executor/RedisStream.ts
  packages/gql-executor/gqlExecutor.ts
  packages/server/graphql/private/mutations/disconnectSocket.ts
  packages/server/package.json
  packages/server/socketHandlers/handleDisconnect.ts
  packages/server/utils/serverHealthChecker.ts
  yarn.lock
Labels: size/s

#10879 fix: remove handleDisconnect logs
  packages/server/socketHandlers/handleDisconnect.ts
  packages/server/utils/serverHealthChecker.ts
Labels: size/xs

#10882 chore: update target GCS bucket for IB action
  .github/workflows/ironbank.yml
Labels: size/xs

#10836 fix: empty discussion stages
  packages/client/components/RetroGroupPhase.tsx
  packages/server/graphql/mutations/helpers/addDiscussionTopics.ts
  packages/server/graphql/mutations/helpers/removeEmptyReflections.ts
Labels: size/s

#10886 fix: Failed to execute `removeChild`
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
Labels: size/s

#10888 fix: Show error message when failing to integrate with Azure DevOps
  packages/client/modules/teamDashboard/components/ProviderRow/AzureDevOpsProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/GcalProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/GitHubProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/GitLabProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
Labels: size/s

#10892 fix: Increase integration OAuth2 access token size
  packages/server/postgres/migrations/2025-02-18T17:07:41.668Z_increaseTeamMemberIntegrationAuthAccessTokenSize.ts
Labels: size/s

#10802 feat: Pages
  .env.example
  codegen.json
  package.json
  packages/client/components/Dashboard.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/components/promptResponse/TiptapLinkExtension.ts
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/modules/pages/MakePage.tsx
  packages/client/modules/pages/Page.tsx
  packages/client/mutations/useCreatePageMutation.ts
  packages/client/package.json
  packages/client/shared/themeBackgroundColors.ts
  packages/client/shared/toSlug.ts
  packages/client/styles/theme/global.css
  packages/client/types/modules.d.ts
  packages/mattermost-plugin/package.json
  packages/server/graphql/private/mutations/helpers/generateIdenticon.ts
  packages/server/graphql/public/mutations/createPage.ts
  packages/server/graphql/public/typeDefs/CreatePagePayload.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/Page.graphql
  packages/server/graphql/public/types/Page.ts
  packages/server/hocusPocus.ts
  packages/server/package.json
  packages/server/postgres/migrations/2025-02-19T21:28:49.250Z_pages.ts
  packages/server/postgres/types/index.d.ts
  packages/server/server.ts
  packages/server/utils/feistelCipher.ts
  scripts/webpack/dev.client.config.js
  yarn.lock
Labels: size/l

#10903 fix: in prod connect ws to /hocuspocus to get forwarded
  packages/client/hooks/useTipTapPageEditor.ts
Labels: size/xs

#10908 fix: schedule time inaccuracy
  packages/client/components/Recurrence/RecurrenceSettings.tsx
  packages/client/components/Recurrence/RecurrenceTimePicker.tsx
Labels: size/s

#10912 fix: issues when replying to comments
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/hooks/useTipTapCommentEditor.ts
Labels: size/xs

#10929 fix: no ai title for custom groups
  packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
  packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
Labels: size/s

#10911 feat: insights block
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/EmojiDropdown.tsx
  packages/client/components/MeetingDatePicker.tsx
  packages/client/components/MeetingTypePickerCombobox.tsx
  packages/client/components/MentionDropdown.tsx
  packages/client/components/NewMeetingTeamPicker.tsx
  packages/client/components/OrgAdminActionMenu.tsx
  packages/client/components/SendCommentButton.tsx
  packages/client/components/SpecificMeetingPicker.tsx
  packages/client/components/SpecificMeetingPickerRoot.tsx
  packages/client/components/TaskTagDropdown.tsx
  packages/client/components/TeamPickerCombobox.tsx
  packages/client/components/TeamPickerComboboxRoot.tsx
  packages/client/components/promptResponse/BubbleMenuButton.tsx
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/package.json
  packages/client/shared/tiptap/extensions/InsightsBlockBase.ts
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/tiptap/extensions/imageBlock/ImageBlockBubbleMenu.tsx
  packages/client/tiptap/extensions/imageBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/imageUpload/InsightsBlockView.tsx
  packages/client/tiptap/extensions/slashCommand/SlashCommandMenu.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
  packages/client/ui/Checkbox/Checkbox.tsx
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/ui/Menu/MenuItem.tsx
  packages/client/ui/Menu/MenuItemCheckbox.tsx
  packages/client/ui/Menu/MenuLabelTrigger.tsx
  packages/mattermost-plugin/index.css
  packages/server/graphql/public/typeDefs/MeetingConnection.graphql
  packages/server/graphql/public/typeDefs/MeetingEdge.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/User.ts
  tailwind.config.js
  yarn.lock
Labels: size/l

#10933 chore: Minor Mattermost Plugin fixes
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/InviteToMeetingModal/InviteToMeetingModal.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
  packages/mattermost-plugin/components/NoLinkedTeamsModal.tsx
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/components/Sidepanel/MeetingRow.tsx
  packages/mattermost-plugin/components/Sidepanel/SidePanel.tsx
  packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
  packages/mattermost-plugin/components/Sidepanel/index.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/hooks/useStartMeeting.tsx
  packages/mattermost-plugin/resolvers.ts
Labels: size/m
