Repository ParabolInc/parabol, pull requests merged in 2025-09, with the labels that each got.

#11967 chore: add tags to dd-traces for hocusPocus
  packages/server/hocusPocus.ts
  packages/server/utils/tiptap/hocusPocusRedis.ts
Labels: size/s

#11976 fix: distinct orgs for pages feature flag migration
  packages/server/postgres/migrations/2025-09-02T12:57:32.479Z_updatePagesFeatureFlag.ts
Labels: size/xs

#11980 chore: reduce logs from server health checker
  packages/server/utils/serverHealthChecker.ts
Labels: size/s

#11981 fix: handle publish to public pages correctly
  packages/server/utils/tiptap/hocusPocusRedisPublisher.ts
Labels: size/s

#11986 fix: version match relay to latest
  package.json
  packages/client/package.json
  packages/mattermost-plugin/package.json
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/s

#11995 chore(heap-dump): allow customizing the folder where the heap dumps are stored
  .env.example
  packages/server/graphql/private/mutations/dumpHeap.ts
Labels: size/xs

#12007 fix: give new users access to shared pages
  packages/client/modules/pages/PageEntry.tsx
  packages/client/modules/pages/PageSharing.tsx
  packages/client/modules/pages/usePageSharingAutocomplete.ts
  packages/client/utils/handleSuccessfulLogin.ts
  packages/server/__tests__/pageAccess.test.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/queries/page.ts
  packages/server/graphql/public/queries/public.ts
  packages/server/graphql/public/typeDefs/PublicRoot.graphql
  packages/server/graphql/public/typeDefs/Query.graphql
  packages/server/graphql/public/types/PublicRoot.ts
  packages/server/postgres/migrations/2025-09-09T16:35:08.159Z_newUserPageAccessTrigger.ts
Labels: size/m

#11973 feat: send page invites to externals via email
  packages/client/modules/email/components/PageSharedInvite.tsx
  packages/client/modules/pages/PageNoAccess.tsx
  packages/client/utils/makeAppURL.ts
  packages/server/email/pageSharedEmailCreator.tsx
  packages/server/graphql/public/mutations/updatePageAccess.ts
Labels: size/m

#12008 chore: add tests for public/restricted pages
  packages/server/__tests__/pageAccess.test.ts
Labels: size/m

#12016 fix: support server usage
  packages/server/email/makeSummaryEmailV2.tsx
  packages/server/utils/tiptap/generateHTML.ts
Labels: size/s

#12036 fix: use watwg-node/fetch for everything on server
  packages/server/graphql/nestedSchema/nestLinearEndpoint.ts
Labels: size/xs

#12045 fix: when restoring child without parent, remove parent from ancestorIds
  packages/server/graphql/public/mutations/archivePage.ts
Labels: size/xs

#12051 chore: improve log format for Datadog ingestion
  packages/server/utils/Logger.ts
Labels: size/s

#12063 fix: dont download packages newer than 2 days old by default
  package.json
  pnpm-workspace.yaml
Labels: size/xs

#12068 chore: add dataloader cache debugging field
  packages/embedder/WorkflowOrchestrator.ts
  packages/server/dataloader/DataLoaderCache.ts
  packages/server/dataloader/__tests__/activeOrganizationUsersCustomLoader.test.ts
  packages/server/dataloader/__tests__/isCompanyDomain.test.ts
  packages/server/dataloader/__tests__/usersCustomRedisQueries.test.ts
  packages/server/dataloader/getNewDataLoader.ts
  packages/server/dataloader/hydrateDataLoader.ts
  packages/server/graphql/getDataLoader.ts
  packages/server/graphql/public/mutations/helpers/__tests__/getIsEmailApprovedByOrg.test.ts
  packages/server/graphql/public/mutations/helpers/movePageToNewParent.ts
  packages/server/hocusPocus.ts
  packages/server/integrations/mattermost/mattermostWebhookHandler.ts
  packages/server/utils/callGQL.ts
  packages/server/utils/tiptap/createChildPage.ts
  packages/server/utils/useDisposeDataloader.ts
  packages/server/wsHandler.ts
Labels: size/s

#12070 fix: dispose dataloaders on socket disconnect
  packages/server/graphql/private/mutations/dumpHeap.ts
  packages/server/wsHandler.ts
Labels: size/xs

#12048 feat: add audit logs
  .env.example
  packages/server/utils/useAuditLogs.ts
  packages/server/yoga.ts
Labels: size/m

#12034 chore: disable static file handle if not needed
  packages/server/fileStorage/GCSManager.ts
  packages/server/server.ts
Labels: size/s

#12073 fix: add error handling on initial script load
  packages/client/serviceWorker/sw.ts
  template.html
Labels: size/m

#12111 fix: name chronos jobs
  packages/server/chronos.ts
Labels: size/xs

#12120 fix: logout user if they have an expired token
  packages/client/Atmosphere.ts
  packages/client/components/ViewerNotOnTeam.tsx
  packages/client/tiptap/providerManager.ts
  packages/server/graphql/public/typeDefs/TeamInvitationPayload.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/types/TeamInvitationPayload.ts
  packages/server/hocusPocus.ts
Labels: size/s

#12124 fix: do not log failed permission checks
  packages/server/graphql/public/rules/hasOrgRole.ts
  packages/server/graphql/public/rules/isAuthenticated.ts
  packages/server/graphql/public/rules/isOrgTier.ts
  packages/server/graphql/public/rules/isSuperUser.ts
  packages/server/graphql/public/rules/isUserViewer.ts
  packages/server/graphql/public/rules/isViewerBillingLeader.ts
  packages/server/graphql/public/rules/isViewerOnOrg.ts
Labels: size/s

#12130 fix: only call on meetingId change setAppLocation
  packages/client/components/MeetingSelector.tsx
  packages/client/utils/createWSClient.ts
Labels: size/s
