Repository ParabolInc/parabol, pull requests merged in 2025-08, with the labels that each got.

#11656 chore: fix server source maps path for Datadog
  .github/workflows/build.yml
Labels: size/s

#11658 chore: fix source map path back
  .github/workflows/build.yml
Labels: size/xs

#11695 fix: drop unused dependencies chart.js, immutablejs
  package.json
  packages/client/package.json
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/xs

#11696 fix: always consume stream before abort handler throws
  package.json
  packages/client/utils/AtlassianManager.ts
  packages/server/fileStorage/GCSManager.ts
  pnpm-lock.yaml
Labels: size/s

#11698 fix: remove reconnecting toast
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/ErrorComponent/ErrorComponent.tsx
  packages/client/components/PokerSidebarEstimateSection.tsx
  packages/client/mutations/UpdateTaskMutation.ts
  packages/client/utils/createWSClient.ts
  packages/server/utils/uwsGetIP.ts
  packages/server/wsHandler.ts
Labels: size/s

#11709 fix: tiptap memory leak
  packages/client/hooks/useGotoStageId.ts
  packages/server/email/renderSSRElement.tsx
  packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
  packages/server/graphql/mutations/helpers/addSeedTasks.ts
  packages/server/graphql/mutations/helpers/dumpTranscriptToPage.ts
  packages/server/graphql/mutations/helpers/summaryPage/publishSummaryPage.ts
  packages/server/graphql/mutations/helpers/summaryPage/streamSummaryBlocksToPage.ts
  packages/server/package.json
  packages/server/utils/tiptap/generateJSON.ts
  pnpm-lock.yaml
Labels: size/m

#11737 feat: add page access modal
  package.json
  packages/client/lint-staged.config.js
  packages/client/modules/pages/Page.tsx
  packages/client/modules/pages/PageEntry.tsx
  packages/client/modules/pages/PageNoAccess.tsx
  packages/client/modules/pages/PageRoot.tsx
  packages/client/modules/pages/PageSharing.tsx
  packages/client/modules/pages/usePageSharingAutocomplete.ts
  packages/client/ui/Dialog/DialogContent.tsx
  packages/embedder/lint-staged.config.js
  packages/mattermost-plugin/lint-staged.config.js
  packages/mattermost-plugin/package.json
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/lint-staged.config.js
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/m

#11815 fix: hide access to teams and orgs
  packages/client/mutations/useUpdatePageAccessMutation.ts
  packages/server/__tests__/createPage.test.ts
  packages/server/graphql/mutations/helpers/summaryPage/getPokerTable.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/typeDefs/OrganizationPartial.graphql
  packages/server/graphql/public/typeDefs/OrganizationPreview.graphql
  packages/server/graphql/public/typeDefs/PageAccessOrganization.graphql
  packages/server/graphql/public/typeDefs/PageAccessTeam.graphql
  packages/server/graphql/public/typeDefs/PageAccessUser.graphql
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/typeDefs/TeamPartial.graphql
  packages/server/graphql/public/typeDefs/TeamPreview.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/typeDefs/UserPartial.graphql
  packages/server/graphql/public/typeDefs/UserPreview.graphql
  packages/server/graphql/public/types/ActionMeeting.ts
  packages/server/graphql/public/types/PageAccessOrganization.ts
  packages/server/graphql/public/types/PageAccessTeam.ts
  packages/server/graphql/public/types/PageAccessUser.ts
  packages/server/graphql/public/types/PokerMeeting.ts
  packages/server/graphql/public/types/RetrospectiveMeeting.ts
Labels: size/m

#11824 fix: prefix breadcrumbs with team name
  packages/client/modules/pages/PageBreadCrumbs.tsx
  packages/client/mutations/useUpdatePageMutation.ts
  packages/server/graphql/public/typeDefs/PagePartial.graphql
  packages/server/graphql/public/typeDefs/PagePreview.graphql
  packages/server/graphql/public/types/Page.ts
  packages/server/graphql/public/types/PagePartial.ts
Labels: size/s

#11867 chore(gh-actions): report to Slack GH Actions docker-external, ironbank and release-please if they fail.
  .github/workflows/docker-external.yml
  .github/workflows/ironbank.yml
  .github/workflows/release-please.yml
Labels: size/s

#11880 fix: update top-level title updates
  packages/server/hocusPocus.ts
Labels: size/xs

#11886 fix: remove poker template dimensions
  packages/server/graphql/mutations/removePokerTemplateDimension.ts
  packages/server/graphql/types/RemovePokerTemplateDimensionPayload.ts
Labels: size/xs

#11891 fix: fetch active meetings when joining public team
  packages/client/mutations/JoinTeamMutation.ts
Labels: size/xs

#11892 chore: decode HTML entities for issue titles
  .github/workflows/new-datadog-issue.yml
Labels: size/s

#11901 feat: Public Pages without Auth
  packages/client/Atmosphere.ts
  packages/client/components/Action/Action.tsx
  packages/client/components/PageRoute.tsx
  packages/client/components/PrivatePage.tsx
  packages/client/components/PrivateRoutes.tsx
  packages/client/hooks/useAuthRoute.ts
  packages/client/modules/pages/Page.tsx
  packages/client/modules/pages/PageAccessCombobox.tsx
  packages/client/modules/pages/PageAccessComboboxControl.tsx
  packages/client/modules/pages/PageDeletedHeader.tsx
  packages/client/modules/pages/PageEntry.tsx
  packages/client/modules/pages/PageHeader.tsx
  packages/client/modules/pages/PageHeaderPublic.tsx
  packages/client/modules/pages/PageRoot.tsx
  packages/client/modules/pages/PageSharing.tsx
  packages/client/modules/pages/PageSharingAccessList.tsx
  packages/client/modules/pages/PageSharingGeneralAccess.tsx
  packages/client/modules/pages/usePageSharingAutocomplete.ts
  packages/client/mutations/useArchivePageMutation.ts
  packages/client/mutations/useUpdatePageAccessMutation.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/providerManager.ts
  packages/server/__tests__/createPage.test.ts
  packages/server/dataloader/pageLoaderMakers.ts
  packages/server/graphql/public/mutations/archivePage.ts
  packages/server/graphql/public/mutations/helpers/movePageToNewParent.ts
  packages/server/graphql/public/mutations/updatePageAccess.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/typeDefs/NotificationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/Query.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/Query.ts
  packages/server/graphql/public/types/User.ts
  packages/server/hocusPocus.ts
  packages/server/utils/publishPageNotification.ts
  packages/server/utils/tiptap/createChildPage.ts
  packages/server/utils/tiptap/createTopLevelPage.ts
  packages/server/utils/tiptap/hocusPocusRedisPublisher.ts
Labels: size/l

#11929 fix: shared pages include top-level accessible
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/postgres/select.ts
Labels: size/s

#11931 fix: left nav max length overflow
  packages/client/components/DashNavList/LeftNavHeader.tsx
  packages/client/components/DashNavList/LeftNavItem.tsx
  packages/client/components/DashNavList/LeftNavItemButtons.tsx
  packages/client/components/DashNavList/LeftNavPageLink.tsx
  packages/client/components/DashNavList/LeftNavTeamLink.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
Labels: size/s

#11932 chore: measure hocusPocus store document
  packages/server/utils/tiptap/hocusPocusRedis.ts
Labels: size/s

#11937 fix: do not crash when failing to acquire page store lock
  packages/server/utils/tiptap/hocusPocusRedis.ts
Labels: size/s

#11943 chore: add more hocus pocus tracing
  packages/server/hocusPocus.ts
Labels: size/s

#11947 feat: add starter actions for adding insights
  packages/client/modules/pages/Page.tsx
  packages/client/modules/pages/StarterActions.tsx
  packages/client/shared/tiptap/extensions/InsightsBlockBase.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/isCustomNodeSelected.ts
Labels: size/s

#11951 fix: shared pages include pages where teamId is null
  packages/server/graphql/public/types/User.ts
Labels: size/xs
