Repository ParabolInc/parabol, pull requests merged in 2025-03, with the labels that each got.

#10899 chore(Notifications): Refactor notification settings to be per team
  codegen.json
  package.json
  packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
  packages/client/modules/teamDashboard/components/ProviderRow/NotificationSettings.tsx
  packages/client/mutations/SetNotificationSettingMutation.ts
  packages/client/mutations/SetTeamNotificationSettingMutation.ts
  packages/client/shared/gqlIds/TeamNotificationSettingsId.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/dataloader/integrationAuthLoaders.ts
  packages/server/dataloader/primaryKeyLoaderMakers.ts
  packages/server/graphql/mutations/addIntegrationProvider.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/public/mutations/addIntegrationProvider.ts
  packages/server/graphql/public/mutations/addTeamMemberIntegrationAuth.ts
  packages/server/graphql/public/mutations/setNotificationSetting.ts
  packages/server/graphql/public/mutations/setTeamNotificationSetting.ts
  packages/server/graphql/public/typeDefs/MSTeamsIntegration.graphql
  packages/server/graphql/public/typeDefs/MattermostIntegration.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/SetNotificationSettingPayload.graphql
  packages/server/graphql/public/typeDefs/SetNotificationSettingSuccess.graphql
  packages/server/graphql/public/typeDefs/SetTeamNotificationSettingPayload.graphql
  packages/server/graphql/public/typeDefs/SetTeamNotificationSettingSuccess.graphql
  packages/server/graphql/public/typeDefs/TeamMemberIntegrationAuthWebhook.graphql
  packages/server/graphql/public/typeDefs/TeamNotificationSettings.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/types/IntegrationProvider.ts
  packages/server/graphql/public/types/IntegrationProviderOAuth1.ts
  packages/server/graphql/public/types/IntegrationProviderOAuth2.ts
  packages/server/graphql/public/types/IntegrationProviderWebhook.ts
  packages/server/graphql/public/types/MSTeamsIntegration.ts
  packages/server/graphql/public/types/MattermostIntegration.ts
  packages/server/graphql/public/types/SetNotificationSettingSuccess.ts
  packages/server/graphql/public/types/SetTeamNotificationSettingSuccess.ts
  packages/server/graphql/public/types/TeamMemberIntegrationAuthWebhook.ts
  packages/server/graphql/public/types/TeamNotificationSettings.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/AddIntegrationProviderPayload.ts
  packages/server/graphql/types/IntegrationProvider.ts
  packages/server/graphql/types/IntegrationProviderOAuth1.ts
  packages/server/graphql/types/IntegrationProviderOAuth2.ts
  packages/server/graphql/types/IntegrationProviderSharedSecret.ts
  packages/server/graphql/types/IntegrationProviderWebhook.ts
  packages/server/postgres/migrations/2025-02-28T15:28:11.536Z_notificationSettingsPerTeamAndChannel.ts
  packages/server/postgres/queries/upsertIntegrationProvider.ts
  yarn.lock
Labels: size/xl

#10805 feat: add client-side RemoveMultipleOrgUsersMutation
  packages/client/modules/teamDashboard/components/TeamDashMainRoot.tsx
  packages/client/mutations/RemoveMultipleOrgUsersMutation.ts
  packages/client/mutations/RemoveOrgUserMutation.ts
  packages/client/mutations/handlers/handleTasksForRemovedUsers.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TaskSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/client/utils/onMeetingRoute.ts
  packages/server/graphql/mutations/helpers/removeFromOrg.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/mutations/removeOrgUser.ts
  packages/server/graphql/public/mutations/removeMultipleOrgUsers.ts
  packages/server/graphql/public/typeDefs/NotificationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/OrganizationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveMultipleOrgUsersSuccess.graphql
  packages/server/graphql/public/typeDefs/TaskSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/types/RemoveMultipleOrgUsersSuccess.ts
Labels: size/l

#10943 chore: Add loginMattermost private mutation
  packages/server/graphql/private/mutations/loginMattermost.ts
  packages/server/graphql/private/typeDefs/Mutation.graphql
  packages/server/integrations/mattermost/mattermostWebhookHandler.ts
  packages/server/postgres/queries/src/upsertIntegrationProviderQuery.sql
  packages/server/postgres/queries/upsertIntegrationProvider.ts
  scripts/toolboxSrc/primeIntegrations.ts
Labels: size/m

#10946 feat(templates): allow org admins to access team templates
  packages/server/graphql/public/types/MeetingTemplate.ts
Labels: Skip Maintainer Review, size/s

#10947 chore: rename removeMultipleOrgUsers to removeOrgUsers
  codegen.json
  packages/client/mutations/RemoveOrgUsersMutation.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TaskSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/public/mutations/removeOrgUsers.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/NotificationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/OrganizationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveMultipleOrgUsersPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveOrgUsersPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveOrgUsersSuccess.graphql
  packages/server/graphql/public/typeDefs/TaskSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/public/types/RemoveOrgUsersSuccess.ts
Labels: size/m

#10950 chore(Mattermost Plugin): Poll active meetings
  packages/mattermost-plugin/Atmosphere.ts
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
Labels: size/s

#10936 feat: insights backend
  package.json
  packages/client/Atmosphere.ts
  packages/client/components/AnalyticsPage.tsx
  packages/client/components/MeetingDatePicker.tsx
  packages/client/components/MeetingTypePickerCombobox.tsx
  packages/client/components/SpecificMeetingPicker.tsx
  packages/client/components/SpecificMeetingPickerRoot.tsx
  packages/client/components/TeamPickerCombobox.tsx
  packages/client/components/TeamPickerComboboxRoot.tsx
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterTeamAssigneeMenu.tsx
  packages/client/modules/pages/Page.tsx
  packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
  packages/client/package.json
  packages/client/shared/tiptap/extensions/InsightsBlockBase.ts
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/docWithID/UniqueID.ts
  packages/client/tiptap/extensions/imageUpload/InsightsBlockView.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockResult.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockView.tsx
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
  packages/client/ui/Menu/MenuContent.tsx
  packages/client/ui/Menu/MenuItemCheckbox.tsx
  packages/client/utils/getSAMLIdP.ts
  packages/client/utils/tiptapMentionConfig.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/graphql/handleGraphQLTrebuchetRequest.ts
  packages/server/graphql/mutations/helpers/generateStandupMeetingSummary.ts
  packages/server/graphql/public/fields/pageInsights.ts
  packages/server/graphql/public/mutations/helpers/getTopics.ts
  packages/server/graphql/public/typeDefs/ContentFormatEnum.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/package.json
  packages/server/postgres/constants.ts
  packages/server/postgres/migrations/2025-02-28T19:04:28.992Z_tokenUsage.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/PubSubPromise.ts
  packages/server/utils/makeMeetingInsightInput.ts
  yarn.lock
Labels: size/l

#10931 fix: line height, padding for editor instances
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/EditableText.tsx
  packages/client/components/EditingStatus/EditingStatus.tsx
  packages/client/components/ParabolScopingSearchResultItem.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionCard/ReflectionCardAuthor.tsx
  packages/client/components/ReflectionGroup/RemoteReflection.tsx
  packages/client/components/RetroReflectPhase/HTMLReflection.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/components/TeamPrompt/TeamPromptGridDimensions.ts
  packages/client/components/ThreadedAvatarColumn.tsx
  packages/client/components/ThreadedCommentBase.tsx
  packages/client/components/ThreadedItemHeaderDescription.tsx
  packages/client/components/ThreadedTaskBase.tsx
  packages/client/components/promptResponse/TipTapEditor.tsx
  packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooter.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterTeamAssignee.tsx
  packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterUserAssignee.tsx
  packages/client/modules/pages/Page.tsx
  packages/client/styles/theme/global.css
Labels: size/m

#10905 feat(Mattermost Plugin): Configure notifications
  packages/mattermost-plugin/components/ConfigureNotificationsModal/ConfigureNotificationsModal.tsx
  packages/mattermost-plugin/components/ConfigureNotificationsModal/NotificationSettings.tsx
  packages/mattermost-plugin/components/ConfigureNotificationsModal/index.tsx
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/InviteToMeetingModal/InviteToMeetingModal.tsx
  packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
  packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
  packages/mattermost-plugin/components/Modal.tsx
  packages/mattermost-plugin/components/ModalRoot.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/components/Sidepanel/SidePanel.tsx
  packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/hooks/useAtmosphere.ts
  packages/mattermost-plugin/hooks/useConfig.ts
  packages/mattermost-plugin/hooks/useCurrentChannel.ts
  packages/mattermost-plugin/hooks/useCurrentUser.ts
  packages/mattermost-plugin/hooks/useLinkTeam.ts
  packages/mattermost-plugin/hooks/useLinkTeam.tsx
  packages/mattermost-plugin/hooks/useMassInvitationToken.ts
  packages/mattermost-plugin/hooks/useStartMeeting.ts
  packages/mattermost-plugin/hooks/useTipTapTaskEditor.ts
  packages/mattermost-plugin/hooks/useUnlinkTeam.ts
  packages/mattermost-plugin/hooks/useUnlinkTeam.tsx
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/public/mattermost-plugin-commands.json
  packages/mattermost-plugin/reducers.ts
  packages/mattermost-plugin/resolvers.ts
  packages/mattermost-plugin/selectors.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/public/mutations/linkMattermostChannel.ts
  packages/server/graphql/public/mutations/unlinkMattermostChannel.ts
  packages/server/graphql/public/typeDefs/AddTeamMemberIntegrationAuthPayload.graphql
  packages/server/graphql/public/typeDefs/LinkMattermostChannelPayload.graphql
  packages/server/graphql/public/typeDefs/LinkMattermostChannelSuccess.graphql
  packages/server/graphql/public/typeDefs/MattermostIntegration.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/UnlinkMattermostChannelPayload.graphql
  packages/server/graphql/public/typeDefs/UnlinkMattermostChannelSuccess.graphql
  packages/server/graphql/public/types/MattermostIntegration.ts
Labels: size/xl

#10960 chore(Mattermost Plugin): Update notify API
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
Labels: size/xs

#10963 feat: copy insights to markdown
  packages/client/components/SpecificMeetingPicker.tsx
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
  packages/client/package.json
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/insightsBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockResult.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockView.tsx
  packages/client/utils/quickHash.ts
  packages/server/graphql/public/fields/pageInsights.ts
  packages/server/package.json
  packages/server/postgres/migrations/2025-02-28T19:04:28.992Z_tokenUsage.ts
  packages/server/utils/convertTipTapToMarkdown.ts
  static/css/Draft.css
  yarn.lock
Labels: size/m

#10964 chore(Mattermost Plugin): Sidepanel styling
  packages/client/components/Tabs/Tabs.tsx
  packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelector.tsx
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/components/Sidepanel/SidePanel.tsx
  packages/mattermost-plugin/components/Sidepanel/index.tsx
Labels: size/m

#10967 chore(Mattermost Plugin): Error and loading states
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
  packages/mattermost-plugin/components/LoadingSpinner.tsx
  packages/mattermost-plugin/components/Modal.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/components/Sidepanel/MeetingRow.tsx
  packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/hooks/useLinkTeam.ts
  packages/mattermost-plugin/hooks/useStartMeeting.ts
  packages/mattermost-plugin/hooks/useUnlinkTeam.ts
Labels: size/m

#10971 fix: getIsEmailApprovedByOrg was overly permissive
  packages/server/graphql/public/mutations/helpers/__tests__/getIsEmailApprovedByOrg.test.ts
  packages/server/graphql/public/mutations/helpers/getIsEmailApprovedByOrg.ts
Labels: size/s

#10970 chore: update copy that says only team leads can upgrade
  packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
Labels: size/xs

#10976 chore(postgresql): upgrade pgvector to 0.8.0
  .github/workflows/build.yml
  .github/workflows/test.yml
  docker/stacks/development/docker-compose.yml
  docker/stacks/single-tenant-host/docker-compose.yml
Labels: size/xs

#10977 feat(pages): drag handles, copy/paste markdown
  packages/client/components/SpecificMeetingPicker.tsx
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/modules/pages/Page.tsx
  packages/client/package.json
  packages/client/shared/tiptap/extensions/InsightsBlockBase.ts
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/insightsBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockResult.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockView.tsx
  packages/server/graphql/public/fields/pageInsights.ts
  yarn.lock
Labels: size/m

#10981 chore: Add logging for SAML login errors
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/s

#10951 chore: deprecate `RemoveOrgUser` in favor of `RemoveOrgUsers`
  packages/client/modules/userDashboard/components/LeaveOrgModal/LeaveOrgModal.tsx
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/modules/userDashboard/components/RemoveFromOrgModal/RemoveFromOrgModal.tsx
  packages/client/mutations/RemoveOrgUserMutation.ts
  packages/client/mutations/RemoveOrgUsersMutation.ts
  packages/client/subscriptions/NotificationSubscription.ts
  packages/client/subscriptions/OrganizationSubscription.ts
  packages/client/subscriptions/TaskSubscription.ts
  packages/client/subscriptions/TeamSubscription.ts
  packages/server/graphql/mutations/removeOrgUser.ts
  packages/server/graphql/public/mutations/removeOrgUsers.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/NotificationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/OrganizationSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/RemoveOrgUserPayload.graphql
  packages/server/graphql/public/typeDefs/TaskSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/rootTypes.ts
  packages/server/graphql/types/RemoveOrgUserPayload.ts
Labels: size/l

#10986 chore: Log attributes if the emails don't match
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/xs

#10988 fix: Handle duplicate SAML attributes
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/xs

#10639 chore: remove google language manager
  codegen.json
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/client/modules/demo/entityLookup.ts
  packages/client/modules/demo/getDemoEntities.ts
  packages/client/modules/demo/getDemoTitles.ts
  packages/client/utils/getSimpleGroupTitle.ts
  packages/client/utils/smartGroup/computeDistanceMatrix.ts
  packages/client/utils/smartGroup/computeJaccardDistanceMatrix.ts
  packages/client/utils/smartGroup/getAllLemmasFromReflections.ts
  packages/client/utils/smartGroup/getGroupSmartTitle.ts
  packages/client/utils/smartGroup/getTitleFromComputedGroup.ts
  packages/client/utils/smartGroup/groupReflections.ts
  packages/integration-tests/tests/retrospective-demo/step2-group.test.ts
  packages/integration-tests/tests/retrospective-demo/step4-discuss.test.ts
  packages/server/GoogleLanguageManager.ts
  packages/server/database/types/GoogleAnalyzedEntity.ts
  packages/server/getGoogleLanguageManager.ts
  packages/server/graphql/mutations/createReflection.ts
  packages/server/graphql/mutations/helpers/autoGroup/__tests__/getGroupMatrix.test.js
  packages/server/graphql/mutations/helpers/autoGroup/addLemmaToEntities.ts
  packages/server/graphql/mutations/helpers/autoGroup/sanitizeAnalyzedEntititesResponse.ts
  packages/server/graphql/mutations/helpers/generateAIGroupTitle.ts
  packages/server/graphql/mutations/helpers/getReflectionEntities.ts
  packages/server/graphql/mutations/helpers/getReflectionSentimentScore.ts
  packages/server/graphql/mutations/helpers/manageGoogleNLPErrorResponse.ts
  packages/server/graphql/mutations/helpers/updateGroupTitle.ts
  packages/server/graphql/mutations/updateReflectionContent.ts
  packages/server/graphql/public/permissions.ts
  packages/server/graphql/public/queries/getDemoEntities.ts
  packages/server/graphql/public/queries/getDemoGroupTitle.ts
  packages/server/graphql/public/typeDefs/GetDemoEntitiesPayload.graphql
  packages/server/graphql/public/typeDefs/GetDemoGroupTitlePayload.graphql
  packages/server/graphql/public/typeDefs/GetDemoGroupTitleSuccess.graphql
  packages/server/graphql/public/typeDefs/GoogleAnalyzedEntity.graphql
  packages/server/graphql/public/typeDefs/Query.graphql
  packages/server/graphql/public/typeDefs/RetroReflection.graphql
  packages/server/postgres/helpers/toGoogleAnalyzedEntity.ts
  packages/server/postgres/migrations/2025-03-12T18:37:30.953Z_remove-entities.ts
  packages/server/postgres/select.ts
Labels: size/xl

#10985 feat(pages): custom prompts
  .config/kyselyMigrations.ts
  codegen.json
  docker/images/parabol-ubi/environments/pipeline
  package.json
  packages/client/tiptap/extensions/insightsBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockPrompt.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockPromptRoot.tsx
  packages/server/graphql/public/fields/aiPrompts.ts
  packages/server/graphql/public/fields/pageInsights.ts
  packages/server/graphql/public/typeDefs/AIPrompt.graphql
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/AIPrompt.ts
  packages/server/graphql/public/types/User.ts
  packages/server/hocusPocus.ts
  packages/server/postgres/migrations/2025-03-12T19:52:10.902Z_aiPrompts.ts
  packages/server/postgres/types/index.d.ts
  scripts/toolboxSrc/standaloneMigrations.ts
  yarn.lock
Labels: size/m

#11000 fix: drag handles and scrollbar on specific meeting table
  packages/client/components/SpecificMeetingPicker.tsx
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockPrompt.tsx
  static/fonts/IBMPlexSans-Medium.woff2
  static/fonts/IBMPlexSans-MediumItalic.woff2
Labels: size/m

#11007 fix: placeholder regression in tiptap
  packages/client/modules/pages/Page.tsx
  packages/client/styles/theme/global.css
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
Labels: size/m

#11008 fix: several people are not editing, thank you
  packages/client/hooks/useTipTapTypingStatus.ts
Labels: size/xs

#11013 fix: Syntax error in down migration
  packages/server/postgres/migrations/2025-03-12T18:37:30.953Z_remove-entities.ts
Labels: size/xs

#11014 chore: check down migrations are valid
  .github/workflows/test.yml
  .husky/post-checkout
Labels: size/xs

#10883 chore: Security upgrade dompurify from 2.5.8 to 3.2.4
  packages/client/components/TypeAheadLabel.tsx
  packages/client/package.json
  yarn.lock
Labels: size/xs

#10997 feat: sort public teams dialog
  packages/server/graphql/public/types/Organization.ts
Labels: size/s

#10994 chore: remove public teams feature flag
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgFeatureFlags.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/postgres/migrations/2025-03-12T15:20:56.255Z_remove-publicTeams.ts
Labels: size/s

#10974 feat: implement team public/private settings
  codegen.json
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyConfirmModal.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
  packages/client/modules/userDashboard/components/OrgBilling/OrgFeatureFlags.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/mutations/DowngradeToStarterMutation.ts
  packages/client/mutations/ToggleTeamPrivacyMutation.ts
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/server/graphql/public/mutations/toggleTeamPrivacy.ts
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/ToggleTeamPrivacyPayload.graphql
  packages/server/graphql/public/typeDefs/ToggleTeamPrivacySuccess.graphql
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/public/types/ToggleTeamPrivacySuccess.ts
  packages/server/postgres/migrations/2025-03-12T15:20:56.255Z_remove-publicTeams.ts
Labels: size/m

#11025 fix: GQL retries consuming the stream on failover
  packages/gql-executor/RedisStream.ts
Labels: size/xs

#11023 feat: add gitlab to demo
  packages/client/modules/demo/ClientGraphQLServer.ts
  packages/client/modules/demo/initDB.ts
Labels: size/s

#11027 chore: Fixes for down migration checks
  .github/workflows/test.yml
  .husky/post-checkout
Labels: size/xs

#11030 chore: company query allows super user to query all companies
  packages/server/graphql/public/types/Company.ts
Labels: size/s

#10984 feat(orgAdmin): UI for mass org user removal
  packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
  packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
  packages/client/modules/userDashboard/components/RemoveFromOrgModal/RemoveFromOrgModal.tsx
  packages/client/mutations/RemoveOrgUsersMutation.ts
Labels: size/m

#11037 chore: Cork serving static files
  packages/server/pipeStreamOverResponse.ts
  packages/server/selfHostedHandler.ts
Labels: size/s

#11042 fix: Undefined TeamMember in NewMeetingCheckIn
  packages/client/components/NewMeetingCheckIn.tsx
Labels: size/xs

#11056 fix: can see public teams when there are no viewer teams
  packages/client/components/DashNavList/DashNavListTeams.tsx
Labels: size/xs

#11062 fix: correct meeting link URL in the prompt for generating meeting summaries
  packages/server/utils/OpenAIServerManager.ts
Labels: size/xs

#11061 chore: add private teams to team benefits
  packages/client/utils/constants.ts
Labels: size/xs

#11063 fix: typo on public team setting help text
  packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
Labels: size/xs

#11069 fix: Public Teams Modal Layout on Safari
  packages/client/components/DashNavList/PublicTeamsModal.tsx
Labels: size/s

#11046 feat: can choose privacy when creating a team
  packages/client/components/AddTeamDialog.tsx
  packages/client/components/AddTeamDialogRoot.tsx
  packages/client/components/AdhocTeamMultiSelect/AdhocTeamMultiSelect.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/server/graphql/mutations/helpers/addTeamValidation.ts
  packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/types/NewTeamInput.ts
Labels: size/m

#11054 feat: Join your organization when signing up with SAML
  packages/server/graphql/private/mutations/loginSAML.ts
Labels: size/s

#11070 feat: Add actions to the empty team experience
  packages/client/components/AddTeamDialog.tsx
  packages/client/components/AddTeamDialogRoot.tsx
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/EmptyTeams.tsx
  packages/client/components/DashNavList/PublicTeamsModal.tsx
  packages/client/components/EmailPasswordAuthForm.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/mutations/LoginWithGoogleMutation.ts
  packages/client/mutations/LoginWithMicrosoftMutation.ts
  packages/client/mutations/LoginWithPasswordMutation.ts
  packages/client/mutations/SignUpWithPasswordMutation.ts
  packages/client/mutations/VerifyEmailMutation.ts
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/utils/handleSuccessfulLogin.ts
Labels: size/m

#11081 refactor: replace sendAccountRemovedEvent with analytics call in user deletion mutations
  packages/server/graphql/mutations/deleteUser.ts
  packages/server/graphql/mutations/helpers/sendAccountRemovedEvent.ts
  packages/server/graphql/private/mutations/hardDeleteUser.ts
Labels: size/s

#11078 feat: team privacy UI updates
  packages/client/components/AddTeamDialog.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
Labels: size/m
