Repository ParabolInc/parabol, pull requests merged in 2025-04, with the labels that each got.

#11086 feat: update OrgMembers component to display matched users in search results
  packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Labels: Skip Maintainer Review, size/xs

#11087 feat(orgAdmin): org admin can invite people right in the org team view
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx
Labels: Skip Maintainer Review, size/s

#11093 fix: tiptap mentions
  packages/client/utils/tiptapMentionConfig.ts
Labels: size/s

#11089 chore(Mattermost Plugin): Move plugin commands
  packages/mattermost-plugin/index.tsx
  packages/mattermost-plugin/plugin-commands.json
Labels: size/xs

#11091 fix: gitlab & azure summaries show up
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryPokerStories.tsx
Labels: size/s

#11097 chore: remove S3 from Iron Bank action
  .github/workflows/ironbank.yml
Labels: size/s

#11075 chore: add metrics for page creation, insight generation, and team privacy changes
  packages/server/graphql/public/mutations/createPage.ts
  packages/server/graphql/public/mutations/generateInsight.ts
  packages/server/graphql/public/mutations/toggleTeamPrivacy.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/s

#11102 fix: dataloaders in redis bugfix
  packages/server/graphql/getDataLoader.ts
  packages/server/utils/publish.ts
Labels: size/s

#11105 fix: missing githubRequest from schema
  packages/server/activeClients.ts
  packages/server/graphql/private/rootSchema.ts
  packages/server/graphql/public/rootSchema.ts
  packages/server/integrations/gitlab/GitLabServerManager.ts
  packages/server/server.ts
  packages/server/types/custom.d.ts
  packages/server/utils/getGitHubRequest.ts
  packages/server/utils/importAll.ts
  packages/server/wsHandler.ts
Labels: size/s

#11109 fix: set app location on ws conn
  packages/client/Atmosphere.ts
  packages/client/mutations/SetAppLocationMutation.ts
Labels: size/s

#11116 fix: bugs found under production load with graphql-yoga
  packages/embedder/WorkflowOrchestrator.ts
  packages/embedder/custom.d.ts
  packages/embedder/workflows/helpers/publishSimilarRetroTopics.ts
  packages/server/hocusPocus.ts
  packages/server/utils/publish.ts
  packages/server/utils/useDatadogTracing.ts
Labels: size/m

#11119 fix: #11107 push server sourcemaps to dd
  .github/workflows/build.yml
  scripts/webpack/prod.servers.config.js
Labels: size/s

#11085 chore: refactor teams query in organization
  packages/client/components/DashNavList/DashNavList.tsx
  packages/client/components/DashNavList/DashNavListTeams.tsx
  packages/client/components/DashNavList/EmptyTeams.tsx
  packages/client/components/DashNavList/PublicTeamsModal.tsx
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/teamDashboard/components/EditTeamName/EditableTeamName.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
  packages/client/mutations/ArchiveTeamMutation.ts
  packages/client/mutations/DowngradeToStarterMutation.ts
  packages/client/mutations/fragments/PublicTeamsFrag.ts
  packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
  packages/server/graphql/public/typeDefs/Organization.graphql
  packages/server/graphql/public/types/Organization.ts
Labels: size/m

#11132 chore: Trace Azure DevOps workItems queries
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/m

#11125 fix: turn on dd resolvers
  packages/server/dataloader/RootDataLoader.ts
  packages/server/graphql/private/mutations/disconnectSocket.ts
  packages/server/utils/useDatadogTracing.ts
Labels: size/s

#11144 fix: super user can toggle ai features
  packages/server/graphql/public/mutations/toggleAIFeatures.ts
Labels: size/xs

#11130 chore: track upgrade clicks from public teams
  packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
  packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
  packages/client/shared/UpgradeCTALocationEnumType.d.ts
Labels: size/s

#11133 feat: Disable Suggest Groups button if the free team has exceeded the limit
  packages/client/components/RetroGroupPhase.tsx
Labels: Skip Maintainer Review, size/s

#11150 fix: handle sigterm more gracefully
  .env.example
  package.json
  packages/client/hooks/handleInvalidatedSession.ts
  packages/client/utils/createWSClient.ts
  packages/server/getIsShuttingDown.ts
  packages/server/graphql/getDataLoader.ts
  packages/server/server.ts
  packages/server/wsHandler.ts
  packages/server/yoga.ts
  pm2.dev.config.js
Labels: size/m

#11152 fix: sigterm faster
  packages/server/server.ts
Labels: size/s

#11155 fix: serialize using msgpack to preserve Dates for dataloaders
  packages/server/dataloader/getRedisDataLoader.ts
  packages/server/dataloader/hydrateDataLoader.ts
  packages/server/dataloader/serializeDataLoader.ts
  packages/server/package.json
  packages/server/utils/publish.ts
  yarn.lock
Labels: size/s

#11169 fix: bugs from datadog logs updateTask, acceptTeamInvitation
  packages/server/graphql/mutations/helpers/publishChangeNotifications.ts
  packages/server/graphql/public/mutations/acceptTeamInvitation.ts
Labels: size/s

#11168 chore: Update service diagram
  docs/serviceDiagram.md
Labels: size/s

#11178 fix: org admins can delete teams
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx
  packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembersMenu.tsx
Labels: size/s

#11181 fix: multipart header vuln
  packages/server/yoga.ts
Labels: size/s

#11183 fix: support poker removing unintegrated items
  packages/client/components/PokerEstimateHeaderCard.tsx
  packages/client/components/PokerEstimateHeaderCardError.tsx
Labels: size/s

#11193 fix: chronos primary lock
  packages/server/chronos.ts
Labels: size/xs

#11198 fix: terminate client WS if server does not respond
  packages/client/utils/createWSClient.ts
Labels: size/s

#11191 feat: streaming page insights
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/server/graphql/public/fields/pageInsights.ts
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/utils/OpenAIServerManager.ts
  packages/server/yoga.ts
Labels: size/m

#11204 fix: listitem updates inside insights
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockResult.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockView.tsx
Labels: size/xs

#11209 fix: bump node version
  package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#11215 fix: remove referece to dispose fn
  packages/server/wsHandler.ts
Labels: size/xs

#11220 chore: Add Self Managed GitLab to the Enterprise benefits list
  packages/client/utils/constants.ts
Labels: size/xs

#11226 chore: Use Parabol URL from environment for Mattermost Plugin
  packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
  packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
  packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/components/Sidepanel/MeetingRow.tsx
  packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
  packages/mattermost-plugin/components/Sidepanel/index.tsx
  packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
  packages/mattermost-plugin/env.js
  packages/mattermost-plugin/hooks/useConfig.ts
  packages/mattermost-plugin/hooks/useInviteToMeeting.ts
  packages/mattermost-plugin/hooks/useInviteToTeam.ts
  packages/mattermost-plugin/prod.webpack.config.js
  packages/mattermost-plugin/resolvers.ts
  packages/mattermost-plugin/webpack.config.js
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
Labels: size/m

#11213 fix: dump sockets before dumping heap
  packages/server/disconnectAllSockets.ts
  packages/server/getIsBusy.ts
  packages/server/graphql/private/mutations/dumpHeap.ts
  packages/server/graphql/private/typeDefs/Mutation.graphql
  packages/server/server.ts
  packages/server/wsHandler.ts
  packages/server/yoga.ts
Labels: size/s

#11230 fix: udpaterecurrencesetting return type
  packages/server/graphql/public/typeDefs/UpdateRecurrenceSettingsSuccess.graphql
  packages/server/graphql/public/types/UpdateRecurrenceSettingsSuccess.ts
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/xs

#11196 fix: group titles sometimes load indefinitely until refresh
  packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
  packages/client/mutations/EndDraggingReflectionMutation.ts
  packages/server/graphql/mutations/helpers/updateGroupTitle.ts
Labels: size/s

#11231 fix: bump sentry from v7 to v9
  packages/server/initSentry.ts
  packages/server/package.json
  yarn.lock
Labels: size/s

#11236 fix: pageInsights set initial prompt on load
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockPrompt.tsx
Labels: size/s

#11248 fix: Handle publish taking longer than 30s
  packages/server/billing/helpers/removeTeamsLimitObjects.ts
  packages/server/database/types/processTeamsLimitsJob.ts
  packages/server/graphql/mutations/helpers/generateAIGroupTitle.ts
  packages/server/graphql/mutations/helpers/generateGroups.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/utils/publish.ts
Labels: size/s

#11252 fix: revert back to @whatwg-node/fetch
  packages/server/package.json
  packages/server/yoga.ts
  yarn.lock
Labels: size/s

#11247 fix: disconnectAllSockets accepts an input parameters for the disconnect window
  packages/server/disconnectAllSockets.ts
  packages/server/server.ts
Labels: size/xs

#11263 fix: Switch to @whatwg/fetch throughout the server
  packages/embedder/ai_models/helpers/fetchWithRetry.ts
  packages/server/fileStorage/GCSManager.ts
  packages/server/graphql/nestedSchema/nestGitLabEndpoint.ts
  packages/server/graphql/public/mutations/embedUserAsset.ts
  packages/server/graphql/public/types/User.ts
  packages/server/hubSpot/backfillHubSpot.ts
  packages/server/hubSpot/hubSpotApi.ts
  packages/server/integrations/helpers/authorizeOAuth2.ts
  packages/server/integrations/jiraServer/JiraServerOAuth1Manager.ts
  packages/server/integrations/jiraServer/JiraServerRestManager.ts
  packages/server/jiraImagesHandler.ts
  packages/server/utils/AtlassianServerManager.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/GoogleServerManager.ts
  packages/server/utils/MSTeamsServerManager.ts
  packages/server/utils/MattermostServerManager.ts
  packages/server/utils/MicrosoftServerManager.ts
  packages/server/utils/SlackServerManager.ts
  packages/server/utils/TenorManager.ts
  packages/server/utils/fetchGQL.ts
  packages/server/utils/getSSOMetadataFromURL.ts
Labels: size/s

#11260 fix: Node 22 type fixes
  packages/embedder/package.json
  packages/server/package.json
  packages/server/pipeStreamOverResponse.ts
  yarn.lock
Labels: size/s

#11267 fix: leader election on interval
  .gitignore
  package.json
  packages/server/LeaderElector.ts
  packages/server/chronos.ts
  packages/server/package.json
  packages/server/server.ts
  yarn.lock
Labels: size/m

#11272 fix: elect chronos leader per tick
  packages/server/LeaderElector.ts
  packages/server/LeaderRunner.ts
  packages/server/chronos.ts
Labels: size/m

#11277 fix: ensure process recurrence runs sequentially
  packages/server/graphql/private/mutations/helpers/checkSequential.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
Labels: size/m
