Repository ParabolInc/parabol, pull requests merged in 2025-06, with the labels that each got.

#11376 fix: fix suUserCount after DB schema migration
  packages/server/graphql/private/queries/suUserCount.ts
Labels: size/s

#11311 fix: ungrouped reflection layout issue on kanban
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
Labels: size/s

#11393 feat: background music UI improvements
  packages/client/components/BottomControlBarMusic.tsx
  packages/client/hooks/useMeetingMusicSync.ts
Labels: size/s

#11373 feat: background music plays for subscribers
  packages/client/components/BottomControlBarMusic.tsx
  packages/client/components/MeetingControlBar.tsx
  packages/client/hooks/useBackgroundMusicManager.ts
  packages/client/hooks/useMeetingMusicSync.ts
  packages/client/mutations/SetMeetingMusicMutation.ts
  packages/client/schemaExtensions/clientSchema.graphql
  packages/client/subscriptions/MeetingSubscription.ts
  packages/server/graphql/public/mutations/setMeetingMusic.ts
  packages/server/graphql/public/typeDefs/MeetingSubscriptionPayload.graphql
  packages/server/graphql/public/typeDefs/Mutation.graphql
  packages/server/graphql/public/typeDefs/SetMeetingMusicPayload.graphql
  packages/server/graphql/public/typeDefs/SetMeetingMusicSuccess.graphql
  packages/server/graphql/public/types/SetMeetingMusicSuccess.ts
Labels: size/l

#11405 chore: hide tips on mobile
  packages/client/components/MeetingControlBar.tsx
Labels: size/xs

#11367 fix: show meeting series without active meetings in dash
  packages/client/components/MeetingCard.tsx
  packages/client/components/MeetingsDash.tsx
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/utils/date/relativeDate.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/graphql/public/typeDefs/Team.graphql
  packages/server/graphql/public/types/Team.ts
  packages/server/graphql/types/Team.ts
  packages/server/postgres/queries/src/TierEnum.sql
Labels: size/m

#11400 chore: improve recurring badge readability
  packages/client/components/MeetingCard.tsx
  packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
  packages/client/styles/theme/global.css
Labels: size/s

#11413 fix: reduce MS Teams error logs
  packages/server/utils/MSTeamsServerManager.ts
  scripts/webpack/dev.client.config.js
Labels: size/xs

#11408 chore: track background music activity
  packages/client/hooks/useMeetingMusicSync.ts
  packages/server/graphql/public/mutations/setMeetingMusic.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/s

#11375 chore: Reflect phase restyling
  packages/client/components/ReflectionCard/DeleteReflectionButton.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionCard/ReflectionCardAuthor.tsx
  packages/client/components/ReflectionCard/ReflectionCardButton.tsx
  packages/client/components/ReflectionCard/ReflectionCardDeleteButton.tsx
  packages/client/components/ReflectionCard/SpotlightButton.tsx
  packages/client/components/ReflectionCard/SubmitReflectionButton.tsx
  packages/client/components/RetroReflectPhase/PhaseItemChits.tsx
  packages/client/components/RetroReflectPhase/PhaseItemColumn.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/hooks/useIsEditing.ts
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/styles/animation.ts
  packages/client/ui/cn.ts
  packages/client/ui/twStyled.ts
  packages/integration-tests/tests/retrospective-demo/step1-reflect.test.ts
  packages/integration-tests/tests/retrospective-demo/step2-group.test.ts
  packages/integration-tests/tests/retrospective-demo/step4-discuss.test.ts
Labels: size/m, size/l

#11426 chore: kysely orderBy(array) is deprecated
  packages/embedder/EmbeddingsJobQueueStream.ts
  packages/embedder/debug.ts
  packages/embedder/importHistoricalMeetingTemplates.ts
  packages/embedder/importHistoricalRetrospectiveDiscussionTopic.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/graphql/public/types/MeetingSeries.ts
Labels: size/s

#11430 fix: migration order for delete pages
  packages/server/postgres/migrations/2025-06-12T15:06:21.490Z_delPage.ts
Labels: size/xs

#11461 feat(pages): PageLinkBlock
  packages/client/components/DashNavList/LeftNavSharedPagesSection.tsx
  packages/client/components/Dashboard.tsx
  packages/client/components/DashboardRoot.tsx
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
  packages/client/hooks/useDraggablePage.tsx
  packages/client/hooks/usePageLinkPlaceholder.ts
  packages/client/hooks/usePageProvider.ts
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/summary/components/NewMeetingSummaryRoot.tsx
  packages/client/mutations/useArchivePageMutation.ts
  packages/client/mutations/useCreatePageMutation.ts
  packages/client/mutations/useUpdatePageAccessMutation.ts
  packages/client/mutations/useUpdatePageMutation.ts
  packages/client/shared/tiptap/extensions/PageLinkBlockBase.ts
  packages/client/shared/tiptap/getAllNodesAttributesByType.ts
  packages/client/shared/tiptap/getPageLinksFromPage.ts
  packages/client/shared/tiptap/getTitleFromPageText.ts
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/tiptap/extensions/pageLinkBlock/PageLinkBlock.ts
  packages/client/tiptap/extensions/pageLinkBlock/PageLinkBlockView.tsx
  packages/client/tiptap/extensions/pageLinkPicker/PageLinkMenu.tsx
  packages/client/tiptap/extensions/pageLinkPicker/PageLinkPicker.ts
  packages/client/tiptap/extensions/renderSuggestion.ts
  packages/client/tiptap/extensions/slashCommand/slashCommands.ts
  packages/client/tiptap/getPageSlug.ts
  packages/server/graphql/public/typeDefs/User.graphql
  packages/server/graphql/public/types/User.ts
  packages/server/hocusPocus.ts
  packages/server/postgres/migrations/2025-06-18T21:19:19.608Z_PageBacklink.ts
  packages/server/updateBacklinks.ts
  packages/server/utils/CipherId.ts
  packages/server/utils/feistelCipher.ts
  packages/server/utils/tiptap/getPageLinkDiffs.ts
  packages/server/utils/tiptap/updatePageContent.ts
  packages/server/utils/tiptap/updateTitleInBacklinks.ts
  packages/server/utils/tiptap/updateYDocNodes.ts
Labels: size/l

#11446 chore: background music loops
  packages/client/hooks/useMeetingMusicSync.ts
Labels: size/xs

#11472 feat: Automatic Table of Contents for child pages
  package.json
  packages/client/components/DashNavList/LeftNavHeader.tsx
  packages/client/components/DashNavList/LeftNavItem.tsx
  packages/client/components/DashNavList/LeftNavItemButtons.tsx
  packages/client/components/DashNavList/LeftNavPrivatePagesSection.tsx
  packages/client/components/DashNavList/LeftNavSharedPagesSection.tsx
  packages/client/components/DashNavList/PageActions.tsx
  packages/client/components/Dashboard.tsx
  packages/client/components/DashboardRoot.tsx
  packages/client/modules/summary/components/NewMeetingSummary.tsx
  packages/client/modules/summary/components/NewMeetingSummaryRoot.tsx
  packages/client/shared/sortOrder.ts
  packages/client/shared/tiptap/extensions/PageLinkBlockBase.ts
  packages/client/tiptap/extensions/pageLinkBlock/PageLinkBlock.ts
  packages/client/tiptap/extensions/pageLinkBlock/PageLinkBlockView.tsx
  packages/client/ui/Menu/MenuItem.tsx
  packages/embedder/package.json
  packages/server/LeaderRunner.ts
  packages/server/establishPrimaryServer.ts
  packages/server/graphql/private/mutations/helpers/checkSequential.ts
  packages/server/graphql/public/mutations/archivePage.ts
  packages/server/graphql/public/mutations/createPage.ts
  packages/server/graphql/public/mutations/helpers/getPageNextSortOrder.ts
  packages/server/graphql/public/mutations/helpers/privatizePage.ts
  packages/server/graphql/public/mutations/updatePage.ts
  packages/server/hocusPocus.ts
  packages/server/package.json
  packages/server/postgres/helpers/logQuery.ts
  packages/server/utils/tiptap/hocusPocusHub.ts
  packages/server/utils/tiptap/hocusPocusRedis.ts
  packages/server/utils/tiptap/updatePageContent.ts
  packages/server/utils/tiptap/updateTitleInBacklinks.ts
  packages/server/utils/tiptap/updateYDocNodes.ts
  pnpm-lock.yaml
Labels: size/l

#11477 fix: ignore dismiss new feature after logout
  packages/client/hooks/useNewFeatureSnackbar.ts
  packages/client/mutations/DismissNewFeatureMutation.ts
Labels: size/s

#11481 chore: fix PR size labeler
  .github/workflows/labeler.yml
Labels: size/xs

#11371 feat: Prometheus metrics
  .env.example
  package.json
  packages/server/metricsHandler.ts
  packages/server/server.ts
  pnpm-lock.yaml
Labels: size/m

#11484 feat: zoom transcript proof of concept
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/utils/RecallAIServerManager.ts
Labels: size/m

#11494 fix: use imported quietLofi file
  packages/client/hooks/useMeetingMusicSync.ts
Labels: size/xs
