Repository ParabolInc/parabol, pull requests merged in 2025-07, with the labels that each got.

#11468 chore: improve meeting series naming
  packages/client/components/MeetingCard.tsx
  packages/client/components/MeetingsDash.tsx
  packages/client/components/NewMeetingSidebar.tsx
  packages/client/components/Recurrence/MeetingDateLabel.tsx
  packages/client/components/Recurrence/RecurrenceDayCheckbox.tsx
  packages/client/components/Recurrence/RecurrenceSettings.tsx
  packages/client/components/Recurrence/UpdateRecurrenceSettingsModal.tsx
  packages/client/components/ScheduleDialog.tsx
  packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
  packages/client/hooks/useMeetingSeriesDate.ts
  packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
  packages/client/utils/humanReadableRecurrenceRule.ts
  packages/server/__tests__/startRetrospective.test.ts
  packages/server/graphql/mutations/helpers/createMeetingSeriesTitle.ts
  packages/server/graphql/private/mutations/processRecurrence.ts
  packages/server/graphql/public/mutations/startRetrospective.ts
  packages/server/graphql/public/mutations/startTeamPrompt.ts
Labels: size/m

#10992 chore: Normalize User.tms
  packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
  packages/server/graphql/mutations/helpers/removeTeamMember.ts
  packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
  packages/server/postgres/migrations/2025-06-24T13:42:32.158Z_addTMSTriggers.ts
  packages/server/postgres/migrations/2025-06-26T13:51:02.635Z_cleanupUserTMS.ts
  packages/server/safeMutations/acceptTeamInvitation.ts
  packages/server/safeMutations/safeArchiveTeam.ts
Labels: size/m

#11340 chore: remove Sentry error logging
  .env.example
  packages/client/components/ErrorBoundary.tsx
  packages/client/components/ErrorComponent/ErrorComponent.tsx
  packages/client/components/ModalError.tsx
  packages/client/components/ReportErrorFeedback.tsx
  packages/client/types/modules.d.ts
  packages/server/billing/helpers/updateSubscriptionQuantity.ts
  packages/server/dataloader/atlassianLoaders.ts
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/dataloader/gcalLoaders.ts
  packages/server/dataloader/gitlabLoaders.ts
  packages/server/dataloader/jiraServerLoaders.ts
  packages/server/email/MailManagerGoogle.ts
  packages/server/email/MailManagerMailgun.ts
  packages/server/email/MailManagerSMTP.ts
  packages/server/graphql/mutations/createTaskIntegration.ts
  packages/server/graphql/mutations/helpers/generateDiscussionPrompt.ts
  packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
  packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/Notifier.ts
  packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
  packages/server/graphql/mutations/helpers/notifications/getSummaryText.ts
  packages/server/graphql/mutations/setAppLocation.ts
  packages/server/graphql/private/mutations/addNewFeature.ts
  packages/server/graphql/private/mutations/loginSAML.ts
  packages/server/graphql/public/mutations/helpers/getTopics.ts
  packages/server/graphql/public/mutations/linkMattermostChannel.ts
  packages/server/graphql/public/types/EstimateStage.ts
  packages/server/graphql/public/types/GitLabIntegration.ts
  packages/server/graphql/public/types/Task.ts
  packages/server/graphql/public/types/User.ts
  packages/server/graphql/uWSAsyncHandler.ts
  packages/server/listenHandler.ts
  packages/server/logging.ts
  packages/server/utils/AzureDevOpsServerManager.ts
  packages/server/utils/GoogleServerManager.ts
  packages/server/utils/MSTeamsServerManager.ts
  packages/server/utils/MattermostServerManager.ts
  packages/server/utils/MicrosoftServerManager.ts
  packages/server/utils/OpenAIServerManager.ts
  packages/server/utils/RecallAIServerManager.ts
  packages/server/utils/TenorManager.ts
  packages/server/utils/getVerifiedAuthToken.ts
  packages/server/utils/logError.ts
  packages/server/utils/standardError.ts
  packages/server/utils/stripe/StripeManager.ts
  scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
  scripts/webpack/dev.client.config.js
Labels: size/m

#11504 chore: Remove OrganizationUser.inactive
  packages/server/billing/helpers/adjustUserCount.ts
  packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
  packages/server/billing/helpers/updateSubscriptionQuantity.ts
  packages/server/dataloader/__tests__/activeOrganizationUsersCustomLoader.test.ts
  packages/server/dataloader/__tests__/isOrgVerified.test.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/graphql/private/queries/suOrgCount.ts
  packages/server/graphql/private/queries/suProOrgInfo.ts
  packages/server/graphql/private/queries/suUserCount.ts
  packages/server/graphql/public/mutations/createStripeSubscription.ts
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/Organization.ts
  packages/server/graphql/queries/helpers/countTiersForUserId.ts
  packages/server/postgres/migrations/2025-07-02T12:57:36.236Z_removeOrgUserInactive.ts
  packages/server/postgres/queries/insertStripeQuantityMismatchLogging.ts
  packages/server/postgres/queries/src/insertStripeQuantityMismatchLoggingQuery.sql
  packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
  packages/server/utils/isRequestToJoinDomainAllowed.ts
Labels: size/m

#11518 fix: clear typing notification on submit
  packages/client/components/DiscussionThreadInput.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/hooks/useIsEditing.ts
  packages/client/hooks/useTipTapCommentEditor.ts
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/tiptap/extensions/ClearOnSubmit.ts
Labels: size/s

#11522 fix: show correct meeting phase in dashboard
  packages/client/components/MeetingCard.tsx
  packages/client/components/SelectMeetingDropdownItem.tsx
  packages/client/utils/getMeetingPhase.ts
Labels: size/s

#11526 chore: fix client schema types
  packages/client/components/ParabolScopingSearchFilterMenu.tsx
  packages/client/types/clientSchema.d.ts
Labels: size/s

#11529 fix: drop stripe quantity mismatch logging not null constraint
  packages/server/postgres/migrations/2025-07-07T15:47:38.108Z_dropStripeQuantityMismatchOrgUsersNotNull.ts
Labels: size/s

#11535 chore(github-actions): explicit permissions added and unused workflows deleted
  .github/workflows/assign_reviewers.yml
  .github/workflows/labeler.yml
  .github/workflows/migration-order.yml
  .github/workflows/notify_bug_assign.yml
  .github/workflows/points_label_to_project.yml
  .github/workflows/release-please.yml
  .github/workflows/stale.yml
  .github/workflows/stats.yml
  .github/workflows/synk-yarn-lock-commit.yml
  .github/workflows/validate_pr_title.yml
Labels: size/m

#11538 chore(dependabot): ignore devDependencies
  .github/dependabot.yml
Labels: size/s

#11539 fix(dependabot): fix configuration file
  .github/dependabot.yml
Labels: size/s

#11514 feat: add transcript to Page
  packages/server/graphql/mutations/helpers/dumpTranscriptToPage.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
Labels: size/m

#11561 feat: submit reflections, tasks and standup responses on Mod+Enter
  packages/client/components/EditorHelpModal/EditorHelpModal.tsx
  packages/client/components/NullableTask/NullableTask.tsx
  packages/client/components/ReflectionCard/ReflectionCard.tsx
  packages/client/components/ReflectionCard/SubmitReflectionButton.tsx
  packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
  packages/client/components/promptResponse/PromptResponseEditor.tsx
  packages/client/hooks/useTipTapReflectionEditor.ts
  packages/client/hooks/useTipTapTaskEditor.ts
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
  packages/client/utils/platform.ts
Labels: size/m

#11584 chore: remove direct lodash dependencies
  package.json
  packages/client/validation/Legitity.ts
  packages/client/validation/__tests__/Legitity.test.ts
  packages/server/graphql/mutations/helpers/validateScaleValue.ts
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/s

#11585 chore: remove api package dependency
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/xs

#11586 chore: update franc-min to 6.2.0
  packages/embedder/package.json
  pnpm-lock.yaml
Labels: size/xs

#11594 chore: Add userId to Datadog traces
  packages/server/utils/useDatadogTracing.ts
Labels: size/s

#11600 fix: approve oxide for tailwindcss builds
  pnpm-workspace.yaml
Labels: size/xs

#11575 feat: Retro Meeting Summary on a Page
  codegen.json
  package.json
  packages/client/components/SpecificMeetingPicker.tsx
  packages/client/hooks/useTipTapPageEditor.ts
  packages/client/modules/outcomeCard/components/OutcomeCardStatusIndicator/OutcomeCardStatusIndicator.ts
  packages/client/modules/outcomeCard/components/OutcomeCardStatusIndicator/OutcomeCardStatusIndicator.tsx
  packages/client/mutations/EndRetrospectiveMutation.ts
  packages/client/package.json
  packages/client/shared/tiptap/extensions/InsightsBlockBase.ts
  packages/client/shared/tiptap/extensions/TaskBlockBase.ts
  packages/client/shared/tiptap/extensions/ThinkingBlockBase.ts
  packages/client/shared/tiptap/markdownToTipTap.ts
  packages/client/shared/tiptap/serverTipTapExtensions.ts
  packages/client/shared/utils/quickHash.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlock.ts
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockDisabled.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockNoData.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockResult.tsx
  packages/client/tiptap/extensions/insightsBlock/InsightsBlockView.tsx
  packages/client/tiptap/extensions/insightsBlock/TaskBlock.ts
  packages/client/tiptap/extensions/insightsBlock/TaskBlockView.tsx
  packages/client/tiptap/extensions/insightsBlock/ThinkingBlock.ts
  packages/client/tiptap/extensions/insightsBlock/ThinkingBlockView.tsx
  packages/client/tiptap/isCustomNodeSelected.ts
  packages/client/types/constEnums.ts
  packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
  packages/mattermost-plugin/prod.webpack.config.js
  packages/server/graphql/mutations/endRetrospective.ts
  packages/server/graphql/mutations/helpers/gatherInsights.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/summaryPage/generateRetroMeetingSummaryPage.ts
  packages/server/graphql/mutations/helpers/summaryPage/getInsightsBlocks.ts
  packages/server/graphql/mutations/helpers/summaryPage/getParticipantBlocks.ts
  packages/server/graphql/mutations/helpers/summaryPage/getRetroMetaBlock.ts
  packages/server/graphql/mutations/helpers/summaryPage/getSubtitleBlock.ts
  packages/server/graphql/mutations/helpers/summaryPage/getTaskBlocks.ts
  packages/server/graphql/mutations/helpers/summaryPage/getTitleBlock.ts
  packages/server/graphql/mutations/helpers/summaryPage/getTopicBlocks.ts
  packages/server/graphql/mutations/helpers/summaryPage/publishSummaryPage.ts
  packages/server/graphql/public/fields/pageInsights.ts
  packages/server/graphql/public/mutations/createPage.ts
  packages/server/graphql/public/mutations/endRetrospective.ts
  packages/server/graphql/public/mutations/helpers/getTopics.ts
  packages/server/graphql/public/typeDefs/EndRetrospectiveSuccess.graphql
  packages/server/graphql/public/typeDefs/RetrospectiveMeeting.graphql
  packages/server/graphql/public/types/EndRetrospectiveSuccess.ts
  packages/server/graphql/public/types/RetrospectiveMeeting.ts
  packages/server/graphql/rootMutation.ts
  packages/server/graphql/types/EndRetrospectivePayload.ts
  packages/server/package.json
  packages/server/postgres/migrations/2025-07-25T21:31:35.398Z_newMeeting-summaryPageId.ts
  packages/server/postgres/select.ts
  packages/server/postgres/types/Meeting.d.ts
  packages/server/utils/makeMeetingInsightInput.ts
  packages/server/utils/tiptap/createTopLevelPage.ts
  packages/server/utils/tiptap/getPlaintextFromTipTap.ts
  packages/server/utils/tiptap/updatePageContent.ts
  packages/server/utils/tiptap/withDoc.ts
  pnpm-lock.yaml
Labels: size/xl

#11623 fix: window.__ACTION__ is not defined for MattermostPlugin
  packages/client/components/promptResponse/BubbleMenuButton.tsx
  packages/client/components/promptResponse/StandardBubbleMenu.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelector.tsx
  packages/client/tiptap/extensions/imageUpload/ImageSelectorSearchTab.tsx
  packages/mattermost-plugin/components/TipTap/Editor.tsx
  packages/mattermost-plugin/types/modules.d.ts
  packages/mattermost-plugin/webpack.config.js
Labels: size/s

#11627 chore: add more ignore files to biome and add .editorconfig
  .editorconfig
  biome.jsonc
Labels: size/s

#11645 feat: new email summary for retros
  biome.jsonc
  packages/server/dataloader/RootDataLoader.ts
  packages/server/dataloader/aiLoaderMakers.ts
  packages/server/email/makeSummaryEmailV2.tsx
  packages/server/email/sendSummaryEmailV2.tsx
  packages/server/graphql/mutations/endCheckIn.ts
  packages/server/graphql/mutations/endSprintPoker.ts
  packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts
  packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
  packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
  packages/server/graphql/mutations/helpers/summaryPage/generateRetroMeetingSummaryPage.ts
  packages/server/graphql/mutations/helpers/summaryPage/getInsightsBlocks.ts
  packages/server/graphql/mutations/helpers/summaryPage/getTopicBlocks.ts
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/l
