Repository ParabolInc/parabol, pull requests merged in 2025-05, with the labels that each got.

#11282 fix: improve error handling for websocket connections in safari
  packages/client/Atmosphere.ts
  packages/client/utils/createWSClient.ts
Labels: size/s

#11284 fix: remove resolver-level tracing for DD debugging
  packages/server/utils/useDatadogTracing.ts
Labels: size/s

#11285 feat: dump on sigusr2
  packages/server/graphql/private/mutations/dumpHeap.ts
Labels: size/xs

#11281 fix: only call wsHandler message if socket is open
  packages/server/wsHandler.ts
Labels: size/xs

#11275 fix: can push task card to integration
  packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
Labels: size/xs

#11297 fix(Mattermost): use x-application-authorization header
  package.json
  packages/mattermost-plugin/Atmosphere.ts
  packages/server/utils/getReqAuth.ts
Labels: size/xs

#11299 fix(Mattermost): fix notifications
  packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
Labels: size/xs

#11242 fix: db:start command created the dev folder with the current user
  package.json
Labels: size/xs

#11303 fix: await tick in chronos to not run it in parallel
  packages/server/chronos.ts
Labels: size/xs

#11308 fix: bump kysely
  package.json
  packages/server/__tests__/processRecurrence.test.ts
  packages/server/dataloader/customLoaderMakers.ts
  packages/server/dataloader/foreignKeyLoaderMakers.ts
  packages/server/graphql/public/mutations/addReactjiToReactable.ts
  packages/server/graphql/public/types/Company.ts
  packages/server/graphql/public/types/TeamPromptMeeting.ts
  packages/server/graphql/public/types/User.ts
  packages/server/package.json
  pnpm-lock.yaml
Labels: size/s

#11305 fix: Mattermost relay compiler in dev
  pm2.dev.config.js
Labels: size/xs

#11312 chore: cleanup Mattermost webhook handler
  packages/client/types/generics.ts
  packages/server/graphql/private/mutations/loginMattermost.ts
  packages/server/graphql/private/typeDefs/Mutation.graphql
  packages/server/integrations/mattermost/mattermostWebhookHandler.ts
  packages/server/utils/atlassian/jiraIssues.ts
Labels: size/m

#11313 chore(Mattermost Plugin): improve not logged in experience
  packages/mattermost-plugin/Atmosphere.ts
  packages/mattermost-plugin/components/Sidepanel/index.tsx
  packages/mattermost-plugin/index.tsx
Labels: size/s

#11318 turn on resolver tracing
  packages/server/utils/useDatadogTracing.ts
Labels: size/s

#11320 fix: gitlab name in summary
  packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasks.tsx
  packages/client/types/constEnums.ts
Labels: size/xs

#11324 chore: fail on pgtyped errors
  package.json
  packages/server/postgres/pgtypedConfig.js
  packages/server/postgres/queries/src/backupUserQuery.sql
Labels: size/xs

#11325 fix: mark wrapped resolvers
  packages/server/logging.ts
  packages/server/server.ts
  packages/server/utils/useDatadogTracing.ts
  scripts/webpack/prod.servers.config.js
Labels: size/s

#11334 chore: make chronos debug output optional
  .env.example
  packages/server/chronos.ts
Labels: size/s

#11331 feat(orgAdmin): org admin can rename a team in org teams view
  packages/client/components/EditableText.tsx
  packages/client/modules/teamDashboard/components/EditTeamName/EditableTeamName.tsx
  packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
Labels: Skip Maintainer Review, size/m

#11332 fix(metrics): add metric for page insights generated
  packages/server/graphql/public/fields/pageInsights.ts
  packages/server/utils/analytics/analytics.ts
Labels: size/xs

#11349 fix: ScopePhaseArea styling
  packages/client/components/ScopePhaseArea.tsx
Labels: Skip Maintainer Review, size/s

#11345 fix: limit the Azure DevOps work items fetched
  packages/server/dataloader/azureDevOpsLoaders.ts
  packages/server/graphql/public/types/AzureDevOpsIntegration.ts
  packages/server/graphql/queries/helpers/connectionFromTasks.ts
  packages/server/utils/AzureDevOpsServerManager.ts
Labels: size/m

#11354 fix: integration logo sizing
  packages/client/components/JiraServerSVG.tsx
  packages/client/components/LinearProviderLogo.tsx
Labels: size/s

#11360 fix: return missing Organization.isPaid field
  packages/server/graphql/types/Team.ts
Labels: size/xs

#11361 fix: disable unsafe webpack cache
  scripts/webpack/dev.client.config.js
  scripts/webpack/toolbox.config.js
Labels: size/xs

#11363 fix: set message in lockOrganizations
  packages/server/graphql/private/mutations/lockOrganizations.ts
Labels: size/xs

#11368 fix: show correct emoji suggestion for :) and :(
  packages/client/utils/tiptapEmojiConfig.ts
Labels: size/xs, size/s
